### ISSUE TITLE
Confusing due to interface of `PipeableApply`

### ISSUE THREAD

**Issue by mozisan** [gcanti/fp-ts#1000]
I wrote some codes like following...

```ts
import { pipeable, option } from 'fp-ts';

declare const converter1: option.Option<(value: string) => string>;
declare const converter2: option.Option<(value: string) => string>;
declare const converter3: option.Option<(value: string) => string>;

pipeable.pipe(
  option.some('value'),
  option.ap(converter1),
  option.ap(converter2),
  option.ap(converter3),
);
```

But `option.ap()` takes `Option` instance as first argument.  
This behavior is defined by `PipeableApply`.

```ts
export interface PipeableApply<F> extends PipeableFunctor<F> {
  readonly ap: <A>(fa: HKT<F, A>) => <B>(fab: HKT<F, (a: A) => B>) => HKT<F, B>
  //           ^^^^^^^^^^^^^^^^^^
  ...
}
```

I have usesd `fp-ts@^1` before, at that time the codes like above was valid.  
Like next...

```ts
import { option } from 'fp-ts'; // fp-ts@^1

declare const converter1: option.Option<(value: string) => string>;
declare const converter2: option.Option<(value: string) => string>;
declare const converter3: option.Option<(value: string) => string>;

option
  .some('value')
  .ap(converter1)
  .ap(converter2)
  .ap(converter3);
```

I don't know why `ap()` of `fp-ts@^2` is defined in this way.  
I am not professional at functional programming, so I don't know whether this is bug or not.  
If you know correct usage of `ap()`, please let me know.

(I'm sorry if my English is strange, but I tried to write politely.)

**Comment by gcanti** [comment]
`ap` signature is optimized for lifting a `n`-ary function (IME should be the most common case)

```ts
import { ap, Option, some } from 'fp-ts/lib/Option'
import { pipe } from 'fp-ts/lib/pipeable'

declare const f: (a: string) => (b: number) => boolean
declare const a: Option<string>
declare const b: Option<number>

const result = pipe(
  some(f),
  ap(a),
  ap(b)
)
```

**Comment by steida** [comment]
Do I understand it correctly, that ap is only for wrapped functions? I somehow do not see real-world use cases.

**Comment by sledorze** [comment]
That's the gist of Applicative, enabling 'parallel' (indépendant) évaluation whereas monadic computation are sequentials (and may depend from previous results).

**Comment by mozisan** [comment]
@gcanti @sledorze 
Thanks for reply.
I see the use case.
