### ISSUE TITLE
Suggestion: use union for `getOrElse` return type

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#1002]
### Current Behavior

Given the following code, I have an unexpected error (see comment):

```tsx
import * as O from 'fp-ts/lib/Option';
import { pipe } from 'fp-ts/lib/pipeable';
import * as React from 'react';

declare const maybeDescription: O.Option<string>;
const renderDescriptionPlaceholder = () => <div>foo</div>;

<div>
  {pipe(
    maybeDescription,
    // Type 'string' is not assignable to type 'Element'
    O.getOrElse(renderDescriptionPlaceholder),
  )}
</div>;
```

### Expected behavior

No error

### Reproducible example

(above)

### Suggested solution(s)

I can work around it by using an explicit generic:

```diff
-    O.getOrElse(renderDescriptionPlaceholder),
+    O.getOrElse<React.ReactNode>(renderDescriptionPlaceholder),
```

However, if `getOrElse` returned a union ([like it does in Funfix](https://github.com/funfix/funfix/blob/d6003e778ee59a439ad345ef59f48c80db46905f/packages/funfix-core/src/disjunctions.ts#L635)), this explicit generic wouldn't be necessary:

```diff
-<A>(onNone: () => A): (ma: Option<A>) => A
+<B>(onNone: () => B): (ma: Option<A>) => A | B
```

Perhaps we could make this change to `getOrElse`, or would there be unintended side effects from this?

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |            |
| TypeScript |            |

**Comment by raveclassic** [comment]
Oh, that "superflexible" React :)

**Comment by giogonzo** [comment]
> Oh, that "superflexible" React :)

yeah...

I'm not sure I'd want this behavior in general, see e.g. my thoughts here: https://github.com/gcanti/fp-ts/pull/945

**Comment by OliverJAsh** [comment]
[Your explanation here](https://github.com/gcanti/fp-ts/pull/945#issuecomment-526154807) makes sense to me, thanks.

**Comment by Gurimarukin** [comment]
You could also do:

```tsx
<div>
  {pipe(
    maybeDescription,
    O.getOrElse<ReactNode>(renderDescriptionPlaceholder),
  )}
</div>;
```
