### ISSUE TITLE
import best practices

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1003]
## 📖 Documentation

When you are using both Option and IO, what is your best practice? * or aliasing?

```ts
import * as o from 'fp-ts/lib/Option';
import * as i from 'fp-ts/lib/IO';
import * as te from 'fp-ts/lib/TaskEither';
```

**Comment by DenisFrezzato** [comment]
I found myself (and I guess this is the more common approach among other `fp-ts` users) to import the whole module using the first letters of the module itself, for example:
```
import * as O from 'fp-ts/lib/Option'
import * as IO from 'fp-ts/lib/IO'
import * as TE from 'fp-ts/lib/TaskEither'
```

**Comment by steida** [comment]
Isn't one small letter better?

```ts
import * as o from 'fp-ts/lib/Option';
import * as i from 'fp-ts/lib/IO';
import * as te from 'fp-ts/lib/IO';
```

Why capitalize namespaces?

**Comment by raveclassic** [comment]
I find writing imports by hand tedious and always rely on autocomplete/autoimport. Firstly I tried aliasing but finally came to named imports from fp-ts index:
```typescript
import { option } from 'fp-ts';
```

**Comment by steida** [comment]
@raveclassic Interesting. Isn't `either.Either` verbose? Also, does it tree-shake?

**Comment by raveclassic** [comment]
@steida except types :) only `either.map`, `either.chain` etc

**Comment by steida** [comment]
@raveclassic Because you are online, may I have a completely unrelated question? 

How to mix pipe value transformation with ad-hoc side effect? Is this right? 

```ts
const nextValue = pipe(
    value,
    // We don't need side effect.
    select({ anchor: [0, 0, 0], focus: [0, 0, 2] }),
    // insertText needs some ad-hoc computed data from DOM via editor.
    insertText('foo')(editor),
  )
```

**Comment by steida** [comment]
Github really should allow people to pay for answers. I would pay a lot 😂

**Comment by steida** [comment]
@raveclassic I like it. It's verbose but explicit and with autocomplete. As for tree shaking, it does not work reliably anyway when some other lib like monocle-ts is imported, because it will use `/lib`.

So, `import { option, either } from 'fp-ts';` is ok, and for tree shaking, we would need some imports rewriting anyway.

**Comment by steida** [comment]
@raveclassic Still, I would love to solve tree shaking across fp-ts ecosystem anyway. It seems it's almost ready.

**Comment by steida** [comment]
@gcanti What if the whole fp-ts ecosystem would use `import { option, either } from 'fp-ts';`? I can send PR.

**Comment by steida** [comment]
As a result, in the app, I would use `import { option, either }`.
In a lib, which is going to be tree shaked, it seems we have no other option than aliases. I doubt any tree shaking engine can optimize `option.chain`. It would have to solve clashes.
