### ISSUE TITLE
`fromNullable` should use `NonNullable` in its return type

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#1004]
### Current Behavior

```ts
type MyObject = {
  foo: number | undefined
  bar: number | undefined
}
declare const fn: <Key extends keyof MyObject>(key: Key) => MyObject[Key];
const getKey = flow(fn, O.fromNullable)
const result = getKey('bar'); // $ExpectType Option<number>
```

Actual type is `Option<number | undefined>`.

### Expected behavior

See comment in code above.

### Reproducible example

See above.

This seems to fix it:

```diff
-export declare function fromNullable<A>(a: A | null | undefined): Option<A>;
+export declare function fromNullable<A>(a: A | null | undefined): Option<NonNullable<A>>;
```

### Additional context

Related: https://github.com/funfix/funfix/pull/134

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |   2.0.5         |
| TypeScript | 3.6.3           |

**Comment by gcanti** [comment]
@OliverJAsh thanks for the bug report, fix released in https://github.com/gcanti/fp-ts/releases/tag/2.1.2
