### ISSUE TITLE
Functional switch

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1006]
## 📖 Documentation

What is the functional equivalent to switch? Nested ternary operators? Callback? Anything else?

**Comment by DenisFrezzato** [comment]
If you're asking for a primitive solution, I'd say ternary operators, because it's an expression and not a statement. Even if I may be fine with nested ternary operators, we can do better by creating a match function:
```typescript
type A = { type: 'A' }
type B = { type: 'B', value: string }
type C = { type: 'C', payload: number }

type Foo = A | B | C

function fold<T>(foo: Foo, handlers: {
    whenA: (a: A) => T,
    whenB: (b: B) => T,
    whenC: (c: C) => T
}): T {
    switch (foo.type) {
        case 'A': return handlers.whenA(foo)
        case 'B': return handlers.whenB(foo)
        case 'C': return handlers.whenC(foo)
    }
}

declare const someFoo: Foo

fold(someFoo, {
    whenA: () => 'Yep, it is an A',
    whenB: (b) => b.value,
    whenC: (c) => c.payload.toString()
})
```

**Comment by steida** [comment]
I would create it when to be reused. Otherwise, nested ternaries seem to be best. Thank you!
