### ISSUE TITLE
ReaderEitherTask

### ISSUE THREAD

**Issue by mohaalak** [gcanti/fp-ts#1007]
### Current Behavior

right now `ReaderEitherTask` has only `asks`  function that gets the reader and returns `A` 
```typescript
import {readerTaskEither,asks} from 'fp-ts/lib/ReaderTaskEither';

const get = asks((r) => r + 2)
get(3)().then(console.log) // this returns a right(2)
```

### Desired Behavior

but I want to use `Reader` as a dependency Injection
something like this

```typescript
import {readerTaskEither, fn} from 'fp-ts/lib/ReaderTaskEither';
const getData =   (id: number) => tryCatch(() => Promise.resolve(id), String);

type Read= {
  getData: (id:number) => TaskEither<string, number>
};

const get = fn<Read, string, number>((r) => r.getData(2))
get({getData})().then(console.log);

```

I think we need a function that sends reader and gets the monad that `ReaderT` needs

### Suggested Solution

I think we can write it this way

```typescript
export declare const fn: <R, E = never, A =never>( f: (r: R) =>TaskEither<E, A>) => ReaderTaskEither<R,E,A>;

export const fn = f => r => f(r)
```

**Comment by mlegenhausen** [comment]
This seams to be equivalent to

```ts
import * as RTE from 'fp-ts/lib/ReaderTaskEither'

pipe(
  RTE.ask(),
  RTE.chain(r => RTE.fromTaskEither(r.getData(2))
)
```

I use `ReaderTaskEither` in a project as DI mechanism. I would recommend to split the DI interface from the call function something like

```ts
interface Env {
  getData(id: number): TaskEither<string, number>
}

const getData: ReaderTaskEither<Env, string, number> => env => env.getData(2)

const app = pipe(
  getData(),
  RTE.chain(a => RTE.rightIO(console.log(a))
)

RTE.run(app, {
  getData: id => /* your side effect */
})
```

**Comment by mohaalak** [comment]
> ```ts
> interface Env {
>   getData(id: number): TaskEither<string, number>
> }
> 
> const getData: ReaderTaskEither<Env, string, number> => env => env.getData(2)
> 
> const app = pipe(
>   getData(),
>   RTE.chain(a => RTE.rightIO(console.log(a))
> )
> 
> RTE.run(app, {
>   getData: id => /* your side effect */
> })
> ```

I think you have some syntax error I don't understand `const getData: ReaderTaskEither...`

**Comment by mlegenhausen** [comment]
Sorry haven't tried it in a real program. Maybe it works now better?

**Comment by mohaalak** [comment]
oh now I get it, we just set `getData` as a `ReaderTaskEither`, not a function that gets `Env` and returns an `EitherTask`,
thank you so much.
it will be nice to add this code somewhere in ReaderTaskEither document.

**Comment by mohaalak** [comment]
I think if this repo has a Gitter room, these questions can be asked there.

**Comment by steida** [comment]
@mohaalak Bad for search engine bots.

**Comment by giogonzo** [comment]
not Gitter, and yes it's bad for search engines, but I see many question answered in the #typescript channel at https://fpchat-invite.herokuapp.com/
