### ISSUE TITLE
Option ap

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1011]
## 📖 Documentation

Sorry to disturb you, but I still did not get it. Can someone post some real-world examples of why it is useful? I don't understand the purpose of this code. Thank you 🖤

```ts
const fa = O.some(1)
const fb = O.some('foo')
const f = (a: number) => (b: string): boolean => a + b.length > 2

const fc1 = pipe(
  O.some(f),
  O.ap(fa),
  O.ap(fb)
)

const fc2 = pipe(
  fa,
  O.map(f),
  O.ap(fb)
)
```

**Comment by grossbart** [comment]
This helped me understand `ap` (and many other things, too): https://mostly-adequate.gitbooks.io/mostly-adequate-guide/ch10.html#applying-applicatives

**Comment by DenisFrezzato** [comment]
Other resources on this topic:
- https://dev.to/gcanti/getting-started-with-fp-ts-applicative-1kb3
- http://learnyouahaskell.com/functors-applicative-functors-and-monoids#applicative-functors

**Comment by raveclassic** [comment]
I also find @i-am-tom series very useful http://www.tomharding.me/2017/04/10/fantas-eel-and-specification-8/

**Comment by steida** [comment]
Thank you all!
