### ISSUE TITLE
Any fp-ts advanced developer available for paid consulting?

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1014]
I think I learned a lot and probably can solve the current problem by myself, but it's a slow process. I am designing a system where Task, State, and maybe something else is involved.

I need someone for quick one to one brainstorming to validate my ideas. I really don't want to misuse this issue tracker anymore. Once I finish what I am working on, I will definitely help with docs.

**Comment by steida** [comment]
@gcanti Or can we set up some fp-ts jobs board somewhere?

**Comment by gcanti** [comment]
Duplicated? https://github.com/gcanti/fp-ts/issues/986

> I really don't want to misuse this issue tracker anymore

Yes, please.
