### ISSUE TITLE
Why getEq of Const return identity function

### ISSUE THREAD

**Issue by jituanlin** [gcanti/fp-ts#1020]
`export const getEq: <E, A>(E: Eq<E>) => Eq<Const<E, A>> = identity`
The `getEq` type  signature indicate the return type is `Eq`, 
however the `identity` is not `Eq` obviously.

**Comment by gcanti** [comment]
The constant `getEq` is a function that accepts an `Eq<E>` and returns an `Eq<Const<E, A>>`, since `Const<E, A>` is basically just `E`, `getEq` can be implemented by the identity function
