### ISSUE TITLE
Smart constructor for non-primitive types and Eq

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1022]
## 📖 Documentation

As I understand it, newtype is for primitive types only. For my editor, I need to enforce normalized (no singling text nodes) non-primitive values via types and still leverage Eq etc.

Is it possible or am I missing something?

Related https://github.com/gcanti/newtype-ts/issues/22

**Comment by raveclassic** [comment]
Take a look at https://github.com/gcanti/io-ts#branded-types--refinements

**Comment by steida** [comment]
I don’t understand, it can ne used for nom-primitive types or not?
