### ISSUE TITLE
Array `indexOf`

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#1031]
### Current Behavior

`A.findIndex` provides an alternative to `Array.prototype.findIndex` (accepts a predicate), but there's no alternative for `Array.prototype.indexOf` (accepts an element). Could we consider adding one? How about this?

```ts
const indexOf = <T>(t: T) => (ts: T[]): O.Option<number> => {
  const index = ts.indexOf(t);
  return index !== -1 ? O.some(index) : O.none;
};
```

Like with `findIndex`, when an element is not found, this returns `None` instead of `-1`.

**Comment by raveclassic** [comment]
I believe all equality-based operations should be done using an instance of `Eq`. So it should rather be:
```typescript
const indexOf = <A>(E: Eq<A>) => (a: A) => (as: A[]): Option<number> => {
	for (let i = 0, l = as.length; i < l; i++) {
		if (E.equals(a, as[i])) {
			return some(i);
		}
	}
	return none;
};
const result = pipe(
	[1, 2, 3],
	indexOf(eqNumber)(2),
);
```

Does it make sense to include such operation into the core if it's possible to use `findIndex`?
```typescript
const result2 = pipe(
	[1, 2, 3],
	findIndex(a => a === 2),
);
```

**Comment by raveclassic** [comment]
Or event shorter:
```typescript
const indexOf2: <A>(E: Eq<A>) => (a: A) => (as: []) => Option<number> = E => a => findIndex(_a => E.equals(a, _a));
```

**Comment by OliverJAsh** [comment]
> Does it make sense to include such operation into the core if it's possible to use `findIndex`?

I'm presuming that the built-in `indexOf` would be faster than the built-in `findIndex` (when it's used to do the same thing).

**Comment by gcanti** [comment]
+1 on using `findIndex`
