### ISSUE TITLE
Replace ramda logic functions ?

### ISSUE THREAD

**Issue by guillaumewuip** [gcanti/fp-ts#1038]
### Current Behavior

Ramda has a list of "logic" function that are not available in fp-ts 
![image](https://user-images.githubusercontent.com/748586/70131200-2de89c00-1682-11ea-83e3-25ba9c53a2d5.png)

### Desired Behavior

I would like to have the same kind of functions in the `fp-ts` ecosystem.

### Suggested Solution

One solution could be to create such functions in a `fp-ts-logic` package.

I'm available to help on this but I first want to have your point of view: is there something already provided by `fp-ts` that could help me but that I missed ?

### Who does this impact? Who is this for?

All users

### Describe alternatives you've considered

One alternative could be to keep using ramda for that, but ramda typings are sometimes not that great and that means one more lib in my app. 

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2      |
| TypeScript |     3.7       |

**Comment by gcanti** [comment]
> One solution could be to create such functions in a fp-ts-logic package

@guillaumewuip I would suggest to contribute to [fp-ts-ramda](https://github.com/giogonzo/fp-ts-ramda) instead.

Here's the [current status of porting](https://github.com/giogonzo/fp-ts-ramda/issues/15) if you want to help us :+1:

**Comment by guillaumewuip** [comment]
Nice ! I completely forgot this project.

Thanks, I close this issue then 👍
