### ISSUE TITLE
Perform side effect and return original input (tee)

### ISSUE THREAD

**Issue by abacaj** [gcanti/fp-ts#1039]
## 📖 Documentation
Does fp-ts have a concept of a `tee` example: https://davefancher.com/2015/01/11/extending-f-pipelines-with-a-tee-function/

“given a value, apply a function to it, ignore the result, then return the original value."

I've got a use case for `TaskEither` to perform some uploading and return the original input to the next pipeline function.

**Comment by abacaj** [comment]
example use case:

```
pipe(
  fileUrls,
  TaskEither.tee(upload),
  TaskEither.chain(parseCsv)
)
```

**Comment by abacaj** [comment]
This seems to work for my use case:

```
export const taskEitherEffect = <E, A>(f: (a: A) => TE.TaskEither<E, void>) => (b: TE.TaskEither<E, A>) => {
    return pipe(
        b,
        TE.fold((e) => {
            return TE.left(e);
        }, (value) => {
            return pipe(
                f(value),
                TE.map(() => value)
            );
        })
    )
}```

usage:

```
pipe(
  fileUrls,
  taskEitherEffect(upload)
  TaskEither.chain(parseCsv)
)
```
Upload just returns a promise with an either (taskeither) error and void
```
upload: TaskEither<Error, void>
```

The `parseCsv` now has access to the original input (fileUrls).

**Comment by steida** [comment]
I just needed the same for Either.

https://github.com/typescript-fun/five-minutes-demo/blob/c343f12a2f5d19e71f956f0bb2351ee46df7d5cf/hooks/useForm.ts#L157

@raveclassic What you do in such a case? Thank you.

**Comment by gcanti** [comment]
You may want `chainFirst`

```ts
import { pipe } from 'fp-ts/lib/pipeable'
import * as TE from 'fp-ts/lib/TaskEither'

declare const fileUrls: Array<string>
declare function upload(fileUrls: Array<string>): TE.TaskEither<Error, void>
declare function parseCsv(fileUrls: Array<string>): TE.TaskEither<Error, void>

pipe(TE.right(fileUrls), TE.chainFirst(upload), TE.chain(parseCsv))
```

**Comment by gkamperis** [comment]
@gcanti would be great to add this to the docs and a recipes/how to page...

**Comment by abacaj** [comment]
> You may want `chainFirst`
> 
> ```ts
> import { pipe } from 'fp-ts/lib/pipeable'
> import * as TE from 'fp-ts/lib/TaskEither'
> 
> declare const fileUrls: Array<string>
> declare function upload(fileUrls: Array<string>): TE.TaskEither<Error, void>
> declare function parseCsv(fileUrls: Array<string>): TE.TaskEither<Error, void>
> 
> pipe(TE.right(fileUrls), TE.chainFirst(upload), TE.chain(parseCsv))
> ```

Yep, that looks like it's a direct replacement for my implementation - thank you.

**Comment by gcanti** [comment]
@gkamperis any contribution to the documentation is welcomed!

**Comment by gkamperis** [comment]
@gcanti of course... 
however I do not feel I have enough knowledge to create these sort of examples and I do not know if this page already exists or where it should live.

Is there an example I can look at?

**Comment by JohnForster** [comment]
Just a quick question on this, what would be the correct way to implement this if you also didn't care if the upload failed or not? I'd like to be able to discard the Error state as well. Is there a better way to implement this?

**Comment by mohaalak** [comment]
> Just a quick question on this, what would be the correct way to implement this if you also didn't care if the upload failed or not? I'd like to be able to discard the Error state as well. Is there a better way to implement this?

I think you can use [`TaskEither.getOrElse`](https://gcanti.github.io/fp-ts/modules/TaskEither.ts.html#getorelsew) to get a `Task`

**Comment by gcanti** [comment]
you could define a `discard` utility:

```ts
const discard: <E>(ma: TE.TaskEither<E, void>) => TE.TaskEither<E, void> = TE.alt(() =>
  TE.right(undefined as void)
)

const result = pipe(TE.right(fileUrls), TE.chainFirst(flow(upload, discard)), TE.chain(parseCsv))
```

in `fp-ts@2.10` (<= currently a release candidate) there's a `chainFirstTaskK` utility:

```ts
const result = pipe(TE.right(fileUrls), TE.chainFirstTaskK(upload), TE.chain(parseCsv))
```
