### ISSUE TITLE
Add a blog post to async recipe

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1056]
## 📖 Documentation

https://dev.to/gnomff_65/fp-ts-sequencet-and-sweet-sweet-async-typed-fp-5aop

It would be very helpful because it mentions sequenceT (and somewhere should be mentioned sequenceS).

**Comment by gcanti** [comment]
We could add a section before "Work with a list of dependent tasks", something like "Working with a tuple of tasks"

**Comment by steida** [comment]
That, or add a link to https://gcanti.github.io/fp-ts/introduction/learning-resources.html Blog posts
