### ISSUE TITLE
Make fold implementation O(logn) with recursion

### ISSUE THREAD

**Issue by vicrac** [gcanti/fp-ts#1057]
### Current Behavior
Currently, `fold` simply delegates its call to `Array.reduce`, which is linear in time - it combines elements one by one.

### Desired Behavior
Given formal restrictions on `fold` - associativity, we could implement it recursively, splitting each time array in half. This would give us logarithmic execution time, instead of linear one.The origin of the problem is that I am reducing an array of records, with a few spreads invloved, which is quite inefficient. Currently I am using custom implementation, but I'd love to see it baked into `fp-ts`.

### Suggested Solution

Here's my implementation:
```ts
const reduceRecursively = <A>(fa: (a1: A, a2: A) => A) => (xs: Array<A>): A => {
  return xs.length === 1
    ? xs[0]
    : fa(
        reduceRecursively(fa)(xs.slice(0, Math.floor(xs.length / 2))),
        reduceRecursively(fa)(xs.slice(Math.floor(xs.length / 2), xs.length))
      );
};
```

### Who does this impact? Who is this for?

Anyone using fold with nontrivial semigroup.

### Describe alternatives you've considered

Using custom implementation - abstraction leak.

If this is accepted, I am ready to open a PR.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.3.1      |
| TypeScript |      3.7.3      |

**Comment by gcanti** [comment]
> This would give us logarithmic execution time, instead of linear one

@vicrac could you please explain how is possible? The total number of `concat`s is the same and AFAIK in a standard JavaScript runtime they are not parallelized. Did you write a benchmark?

**Comment by vicrac** [comment]
@gcanti Yes, I've written the benchmark for my code. It's quite specific so to reproduce it here I'd have to simplify it a bit. In meantime, isn't this precisely this case (perhaps I'm wrong, if so, please do correct me): https://en.wikipedia.org/wiki/Exponentiation_by_squaring?

**Comment by vicrac** [comment]
Well, I admit I might be wrong in the first place, I cannot reproduce it in a simplified environment and it indeed feels strange to get processing of `n` elements below `O(n)` complexity :smile: (I still wonder why the heck it does work faster in my project, but apparently I missed something else). Sorry to bother you - can be closed.
