### ISSUE TITLE
Use tuple as function arguments

### ISSUE THREAD

**Issue by frndmg** [gcanti/fp-ts#1062]
### Current Behavior

If you want to pass a tuple as function arguments you have to deconstruct the tuple, but miss point free syntax.

```typescript
declare const f: (a: A, b: B) => C;

pipe(
  tuple(a, b),
  x => f(...x),
);
```

### Desired Behavior

Use function `apT` to resolve this

```typescript
declare const f: (a: A, b: B) => C;

// apT will apply the tuple as function arguments
const fT: (t: [A, B]) => C = apT(f);

pipe(
  tuple(a, b),
  fT,
);
```

### Suggested Solution

This function could be implemented as

```typescript
const apT: <A extends Array<unknown>, B>(f: (...a: A) => B) => (a: A) => B =
    f => a => f(...a);
```

### Your environment

Every OS

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.2.0        |
| TypeScript | 3.7.2           |

**Comment by gkamperis** [comment]
Is unary the right name for this functionality? It clashes with all other references and definitions of unary function or operator I have seen.

**Comment by gcanti** [comment]
@gkamperis we can change the name, no problem. How can we name a combinator that accepts a function `(a: A, b: B) => C` and returns a function `(x: [A, B]) => C`?

**Comment by gcanti** [comment]
Ideally should be a `<name>` such that

- `<name>: (f: (a: A, b: B) => C) => (t: [A, B]) => C`
- `un<name>: (f: (t: [A, B]) => C) => (a: A, b: B) => C)`

(like the pair "curry" / "uncurry")

- `apT` / `unapT`?
- `unary` / `ununary`?

**Comment by gkamperis** [comment]
It's a tough one... But personally I would exclude unary.

Take the below with kindness... :) 

```
tupleArg
untupleArg
```

```
structureArg
destructureArg
```

**Comment by gcanti** [comment]
In Scala there's [`tupled`](https://www.scala-lang.org/api/current/scala/Function2.html#tupled:((T1,T2))=%3ER)

**Comment by gkamperis** [comment]
@gcanti better than `unary` in my opinion

**Comment by frndmg** [comment]
Thanks for the feature! :+1:

Are you considering adding `unTupled` yet?

```typescript
export function unTupled<A extends Array<unknown>, B>(f: (a: A) => B): (...a: A) => B {
  return (...a) => f(a)
}
```

**Comment by gcanti** [comment]
@frndmg https://github.com/gcanti/fp-ts/pull/1063/commits/57417ff970c1b5dddc8dafcb666389f4aba4a5a9

**Comment by frndmg** [comment]
Great!
