### ISSUE TITLE
Possible Bug in Definition of Functor?

### ISSUE THREAD

**Issue by MissingHandle** [gcanti/fp-ts#1079]
## 📖 Documentation

I started reading and working through your documentation about fp-ts,  and here:

https://gcanti.github.io/fp-ts/introduction/core-concepts

it defines the two key properties of the map function: Identity, and Composition.   

I am wondering if the composition rule actually needs to be changed from:

`F.map(fa, a => bc(ab(a))) = F.map(F.map(fa, ab), bc)`

to something like:

`(a => bc(ab(a))))(fa) = F.map(F.map(fa, ab), bc)`

This is because in working through it myself, i was able to construct an operation which _technically_  passes the composition rule as you have it documented by simply ignoring the function argument altogether:

```
const meetsIdentity = {
  map: (value: any, _fn: (a: any) => any) => {
    return value;
  },
};

function appendB(a: string): string {
  return `${a}b`;
}

function appendC(a: string): string {
  return `${a}c`;
}

function appendBC(a: string): string {
  return appendC(appendB(a));
}

console.log(`testing composition-test-as-written with meetsIdentity\n`);
r1 = meetsIdentity.map('a', appendBC);
r2 = meetsIdentity.map(meetsIdentity.map('a', appendB), appendC);
console.log(`composition with meetsIdentity: ${r1} ?= ${r2}`);
console.log(`\n\n`);
```

Can see for more:

https://github.com/MissingHandle/fn-programming-playground/blob/master/src/index.ts#L108-L152

**Comment by gcanti** [comment]
> **Instances** must satisfy the following laws

@MissingHandle see [How to write type class instances for your data type](https://gcanti.github.io/fp-ts/recipes/HKT.html)
