### ISSUE TITLE
Shouldn't there be a `fold` on a `NonEmptyArray<A>`, admitting `Semigroup<A>` instance?

### ISSUE THREAD

**Issue by vicrac** [gcanti/fp-ts#1088]
### Current Behavior

It's more of an aesthetic detail, but still quite confusing for me: if I want to combine a `NonEmptyArray<A>` into one `A` (using `Semoigrup`), I have to use:
```ts
import { cons, head, tail } from "fp-ts/es6/NonEmptyArray"
import { fold, semigroupSum } from "fp-ts/es6/Semigroup";

const nxs = cons(1)([2, 3, 4, 5])
fold(semigroupSum)(head(nxs), tail(nxs))
```
This is quite polluted and verbose to be honest.
### Desired Behavior
```ts
import { fold } from "fp-ts/es6/NonEmptyArray";

const nxs = cons(1)([2, 3, 4, 5])
fold(semigroupSum)(nxs)  // OK, array is not empty, so we don't need Monoid to provide empty, Semigroup is good enough
```

### Suggested Solution

`NonEmptyArray`'s `fold` could be defined in terms of `Semigroup`'s `fold`:
```ts
import { fold as sfold } from './Semigroup'

export const fold = <A>(s: Semigroup<A>) => (nxs: NonEmptyArray<A>) =>
  sfold(s)(head(nxs), tail(nxs));
```

### Describe alternatives you've considered

Using `head` and `tail` every time - as I said, quite confusing for me.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.3.1      |
| TypeScript |     3.7.1       |

**Comment by gcanti** [comment]
With `fp-ts@2.4.1` (see https://github.com/gcanti/fp-ts/pull/1084) you can do

```ts
import { identity } from 'fp-ts/lib/function'
import { foldMap } from 'fp-ts/lib/NonEmptyArray'
import { semigroupSum } from 'fp-ts/lib/Semigroup'

const fold = foldMap(semigroupSum)<number>(identity)
const result = fold([1, 2, 3, 4, 5])
```

**Comment by vicrac** [comment]
@gcanti Sure it can be done via some helpers, but is that handy (manually passing type parameter...)? I'd say that if there's `foldMap` for `NonEmptyArray` we should also have `fold` for simpler, probably more common use. It also follows the "principle of least astonishment" - if I have a `NonEmptyArray<A>`, I can `fold` over it, and I don't have to provide a `Monoid<A>`.

Should I open a PR on it?

**Comment by gcanti** [comment]
> we should also have `fold` for simpler, probably more common use

ok

> Should I open a PR on it?

Sure, thanks
