### ISSUE TITLE
Question: URIS namespace pollution by module augmentation + Naming Rule for Data Type?

### ISSUE THREAD

**Issue by civilizeddev** [gcanti/fp-ts#1091]
## 📖 Question

Once some custom data type are defined,

```
declare module 'fp-ts/lib/HKT' {
  interface URItoKind<A> {
    EitherThrowableOr: EitherThrowableOr<A>
    Test: Test<A>
  }
}
```

Those are permanently added to `URItoKind<A>` during the project.

That means `URIS` namespace is polluted.

Then I cannot use the same name as I have already defined for other data types.

(Kind of intrinsic data types, such as `EitherThrowableOr`, are likely to be reused, but `Test` are not.)

What if someone try to use `Test` again for another data type that he define?

So I think the name `Test` is not proper for custom data type.

## Suggestion

To avoid this URI name collision, a naming convention for data types is needed.

Let me hear your wisdom.

Thank you.

**Comment by raveclassic** [comment]
@civilizeddev You can use something more verbose and unique as a value like:
```typescript
const URI = '@<your-package-or-project-namespace>/<some-verbose-type-name>'
type URI = typeof URI
declare module 'fp-ts/lib/HKT' {
  interface URItoKind<A> {
    [URI]: Test<A>
  }
}
```

**Comment by civilizeddev** [comment]
So far, so good.
I wish TypeScript had supported HKT natively.
