### ISSUE TITLE
Provide module-level type alias (for aesthetic matter)

### ISSUE THREAD

**Issue by civilizeddev** [gcanti/fp-ts#1097]
### Current Behavior

- impossible
  ``` 
  import { ReaderTaskEither } from 'fp-ts/lib/ReaderTaskEither'
  import * as ReaderTaskEither from 'fp-ts/lib/ReaderTaskEither'
  ```

- possible, but awkward (`ReaderTaskEither.ReaderTaskEither?`)
  ```
  import * as ReaderTaskEither from 'fp-ts/lib/ReaderTaskEither'
  
  const m: ReaderTaskEither.ReaderTaskEither<...>
  ...
  ReaderTaskEither.chain(...)
  ```

- possible, but redundant (I have to declare import double for each type)
  ```
  import { ReaderTaskEither } from 'fp-ts/lib/ReaderTaskEither'
  import * as RTE from 'fp-ts/lib/ReaderTaskEither'

  const m: ReaderTaskEither<...>
  ...
  // Later, someone might wonder what RTE is.
  RTE.chain(...)
  ```

### Desired Behavior

- Usage
  ```
  import * as ReaderTaskEither from 'fp-ts/lib/ReaderTaskEither'
  
  const m: ReaderTaskEither.Type<...>
  ...
  ReaderTaskEither.chain(...)
  ```

### Suggested Solution

- Add module-level type alias

  ```
  export interface ReaderTaskEither { ... }

  // alias
  export type Type = ReaderTaskEither
  ```

### Who does this impact? Who is this for?

- Everyone who use fp-ts.
- It won't break the current interface.

### Describe alternatives you've considered

It would make a better code convention when writing with fp-ts.

### Additional context

N/A

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.4.1           |
| TypeScript | 3.7.5           |

**Comment by gcanti** [comment]
> possible, but redundant (I have to declare import double for each type)

you can do

```ts
import * as RTE from 'fp-ts/lib/ReaderTaskEither'

import ReaderTaskEither = RTE.ReaderTaskEither

const m: ReaderTaskEither<...>
```

**Comment by SamHH** [comment]
Another option is to make the types ambient/global (in a `*.d.ts` file):

```typescript
type TaskEither<E, A> = import('fp-ts/lib/TaskEither').TaskEither<E, A>;
```

**Comment by civilizeddev** [comment]
Thank you for your idea.

I'd rather bear with `ReaderTaskEither.ReaderTaskEither`

```
import * as ReaderTaskEither from 'fp-ts/lib/ReaderTaskEither'
import * as TaskEither from 'fp-ts/lib/TaskEither'
import * as Task from 'fp-ts/lib/Task'
import * as Either from 'fp-ts/lib/Either'

ReaderTaskEither.chain(...)
TaskEither.chain(...)
Task.chain(...)
Either.chain(...)
```

I think it's better than using initials like `RTE`.
Because some types are mapped to the same initials, confusing.

`Alt` => `A`
`Apply` => `A`
`Applicative` => `A`
`Monoid` => `M`
`Monad` => `M`
`Task` => `T`
`These` => `T`
`Traversable` => `T`

**Comment by mlegenhausen** [comment]
Then I would recommend to use the direct exports from the `index.ts`

```ts
import { readerTaskEither, taskEither, task, either } from 'fp-ts'
```

> I think it's better than using initials like RTE.
> Because some types are mapped to the same initials, confusing.

You would not do that for all exports. `Monoid`, `Monoad`, `Semigroup`, `Traversable`, `Ord`, `Eq` could mostly be exported without a `*` cause of the unique naming of functions in these modules. In practice I simply extend the exports a little bit like

```ts
import * as R from 'fp-ts/lib/Record'
import * as Rr from 'fp-ts/lib/Reader'
```

In a project I would recommend to create a `prelude.ts` file and define the naming convention you want.

**Comment by civilizeddev** [comment]
> @mlegenhausen wrote:
> You would not do that for all exports. Monoid, Monoad, Semigroup, Traversable, Ord, Eq could mostly be exported without a * cause of the unique naming of functions in these modules.

You're right. I should have mentioned data types instead of type classes.

> @mlegenhausen wrote:
> In a project I would recommend to create a prelude.ts file and define the naming convention you want.

`Prelude.ts` seems to be a good idea.
Thank you.

**Comment by civilizeddev** [comment]
I found out that there was no general import style for fp-ts.

- Some import directly from `fp-ts` (mostly in trivial example code)
- Some import from the sub modules and directly use exported functions. (mostly in trivial example code)
- Some import from the sub modules and use module aliases. (E, I, O, T, TE...)
- Some import from the sub modules and use module as namespace. (TaskEither.chain)

I think it's best to get used to anything first.
