### ISSUE TITLE
ReaderIOEither support

### ISSUE THREAD

**Issue by sobolevn** [gcanti/fp-ts#1106]
## 📖 Documentation

Hi! Thanks a lot for this awesome library.

From the docs it is not clear how to use `Reader` with `IOEither` monad as a result type.
Currently the docs only covers `ReaderEither`.

Should it be a separate type that is currently missing?

I would be very grateful if you will cover this case for users like me 🙂

**Comment by sobolevn** [comment]
Here's the problem I am talking about: https://stackblitz.com/edit/typescript-c5rjgc?file=index.ts

Code:

```ts
import { right, IOEither } from 'fp-ts/lib/IOEither'
import { Either } from 'fp-ts/lib/Either'
import * as r from 'fp-ts/lib/ReaderEither'

const one: IOEither<never, number> = right(1)
const reader: <R>() => r.ReaderEither<R, never, number> = r.fromEitherK(one)
const result: Either<never, number> = reader()(1)
```

Isn't `IO` erased during `fromEitherK` call?

**Comment by gcanti** [comment]
> Should it be a separate type that is currently missing?

Yes, you may want a `ReaderIOEither` data type (see `ReaderTaskEither` for reference)

**Comment by sobolevn** [comment]
Can I work on it? 

Because I will do the same thing for `returns` and I want to contribute to this library as well.

**Comment by gcanti** [comment]
There's no `ReaderIOEither` data type in `fp-ts` because it seems of little use: programs (both frontend and backend) will likely run in a monad stack containing `Task`, so you end up with `ReaderTaskEither` anyway. 

Maybe in [fp-ts-contrib](https://github.com/gcanti/fp-ts-contrib).

**Comment by sobolevn** [comment]
Oh, I see. This is language specific. Because, we don't have almost any async operations in Python. Only its own sublanguage called `asyncio`-stack. I will send a PR to the `fp-ts-contrib` then!

Thanks!
