### ISSUE TITLE
Overload for `zip` for `NonEmptyArray`?

### ISSUE THREAD

**Issue by vicrac** [gcanti/fp-ts#1109]
## 🚀 Feature request
Shouldn't there be an overload for zipping two `NonEmptyArrays`, resulting also in a `NonEmptyArray`?
### Current Behavior
```ts
import { zip } from 'fp-ts/es6/Array';
import { head } from 'fp-ts/es6/NonEmptyArray';

head(zip([0], [1]))  // type error: Property '0' is missing in type '[number, number][]' but required in type 'NonEmptyArray<[number, number]>'
```
### Desired Behavior
```ts
import { head, zip } from 'fp-ts/es6/NonEmptyArray';

head(zip([0], [1]))  // yields a tuple [0, 1]
```
### Suggested Solution

a) add a zip implementation and signature to `NonEmptyArray` module
b) define an overload to `zip` in `Array` module

### Who does this impact? Who is this for?

Anyone using zip with `NonEmptyArrays`

### Describe alternatives you've considered

Asserting or filtering on Array's length? Non really convenient.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.4      |
| TypeScript |      3.7.3      |

**Comment by gcanti** [comment]
> b) define an overload to zip in Array module

@vicrac to `zip`, `zipWith` and `unzip` I think
