### ISSUE TITLE
Broken in IE11 when built with Webpack

### ISSUE THREAD

**Issue by ben-x9** [gcanti/fp-ts#1110]
The package.json file includes `main` and `module` fields but is missing a `browser` field.

The result is that when building with `target` set to `web` the import resolves to `module` which points to `es6/index.js` which includes arrow functions that break in IE11.

To fix this add a `browser` field to package.json that points to `lib/index.js`:

```
"main": "lib/index.js",
"module": "es6/index.js",
"browser:" "lib/index.js",
```

see: https://webpack.js.org/configuration/resolve/#resolvemainfields

**Comment by gcanti** [comment]
@ben-x9 from https://github.com/defunctzombie/package-browser-field-spec

> If your module is pure javascript and can run in both client and server environments, then you do not need a browser field

All `fp-ts` modules can run in both client and server environments

**Comment by ben-x9** [comment]
@gcanti `fp-ts` modules compiled to es6 cannot run in older browser environments that do not support es6 features. Is fp-ts intentionally dropping support for IE11?

**Comment by gcanti** [comment]
IIUC the `browser` field in meant to be used when certain features are not available, for example `localStorage` (*) or the DOM in a node.js environment.

(*) that's the reason why [fp-ts-local-storage](https://github.com/gcanti/fp-ts-local-storage) is a package on its own

**Comment by ben-x9** [comment]
Perhaps... but the fact is that Webpack will opt for the `module` field when compiling for a web environment... despite that many web environments don't support es6, as discussed this Webpack issue: https://github.com/webpack/webpack/issues/5756#issuecomment-504872927

The consensus on that thread seems to be that packages with a `module` field that are also intended for browser environments should also provide a `browser` field.

Other libraries have opted to add a `browser` field to fix this issue: https://github.com/KingSora/OverlayScrollbars/pull/166

Another possible solution would be to remove `"target": "es6"` from `tsconfig.build-es6.json`. This would allow Webpack to resolve imports via es6 modules but have the resulting js bundle work in all javascript environments. But really this feels wrong, es6 should be es6.

**Comment by ben-x9** [comment]
`react-bootstrap` opts for the `modules` field to point to es5 compiled code that uses es6 imports.

https://github.com/react-bootstrap/react-bootstrap

**Comment by ben-x9** [comment]
The project I'm working on has hundreds of dependencies, and the only two dependencies that choked in IE11 are `fp-ts` and `monocle-ts`. So it appears having a `module` field that points to actual es6 code (as opposed to es5 code with es6 imports) and no `browser` field is very very uncommon.

**Comment by gcanti** [comment]
> the module field to point to es5 compiled code that uses es6 imports

this is what `fp-ts` already does, however looks like we had a regression here https://github.com/gcanti/fp-ts/blob/938e44486461dc67c1cd344c9368952bd50964a4/tsconfig.build-es6.json#L5

**Comment by ben-x9** [comment]
Ok I see, so that was not intentional. Fantastic, problem solved!
