### ISSUE TITLE
[feature request] Set/toggle

### ISSUE THREAD

**Issue by ryota-ka** [gcanti/fp-ts#1112]
## 🚀 Feature request

`toggle` function in `Set`, which toggles existence of the given element in the given set.

### Current Behavior

N/A

We have to define it locally every time.

### Desired Behavior

Having `toggle`  function in `Set`.

### Suggested Solution

`toggle: <A>(E: Eq<A>) => (x: A) => Endomorphism<Set<A>>` function, which behaves like:

- checks if `x` is an element of `set` under `Eq<A>`
  - if yes; `remove`s `x` from `set`
  - if no; returns `insert`s `x` into `set`

### Who does this impact? Who is this for?

All users.

### Describe alternatives you've considered

Not to implement this. (Always define `toggle` function locally.)

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.2.0           |
| TypeScript |    3.7.3        |

**Comment by gcanti** [comment]
https://github.com/gcanti/fp-ts/pull/1115
