### ISSUE TITLE
[feature request] Magma/magma{First,Last}

### ISSUE THREAD

**Issue by ryota-ka** [gcanti/fp-ts#1114]
## 🚀 Feature request

For example, `Ord` exports some basic instances like `ordString`.
in analogous to that, how about exporting `magmaFirst` and `magmaLast` from `Magma`?

### Current Behavior

N/A

### Desired Behavior

some basic instances of `Magma` is exported from `fp-ts/lib/Magma`.

### Suggested Solution

```typescript
// `src/Magma.ts`

export const magmaFirst = {
  concat<A>(x: A, _: A): A {
    return x;
  },
};

export const magmaLast = {
  concat<A>(_: A, x: A): A {
    return x;
  }
};
```

### Who does this impact? Who is this for?

All users

### Describe alternatives you've considered

Not to export such stuff from the module.

### Additional context

In Haskell's [`base`](https://hackage.haskell.org/package/base/) package, [`First`](http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Semigroup.html#t:First) and [`Last`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Semigroup.html#t:Last) are defined as `newtype`s, and they have corresponding [`Semigroup`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Semigroup.html#t:Semigroup) instances (Haskell doesn't have `Magma` in the standard library.)

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.2.0      |
| TypeScript |     3.7.3       |

**Comment by gcanti** [comment]
What about [using the Semigroup instances](https://github.com/gcanti/fp-ts/blob/305641abaf7a8290b1c6b996dfcffcd5f97da759/src/Semigroup.ts#L27-L36)?

**Comment by ryota-ka** [comment]
@gcanti oops, I've missed that.
BTW, is there a fair reason not to put them in `Magma` (which is a more general concept)?

**Comment by gcanti** [comment]
> is there a fair reason not to put them in Magma

Because a `Semigroup` is also a `Magma`, so what's the benefit? It would be just a duplication of code

**Comment by raveclassic** [comment]
@gcanti We could reuse `Magma` helpers in `Semigroup` module: 
```typescript
import { getFirstMagma } from './Magma.ts'
export const getFirstSemigroup = getFirstMagma
```

What do you think?

**Comment by ryota-ka** [comment]
> what's the benefit? It would be just a duplication of code

IMHO we can achieve more proper abstraction of module structure with it.

In my case, `Map.fromFoldable` requires me to put a `Magma` instance to it, so I straightforwardly took a look into `Magma` module, found no pre-defined instance. I thought I have to provide an instance all by myself.
At that moment who will take a look into `Semigroup` module, which is more **specific** algebraic structure?
I believe end users will benefit from proper abstraction as they can use the library more intuitively.

Additionally, as @raveclassic points out (thanks!), we can reuse the implementation defined in `Magma` also in `Semigroup`, if you wish to avoid a breaking change.

**Comment by gcanti** [comment]
@raveclassic @ryota-ka are you proposing to move _all_ the semigroup instances to the `Magma.ts` module?

I'd just add a short comment instead:

```ts
/**
 * A `Magma` is a pair `(A, concat)` in which `A` is a non-empty set and `concat` is a binary operation on `A`
 * 
 * See [Semigroup](...) for some instances.
 *
 * @since 2.0.0
 */
export interface Magma<A> {
  readonly concat: (x: A, y: A) => A
}
```

`Magma` is (almost) useless, was added to make easier to pass a `Semigroup` to some APIs (like `Map.fromFoldable`).

**Comment by ryota-ka** [comment]
> @raveclassic @ryota-ka are you proposing to move _all_ the semigroup instances to the `Magma.ts` module?

At first I didn't mean it, but now I think it's better to have all non-associative instances in `Magma`.
But it'll be a big change and your comment looks sufficient.
My proposal is not a strong one.

@raveclassic What do you think?

**Comment by raveclassic** [comment]
I think  the comment is fine for now but ee should think about moving instances to Magma module once again before v3.0
