### ISSUE TITLE
`Array` `updateAt`: use "update function"

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#1127]
`updateAt` requires the new value to be provided immediately:

```ts
A.updateAt(1, 2)(xs)
```

But sometimes we want to derive the new value from the previous value. `updateAt` could allow an update function to be used, similar to https://package.elm-lang.org/packages/elm-community/list-extra/7.1.0/List-Extra#updateAt:

```ts
A.updateAt(1, x => x + 1)(xs)
```

**Comment by gcanti** [comment]
[modifyAt](https://gcanti.github.io/fp-ts/modules/Array.ts.html#modifyat)?

**Comment by OliverJAsh** [comment]
Ah, thanks!
