### ISSUE TITLE
Is there a thrush (T) combinator?

### ISSUE THREAD

**Issue by vicrac** [gcanti/fp-ts#1136]
## 🚀 Feature request

I'd like to have a combinator for "inverting" function application - see example below.

### Current Behavior

Let's say I have several functions I'd like to apply to a fixed argument (e.g. several statistics applied to the same numeric data):
```ts
const data = [1, 2, 18, 5, 4, 9];

// some defined functions (data: Array<number>) => number
const stats = [sum, avg, std, var, max, min];

// In my view
stats.map(stat => stat(data))
```
which looks a bit polluted to me.

### Desired Behavior

I'd like to have combinator similar to Ramda's `applyTo`, Haskell's thrush combinator and Sanctuary's `T`:

```ts
stats.map(T(data))
```

### Suggested Solution

```
export function T<A>(a: A): <B>(fab: (a: A) => B) => B {
    return fab => fab(a);
}
```

### Describe alternatives you've considered

Using arrow function - personally, it's a bit polluted.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.4      |
| TypeScript |      3.7.3      |

**Comment by raveclassic** [comment]
Sidenote - this may quickly end in reimplementing ramda in fp-ts core.

**Comment by vicrac** [comment]
Btw if it's not overlapping with existing implementations and naming, I would also appreciate implementing other combinatory logic combinators (w.g. `W` - duplicate argument, and `C` - swap arguments) - it's not not only just another util, it's also following certain established and battle-tested convention (e.g. Sanctuary has it implemented, and it helps when transitioning).

**Comment by raveclassic** [comment]
Have you tried https://github.com/giogonzo/fp-ts-ramda ?

**Comment by giogonzo** [comment]
PRed here ^

**Comment by gcanti** [comment]
Note: it doesn't play well with polymorphic functions

```ts
import { head, reverse, copy } from 'fp-ts/lib/Array'

export function T<A>(a: A): <B>(f: (a: A) => B) => B {
  return f => f(a)
}

// const x: Option<unknown>[]
const x = [head].map(T([1, 2, 3]))

// const y: unknown[][]
const y = [reverse, copy].map(T([1, 2, 3]))
```

**Comment by vicrac** [comment]
Well, I guess if there's no workaround for this (some additional type parameter, defaulting to `unknown` maybe?) I have to give up on that one :broken_heart:
