### ISSUE TITLE
Piping a Task \ Pipe accepts function that does not take a Task

### ISSUE THREAD

**Issue by cassioarosa** [gcanti/fp-ts#1152]
### Current Behavior

I was studying the library, and I came out with a wrong implementation of the [example](https://github.com/gcanti/fp-ts/blob/master/examples/fp-ts-to-the-max-II.ts) that only printed the last line.
 
The example bellow only prints the third line.

### Expected behavior

Since printThirdLine is not a T.Task the code should not compile.

### Reproducible example

```TypeScript
import * as T from "fp-ts/lib/Task";
import { log } from "fp-ts/lib/Console";
import { flow } from "fp-ts/lib/function";
import { pipe } from "fp-ts/lib/pipeable";

const putStrLn = flow(log, T.fromIO);

const initialValue = T.of(true);
const printFirstLine = T.chain(value => putStrLn(`First Line ${value}`));
const printSecondLine = T.chain(_ => putStrLn(`Second Line`));
const printThirdLine = () => putStrLn(`Third Line`);
//const printThirdLine = T.chain(_ => putStrLn(`Third Line`)); // working

let task = pipe(initialValue, printFirstLine, printSecondLine, printThirdLine);

task().then();
```

### Suggested solution(s)

If possible, apply some restriction to ensure that return type of function bc, matches the arguement of function cd, diagram bellow.

![image](https://user-images.githubusercontent.com/3159047/75509235-a16e2100-59c5-11ea-8461-1a8158504352.png)

Or any other way to invalidate the code, since it could case a lot of confusion.

### Additional context

Is there a better and safer, via compile error,  way to avoid errors like these?

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |  2.4.2  |
| TypeScript | 3.7.5  |

**Comment by gcanti** [comment]
This is not a bug, `printThirdLine` is just ignoring the output of `printSecondLine` (which is legal even if it wasn't your intention)

> ensure that return type of function bc, matches the arguement of function cd

It's already ensured by the type parameters

```ts
let task = pipe(initialValue, printFirstLine, printSecondLine, printThirdLine)
```

^ here the inferred type parameters are

```ts
// C ----------------------------------v
pipe<T.Task<boolean>, T.Task<void>, T.Task<void>, T.Task<void>>
```

> If possible, apply some restriction

I don't think is possible

**Comment by aqrln** [comment]
@cassioarosa to clarify, this has nothing to do with `fp-ts` itself, that's just how TypeScript works. `() => B` is assignable to `(x: A) => B` in TypeScript because it is valid in JavaScript at run time, so that's basically the same thing as a function that ignores its argument.

**Comment by cassioarosa** [comment]
@aqrln, thanks for the explanation.

But seems that this restriction could somehow be added into the pipe function, bellow is an idea using conditional type.

```TypeScript

  declare interface INeedBeCalled {}

  interface Task<A> extends INeedBeCalled {
    (): Promise<A>;
  }

  declare const initialValue: Task<boolean>;
  declare const firstLine: (ma: Task<boolean>) => Task<void>;
  //declare const secondLine: (ma: Task<void>) => Task<void>; // working
  declare const secondLine: () => Task<void>; // compilation error

  declare function pipe<A, B, C, BArg>(
    a: A,
    ab: (a: A) => B,
    bc: (b: BArg) => C
  ): B extends INeedBeCalled ? (BArg extends B ? BArg : never) : C;


  let task = pipe(initialValue, firstLine, secondLine);
  task()
/*  
  ↑
  Compilation error: This expression is not callable. Type 'never' has no call signatures.
*/

```
