### ISSUE TITLE
Higher kinded monoid and semigroup for arrays

### ISSUE THREAD

**Issue by frndmg** [gcanti/fp-ts#1153]
### Current Behavior

It has not been implemented. Or I have been unable to find it.

### Desired Behavior

To have a way to concat `Kind<M, A[]>` types.

Posible use case:

- Generically implement collect from `Task<Either<E, A>>[]` or `IO<Either<E, A>>[]`

Example:

```ts
export const collect = <M extends URIS>(m: Monad1<M>) => <A>(
  te: Kind<M, A>[],
): Kind<M, A[]> => {
  const monoid = getHKTArrayMonoid<M, A>(m); // this is the function I am proposing

  return pipe(
    te,
    foldMap(monoid)(a => m.map(a, v => [v])),
  );
};
```

NOTE: Implement this function generically is my primary interest.

### Suggested Solution

```ts
export const getHKTArraySemigroup: <M extends URIS, A>(
  m: Monad1<M>,
) => Semigroup<Kind<M, A[]>> = m => ({
  concat: (x, y) => m.chain(x, a => m.map(y, b => concat(a)(b))),
});

export const getHKTArrayMonoid: <M extends URIS, A>(
  m: Monad1<M>,
) => Monoid<Kind<M, A[]>> = m => ({
  empty: m.of([] as any),
  concat: (x, y) => m.chain(x, a => m.map(y, b => concat(a)(b))),
});
```

NOTE: I am not sure those are the best names :sweat_smile: 

### Describe alternatives you've considered

I have tried to use direct monoid and semigroup implementations from Array but it is different from what I am proposing.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.5.3           |
| TypeScript | 3.8.2           |

**Comment by gcanti** [comment]
@frndmg `collect` is `sequence` (from `Traversable`) which only requires an `Applicative` instance

```ts
import * as A from 'fp-ts/lib/Array'
import * as IE from 'fp-ts/lib/IOEither'
import * as TE from 'fp-ts/lib/TaskEither'

declare const tes: Array<TE.TaskEither<string, number>>

// result1: TE.TaskEither<string, number[]>
const result1 = A.array.sequence(TE.taskEither)(tes)

declare const ies: Array<IE.IOEither<string, number>>

// result2: IE.IOEither<string, number[]>
const result2 = A.array.sequence(IE.ioEither)(ies)
```

**Comment by frndmg** [comment]
@gcanti Sorry for my late reply.

The issue here is that I want the whole list of `Either`s, not just the accumulation of the results because it brokes when an error occurs if I use `sequence`.

Example:

```ts
import * as E from 'fp-ts/lib/Either'
import * as T from 'fp-ts/lib/Task'
import * as TE from 'fp-ts/lib/TaskEither'

declare const tes: Array<TE.TaskEither<string, number>>

// result1: T.Task<Array<E.Either<string, number>>>
const result1 = collect(T.task)(tes)
```

**Comment by gcanti** [comment]
@frndmg that's `sequence` again, configured with `T.task` this time 

```ts
import * as A from 'fp-ts/lib/Array'
import * as T from 'fp-ts/lib/Task'
import * as TE from 'fp-ts/lib/TaskEither'

declare const tes: Array<TE.TaskEither<string, number>>

// result1: T.Task<Array<E.Either<string, number>>>
const result1 = A.array.sequence(T.task)(tes)
```

**Comment by gkamperis** [comment]
@gcanti sorry to hijack this issue to ask this but how would you sequenseS Options that would keep only the Somes and ignore the Nones...

Because currently and in the example in the code it will be none...

So instead of this
```
const adoOption = sequenceS(option)

    assert.deepStrictEqual(adoOption({ a: some(1), b: none }), none)
```

return this
`    assert.deepStrictEqual(whatToDoHere({ a: some(1), b: none }), some({ a: 1 }))`

**Comment by raveclassic** [comment]
@gkamperis Looks like https://github.com/gcanti/fp-ts/blob/6fe1808dedd879be1add109c27709ced2cb3c753/src/ReadonlyRecord.ts#L716-L726

**Comment by gkamperis** [comment]
@raveclassic thanks! Am using array.compact all the time... Need to read about compactables... :)
