### ISSUE TITLE
Testing monadic code

### ISSUE THREAD

**Issue by schusovskoy** [gcanti/fp-ts#1157]
Hi there! I've read a bunch of resources about FP and using it with JS/TS and finally found fp-ts. I suppose that it is what I was looking for. But after all the information I managed to find and read, I still have a question.

One of the benefits of using pure functions is the ability to test them easily. And I totally agree with this until it comes to using IO monad for example. So my question is how do I test monadic code?

**Comment by mikearnaldi** [comment]
Using monadic code doesn't imply testability per-se as an IO is just a value with a reference to a function that will perform an effect when executed, there are many methods to achieve easier testability one of which is the tagless final approach an example can be found in:
https://github.com/gcanti/fp-ts/blob/master/examples/fp-ts-to-the-max-II.ts

The advantages of tagless is complete freedom but the price is verbosity, in this approach you can test your programs by providing mocked implementation of your typeclasses as you see fit.

Another approach would be embedding dependencies using some form of Reader for example ReaderTaskEither or similar.

On the second approach a complementary library you might find useful is https://github.com/mikearnaldi/matechs-effect that is basically a more complete variant of ReaderTaskEither that allows for varying environment and error parameters. 

The drawback of the second approach is that is no longer possible to provide a different base effect but you can still provide all your dependencies. (In scala you find this method used in ZIO).

The third method would be the classic mocking approach (with jest/mocha/whatever).

**Comment by schusovskoy** [comment]
Thanks for your response! I will study the second approach. Could you suggest any learning resources on this topic?
BTW where it would be better to ask questions like this to not open unnecessary issues?

**Comment by mikearnaldi** [comment]
For a public room to discuss things I advice https://fpchat-invite.herokuapp.com/ one of the channels is #typescript as of material on the second approach there is not much for ts yet my advice would be to look at ZIO in scala that uses the same pattern
