### ISSUE TITLE
How to prevent auto-suggestion when using boolean type in Intellij-IDEA

### ISSUE THREAD

**Issue by jeemyeong** [gcanti/fp-ts#1159]
### Current Behavior

![image](https://user-images.githubusercontent.com/13030735/76136984-10f5a780-607b-11ea-88fa-c50edfee6ca9.png)

Always when I use Intellij-IDEA, it shows auto-suggestion for boolean type.

### Expected behavior

I wanna ignore auto-suggestion

### Your environment

| Software   | Version(s) |
| fp-ts      |    2.0.1     |
| TypeScript |  3.7.4         |
| Intellij IDEA | 2019.3 |

**Comment by gcanti** [comment]
Not sure how this is related to `fp-ts` (maybe because there's a `boolean.ts` module?), you may want to open an issue in Intellij-IDEA

**Comment by jeemyeong** [comment]
That boolean means boolean in `fp-ts`. I need to find another way to solve this. Thx.
