### ISSUE TITLE
Add getting started to sidebar

### ISSUE THREAD

**Issue by waynevanson** [gcanti/fp-ts#1161]
I'm new to FP in this pure way, so as someone who is learning I think this would make things easier for the next person.

## 📖 Documentation

This documentation link exists, which is very helpful: https://gcanti.github.io/fp-ts/getting-started/Functor.html

However, it is not displayed in the sidebar of the website, which I believe it should be.

**Comment by gcanti** [comment]
@waynevanson forgot to remove the `docs/getting-started` folder in https://github.com/gcanti/fp-ts/pull/1105, thanks for pointing out

p.s.
you can find my blog posts [here](https://dev.to/gcanti)
