### ISSUE TITLE
comprehension TypeScript errors

### ISSUE THREAD

**Issue by GrayStrider** [gcanti/fp-ts#1162]
## 🐛 Bug report
`comprehension` example from [docs](https://gcanti.github.io/fp-ts/modules/Array.ts.html#comprehension)
### Current Behavior

TS complains, tests pass
![image](https://user-images.githubusercontent.com/43771776/76528367-cb930900-64c4-11ea-8697-4ebb098785e4.png)

### Reproducible example
```TS
	const exp = [
		[1, 'a'],
		[1, 'b'],
		[3, 'a'],
		[3, 'b']
	]
	const input: [number[], string[]] =
		[
			[1, 2, 3], ['a', 'b']
		]
	const act = comprehension<number, string> (
		input,
		tuple,
		(a, b) => (a + b.length) % 2 === 0
	)
```
### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |       ^2.5.3     |
| TypeScript |      3.8.3      |

**Comment by gcanti** [comment]
This is wrong

```ts
comprehension<number, string>
```

should be

```ts
comprehension<number, string, [number, string]>
```

or, even better, let TypeScript infer the type parameters.

**Comment by GrayStrider** [comment]
@gcanti 
Copied from docs:
![image](https://user-images.githubusercontent.com/43771776/76531720-bf5d7a80-64c9-11ea-8cfd-5cf953e12c64.png)

Explicit typings not working either:
![image](https://user-images.githubusercontent.com/43771776/76531839-e3b95700-64c9-11ea-9067-00455991de2b.png)

**Comment by GrayStrider** [comment]
Whoops, my bad: `tuple` wasn't imported.

**Comment by GrayStrider** [comment]
For some reason it's detected as some global variable, idk. Works now.
