### ISSUE TITLE
missing currying for many functions

### ISSUE THREAD

**Issue by GrayStrider** [gcanti/fp-ts#1163]
https://gcanti.github.io/fp-ts/modules/Array.ts.html#cons

I would expect to be able to do
```TS
const addOne = cons(1)
let withOne = addOne([2, 3]) // [1, 2, 3]
withOne = addOne([]) // [1]
```
But it only accepts 2 arguments.
![image](https://user-images.githubusercontent.com/43771776/76529299-35f87900-64c6-11ea-932d-32f82e7f8bb2.png)

What am I missing?

**Comment by DenisFrezzato** [comment]
`cons` is not curried, as its type signature shows: `<A>(head: A, tail: Array<A>) => NonEmptyArray<A>`.

**Comment by GrayStrider** [comment]
I'm aware it's not curried, I just can't see the reason why it's not

**Comment by GrayStrider** [comment]
Seem to work fine. Strange limitation
```TS
export function consCurried<A> (head: A):
  (tail: ReadonlyArray<A>) => ReadonlyNonEmptyArray<A> {
  return (tail: ReadonlyArray<A>) => {
    const len = tail.length
    const r = Array (len + 1)
    for (let i = 0; i < len; i++) {
      r[i + 1] = tail[i]
    }
    r[0] = head
    return (r as unknown) as ReadonlyNonEmptyArray<A>
  }
}

it ('cons curried', async () => {
  expect.assertions (1)
  const act = consCurried (0)
  const exp = [0, 1, 2]
  isSE (act ([1, 2]), exp)
})

it ('cons curried empty', async () => {
  expect.assertions (1)
  const act = consCurried (0)
  const exp = [0]
  isSE (act ([]), exp)
})

function isSE (act?: unknown, exp?: unknown) {
  return expect
  (act).toStrictEqual (exp)
}
```

**Comment by GrayStrider** [comment]
Oh, nevermind; going futher down the list, `difference` isn't curried  either.
@gcanti, could you give some comments on that fact? Seems to be severely limiting for function composition.

**Comment by alex-ketch** [comment]
@GrayStrider I believe currying was removed due to [limitations with TypeScript's type inference](https://github.com/gcanti/fp-ts/issues/957).

**Comment by DenisFrezzato** [comment]
@alex-ketch `curry` and `compose` functions have been deprecated and removed due to those limitations you mentioned. This doesn't mean we can't create curried function, we just have to create them explicitly.

**Comment by GrayStrider** [comment]
Yes, I'm asking what was the reasoning behind making all those functions NOT curried in the first place, what is the benefit

**Comment by GrayStrider** [comment]
Type inference works perfectly with overloading for binary functions with different types of arguments:
![image](https://user-images.githubusercontent.com/43771776/76579754-7507e800-6521-11ea-8c5f-fa83efe3a429.png)
Maybe a lot of work time-wise but difficulty is clearly trivial, at least for simple cases like this

**Comment by GrayStrider** [comment]
Here's backwards compatibility: a bit of spaghetti code but hey, it works
![image](https://user-images.githubusercontent.com/43771776/76580387-e34daa00-6523-11ea-822e-26d9ebfcd174.png)
![image](https://user-images.githubusercontent.com/43771776/76580406-ec3e7b80-6523-11ea-80a2-579e46e190bd.png)

**Comment by gcanti** [comment]
> could you give some comments on that fact?

@GrayStrider no particular reason other than you'll arguably use `cons` with both arguments more often

**Comment by GrayStrider** [comment]
On the second thought, regular un-curried functions are oftentimes better due to automatic type inference, unlike their curried brethren where you have to do it manually
