### ISSUE TITLE
Add `find` function for Set

### ISSUE THREAD

**Issue by lvitaly** [gcanti/fp-ts#1165]
### Current Behavior

The Set module does not have `get` or `find` value. The functionality of the Set gives the possibility to check is an element in the Set, but you cannot get on Option of it.

### Desired Behavior

Add `get` or `find` functionality into the Set.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.5.3           |
| TypeScript | 3.8.x           |

**Comment by lvitaly** [comment]
@gcanti I can do a PR if you don't mind.

**Comment by gcanti** [comment]
@lvitaly what's the signature?

**Comment by raveclassic** [comment]
Smth like this? 
```typescript
const lookup = <A>(E: Eq<A>) => {
	const elemE = set.elem(E);
	return (a: A, sa: Set<A>): Option<A> => (elemE(a, sa) ? some(a) : none);
};
```
But what's the point?

**Comment by lvitaly** [comment]
@raveclassic Maybe this is not the best usage example, but `elem + map + insert` can be replaced with `get/lookup + insert` here.

```ts
interface User {
  id: string
  name: string
}

interface UserWithFriends extends User {
  friends: Set<string>
}

const eqById = fromEquals<{id: string}>((a, b) => a.id === b.id)

function insertById<T extends {id: string}>(arg: T): (set: Set<T>) => Set<T> {
  return (set: Set<T>) => insert<T>(eqById)(arg)(set)
}

function insertOrMutate(user: User, friend: User): (set: Set<UserWithFriends>) => Set<UserWithFriends> {
  return set => {
    if (elem(eqById)(user, set)) {
      return map<UserWithFriends>(eqById)((uwf: UserWithFriends) => {
        if (eqById.equals(uwf, user)) {
          uwf.friends = insert(eqString)(friend.id)(uwf.friends)
        }
        return uwf
      })(set)
    }
    else return insertById({
      id: user.id,
      name: user.name,
      friends: singleton(friend.id)
    })(set)
  }
}

const usersWithFriend = new Set<UserWithFriends>()

insertOrMutate({id: 'jon', name: 'Jon Snow'}, {id: 'imp', name: 'Tyrion Lannister'})(usersSet)
```

and `insertOrMutate` can be rewritten 

```ts
function insertOrMutate(user: User, friend: User): (set: Set<UserWithFriends>) => Set<UserWithFriends> {
  return set => insertById(
    pipe(
      lookup(eqById)(user, set),
      map((uwf: UserWithFriends) => {
        uwf.friends = insert(eqString)(friend.id)(uwf.friends)
        return uwf
      }),
      getOrElse(() => ({
        id: user.id,
        name: user.name,
        friends: singleton(friend.id)
      }))
    )
  )
```

but maybe it's just a bad implementation of logic.

**Comment by raveclassic** [comment]
I see that you use `Eq` comparing by `id` to provide "uniqueness" for the values of the Set. But are use sure you need a `Set` here?  

Have you considered using `Map<id, User>` instead? This would provide you the same uniqueness based on `id` as well as handy helper for modifying items in that Map: https://github.com/gcanti/fp-ts/blob/26ac6b3cd2d51bb5581e813ed44cfdb988479cdd/src/ReadonlyMap.ts#L246-L259
