### ISSUE TITLE
call the same task twice but only fire internal promise once

### ISSUE THREAD

**Issue by stevemao** [gcanti/fp-ts#1166]
## 🚀 Feature request

I have a `task`. If I call

```ts
task()
task()
```

it fires the internal promise twice. Is there a way to make it only fire once?

### Current Behavior

It fires twice. Say a http request.

### Desired Behavior

Only fire once. The second call returns the same result as the first one. 

Use case: I have 3 tasks: `t1`, `t2`, `t3`. `tA` is called once `t1` and `t2` is done. `tB` is called once `t1` and `t3` is done.  `tC` is called once `t2` and `t3` is done. With raw promise I could do

```ts
Promise.all([
   Promise.all([t1, t2]).then(_ => tA)
   Promise.all([t2, t3]).then(_ => tC)
   Promise.all([t1, t3]).then(_ => tB)
]).then(...)
```

But with Task

```ts
sequence([
   pipe(sequence([t1, t2])), chain(_ => tA)),
   pipe(sequence([t2, t3]), chain(_ => tC)),
   pipe(sequence([t1, t3]), chain(_ => tB)),
])
...
```

side effects of `t1`, `t2`, `t3` will be fired twice each.

### Suggested Solution

Honestly not sure. Maybe add a flag to:

A. Somehow make the wrapped promise the same object if they are the same promise.
B. Cache the result of the promise it's the same one.

### Who does this impact? Who is this for?

Async programming to maximise the concurrency. 

### Describe alternatives you've considered

1. raw promise. 
2. memoization

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.5.0      |
| TypeScript |     3.7.5       |

**Comment by gcanti** [comment]
> Use case: I have 3 tasks: t1, t2, t3. tA is called once t1 and t2 is done. tB is called once t1 and t3 is done. tC is called once t2 and t3 is done

Looks like memoization is the best option

```ts
import { IO } from 'fp-ts/lib/IO'

export function memoize<A>(ma: IO<A>): IO<A> {
  let cache: A
  let done: boolean = false
  return () => {
    if (!done) {
      cache = ma()
      done = true
    }
    return cache
  }
}
```

Example

```ts
import * as T from 'fp-ts/lib/Task'
import * as A from 'fp-ts/lib/Array'
import { pipe } from 'fp-ts/lib/pipeable'

let counter = 0

const make = (label: string, delay: number): T.Task<string> =>
  T.delay(delay)(() => Promise.resolve(`${label}: ${counter++}`))

const t1 = make('t1', 100)
const t2 = make('t2', 200)
const t3 = make('t3', 1000)

const sequence = A.array.sequence(T.task)

export function current() {
  console.time('current')
  const log = (label: string) => (a: unknown): IO<void> => () => console.timeLog('current', `${label}: ${a}`)
  return sequence([
    pipe(sequence([t1, t2]), T.chainIOK(log('tA'))),
    pipe(sequence([t2, t3]), T.chainIOK(log('tC'))),
    pipe(sequence([t1, t3]), T.chainIOK(log('tB')))
  ])
}

export function desired() {
  console.time('desired')
  const log = (label: string) => (a: unknown): IO<void> => () => console.timeLog('desired', `${label}: ${a}`)
  const mt1 = memoize(t1)
  const mt2 = memoize(t2)
  const mt3 = memoize(t3)
  return sequence([
    pipe(sequence([mt1, mt2]), T.chainIOK(log('tA'))),
    pipe(sequence([mt2, mt3]), T.chainIOK(log('tC'))),
    pipe(sequence([mt1, mt3]), T.chainIOK(log('tB')))
  ])
}

// current()()
/*
current: 203.234ms tA: t1: 0,t2: 2
current: 1001.999ms tC: t2: 3,t3: 4
current: 1002.507ms tB: t1: 1,t3: 5
*/
desired()()
/*
desired: 202.854ms tA: t1: 0,t2: 1
desired: 1002.817ms tC: t2: 1,t3: 2
desired: 1003.321ms tB: t1: 0,t3: 2
*/
```
