### ISSUE TITLE
Applicative on TaskEither does not respect Monad equivalence law

### ISSUE THREAD

**Issue by Avaq** [gcanti/fp-ts#1173]
### Current Behavior

```ts
import * as TE from 'fp-ts/lib/TaskEither';
import * as E from 'fp-ts/lib/Either';

const t: TE.TaskEither<string, number> = TE.ap(TE.fromIOEither(() => {
    console.log ('effect 1');
    return E.right (1) as E.Either<string, number>;
}))(TE.fromIOEither(() => {
    console.log ('effect 2');
    return E.left ('fail');
}))

t()
```
```text
effect 2
effect 1
```

### Expected behavior

- I expected `effect 1` to not take place
- Alternatively, I expected `effect 1` to take place before effect 2

Put differently: I expect `ap (mx) (mf)` to be equivalent to `chain (f => map (f) (mx)) (mf)`, where equivalence is defined both in terms of tangible return value, *and monadic effects* (branching and execution order, in this case).

### Suggested solution(s)

If I'm not mistaken, my expectations align with the generally accepted views on how Applicative should interact with Monad instance on the same type. But I might be mistaken. If you believe this is something worth pursuing, I suppose the solution would involve a change the `ap` implementation on (probably) Task. :man_shrugging: 

### Additional context

I ran into this today doing something like this:

```ts
pipe (
  checkDeletionPermission,
  apSecond (deleteFile)
)
```

Where I expected the `deleteFile` TaskEither to run only if `checkDeletionPermission` would not return a `TaskEither.left`. But I later found that `deleteFile` was running under all circumstances, independent of the effects from `checkDeletionPermission`.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.5.3 |
| TypeScript | 3.8.3 |

**Comment by gcanti** [comment]
@Avaq this is intended, the default `Applicative` instance is parallel (for the record, there's an alternative `taskEitherSeq` instance which is sequential).

> my expectations align with the generally accepted views on how Applicative should interact with Monad instance on the same type

See https://github.com/gcanti/fp-ts/issues/1150

**Comment by Avaq** [comment]
Ah. Yes. It is my understanding that a parallel Applicative cannot be a Monad. Exactly because then `ap (mx) (mf) != chain (f => map (f) (mx)) (mf)`. But I also know its a common point of contention. But I think that's all been mentioned in #1150. Apologies for opening a duplicate, I didn't notice #1150.
