### ISSUE TITLE
Either Left type is lost/not enforced in flow of chain 

### ISSUE THREAD

**Issue by cinoss** [gcanti/fp-ts#1184]
### Current Behavior
Consider this snippet:
```ts
import { chain, left, right } from 'fp-ts/lib/Either';
import { flow } from 'fp-ts/lib/function';

export const f1 = flow(
  (x: boolean) =>  x ? left(1) : right('1') ,
  chain(() => right({}))
);

const g = () => right({});
export const f2 = flow((x: boolean) => (x ? left(1) : right('1')), chain(g));

export const f3 = chain(() => right({}))(((x: boolean) => (x ? left(1) : right('1')))(true));

```
`f1` 's type will be inferred to be `(x: boolean) => Either<number, {}>`
however when I take out `() => right({})` (for reusability),

`f2` suddenly has type signature of `(x: boolean) => Either<never, {}>`

when I get rid of `flow` and write `f3`, type checker says:
```
Argument of type 'Left<number> | Right<string>' is not assignable to parameter of type 'Either<never, unknown>'.
  Type 'Left<number>' is not assignable to type 'Either<never, unknown>'.
    Type 'Left<number>' is not assignable to type 'Left<never>'.
      Type 'number' is not assignable to type 'never'.
```
### Expected behavior

`f2` should also have the same type as `f1`.

And if this is not how the code is supposed to be written, the error for `f3` should be produced for both `f1` and `f2`.

### Suggested solution(s)

If I redefine chain's type from
```ts
  chain: <E, A, B>(f: (a: A) => Either<E, B>) => (ma: Either<E, A>) => Either<E, B>
```

to 
```ts
chain: <E, F, A, B>(f: (a: A) => Either<F, B>) => (ma: Either<E, A>) => Either<E | F, B>
```
in my code base, then it works as expected. But I don't know if this is even remotely related to a proper solution.
### Additional context

`TaskEither` is the original type that I have this problem with. I then try Either` and face the same problem.
### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |    2.5.3        |
| TypeScript |  3.7.4          |

**Comment by gcanti** [comment]
This is not a bug, `g` has type

```ts
const g: () => Either<never, {}>
```

You may want to add an explicit type annotation to `g`

```ts
const g = (): Either<number, {}> => right({})
```
