### ISSUE TITLE
sequenceT with NonEmptyArray

### ISSUE THREAD

**Issue by kylegoetz** [gcanti/fp-ts#1192]
Is there any interest / it would be nice to have a `sequenceT` overload that accepts `NonEmptyArray` instead of a list of params. Consider the use case

```
type MissingParameterException = {name:string, message?:string }

const applicativeValidation = E.getValidation(NEA.getSemigroup<MissingParameterException>())

const getUrlParam = (URL:string) => (param:string) =>
    E.Either<'MissingParameterException',string>

const getUrlParams = (URL: string) => (...params:string[]) => 
    pipe(
        sequenceT(applicativeValidation)(**...params.map(getUrlParam(URL))**),
        E.map(someConcatOfResults)
    )
```

Right now, that doesn't work because TypeScript does not seem to infer that `...params:string[]` means params will be a *non-empty* array of strings. So `sequenceT` complains that `...params.map(...)` is missing `{readonly 0: E.Either....}`.

With this new feature, then you could:

```
const folder = O.fold(()=>E.left({name:'NoParamsException"}), as=>E.right(as))
```
and then proceed from there, passing it into `sequenceT(applicativeValidation)(folder(NEA.fromArray(params)))`

I didn't see functionality that replicates this need to spread an indefinite number of function arguments, map them into monads M, and then combine them with sequenceT(M). I've admittedly only been with fp-ts for a week.

**Comment by kylegoetz** [comment]
The idea here is that the result of `url.parse(someUrl).params` using Node's built-in url parser returns `{[index:string]:any|undefined}` and I want to create a function that replicates this but takes arguments of *which* parameters you're fetching, and then it returns `Either<MissingParamException[], ObjectWithThoseRequestedFields>`

**Comment by DenisFrezzato** [comment]
`sequenceT` is meant to be used with **T**uples, if you have to traverse an array you have to use `sequence` from the `Array` module:

```typescript
import * as A from 'fp-ts/lib/Array'
import * as E from 'fp-ts/lib/Either'
import * as NEA from 'fp-ts/lib/NonEmptyArray'
import { identity } from 'fp-ts/lib/function'
import { pipe } from 'fp-ts/lib/pipeable'

interface MissingParameterException{
  name: string;
  message?: string;
}

const applicativeValidation = E.getValidation(
  NEA.getSemigroup<MissingParameterException>()
)

declare function getUrlParam(
  URL: string
): (param: string) => E.Either<MissingParameterException, string>

const lift = <L, A>(check: (a: A) => E.Either<L, A>) => (
  a: A
): E.Either<NEA.NonEmptyArray<L>, A> =>
  pipe(check(a), E.mapLeft(NEA.nonEmptyArray.of))

const getUrlParams = (URL: string) => (params: string[]) =>
  pipe(
    A.array.sequence(applicativeValidation)(params.map(lift(getUrlParam(URL)))),
    E.map(...)
  )

```

I'm not sure this is the end result you want (in your example `someConcatOfResults` is missing and `getUrlParams` is missing the return type), but I hope it answers your question.

If you need further clarification about `sequenceT` and `array.sequence`, just ask.

**Comment by kylegoetz** [comment]
Thanks. I didn't realize JS/TS distinguished between tuples and arrays. I'll learn this today and get back to you. I thought `sequence` vs `sequenceT` was just a difference between "crappy sequencer" and "powerful sequencer" since I know `sequence`'s params must all be of the same typeclass.

**Comment by DenisFrezzato** [comment]
The runtime representation of a tuple is an array anyway, JavaScript can't distinguish them ([yet](https://github.com/tc39/proposal-record-tuple)). TypeScript is able to represent [tuples](https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple).
```typescript
type MyTuple = [string, number]
type MyArray = boolean[]
```
So, an example with `sequence` VS `sequenceT`:
```typescript
declare const k: Option<string>
declare const v: Option<number>
const a: Option<[string, number]> = sequenceT(option)(k, v)

declare const bs: Array<Option<boolean>>
const b: Option<Array<boolean>> = array.sequence(option)(bs)
```

**Comment by kylegoetz** [comment]
@DenisFrezzato  I have `"fp-ts": "^2.5.3"` but

```
import * as A from 'fp-ts/lib/Array'
A.array // fp-ts/lib/Array has no exported member 'array'

**Comment by kylegoetz** [comment]
I'm going to close this since it's been resolved.
