### ISSUE TITLE
sequenceT error inference

### ISSUE THREAD

**Issue by atrianac** [gcanti/fp-ts#1207]
### Current Behavior

For following portion of code:

```
import * as T from 'fp-ts/lib/Task'
import { sequenceT } from 'fp-ts/lib/Apply'
import { Task } from 'fp-ts/lib/Task'

const tasksV: Task<any>[] = [T.of(1), T.of(2)]
const trslt = sequenceT(T.task)(tasksV)
```

A compiler error is presented

> Argument of type '[Task<any>[]]' is not assignable to parameter of type 'Task<any>[] & { readonly 0: Task<any>; }'.
  Type '[Task<any>[]]' is not assignable to type 'Task<any>[]'.
    Type 'Task<any>[]' is not assignable to type 'Task<any>'.
      Type 'Task<any>[]' provides no match for the signature '(): Promise<any>'.ts(2345)

### Expected behavior

The code compile without errors. For the example `trslt` type should Task<any[]> 

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |    2.5.4        |
| TypeScript |   2.8.3         |

**Comment by gcanti** [comment]
- https://github.com/gcanti/fp-ts/issues/1192
- https://github.com/gcanti/fp-ts/issues/1140
- https://github.com/gcanti/fp-ts/issues/1010
