### ISSUE TITLE
(Document how|publish means to) use fp-ts in deno typescript runtime

### ISSUE THREAD

**Issue by clord** [gcanti/fp-ts#1217]
### Current Behavior

Searched https://deno.land/x for fp-ts and could not find. 

### Desired Behavior

I'd like to be able to do this in deno:

```
import * as O from 'https://<somewhere>/ts/Option.ts'
console.log(O.some(5))
```

### Suggested Solution

Not sure what is best solution to publish for deno. Needs research.

### Who does this impact? Who is this for?

Users of deno who want fp-ts.

### Describe alternatives you've considered

I tried importing es6 package and a few other options, but ran into issues. Ideally, if this already works and I'm missing something, documentation would indicate how to do this.

### Additional context

https://deno.land
https://unpkg.com

**Comment by gcanti** [comment]
Related https://github.com/gcanti/fp-ts/issues/1130

**Comment by GabeAtWork** [comment]
I've looked into it a little, and found a tool called [Denoify](https://github.com/garronej/denoify). You can see [an example here](https://github.com/garronej/my_dummy_npm_and_deno_module) with instructions on how to add it to the library.

I've done so locally, but Denoify's output isn't quite right of of the box. Here's the steps I've followed (I could write a script for it in a PR for testing purposes if you're interested):

* In the `deno_lib` folder, replace all occurrences of `declare module './HKT' {` with `declare module './HKT.ts' {`
* Likewise, replace all occurrences of ` DENOIFY: DEPENDENCY UNMET (BUILTIN)` with `.ts`
* Likewise, replace all occurrences of `'fp-ts/lib/` with `'./`

What has puzzled me when I wrote the last two lines is that they only change jsDoc example comments. I'm not quite sure why Deno parses those and makes sure they must be correct... but if they don't get changed, it ain't working 🤷‍♂️
I also tried to change the front of the path with `'https://raw.githubusercontent.com/gcanti/fp-ts/master/`, but as the files don't exist at the url, I get an error as Deno tries to download them, so... it's weird.

Anyway, once this is fixed, with the latest Deno (`deno 0.29.0`, `v8 8.1.108`, `typescript 3.7.2`), I get the following Typescript errors:
<details><summary>Reveal the errors (14 errors in total)</summary><p>

```console
error TS2322: Type 'undefined[]' is not assignable to type 'never[]'.
  Type 'undefined' is not assignable to type 'never'.

► file:///<mycomputer>/fp-ts/deno_lib/Array.ts:1568:14

1568 export const empty: Array<never> = []
                  ~~~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:111:55

111 export function getApply<E>(S: Semigroup<E>): Apply2C<URI, E> {
                                                          ~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:124:64

124 export function getApplicative<E>(M: Monoid<E>): Applicative2C<URI, E> {
                                                                   ~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:139:34

139 const contramap_: Contravariant2<URI>['contramap'] = unsafeCoerce
                                     ~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:140:22

140 const map_: Functor2<URI>['map'] = unsafeCoerce
                         ~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:141:26

141 const bimap_: Bifunctor2<URI>['bimap'] = (fea, f) => make(f(fea))
                             ~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:142:28

142 const mapLeft_: Bifunctor2<URI>['mapLeft'] = (fea, f) => make(f(fea))
                               ~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:206:32

206 export const Functor: Functor2<URI> = {
                                   ~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:215:44

215 export const Contravariant: Contravariant2<URI> = {
                                               ~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:224:36

224 export const Bifunctor: Bifunctor2<URI> = {
                                       ~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:235:31

235 export const const_: Functor2<URI> & Contravariant2<URI> & Bifunctor2<URI> = {
                                  ~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:235:53

235 export const const_: Functor2<URI> & Contravariant2<URI> & Bifunctor2<URI> = {
                                                        ~~~

error TS2344: Type '"Const"' does not satisfy the constraint '"Either" | "IOEither" | "ReadonlyMap" | "Map" | "Reader" | "ReaderTask" | "TaskEither" | "ReadonlyTuple" | "State" | "Store" | "These" | "TaskThese" | "Traced" | "Tuple" | "Writer"'.

► file:///<mycomputer>/fp-ts/deno_lib/Const.ts:235:71

235 export const const_: Functor2<URI> & Contravariant2<URI> & Bifunctor2<URI> = {
                                                                          ~~~

error TS2322: Type 'undefined[]' is not assignable to type 'readonly never[]'.
  Type 'undefined' is not assignable to type 'never'.

► file:///<mycomputer>/fp-ts/deno_lib/ReadonlyArray.ts:2249:14

2249 export const empty: ReadonlyArray<never> = []
                  ~~~~~


Found 14 errors.
```
</p></details>

Any pointers on how to fix those? Are they due to the latest TS versions or something in the config?

I'm guessing those are the last hurdles 😄 I hope it should work after that!



As a sidenote, I was also able to use SkyPack - previously Pika - to import `fp-ts` into a Deno file, but it didn't load the types, which made the whole thing pretty pointless:

```typescript
import * as FpTs from "https://cdn.skypack.dev/fp-ts";

const Option = FpTs.option;
const myOpt = Option.fromNullable(5);

console.log("yay no checking", myOpt.value);
console.log(myOpt.some_obvious_problem);

 // Compiles and executes fine... but it shouldn't
```

**Comment by mushegha** [comment]
As seen on https://deno.land/x a 3rd party module can be added to registry with some config on Github. There's an **Add a module** button with instructions.


![17-Sep-2020|22:06:00 — Navigator](https://user-images.githubusercontent.com/25614707/93510842-ea220300-f932-11ea-95ee-680b641d33d8.png)

**Comment by remexre** [comment]
SkyPack _ought_ to work with types using `import * as FpTs from "https://cdn.skypack.dev/fp-ts?dts";`, but currently doesn't because `https://cdn.skypack.dev/-/fp-ts@v2.9.5-o8xyeRkfhw0jfQPV4zAi/dist\=es2020,mode\=types/lib/HKT.d.ts` is a 404; not sure who needs to tweak things to fix that though. I suspect this is because it only contains types?

**Comment by garronej** [comment]
@GabeAtWork,  
Denoify author here, sorry you had to deal with all those bugs.  
I fixed most of them but the `declare namespace` still remain. I will try to address it tomorrow evening.  
I have open [a draft PR](https://github.com/gcanti/fp-ts/pull/1594) for the Denoify setup on this repo.

**Comment by GabeAtWork** [comment]
Hi @garronej, no problem, thank you very much for taking the time to look at this!

**Comment by garronej** [comment]
@GabeAtWork [that's done](https://github.com/gcanti/fp-ts/pull/1594). Thank you for your investigations. You helped improving Denoify.

**Comment by Industrial** [comment]
I have tried `import * as Eq from "https://esm.sh/fp-ts/Eq";` but when running the program it tries to `Download https://cdn.esm.sh/v53/fp-ts@2.11.4/lib/HKT/HKT.d.ts` which returns a 404. I think it should be `https://cdn.esm.sh/v53/fp-ts@2.11.4/lib/HKT.d.ts` instead but that also returns a 404.

I have opened an issue here: https://github.com/alephjs/esm.sh/issues/185

**Comment by gcanti** [comment]
It's now published https://github.com/gcanti/fp-ts/pull/1594#issuecomment-933795374

**Comment by Industrial** [comment]
Thanks!

**Comment by guy-borderless** [comment]
For anybody reading this, fp-ts works perfectly with deno right now, deno supports npm. 
just go `import { pipe } from 'npm:fp-ts/function'`
