### ISSUE TITLE
Store comonad - question

### ISSUE THREAD

**Issue by brucou** [gcanti/fp-ts#1221]
Could not find a link to stack-overflow in the website or docs so posting this here.

i am struggling with implementing a pattern with fp-ts. I can't seem to decide between the state monad, and the Store comonad.

I have a [state machine library](https://brucou.github.io/documentation/v1/tutorials/model-with-machines.html) with which I implement user interfaces (using basically the Elm architecture + control states). The process is like this:

- have a dispatcher (event emitter) to send event
- have a function (let's call that the reactive function) that computes the commands to perform from the received event and internal state
  - that's a function fsm (for finite state machine) `:: i -> s -> s' -> o` or if that's better `(i, s) -> (s', o)`. The idea is that the function takes an input and computes an outputs using its encapsulated state, and update its encapsulated state post-computation. Currently, in my library, it is imperative `:: i -> o`, as the state is read and updated internally.
- render an initial view (using the dispatcher, so events can reach the reactive function)
* wait for event
  - compute the commands to perform with the reactive function
  - execute the effects associated to those commands. Render is an effect (almost) like any other, and as all commands receives the dispatcher in order to send events back to the reactive function
- loop to *

I thought for a while to use the state monad, but I don't how to thread the state: using chain would handle `i -> s' -> o` but how do I get `s`?. So I thought about using a comonad Store s->a, a, but I don't see how to thread the input...

How would you go about this? I kind of prefere the monadic approach a priori because the commands will have to be turned into effects after execution.

Thanks for your time and consideration (and let me know if there is a stack-overflow to ask questions, or if this is instead a better place).

**Comment by gcanti** [comment]
> let me know if there is a stack-overflow to ask questions, or if this is instead a better place

For a public room to discuss things there's https://fpchat-invite.herokuapp.com/ one of the channels is #typescript (another is #fp-ts)
