### ISSUE TITLE
Unsafe State and Reader types don't produce type errors with a nested chain(inline function -> pipe(chain))

### ISSUE THREAD

**Issue by willheslam** [gcanti/fp-ts#1222]
### Current Behavior

Let's say `Foo` and `Bar` are incompatible types.
Chaining a Reader of R `Foo` with a Reader of R `Bar` produces a type error - that's expected.

Chaining a Reader of R `Foo` into a piped Reader of R `Bar` produces a type error - that's expected.

Chaining a Reader of R `Foo` into a piped Reader of R `Bar` that's been chained does not produce a type error - instead it produces a Reader of R `Foo | Bar` - which is unexpected and can cause a runtime error!

Using a non-inlined function to chain a Reader of R `Foo` into a Reader of R `Bar` that's been chained DOES produce a type error - that's expected.

Chaining a Reader of R `Foo` into a Reader of R `Bar` that's been chained directly (no pipe) produces a type error - that's expected.

It looks to me like something weird is happening with the type inference when you chain a reader with an *inline* function into a Reader that's been piped into a chain function.
Using a non-inline function still produces the type error as you'd expect.

### Expected behavior

I'd expect all examples to produce a type error.

### Reproducible example

```
import * as R from 'fp-ts/lib/Reader'
import { pipe } from 'fp-ts/lib/pipeable'

const readerTest1 = pipe(
  R.ask<number>(),
  R.map(x => x * 10), // Expected a type error and got one
  R.chain(x => R.ask<string>())
)
// const readerTest1: R.Reader<string, string>
/* Type error:
Argument of type '<R>(fa: Reader<R, number>) => Reader<R, number>' is not assignable to parameter of type '(a: Reader<number, number>) => Reader<string, number>'.
  Type 'Reader<number, number>' is not assignable to type 'Reader<string, number>'.
    Type 'number' is not assignable to type 'string'.ts(2345)
*/

const readerTest2 = pipe(
  R.ask<number>(),
  R.map(x => x * 10), // Expected a type error and got one
  R.chain(x => pipe(
    R.ask<string>()
  ))
)
// const readerTest2: R.Reader<string, string>
/* Type error:
Argument of type '<R>(fa: Reader<R, number>) => Reader<R, number>' is not assignable to parameter of type '(a: Reader<number, number>) => Reader<string, number>'.
*/

const readerTest3 = pipe(
  R.ask<number>(),
  R.map(x => x * 10), // Expected a type error, but didn't get one!
  R.chain(x => pipe(
    R.ask<string>(),
    R.chain(x => R.of(x))
  ))
)
// const readerTest3: R.Reader<string | number, string>
/*
^^ This is a dangerous type, because it means I can pass in a string and have it multiplied by 10!
*/

const fn = (x: number) => pipe(
    R.ask<string>(),
    R.chain(x => R.of(x))
  )
// const fn: (x: number) => R.Reader<string, string>

const readerTest4 = pipe(
  R.ask<number>(),
  R.map(x => x * 10), // Expected a type error and got one
  R.chain(fn)
)
// const readerTest4: R.Reader<string, string>
/* Type error:
Argument of type '<R>(fa: Reader<R, number>) => Reader<R, number>' is not assignable to parameter of type '(a: Reader<number, number>) => Reader<string, number>'.
*/

const readerTest5 = pipe(
  R.ask<number>(),
  R.map(x => x * 10), // Expected a type error and got one
  R.chain(x => R.reader.chain(R.ask<string>(), x => R.of(x)))
)
// const readerTest5: R.Reader<string, string>
/* Type error:
Argument of type '<R>(fa: Reader<R, number>) => Reader<R, number>' is not assignable to parameter of type '(a: Reader<number, number>) => Reader<string, number>'.
*/

```
If this needs a simple repo to replicate the problem I can create one.

### Suggested solution(s)

I'm not fully sure what the solution should be.
This only seems to occur in some of the cases where type inference combined with inline functions isn't producing what we want.

At first I thought producing a Reader of R `Foo & Bar` would be OK, because even though earlier Readers of just `Foo` wouldn't know that the context must be `Foo & Bar`, that's OK because they're only interested one part of the type.
That would require updating the chain & orElse functions of the Reader, State and simialar classes.

There ARE classes like `chainW` that can produce a correct type, for example:
```
const readerTest3 = pipe(
  R.ask<number>(),
  R.map(x => x * 10),
  R.chain(x => pipe(
    R.ask<string>(),
    R.chain(x => R.of(x))
  ))
)
```
// R.Reader<string | number, string>
vs
```
const readerTest3 = pipe(
  R.ask<number>(),
  R.map(x => x * 10),
  R.chain(x => pipe(
    R.ask<string>(),
    R.chainW(x => R.of(x))
  ))
)
```
// R.Reader<never, string>
that at least indicates it's impossible to satisfy the Reader context,
but to my understanding the *W widening functions are designed to *allow* for more safer code, not to protect against dangerous code that is otherwise passed by the more conservative `non-W` functions!

Maybe the fix is not to the `chain`/`orElse` functions but instead to fix the inference of an inline function chaining a pipe chained monad...

### Additional context

This also applies to the State monad:

```
const stateTest1 = pipe(
  S.get<number>(),
  S.map(x => x * 10), // Type error - expected
  S.chain(x => S.get<string>())
)
// const stateTest1: S.State<string, string>

const stateTest2 = pipe(
  S.get<number>(),
  S.map(x => x * 10), // Type error - expected
  S.chain(x => pipe(
    S.get<string>(),
  ))
)
// const stateTest2: S.State<string, string>

const stateTest3 = pipe(
  S.get<number>(),
  S.map(x => x * 10), // No type error - unexpected!
  S.chain(x => pipe(
    S.get<string>(),
    S.chain(x => S.of(x))
  ))
)
const stateTest3: S.State<string | number, string>
// dangerous ^^
```

and ReaderTaskEither monad - and I presume also the ReaderTask monad.

As an example, it also applies to `orElse` of a ReaderTaskEither.
The original code where I identified this problem was:
```
import * as TE from'fp-ts/lib/TaskEither'
import * as RTE from 'fp-ts/lib/ReaderTaskEither'

class RefreshTokensError extends Error { }
class LogInError extends Error { }

type LoginCreds = {
  username: string,
  password: string
}
type AuthCreds = ({
  access: string,
  refresh: string
} | undefined)

type RefreshTokens = {
  refreshTokens: (auth: AuthCreds) => TE.TaskEither<RefreshTokensError, AuthCreds>
}

type LogIn = {
  logIn: (login: LoginCreds) => TE.TaskEither<LogInError, AuthCreds>
}

const auth = pipe(
    RTE.ask<AuthCreds & RefreshTokens>(),
    RTE.chain(deps => RTE.fromTaskEither(deps.refreshTokens(deps))),

    RTE.orElse(auth =>
      pipe(
        RTE.ask<LoginCreds & LogIn>(),
        RTE.chain(deps => RTE.fromTaskEither(deps.logIn(deps)))
      )
    )
  )
/* auth type:
const auth: RTE.ReaderTaskEither<({
    access: string;
    refresh: string;
} & RefreshTokens) | (LoginCreds & LogIn), LogInError, {
    access: string;
    refresh: string;
}>
*/

const te = auth({
  logIn: () => TE.right({ access: 'foo', refresh: 'bar' }),
  username: 'will', password: 'foobar',
}) // dangerous but satisfies type!
const p = te()

p.then(err => {
  console.log('err', err)
}, val => {
  console.log('val', val)
})
```
which is dangerous because it can be satisfied with just half of the necessary context, causing it to log this TypeError:
```
val [TypeError: deps.refreshTokens is not a function] 
```

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |       2.6.2    |
| TypeScript |      3.9.3      |

I'm not sure if this worked in older versions of fp-ts, I haven't checked yet.

**Comment by raveclassic** [comment]
The following gives compile-time error:
```typescript
const readerTest3 = pipe(
	R.ask<number>(),
	R.map(x => x * 10), // Expected a type error, but didn't get one!
	R.chain(x =>
		pipe(
			R.ask<string>(), // Error: Reader<string, string> is not assignable to Reader<number, string>
			R.chain(x => R.of(x)),
		),
	),
);
`

TS: 3.7.5
fp-ts: 2.5.3

**Comment by gcanti** [comment]
@raveclassic I can see the same error in VS Code.

fp-ts: 2.6.2
ts: 3.9.3

@willheslam maybe something in your setup?

**Comment by gcanti** [comment]
> maybe something in your setup?

@willheslam like `"strict": false` in `tsconfig.json` perhaps?

**Comment by willheslam** [comment]
Hi @gcanti - you're absolutely right, I completely overlooked that - I had `"strict": false`. Changing that causes my examples to show a type error.

Sorry to waste your time! I'm very pleased this was such a simple fix, less pleased I didn't notice it before posting this. :)

In the case of my real world example, it looks like I'll have to explicitly include the outside context:
```
    RTE.orElse(auth =>
      pipe(
        RTE.ask<LoginCreds & LogIn & AuthCreds & RefreshTokens>(),
        RTE.chain(deps => RTE.fromTaskEither(deps.logIn(deps)))
      )
    )
```
to prevent a type error on the RTE.ask<LoginCreds... line - I couldn't think of a good way to have it applied automatically.
