### ISSUE TITLE
Links in Introduction 404

### ISSUE THREAD

**Issue by dyerw** [gcanti/fp-ts#1223]
## 📖 Documentation

On the homepage of the docs here: https://gcanti.github.io/fp-ts/ in this paragraph:

Functional programming is all about pure functions and how to compose them into bigger structures. fp-ts provides a few general functions to support you with composition, constant functions, and more.

The link to "functions" links to the url https://gcanti.github.io/modules/function.ts.html gives a 404. I believe it should instead link to https://gcanti.github.io/fp-ts/modules/function.ts.html (note `/fp-ts/` in the path). 

Similar links in the introduction also have this issue

**Comment by gcanti** [comment]
Thanks @dyerw
