### ISSUE TITLE
Motivating example for IO currently doesn't break without IO

### ISSUE THREAD

**Issue by nyctef** [gcanti/fp-ts#1228]
## 📖 Documentation

From this bit of the [docs on IO](https://gcanti.github.io/fp-ts/modules/IO.ts.html):
> The next code snippet below is an example of a case where type safety affects the end result. Using console.log() directly would break the code, resulting in both logging actions being executed when the value is not null. You can confirm this by removing () from the end of the example code and replacing calls to log() with standard console.log().

I got confused by this, so I decided try it out but it didn't break:
https://repl.it/@nyctef/fp-ts-IO-example
```ts
import { fromNullable, fold } from 'fp-ts/lib/Option'
import { pipe } from 'fp-ts/lib/pipeable'

const logger = (input: number | null) =>
  pipe(
    fromNullable(input),
    fold(
      () => console.log('Received null'),
      (value) => console.log(`Received ${value}`)
    )
  )

logger(123)
```

I think this is due to `fold`'s first parameter changing from a default value to a default function? I'm new to a lot of fp concepts so it would be good to have another example which demonstrates where IO is necessary.

Thanks for making `fp-ts`! I've been learning about it recently and it seems like a very valuable library :)

**Comment by gcanti** [comment]
@nyctef you are right, https://github.com/gcanti/fp-ts/pull/1219 fixed the API call but now the example makes no sense.
I should just remove all the documentation that is not type-checked and / or tested, thanks for pointing out.

**Comment by gcanti** [comment]
@nyctef I mean that all the examples tagged with `@example` (see for example https://github.com/gcanti/fp-ts/blob/master/src/Array.ts#L66-L72) are type checked and executed when I generate the documentation, so I'm sure that they are aligned with the code.

Snippets like the one above are out of this process and this is really bad, sooner or later they end up out of sync and just become a source of confusion.
