### ISSUE TITLE
[feature] Implement Map with insertion order

### ISSUE THREAD

**Issue by waynevanson** [gcanti/fp-ts#1243]
## 🚀 Feature request

Implement `Map` to hold the order of elements, using the order of insertion to keep track of it.

### Current Behavior

Currently, `Map`'s implementation does not have any typeclass properties such as `sort` and `traverse` on the instance.

We can see that the implementation of `Map` does not keep track of the order, as the `toArray` needs and `Ord<A>` to give it an order:
```ts
export declare const toArray: <K>(O: Ord<K>) => <A>(m: Map<K, A>) => [K, A][]
```

### Desired Behavior

Map should have many of the methods that the `Array` typeclass has, because `Map`'s are ordered, as seen in the link provided under "Additional context".

The `toArray` method should look like this:
```ts
export declare const toArray: <K, A>(m: Map<K, A>) => [K, A][]
```

### Suggested Solution

Add each item in this non-exhaustive list of methods and typeclasses to the `Map` and `ReadonlyMap` typeclass:

+ [ ] `TraversableWithIndex2<URI>`
+ [ ] `FunctorWithIndex2<URI>`
+ [ ] `Compactable2<URI>`
+ [ ] `Monad2<URI>`

I would love to hear some feedback on the viability of the list above, as I haven't tried to implement these myself yet.

### Who does this impact? Who is this for?

All users who work with map.

This looks like a breaking change if done to the current `Map` typeclasses.
Instead, we could add `OrderedMap` and `ReadonlyOrderedMap`.

### Describe alternatives you've considered

+ Creating a new URI for "OrderedMap" and "ReadonlyOrderedMap", to avoid breaking changes.
+ Replacing the implementations of Map with the implementation mentioned in this issue, which is a breaking change.
+ `getWitherable<A>(Ord<A>)` looked promising, but it requires an `Ord` to work, which it shouldn't really need.

#### Key Order

> The keys in Map are ordered. Thus, when iterating over it, a Map object returns keys in order of insertion.

Go to the `Objects vs. Maps` section of the page:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      ^2.5.4      |
| TypeScript |        ^3.8.3    |

**Comment by gcanti** [comment]
> using the order of insertion

The "order of insertion" is not actually an order, you can't define an `Ord` for it.

If you don't sort the keys with an `Ord`, functions like `toArray` are not a pure

```ts
const m1 = new Map([
  ['a', 1],
  ['b', 2]
])

console.log(...m1.keys()) // a b

const m2 = new Map([
  ['b', 2],
  ['a', 1]
])

console.log(...m2.keys()) // b a
```

`m1` is equal to `m2` but `a b` is not equal to `b a` (i.e. `keys` is not pure)...

...unless all keys are equal. Indeed you can get what you want by passing the trivial `Ord`

```ts
import * as M from 'fp-ts/lib/Map'
import { Ord, fromCompare } from 'fp-ts/lib/Ord'

const trivial: Ord<unknown> = fromCompare(() => 0)

console.log(M.keys(trivial)(m1)) // [ 'a', 'b' ]
console.log(M.keys(trivial)(m2)) // [ 'b', 'a' ]
```

but that's a hack.

**Comment by waynevanson** [comment]
> `m1` is equal to `m2` but a b is not equal to `b a`

I see. We learn something new every day! Thank you for your explanation and response.
