### ISSUE TITLE
Immer, monocle-ts, or manual spread?

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1245]
A bit off-topic, but I am curious about what the community of `fp-ts` is using for object updates.

**Comment by waynevanson** [comment]
@steida  I'd say monocle-ts. I'm using it right now actually.

**Comment by raveclassic** [comment]
All 3 :)

**Comment by SRachamim** [comment]
`monocle-ts`.

**Comment by mlegenhausen** [comment]
`monocle-ts`

**Comment by steida** [comment]
OK, I have enough answers I would say. Thank you.
