### ISSUE TITLE
chainW for ReaderTask

### ISSUE THREAD

**Issue by adameier** [gcanti/fp-ts#1248]
## 🚀 Feature request

It would be nice to have the `chainW` function for `ReaderTask`. Personally I find it very useful to chain Readers which have different `R` type parameters together.

### Current Behavior

Right now we have `chainW` for `Reader` and `ReaderTaskEither` but not for `ReaderTask`. 

### Desired Behavior

Implement the function for `ReaderTask`.

### Suggested Solution

Would need to have something that satisfies the following:
```
export declare const chainW: <R, A, B>(f: (a: A) => ReaderTask<R, B>) => <Q>(ma: ReaderTask<Q, A>) => ReaderTask<Q & R, B>
```

### Who does this impact? Who is this for?

All users

---

If there's no specific reason that this should not be implemented I can follow up with a PR as well.

**Comment by gcanti** [comment]
> If there's no specific reason that this should not be implemented

@adameier no no, I simply forgot to add `chainW` to `ReaderTask`

>  I can follow up with a PR as well

Sure, thanks.

**Comment by gcanti** [comment]
Closed by https://github.com/gcanti/fp-ts/pull/1254
