### ISSUE TITLE
Question: Typeclass to provide a default value for a type?

### ISSUE THREAD

**Issue by kasugaicrow** [gcanti/fp-ts#1250]
## Problem

Too many times I find myself creating an empty object based on an interface.

## Example in typescript
```typescript
interface User {
  id: string
  firstName: string
  lastName: string
  age: number
}

const initialStateUser: User = {
  id: "0",
  firstName: "roger",
  lastName: "liftman",
  age: 45
}
```

I mainly need this as a default value in react `useState` hook like the following
```typescript
const [user, setUser] = React.useState<User>(initialStateUser)
```

I can lose type safety using type assertion like 
```typescript
const user: User = {} as User
```
but honestly I don't want to.

## Question

Is there a way to achieve something like [GDefault](https://pursuit.purescript.org/packages/purescript-data-default/0.3.2/docs/Data.Default#t:GDefault) does in purescript?

**Comment by giogonzo** [comment]
What about modeling this state with `Option<User>`? So that it correctly represents the fact that at the beginning of time there's no valid user to work with

**Comment by kasugaicrow** [comment]
I could do it but I was looking for another way to achieve this task in order to gain the possibility to choose based on the situation. Sometime I just can't have a `none` value of an `Option<T>` by default.
Plus, I would like to know, for personal interest, if it's possible.

**Comment by gcanti** [comment]
Possible? Yes. However, unlike in PureScript, you must pass the instances by hand, see the `getStructDefault` function (no compiler help here)

```ts
import * as R from 'fp-ts/lib/Record'
import { pipe } from 'fp-ts/lib/function'

export interface Default<A> {
  readonly def: A
}

export const defaultString: Default<string> = {
  def: ''
}

export const defaultNumber: Default<number> = {
  def: 0
}

export function getStructDefault<A>(defaults: { [K in keyof A]: Default<A[K]> }): Default<A> {
  return {
    def: pipe(
      defaults as Record<string, Default<any>>,
      R.map((d) => d.def)
    ) as any
  }
}

interface User {
  id: string
  firstName: string
  lastName: string
  age: number
}

const defaultUser = getStructDefault<User>({
  id: defaultString,
  firstName: defaultString,
  lastName: defaultString,
  age: defaultNumber
})

const initialStateUser = defaultUser.def
```

**Comment by kasugaicrow** [comment]
It makes sense to me, sadly typescript lack of a bit of magic like purescript or haskell. That said I think I'll create a default value for every type in js, then I'll expose something like that
```typescript
export const def = {
  type: getStructDefault,
  string: defaultString,
  number: defaultNumber,
  boolean: defaultBoolean,
  object: defaultObject
}
```
and then
```typescript
const User = def.type<User>({
  id: def.string,
  firstName: def.string,
  lastName: def.string,
  age: def.number
})
```

Anyway thank you!

**Comment by SRachamim** [comment]
I'd go for `Option` or the `empty` of the Monoid, depends on the situation.
