### ISSUE TITLE
`Either.parseJSON` should return JSON type instead of `unknown`

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#1251]
### Current Behavior

`Either.parseJSON` returns `Either<E, unknown>`, but we can refine the `unknown` type to something like `AnyJson`:

```ts
// Copied from https://github.com/Microsoft/TypeScript/issues/1897#issuecomment-338650717
export type AnyJson = boolean | number | string | null | JsonArray | JsonMap;
export type JsonMap = { [key: string]: AnyJson };
export type JsonArray = Array<AnyJson>;
```

Would you accept a PR for this?

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |            |
| TypeScript |            |

**Comment by gcanti** [comment]
> Would you accept a PR for this?

👍
