### ISSUE TITLE
Add tryCatchAsync function to Either

### ISSUE THREAD

**Issue by munierujp** [gcanti/fp-ts#1266]
## 🚀 Feature request

Add `tryCatchAsync` function to [Either](https://gcanti.github.io/fp-ts/modules/.ts.html).

### Current Behavior

[trycatch](https://gcanti.github.io/fp-ts/modules/.ts.html#trycatch) function does not await an async function.

### Desired Behavior

fp-ts provides function that constructs a new Either from an async function that might return Promise which will be rejected.

### Suggested Solution

Add below function to `src/Either.ts`:

```ts
export function tryCatchAsync<E, A>(f: Lazy<Promise<A>>, onError: (e: unknown) => E): Promise<Either<E, A>> {
  try {
    const r = await f()
    return right(r)
  } catch (e) {
    return left(onError(e))
  }
}
```

#### Example

```ts
import { Either, left, right, tryCatchAsync } from 'fp-ts/lib/Either'

const unsafeHead = <A>(as: Array<A>): Promise<A> => {
  if (as.length > 0) {
    return Promise.resolve(as[0])
  } else {
    return Promise.reject(new Error('empty array'))
  }
}

const head = <A>(as: Array<A>): Promise<Either<Error, A>> => {
  return tryCatchAsync(
    async () => await unsafeHead(as),
    (e) => (e instanceof Error ? e : new Error('unknown error'))
  )
}

const head1 = await head([])
assert.deepStrictEqual(head1, left(new Error('empty array')))
const head2 = await head([1, 2, 3])
assert.deepStrictEqual(head2, right(1))
```

#### More specific example

`valid.json`:

```json
{
  "foo": "bar"
}
```

`invalid.json`:

```json
{
```

```ts
import { Either, left, right, tryCatchAsync } from 'fp-ts/lib/Either'
import { readFile } from 'fs/promises'

const readJsonFile = (path: Parameters<typeof readFile>[0]): Promise<Either<Error,unknown>> => {
  return tryCatchAsync(
    async () => await readFile(as).then(d => JSON.parse(d)),
    (e) => new Error('failed to read JSON file')
  )
}

const invalid = await readJsonFile('./invalid.json')
assert.deepStrictEqual(invalid, left(new Error('failed to read JSON file')))
const valid = await readJsonFile('./valid.json')
assert.deepStrictEqual(valid, right({ foo: 'bar' }))
```

### Who does this impact? Who is this for?

People using Either

### Describe alternatives you've considered

It could not be realized with tryCatch function.

### Additional context

none

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |2.6.7|
| TypeScript |3.9.4|

**Comment by gcanti** [comment]
See [`tryCatch`](https://gcanti.github.io/fp-ts/modules/TaskEither.ts.html#trycatch) in the `TaskEither` module

**Comment by munierujp** [comment]
@gcanti thanks :smile:
