### ISSUE TITLE
[feature ] Reader as a non-unary function

### ISSUE THREAD

**Issue by waynevanson** [gcanti/fp-ts#1269]
### Current Behavior

We currently have the Reader monad & friends, which are an absolute joy to work with.
An issue I come across is seeing a pattern which could use reader, but my function take more than one argument.

If the function is unary, it can be a reader. If it's not, then I have to wrap the function in `tupled` to make it unary.

### Desired Behavior

A new monad that can be of any arity above 0.

### Suggested Solution

I don't have one yet. 
Has anyone thought of this? How do you get around this problem?

### Describe alternatives you've considered

 + A new monad, with a name deriving from `Reader` and `Tuple`/`Many`.
+ BREAKING: Change `Reader` to take a tuple that is spread across the arguments.
+ Combinator in the Reader and Reader[x] modules that can lift multi-arity functions to tuples and structs.

### Additional context

In the purely functional languages like Haskell, I'm pretty sure all functions are unary and so they don't have this barrier to deal with.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |         ^2.5.4   |
| TypeScript |         ^3.9.6   |

**Comment by kylegoetz** [comment]
You could write these yourself fairly easily:

```
interface Error {}
interface Result{}
function lift2<R1,R2,E,A>(f: (r1:R1,r2:R2) => TE.TaskEither<E,A>):RTE.ReaderTaskEither<Parameters<typeof f>, E, A> {
  return a => f(...a)
}
declare function x(a:string,b:boolean): TE.TaskEither<Error,Result>
lift2(x) // ReaderTaskEither<[string,boolean],Error,Result>
```

Define `lift3` as taking a function `(f: (r1:R1,r2:R2,r3:R3) => TE.TaskEither<E,A>)` as parameter and that's the only change you need for lift3. And so forth. Everything else can remain the same.

It would be nice to have a single `lift1` function, but for that your function needs to be defined generically as `f: (...r:R[]) => TaskEither<Error,Result>` but then your `Parameters<typeof f>` gets garbled up and your `lift` ends up returning `ReaderTaskEither<(arg1type, arg2type, arg3type)[], Error,Result>`, so it fails to enforce the correct ordering of params from your original function.

**Comment by kylegoetz** [comment]
Actually this is better
```
export function lift<R1,R2,E,A>(f: (r1:R1,r2:R2) => TE.TaskEither<E,A>):RTE.ReaderTaskEither<Parameters<typeof f>, E, A>
export function lift<R1,R2,R3, E,A>(f: (r1:R1,r2:R2,r3:R3) => TE.TaskEither<E,A>):RTE.ReaderTaskEither<Parameters<typeof f>, E, A>
export function lift<R1,R2,R3,R4,E,A>(f: (r1:R1,r2:R2,r3:R3,r4:R4) => TE.TaskEither<E,A>):RTE.ReaderTaskEither<Parameters<typeof f>, E, A>
export function lift<R1,R2,R3,R4,R5,E,A>(f: (r1:R1,r2:R2,r3:R3,r4:R4,r5:R5) => TE.TaskEither<E,A>):RTE.ReaderTaskEither<Parameters<typeof f>, E, A>
export function lift(f:Function) { return a => f(...a) }

declare function x2(a:string,b:boolean): TE.TaskEither<Error,void>
declare function x3(a:string,b:boolean,c:number): TE.TaskEither<Error,void>

const result1 = lift(x2) // ReaderTaskEither<[string,boolean],Error,void>
const result2 = lift(x3) // ReaderTaskEither<[string,boolean,number],Error,void>
```

**Comment by waynevanson** [comment]
@kylegoetz We can use tuples to spread across the arguments, removing the need for overloads.

```ts
declare function toNReader<R extends readonly [any, ...any[]], A>(fa: (...r: R ) => A): Reader<R, A>
```

**Comment by kylegoetz** [comment]
That's a very cool way to do it!

**Comment by waynevanson** [comment]
Closing as we can just use a tuple.
