### ISSUE TITLE
Scenario where `flow` does not catch non-typesafe composition

### ISSUE THREAD

**Issue by kylegoetz** [gcanti/fp-ts#1279]
### Current Behavior

If I do functional composition by just nesting the calls D(C(B(A(data)))) then TypeScript catches the fact that B and C cannot compose, but flow(A,B,C,D) does not trigger the same error. I don't know how to diagnose whether this is `fp-ts`'s `flow` or TypeScript that is the problem.

Note: Technically (referenced in code) `PayloadActionCreator<Tag, Payload>` is a typealias for `(payload:Payload) => { _tag: Tag, payload: Payload }` (or extends the type).

## Description

Code:

In a certain scenario with a branded nominal type, when I manually compose `d(c(b(a(data)))` TypeScript will give me a type error when `flow(a,b,c,d)(data)` will not. Details below:

```
import { Option, none, some } from 'fp-ts/lib/Option'
import { createAction } from 'typesafe-actions'
import { useDispatch } from 'react-redux'
import { flow } from 'fp-ts/lib/function'

type Brand<A, T> = A & { __brand: T }
type UniqueString = Brand<string, 'unique'>

const extractFromInputEvent = (e:React.ChangeEvent<HTMLInputElement>):string => e.target.value
const getStringOption = (s:string):Option<string> => s==='' ? none : some(s)
const updateName = createAction('update name')<Option<UniqueString>>() // PayloadActionCreator<'update name', Option<Brand<string, 'unique'>>>
const dispatcher = useDispatch() // (action: any) => any

dispatcher(updateName(getStringOption(extractFromInputEvent()))) // <-- type 'string' is not assignable to type { __brand: 'unique' }

const setName = flow(
    extractFromInputEvent,
    getStringOption, 
    updateName,  // <-- no error here about type mismatch
    dispatcher)

```

### Expected behavior

Should be a type mismatch error that leads me to create a new function that casts `string` to `UniqueString` if the string is unique in the data set and insert that between `getStringOption` and `updateName` since the first yields a string and the latter expects a UniqueString.

### Reproducible example

See code above.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |    2.6.0        |
| TypeScript |   3.9.2         |

**Comment by gcanti** [comment]
@kylegoetz I can't repro

```ts
import { flow } from 'fp-ts/lib/function'
import { Option } from 'fp-ts/lib/Option'

type Brand<A, T> = A & { __brand: T }
type UniqueString = Brand<string, 'unique'>

declare function f(s: string): Option<string>
declare function g(s: Option<UniqueString>): number

g(f('a')) // error: Type 'string' is not assignable to type { __brand: 'unique' }

flow(f, g) // error: Type 'Some<string>' is not assignable to type 'Some<Brand<string, "unique">>'
```

**Comment by DenisFrezzato** [comment]
@kylegoetz I've tried with your example, and I get the error you were expecting (but not getting), so I reckon there is nothing wrong with `flow`.

Perhaps it has something to do with your project configuration. Is `strict` in your `tsconfig.json` set to `true`? Or maybe other strict flags...

**Comment by kylegoetz** [comment]
Both of you, thank you. I tracked down the issue. The long and short of it was I didn't have `strict` mode on, so the code

`const A = flow(some, updateName, dispatcher)` was "swallowing" the type `updateName` required and making `A` a function that takes `any` rather than `UniqueString`.

Turning `strict` on turned this into an error that type `unknown` was not assignable to type `Brand<string, 'unique'>`.

Thanks @gcanti for checking. I'm sorry it was just me being careless. @DenisFrezzato thanks for the tip about `strict`.
