### ISSUE TITLE
URIS is never in client projects if no typeclasses are imported

### ISSUE THREAD

**Issue by mstn** [gcanti/fp-ts#1282]
Hi, this is more a question than a bug report. 

Let's assume I want to build a library dependent on `fp-ts` (e.g. a new typeclass). Then I define a function `fun` that depends on `URIS` like the following:

```
import { URIS } from 'fp-ts/lib/HKT';

const fun = <T extends URIS>() => { ... }
```

It happens that `URIS` is `never`. In order to populate `URIS` with the right types I have to import them in any place of my library. For example,

```
import { Task } from 'fp-ts/lib/Task';
```
In other words, module augmentation is not visible outside a library if files are not imported explicitly (which makes sense if you think about how `import` works in js/ts).

The problem is relevant when you compile the client library. In fact, `tsc` expands `URIS` with the types available at the time of compilation. The code above would become,

```
const fun = <T extends never>() => { ... }
```
Is it possible to preserve `URIS` instead of expanding it? If we expand `URIS` at compilation time, then the client library wouldn't work with other types defined outside `fp-ts` (*2).

A solution (it does not solve *2) could be to add this line in `index.ts` of the client library.

```
export * from 'fp-ts';
```

I am wondering if there is a smarter way to do that.

**Comment by gcanti** [comment]
> Is it possible to preserve URIS instead of expanding it?

Yes, do not define your function as a function expression, use a function declaration instead

```ts
function fun<T extends URIS>() { 
  ... 
}
```

See https://github.com/microsoft/TypeScript/issues/27171

**Comment by mstn** [comment]
@gcanti thanks for the tip, it works.
