### ISSUE TITLE
Consider microbundle

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1287]
It looks like the best tool for the (boring and error-prone) job.

https://github.com/developit/microbundle

**Comment by waynevanson** [comment]
I've tried it for a few of my projects and had mixed results. It works well for javascript projects/

microbundle uses rollup under the hood, which still has bad support for Typescript. The typescript plugin doesn't even work properly and has many bugs, to the point I cannot use it in the projects I maintain.

**Comment by steida** [comment]
@waynevanson Thank you for an explanation.

**Comment by waynevanson** [comment]
@steida I take back what I said about microbundle to some extent. The support for newer typescript features like `export * as namespace from 'module-name'` is dodgy, but all bundlers seem to be dodgy with this. 

As long as a compatible tsconfig file is used to bundle each target (esm,cjs,umd) then it works fine.
Examples are [HERE](https://github.com/waynevanson/template-typescript-library)
