### ISSUE TITLE
`fpFirst` keeping only the result of the *second*, not *first*

### ISSUE THREAD

**Issue by jituanlin** [gcanti/fp-ts#1290]
## 📖 Documentation
From `apFIrst` document:

> Combine two effectful actions, keeping only the result of the first. 

However, the type signature indicate sthat the it keeping the result of *second*.

> export declare const apFirst: <B>(fb: Option<B>) => <A>(fa: Option<A>) => Option<A>

**Comment by jituanlin** [comment]
> ## 📖 Documentation
> From `apFIrst` document:
> 
> > Combine two effectful actions, keeping only the result of the first.
> 
> However, the type signature indicate sthat the it keeping the result of _second_.
> 
> > export declare const apFirst: (fb: Option) => (fa: Option) => Option

I also have this confusion for `apSecond`

**Comment by DenisFrezzato** [comment]
Curried functions are data-last and meant to be used with `pipe`.

```typescript
pipe(
  O.some('a'),
  O.apFirst(O.some('b'))
) // result is `some('a')`
```

**Comment by jituanlin** [comment]
Quote from [sanctuary-js](https://sanctuary.js.org/#apFirst), the type signature is:
> apFirst :: Apply f => f a -> f b -> f a

It return `fa` rather than `fb`. 

The current signature design is different from this, is it intentional?

With `pipe`, the position description is right. 
Even so, more clear documents may be helpful.

**Comment by kyle-007** [comment]
In PureScript the function signature is: `applyFirst :: forall a b f. Apply f => f a -> f b -> f b`
Shall we initiate a PR?
