### ISSUE TITLE
Add expressive-ts to the ecosystem

### ISSUE THREAD

**Issue by IMax153** [gcanti/fp-ts#1292]
## 📖 Documentation

I recently finished up `v0.0.1` of [`expressive-ts`](https://github.com/IMax153/expressive-ts), a simple comonadic builder library that allows for a declarative approach to constructing regular expressions. 

I would very much like to see the lib become a part of the `fp-ts` ecosystem. I would also appreciate your thoughts on the comonadic implementation using `Traced` if you have the time to review.

**Comment by gcanti** [comment]
@IMax153 nice!

> I would very much like to see the lib become a part of the fp-ts ecosystem

feel free to send a PR for the `docs/ecosystem.md` file :+1:
