### ISSUE TITLE
Fate of IxMonad

### ISSUE THREAD

**Issue by TheFalseFriend** [gcanti/fp-ts#1298]
Hi @gcanti,

First of all: great library! 

I was perusing https://dev.to/gnomff_65/hyper-ts-is-my-cyborg-brain-34kf, and the concept of ```IxMonad``` caught my eye. I was looking to play around with these monads using fp-ts and it seems there did exist an implementation in-library  (https://github.com/gcanti/fp-ts/pull/180) up until relatively recently ([here](https://github.com/gcanti/fp-ts/issues/823#issuecomment-490814901) is a reference from 9/5/19). 

Upon closer inspection it looks like IxMonad was deprecated and removed in v2. However, I can't find any documentation as to _why_ that module was removed. The only references I could find were;

- [here](https://github.com/gcanti/fp-ts/blob/bdc9515c00d4f735558ea52f2523fa54d487fda0/docs/guides/upgrade-to-v2.md#removed-modules) - just mentions IxMonad as a 'removed module', does not elaborate
- [here](https://github.com/gcanti/fp-ts/pull/881) - just mentions IxMonad as 'deprecated', does not elaborate

Further the 'technical discussion that resulted in v2' [this](https://github.com/gcanti/fp-ts/issues/823) doesn't mention IxMonad other than the reference above. 

I can see hyper-ts also ripped out its use of fp-ts' IxMonad in favour of its own implementation for the release of fp-ts v2.

So these are my questions:
- what was the fate of IxMonad? Why cull it?
- what was IxMonad depcrecated in favour of?

Thanks in advance!

**Comment by anilanar** [comment]
Maybe I can necro bump this question @gcanti

**Comment by gcanti** [comment]
I don't remember the details now but I wasn't satisfied by the encoding of `IxMonad` in TypeScript

**Comment by derrickbeining** [comment]
I've been wanting IxMonad et. al. in `fp-ts` lately. I has to implement them in order to port `purescript-react-basic-hooks` to TS recently.

**Comment by anilanar** [comment]
@derrickbeining Funny enough, I did the same.

**Comment by derrickbeining** [comment]
FYI: there's been some more activity on this front over here https://github.com/gcanti/fp-ts/pull/1473

**Comment by EricCrosson** [comment]
#1473 has been closed (resolved -- separate package published), perhaps it's time to close this issue too?
