### ISSUE TITLE
reverse/descending sort via sortBy()

### ISSUE THREAD

**Issue by krcourville** [gcanti/fp-ts#1304]
## 📖 Documentation

Hello,

I'm entirely new to fp-ts and still learning the concepts.  Off-hand, I'm wondering if it's possible, with current library functions to sort in reverse? And, if so, can an example be added to the docs?

This stackblitz app represents what I am experimenting with: https://stackblitz.com/edit/sorting-demo.

**Comment by moshensky** [comment]
@krcourville you could use getDualOrd, check here for a sample: https://dev.to/gcanti/getting-started-with-fp-ts-ord-5f1e

**Comment by krcourville** [comment]
thanks, that works!
