### ISSUE TITLE
Set up a contribution fund

### ISSUE THREAD

**Issue by Nvveen** [gcanti/fp-ts#1308]
Hi,

Me and a lot of other people really enjoy this library, and its siblings such as io-ts and monocle-ts. I would like to show my appreciation by donating a monetary sum, so that I can also give something back, and I wouldn't be surprised if there are actual professional companies willing to contribute something too. Is there a plan to set up a contribution/donation fund to do this?

**Comment by jkomyno** [comment]
Hi @Nvveen, you can donate to @gcanti here: https://github.com/sponsors/gcanti.
I believe we can now close this issue :)
