### ISSUE TITLE
Natural transformation from union type A|B to Either<A,B> 

### ISSUE THREAD

**Issue by ingun37** [gcanti/fp-ts#1316]
### Current Behavior

There’s no construction of `Either<A,B>` from `A|B`.

### Desired Behavior

I often desire to transform `A|B` to `Either<A,B>`.

Because Union type is prevalent and I want to apply algebraic operations on it.

I need a direct and easy construction of `Either<A,B>`  from `A|B`.

Union type `A|B` is naturaly isomorphic to `Either<A,B>` so I think it’s going to be a trivial job but very useful.

### Suggested Solution

```
function fromUnion<A,B>(ab: A|B): Either<A:B> {
  if ab is A then Left(ab) else Right(ab)
}
```

### Who does this impact? Who is this for?

Functional programmers who wants to apply sum-type operations (e.g, bimap) on Union type.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.8.2      |
| TypeScript |       4.0     |

**Comment by raveclassic** [comment]
How would you check generically "if ab is a"?

**Comment by ingun37** [comment]
@raveclassic 
I didn't think it through. Now I realize that's the real problem.
I guess something like this would probably be the best I could do
```
function fromUnion<A,B>(ab:A|B, constructorA:{new ():A}):Either<A,B> {
  if ab instanced constructorA then Left(a) else Right(b)
}
```
It's probably best to keep it in the application level...
I'm closing the issue
