### ISSUE TITLE
Reader does not export Strong

### ISSUE THREAD

**Issue by urgent** [gcanti/fp-ts#1317]
### Current Behavior

When trying to do a fanout like:

https://github.com/gcanti/fp-ts/blob/master/test/Strong.ts#L16

The IDE returns an error:

> Property 'Strong' does not exist on type 'typeof import("  fp-ts/lib/Reader")'

### Expected behavior

Importing from `lib` instead of `src` provides typedefs for `R.Strong`.

### Reproducible example

```
import * as R from 'fp-ts/lib/Reader'
import { fanout } from 'fp-ts/lib/Strong'

fanout({ ...R.Strong, ...R.Category })
```

### Suggested solution(s)

Change `internal` to `category` in `src` for `tsc build`

https://github.com/gcanti/fp-ts/blob/master/src/Reader.ts#L298

### Your environment

Which versions of fp-ts are affected by this issue?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |     2.8.2       |
| TypeScript |   4.0.2        |

Did this work in previous versions of fp-ts? 
Unknown

**Comment by gcanti** [comment]
Closed by https://github.com/gcanti/fp-ts/pull/1319
