### ISSUE TITLE
Add ap2 methods to FantasyApply instances

### ISSUE THREAD

**Issue by gcanti** [gcanti/fp-ts#132]
`ap` methods, while being fantasy-land compliant, are pretty awkward: I must apply the arguments in a kind of reversed order

```ts
import * as option from 'fp-ts/lib/Option'

function f(a: string): (b: number) => number {
  return b => a.length + b
}

const a = option.of('a')
const b = option.of(2)

// I must apply the arguments in a kind of reversed order
console.log(b.ap(a.map(f))) // some(3)
```

I propose to add an additoinal `ap2` method: thanks to a handy TypeScript feature (type annotations for `this`) we can define `ap2` as

```ts
// Option.ts

export class Some<A> {
  ...
  ap<B>(fab: Option<(a: A) => B>): Option<B> {
    return fab.map(f => f(this.value))
  }
  ap2<B, C>(this: Option<(a: B) => C>, fb: Option<B>): Option<C> {
    return fb.ap(this)
  }
  ...
}
```

and then I can use `ap2` in a more natural way

```ts
console.log(a.map(f).ap2(b)) // some(3)
```

while retaining type safety

```ts
function g(a: number): (b: number) => number {
  return b => a + b
}

a.map(g).ap2(b) // error
option.some(1).map(g).ap2(option.some('a')) // error
```

**Comment by DylanRJohnston** [comment]
Can anyone think of a better alternate name than ap2? When I first read this proposal I was confusing it with the variadic naming pattern of `lift` `lift2` `lift3` etc.

Maybe `_ap`? or `apply`?

**Comment by gcanti** [comment]
> Can anyone think of a better alternate name than ap2?

Yes please. `flippedAp` seems too long. Maybe `ap_`? There's `traverse_` and `sequance_` too in `Foldable`

**Comment by gcanti** [comment]
PR here https://github.com/gcanti/fp-ts/pull/135 (name is temporary)
