### ISSUE TITLE
Question about  IOEither - Applicative

### ISSUE THREAD

**Issue by twiggler** [gcanti/fp-ts#1321]
## 🐛 Question 

Cool library!

### Current Behavior

I have an array of job desciptions, which I map to an array of `IOEither`, which i then sequence using the `IOEIther.Applicative` instance. 

```
const dumpJobs = (destination: string) => (jobs: DumpJob[]) =>
	pipe(
		jobs,
		A.mapWithIndex(dumpJob(destination, jobs.length)),
		A.map(IOEither.map(buf => buf.toString())),
		A.sequence(IOEither.Applicative)
	);
```

All jobs are always executed, irrespective of failures.

### Expected behavior

Bail out when a job fails. 

### Question

Is this intentional behavior? 
If so, is there something in `fp-ts` which I can use to get the desired behavior?
Could this behavior be clarified in the documentation, or is this what most people expect to happen?
Or am I doing something wrong?

**Comment by kylegoetz** [comment]
`sequenceT` takes a tuple of `HKT<F, A>` where `F` is of the `Apply` class (applicative functor minus the `pure/of` lifting function). I looked at the code, and it appears to bail on the first failure.

```
export function sequenceT<F>(F: Apply<F>): any {
  return <A>(...args: Array<HKT<F, A>>) => {
    const len = args.length
    const f = getTupleConstructor(len)
    let fas = F.map(args[0], f)
    for (let i = 1; i < len; i++) {
      fas = F.ap(fas, args[i])
    }
    return fas
  }
}
```

This code doesn't show the short circuiting, but if you check out, for example, the code for `Option`'s `ap`, it will only eval the "second" option if the first is `Some<A>` rather than `None`.

**Comment by twiggler** [comment]
Hi @kylegoetz, thank you for your response.

I cannot use `sequenceT`, because the array of jobs is of dynamic length.

Further, I don't think `sequenceT` would give bailout on error behavior for `IOEither.Applicative`, because the following code fragment also does not bail out on error:

```
import * as IOEither from 'fp-ts/lib/IOEither';
import { log } from 'fp-ts/lib/Console';
import { toError } from "fp-ts/lib/Either";
import { pipe } from 'fp-ts/lib/function';

const firstTask = IOEither.left(Error("Crash and burn"));
const secondTask = IOEither.tryCatch(log("Second task here"), toError);
const collect = () => () => "We are happy"

const result = pipe(
	IOEither.right(collect),
	IOEither.ap(firstTask),
	IOEither.ap(secondTask)
)()
```

When running this, the output is: 
`Second task here`

But the first task always has a left-value.

**Comment by twiggler** [comment]
The analogue with Either:

```
const firstEither = Either.left(Error("Crash and burn"));
const secondEither: Either.Either<Error, string> = Either.right("Second Either here");

const result = pipe(
	Either.right(collect),
	Either.ap(firstEither),
	Either.ap(secondEither)
)

console.log(
	Either.getOrElse((left: Error) => left.toString())(result)
);
```

*does* bail-out with "Error: Crash and burn", as expected.

**Comment by gcanti** [comment]
@twiggler I think we can export two `Applicative` instances (like in `TaskEither`)

- `ApplicativePar` (does not bail out)
- `ApplicativeSeq` (does bail out)

and deprecate `Applicative` in favour of `ApplicativePar`.

See https://github.com/gcanti/fp-ts/pull/1325

**Comment by twiggler** [comment]
@gcanti Thank you!
This seems to be a great solution  🥳.

I will test the PR and will get back to you on Saturday,

**Comment by twiggler** [comment]
@gcanti I have checked out the PR, and it works splendidly.

**Comment by gcanti** [comment]
@twiggler thanks for checking out, released.
