### ISSUE TITLE
convert Task<Either<E, A>> to TaskEither<E, A>

### ISSUE THREAD

**Issue by imcotton** [gcanti/fp-ts#1322]
### Current Behavior

Normally you would have `TaskEither` beforehand, but in case of having `Task<Either>` on hold.

### Desired Behavior

New constructor to lift `Task<Either<E, A>>` into `TaskEither<E, A>` automatically.

### Suggested Solution

```typescript
declare const fromTaskWithEither: <E, A>(fa: Task<Either<E, A>>) => TaskEither<E, A>
```

### Who does this impact? Who is this for?

All users.

### Describe alternatives you've considered

Nothing yet.

### Additional context

Also nice to have:

```typescript
declare const fromIOWithEither: <E, A>(fa: IO<Either<E, A>>) => TaskEither<E, A>
```

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |       2.8     |
| TypeScript |     4       |

**Comment by DenisFrezzato** [comment]
`TaskEither<E, A>` is just an alias for `Task<Either<E, A>>`, so you don't need to "convert" them.

```typescript
import * as T from 'fp-ts/Task'
import * as TE from 'fp-ts/TaskEither'
import * as E from 'fp-ts/Either'

const a: T.Task<E.Either<string, number>> = T.of(E.right(1))
const a1: TE.TaskEither<string, number> = a // Everything's fine.
```

**Comment by imcotton** [comment]
Cool, thanks for the hint, I was thinking something at least:

```typescript
import { identity } from 'fp-ts/function'

const fromTaskWithEither: <E, A>(fa: Task<Either<E, A>>) => TaskEither<E, A> = identity
```

But it turns out those two types were exchangeable at no cost:

```typescript
import { task as T, taskEither as TE, function as F } from 'fp-ts'

const task: T.Task<E.Either<string, number>> = F.pipe(
    T.of(E.right(Math.random())),
    TE.chain(num => num < 0.5 ? TE.left('oops') : TE.right(num)),
    T.delay(100),
)
```

Problem solved, but I was wondering would it be acting differently in other system (e.g.: **Haskell**), or this just a special trait to **TypeScript** only?

**Comment by kylegoetz** [comment]
I don't think Haskell has a type called `Task`. It has `Async`, which is not an alias for `Either`.

**Comment by kylegoetz** [comment]
Are you asking if Haskell has a typealias for `Async Either a b`?

**Comment by samhh** [comment]
I _think_:

In terms of it being a mere type alias, it would behave the same way in Haskell and most other languages.

In terms of the `TaskEither` type being implemented in this way, such that it can be defined as a type alias, it is distinct from something like Haskell where you'd probably be utilising monad transformers.

**Comment by imcotton** [comment]
Thanks folks 😄
