### ISSUE TITLE
Nullable type

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1337]
## 🚀 Feature request

```ts
export type Nullable<T> = T | null; // not undefined, because of fp-ts Nullable
```

It's not a replacement for Option, but a convenient supplement. 
There are cases when we have to deal with non-FP API (that's why there are `toNullable` and `fromNullable`) and Option is not practical. For example, React Context which uses strict check.
Also, people never know whether they should choose `A | null` or `A | null | undefined` or `A | undefined`.
That's why the Nullable type could be useful.

```ts
export function toNullable<A>(ma: Option<A>): Nullable<A> {
  return isNone(ma) ? null : ma.value
}
```

### Current Behavior

None. 

Not related to https://github.com/gcanti/fp-ts/issues/1336

**Comment by mohaalak** [comment]
thre is a `toNullable` right now 
https://gcanti.github.io/fp-ts/modules/Option.ts.html#tonullable

also there is a `toUndefined` 
what's the point to have a type  like `Nullable<T>`?

**Comment by steida** [comment]
> thre is a toNullable right now
Yep, and it can use Nullable type instead of A | null.

> what's the point to have a type like Nullable<T>?

As I wrote.

**Comment by steida** [comment]
OK, maybe it belongs to user space...
