### ISSUE TITLE
array every

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1348]
## 🚀 Feature request

Like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

Or does fp-ts provide an alternative way?

**Comment by samhh** [comment]
There's [fp-ts-std/Array::all](https://samhh.github.io/fp-ts-std/modules/Array.ts.html#all), but I'm curious if there's a clever way of doing this with fp-ts proper that I've missed.

**Comment by IMax153** [comment]
Hey @steida - you could use `Array.foldMap` to first map the values of the array to a `boolean` and then fold them together with an appropriate `Monoid`. See below.

```typescript
import * as Ord from "fp-ts/Ord";
import * as M from "fp-ts/Monoid";
import * as RA from "fp-ts/ReadonlyArray";
import { pipe } from "fp-ts/function";

const isBelowThreshold = (threshold: number) => (value: number) =>
  Ord.lt(Ord.ordNumber)(value, threshold);

console.log(
  pipe(
    [1, 30, 39, 29, 10, 13], 
    RA.foldMap(M.monoidAll)(isBelowThreshold(40))
  )
);
// => true
```

**Comment by steida** [comment]
@IMax153 Thank you.

**Comment by steida** [comment]
With modern fp-ts imports.

```ts
import { array, monoid, ord } from 'fp-ts';
import { pipe } from 'fp-ts/function';

const isBelowThreshold = (threshold: number) => (value: number) =>
  ord.lt(ord.ordNumber)(value, threshold);

// => true
console.log(
  pipe(
    [1, 30, 39, 29, 10, 13],
    array.foldMap(monoid.monoidAll)(isBelowThreshold(40)),
  ),
);
```
