### ISSUE TITLE
TaskThese.chain is wrong when ma=both and f(a) returns a right (inconsistent with These.chain)

### ISSUE THREAD

**Issue by entropitor** [gcanti/fp-ts#1350]
### Current Behavior
```typescript
it("test simplified", async () => {
  const monad = TaskThese.getMonad(getMonoid());
  const t = TaskThese.both<number[], string>([3], "test");
  const result = monad.chain(t, (str: string) => TaskThese.right(str.length));
  expect(await result()).resolves.toEqual({
    _tag: "Right",
    right: 4,
  });
});
```
(I'm getting a type error for this specific example but it does run in jest and succeeds)

### Expected behavior
```typescript
it("test simplified", async () => {
  const monad = TaskThese.getMonad(getMonoid());
  const t = TaskThese.both<number[], string>([3], "test");
  const result = monad.chain(t, (str: string) => TaskThese.right(str.length));
  expect(await result()).resolves.toEqual({
    _tag: "Both",
    left: [3],
    right: 4,
  });
});
```

(I'm getting a type error for this specific example but it does run in jest and fails)

### Reproducible example
see above

### Suggested solution(s)

Replace https://github.com/gcanti/fp-ts/blob/master/src/TaskThese.ts#L270 with 
```typescript
(b) => TH.both(e1, b)
```

### Additional context

This would make it consistent with how the monad in These works.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |  2.8.5          |
| TypeScript |  4.0.5          |

**Comment by gcanti** [comment]
@entropitor thanks for the bug report, patch released.

**Comment by entropitor** [comment]
Thanks!
