### ISSUE TITLE
tryCatch in an interface/"typeclass"?

### ISSUE THREAD

**Issue by kylegoetz** [gcanti/fp-ts#1359]
## 🚀 Feature request

Is there a plan (or is it already possible) to have a single interface representing `IOEither` and `TaskEither` that includes their `tryCatch` (like by adding to `MonadIO2`)?

### Current Behavior

`tryCatch` is not part of `MonadIO2` and not part of any relevant typeclass best I can tell.

I consume an API that currently is over the network and it makes sense to use `TaskEither`. I anticipate this will move closer to the application (say, changing from DB to flat file) and it will make sense to be `IOEither` instead.

If I wanted to write this API interface in "tagless final" (or at least generically) so I don't have to change a bunch of code when we switch from async to sync, I might do (and then like to do):

```
interface Consumer<M extends URIS2> {
  getDatum: (a:string) => Kind2<M, DomainError, number>
}
const consumer = <M extends URIS2>(m:IOMonad2<M>) => ({
  getDatum: m.tryCatch(()=>someApiCall('test'), ()=>({_tag:'SomeDomainError'})
})
```

### What I Tried

The problem is that `IOMonad2` (and, it seems, no related interface) has `tryCatch` as a property. I tried creating my own,

```
interface Tryable<M extends URIS2> {
  tryCatch: <E,A>(f:Lazy<Promise<A>>, onError: (reason: unknown) => E) => Kind2<M, E, A>
}
```
But as you can guess this does not work because only `TaskEither`'s `tryCatch` takes `Lazy<Promise<A>>`. The others take `Lazy<A>`.

### Suggested Solution

Right now, I figure I need to pass in the "thunk type" as part of the interface definition:

```
interface Tryable<M extends URIS2, ThunkType extends 'Task'|'IO'> extends MonadIO2<M> {
  tryCatch: <E, A>(f:Kind<ThunkType, A>, onError: (e:unknown)=>E) => Kind2<M, E, A>
}
const te: Tryable<'TaskEither', 'Task'> = { ...TE.taskEither, tryCatch: TE.tryCatch}
const ioe: Tryable<'IOEither', 'IO'> = { ...IOE.ioEither, tryCatch: IOE.tryCatch}
```

*Luckily* `Lazy<Promise<A>>` is the same type as `Task<A>` and `Lazy<A>` is the same type as `IO<A>`, but this wouldn't hold true for, say, `Option.tryCatch`. I suppose that would be `o: Tryable<'Option', 'IO'>` as a hack. Same for `e: Tryable<'Either', 'IO'>`. IT feels like a hack to involve `IO` in `Option` and `Either` to make `Tryable` work.

### Who does this impact? Who is this for?

This impacts anyone who'd like to write in a more generic style. I think this is "tagless final", but I am not fully fluent in FP terminology yet.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |     2.6.0       |
| TypeScript |      3.9.2      |

**Comment by kylegoetz** [comment]
Hm, this still doesn't seem to work when trying to instantiate an object that implements an interface

```
export default <M extends URIS2>(m:Tryable<M>) => (config: Config) => ({
  repository: consumer(m)(config.repoConfig)
})
```

Need to pass in an `N` generic as well, but there's no current way of tying M and N together. Maybe some kind of "thunk type lookup table":

```
interface MNLookup {
  'TaskEither': 'Task'
  'IOEither': 'IO'
}
interface _Tryable<M extends keyof MNLookup> extends Monad2<M> {
  tryCatch: <E,A>(m:Kind<MNLookup[M],A>, onError: (e:unknown) => E) => Kind2<M,E,A>
}

declare const _te: _Tryable<'TaskEither'>
declare const _ioe: _Tryable<'IOEither'>
declare const f: (i:string)=>Promise<number>
const isEven = (a:number) => a%2===0

F.pipe(
  _te.tryCatch(()=>f('test'), _e => 'async error'),
  resultTE => _te.map(resultTE, isEven)
)  // TaskEither<string,boolean> (TE.right(false))

F.pipe(
  _ioe.tryCatch(()=>5, _e => 'sync error'),
  resultIOE => _ioe.map(resultIOE, isEven)
) // IOEither<string,boolean> (IOE.right(false))
```

Hmm, seems like at the end of the day, you still end up having your core repository functions explicitly written using `fetch` (async) or `sequeliteTable.findAll` or `fs.readFileSync`, so maybe is just a pointless exercise.

**Comment by gcanti** [comment]
`tryCatch` is for interop so it's supposed to be used to define an instance of the `Consumer` type class

```ts
import { Kind2, URIS2 } from 'fp-ts/HKT'
import { Monad2 } from 'fp-ts/Monad'
import * as TE from 'fp-ts/TaskEither'
import * as IE from 'fp-ts/IOEither'

// -------------------------------------
// tagless final pattern
// -------------------------------------

// type class
interface Consumer2<M extends URIS2> extends Monad2<M> {
  readonly getDatum: (a: string) => Kind2<M, Error, number>
}

// program usgin the type class
function myprogram<M extends URIS2>(C: Consumer2<M>): Kind2<M, Error, string> {
  return C.map(C.getDatum('a'), (n): string => (n > 0 ? 'positive' : 'non positive'))
}

// instance for TaskEither
const consumerTaskEither: Consumer2<TE.URI> = {
  ...TE.taskEither,
  getDatum: (s) =>
    TE.tryCatch(
      () => Promise.resolve(s.length),
      () => new Error()
    )
}

// instance for IOEither
const consumerIOEither: Consumer2<IE.URI> = {
  ...IE.ioEither,
  getDatum: (s) =>
    IE.tryCatch(
      () => s.length,
      () => new Error()
    )
}

// run
myprogram(consumerTaskEither)()
```
