### ISSUE TITLE
TypeScript: importing from es6 produces "not a module" issues

### ISSUE THREAD

**Issue by kylegoetz** [gcanti/fp-ts#1361]
### Current Behavior

In my TypeScript project, I recently started using `fp-ts/es6/*` instead of `fp-ts/lib/*` because I read a comment in the issue tracker talking about tree shaking not working with lib but working with es6, and I wanted tree shaking to work if possible.

I had not tried to transpile the TS to JS from then until now, and now when I try, I get errors like

```
/path/to/package/node_modules/fp-ts/es6/Apply.js:1
import { tuple } from './function';
```

In my code, I had

//file.ts
```
import { sequenceT } from 'fp-ts/es6/Apply'
```

If I change "es6" to "lib" the error goes away and the code compiles.

### Expected behavior

Shouldn't get this error.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |          2.6.0  |
| TypeScript |         3.9.2   |

**Comment by kylegoetz** [comment]
So it seems like TypeScript does not recognize the `es6` code as modules, so it cannot use the module import syntax in those es6/* files.

**Comment by steida** [comment]
I think /lib and /es6 directories should be removed. This is tree-shaked with Webpack5:

```ts
import { option } from 'fp-ts';
import { constVoid, pipe } from 'fp-ts/function';
```

**Comment by gcanti** [comment]
@kylegoetz the recommended way is no `es6` / `lib` at all when importing a single module, i.e.

```ts
import { sequenceT } from 'fp-ts/Apply'
```
