### ISSUE TITLE
Either merge to union function

### ISSUE THREAD

**Issue by jleider** [gcanti/fp-ts#1362]
### Current Behavior

There is no `merge` function or equivalent that I could find.

### Desired Behavior

```typescript
const merge = <E, A>(ma: E.Either<E, A>): E | A => E.fold<E, A, E | A>(identity, identity)(ma);

const e: E.Either<string, number> = E.left("a");
const m: string | number = merge(e)
```

### Suggested Solution

This could probably also apply to other `Either` derivatives.

### Who does this impact? Who is this for?

This would be used by anyone wanting to convert an `Either` type into a standard TypeScript union type.

### Describe alternatives you've considered

You can always just write  `E.fold<E, A, E | A>(identity, identity)(ma)` but it would be nice to have a convenience function.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |       2.9.1     |
| TypeScript |     4.1       |

**Comment by IMax153** [comment]
@jleider - I would argue that `merge` goes against the semantics of working with an `Either`.  The point of the `Either` monad is to elegantly handle with two separate possible execution paths in your program. The two execution paths can be merged using `fold`, as you have done in your implementation. 

```ts
import * as E from 'fp-ts/Either'

const fold = E.fold<number, string, number>(
  (n) => n + 1,
  (s) => s.length
)

console.log(fold(E.left(1))) // => 2
console.log(fold(E.right('hello'))) // => 5
```

Is there a reason why you cannot work with the separate paths of execution when `fold`ing the `Either`? Are you able to share any code snippets that were the impetus for `merge`? Happy to discuss further!

**Comment by jleider** [comment]
@IMax153 I certainly agree that the `Either` is the better type to be working with. 

However, there are instances, usually at the seams of our application, where we need to interface with libraries and APIs that are not written with `fp-ts`. In these instances we often need to convert our `Either` into a union type. Of course it can be done with a `fold` but you are required to provide the union type as either a type parameter to the `fold<E, A, E | A>` or as the return type of the first function for the TypeScript inference to understand what you are trying to accomplish. By default the return value of the first `onLeft` function is used to determine the return value of the second `onRight` function. 

`merge` would simply be a convenience method, just as `getOrElseW` and probably most any other widen function already available are.

**Comment by samhh** [comment]
It's a bit more work, but you might find the best solution is to create an io-ts codec for your payload where the property with the `Either` value uses a new "eitherFromUnion" codec.

**Comment by gcanti** [comment]
@jleider can we come up with a better name than `merge`? (seems too generic)

`squash`? `toUntaggedUnion`? `toUnion`? `unionize`? `untag`? `untagged`?

**Comment by jleider** [comment]
Im all for another name for it but both the Scala STL and ScalaZ use the term `merge`. Although they rely on implicits to ensure that both the left and right types are the same type at the end of the day. This would be a bit different since its possibly producing a union.

That said I would be in favor of `unionize` or `toUnion` which would be more consistent with the other `toXxx` functions that already exist. In the same realm of `untagged` I could suggest `toSimpleUnion` as well. `Squash` is too similar to `merge`, in that case I would just rather `merge` since it's consistent with other existing FP libraries. 

https://www.scala-lang.org/api/current/scala/util/Either$$MergeableEither.html
https://github.com/scalaz/scalaz/blob/master/core/src/main/scala/scalaz/Either.scala#L337

**Comment by gcanti** [comment]
> `toUnion` which would be more consistent with the other `toXxx` functions that already exist

:+1:

Example: `toNullable` in `Option.ts` https://gcanti.github.io/fp-ts/modules/Option.ts.html#tonullable
