### ISSUE TITLE
Either foldW

### ISSUE THREAD

**Issue by jleider** [gcanti/fp-ts#1363]
### Current Behavior

There is no `foldW` for `Either`

### Desired Behavior

To act like other `xxxW` functions where the goal is to widen the type via way of a TypeScript union type.

### Who does this impact? Who is this for?

This would be useful for everyone I would imagine?

### Describe alternatives you've considered

Without the `W` variant, you are required to type either the `fold` function with the three type parameters or type the return of at least the first function with your expected union type.
`E.fold<E, A, E | A>(onLeft, onRight)`
`E.fold((e): E | A => onLeft, (a): E | A => onRight)`

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |     2.9.1       |
| TypeScript |     4.1       |

**Comment by mohaalak** [comment]
as long as you are on it, Can you add `foldW` to `Option` too?

**Comment by gcanti** [comment]
@mohaalak I'm going to add `foldW` to all data types which already supports `fold`
