### ISSUE TITLE
Add orElseW

### ISSUE THREAD

**Issue by xuanduc987** [gcanti/fp-ts#1374]
### Current Behavior

There is no `orElseW` for `Either`, `TaskEither`, `ReaderTaskEither`

### Desired Behavior

`orElseW` acts like `orElse`, but with automatic widen type on the right `A`

### Suggested Solution

For `Either`

```typescript
function orElse<E, B, M>(onLeft: (e: E) => Either<M, B>): <A>(ma: Either<E, A>) => Either<M, A | B>
```

### Who does this impact? Who is this for?

All users

### Describe alternatives you've considered

Explicit annotate all generic parameter with widened type

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |     2.9.3       |
| TypeScript |      4.1      |

**Comment by gcanti** [comment]
No need to widen

```ts
export declare function orElse<E, A, M>(onLeft: (e: E) => Either<M, A>): (ma: Either<E, A>) => Either<M, A>
```

The `M` type always overrides the `E` type

**Comment by xuanduc987** [comment]
Sorry, what I meant is to widen the `A` type
```typescript
function orElse<E, B, M>(onLeft: (e: E) => Either<M, B>): <A>(ma: Either<E, A>) => Either<M, A|B>
```
