### ISSUE TITLE
`fromFoldable` (`Map`) returns `any`

### ISSUE THREAD

**Issue by thought2** [gcanti/fp-ts#1380]
### Current Behavior

```ts
import { array } from "fp-ts/Array";
import { getLastSemigroup } from "fp-ts/Semigroup";
import * as Map_ from "fp-ts/Map";
import { eqString } from "fp-ts/lib/Eq";

const foldableToMap = Map_.fromFoldable(
  eqString,
  getLastSemigroup<boolean>(),
  array
);
```

The inferred type of `foldableToMap` is `(fka: [string, boolean][]) => any`

### Expected behavior

The inferred type of `foldableToMap` should be `(fka: [string, boolean][]) => Map<string, boolean>`

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.9.3 |
| TypeScript | 4.1.3 |

**Comment by gcanti** [comment]
@thought2 I can't repro, I see `const foldableToMap: (fka: [string, boolean][]) => Map<string, boolean>` on hover (VS Code)

**Comment by thought2** [comment]
Thanks for the fast reply. Got the solution:
missing `{ "lib": [ "ES2015" ] }`in `tsconfig.json` compiler options.

**Comment by thought2** [comment]
Maybe worth considering to add this to the `Readme`, as it's not the default of `tsc --init`.

**Comment by gcanti** [comment]
I've double checked locally and I have no `lib` entry in `tsconfig`, are you sure it's required?

**Comment by thought2** [comment]
For me the following gives me an error (with the above mentioned version of typescript):
```bash
tsc --init
echo "type T = Map<string, string>" > index.ts
tsc
```

I can only make it work, when I add "ES2015" or later to the tsconfig.

**Comment by gcanti** [comment]
@thought2 sorry, my fault, locally I have `@types/node` installed which works too
