### ISSUE TITLE
Heterogeneous Records

### ISSUE THREAD

**Issue by thought2** [gcanti/fp-ts#1382]
### Current Behavior

The `Record` module contains data structures for homogeneous Records, meaning that every value of a Record has the same type. But this is just a special case of records, in most cases their fields have different types.

```ts
import { pipe } from "fp-ts/function";
import * as Record_ from "fp-ts/Record";

type Person = {
  age: number;
  name: string;
  active: boolean;
};

const person: Person = { name: "Joe B.", age: 78, active: true };

const plusOne = (n: number): number => n + 1;
```

If I want to modify a field in a value of type `Person` the existing record module is of little help.

The following does not compile:
```ts
const person2 : Person = pipe(person, Reocrd_.modifyAt("age", plusOne))
```

The reason is that `Person`, treated as a homogeneous record has the type `Record<string, string | number | boolean>`, all possible value types are subsumed in a union type. However the given update function `addOne` only works for the number field.

(Moreover `Reocrd_.modifyAt` only works with string keys returning an `Option` as the key may not be present. This is maybe another topic to discuss, in any way: in the above scenario I know the key at compile time and so there is no need to cover runtime failure here.)

### Desired Behavior

If there was a dedicated module for heterogeneous records, the following would work:

```ts
import * as HetRecord_ from "fp-ts/HeterogeneousRecord";

const person2 : Person = pipe(person, HetReocrd_.modifyAt("age", plusOne))
```

### Suggested Solution

A stub for the suggested module could look like:

```ts
// HeterogeneousRecord.ts

import * as RR from "fp-ts/lib/ReadonlyRecord";

export const modifyAt: <R extends Record<Key, any>, Key extends string>(
  key: Key,
  f: (val: R[Key]) => R[Key]
) => (r: R) => R = RR.modifyAt as any;
```

We can use the implementation of the `ReadonlyRecord` module (as it's done in the Record module) and just add some more general types to it: Basically we track the whole record and the key top update as type arguments, with the constraints that the key should be a string and that it should be an actual key of the record.

### Who does this impact? Who is this for?

I think this could be useful for users of any kind of skill level. One does not need to know much additional concepts to work with it.

### Describe alternatives you've considered

Why not just use native record updates/the spread operator?

Currently one would go ahead and write this code:
```ts
const person3 : Person = pipe(person, p => ({ ...p, age: plusOne(p.age) }));
```

Apart from the fact that this is a bit boiler platy. I recently discovered another danger of this approach, which in the end was my motivation for my suggestion.

Consider this snippet, it perfectly compiles:
```ts
const person4 : Person = pipe(person, p => ({ ...p, ages: plusOne(p.age) }));
```

But do you spot the mistake? I'm using the field "ages" instead of age. This works due to the nature of typescript's structural type system. `p` already has all the fields/structure of `Person`. Adding more fields always typechecks and so `person4` would have this value:

```ts
{ name: "Joe B.", age: 78, active: true, ages: 79 }
```

Which is not wat we want.

### Additional context

For now I have not investigated further what this concept would mean for other useful functions in the suggested module. But at the first sight it look like many of them could be implemented with ease.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |         2.9.3   |
| TypeScript |       4.1.3     |

**Comment by DenisFrezzato** [comment]
Have a look at [monocle-ts](https://github.com/gcanti/monocle-ts).

**Comment by thought2** [comment]
Nice. When writing this request I did not realize that most of the other functions from the existing Record module would not make sense in the suggested one. So it's really about updating/getting values form structures, for which of course lenses are a nice choice. 
I'll check out the suggested library, I think having an extra module in `fp-ts` is not needed then.
