### ISSUE TITLE
function.flow should be unary

### ISSUE THREAD

**Issue by imcotton** [gcanti/fp-ts#1383]
### Current Behavior

The **first** function inside `flow` be count as any arity.

### Expected behavior

The **first** function inside `flow` should been taken as unary, the same as its afterward.

### Reproducible example

```ts
import { function as F } from 'fp-ts';

[ '1', '2', '3' ].map(F.flow(
    parseInt,
    F.increment,
));

// [ 2, NaN, NaN ]
```

```diff
[ '1', '2', '3' ].map(F.flow(
+   s => s,
    parseInt,
    F.increment,
));

// [ 2, 3, 4 ]
```

### Suggested solution(s)

https://github.com/gcanti/fp-ts/blob/9759cb09d7cead603925748adb5fae5c6919b728/src/function.ts#L212-L218

I think only pass `fab` to `ab` should be sufficient, instead of apply `arguments`.

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |    1.x, 2.x   |
| TypeScript |   4.1.3   |

**Comment by EricCrosson** [comment]
I would consider this a feature rather than a bug. How about adding a `unary` function to `function.ts`?

**Comment by imcotton** [comment]
@EricCrosson 

That's one way to look at it, but I find it rather impractical in FP context, do you have some use case particularly in mind?

**Comment by samhh** [comment]
Two ways of looking at this.

One, don't use native prototypal methods, instead use fp-ts alternatives that sidestep this issue by providing explicitly different functions for e.g. mapping and mapping with index.

Two, fp-ts should curry everything and simply not support variadic functions.

They're not mutually exclusive approaches, either. Curiously I think both approaches can be considered hazardous to developers inexperienced with fp-ts, but so is the status quo. :man_shrugging:

**Comment by EricCrosson** [comment]
> That's one way to look at it, but I find it rather impractical in FP context, do you have some use case particularly in mind?

The higher arity has helped me reduce boilerplate when interfacing with third-party, non fp-ts functions. Here's a [snippet](https://github.com/typescript-tools/typescript-tools/blob/48744f5830d8dbe95b9569516e434c8831eff7ee/packages/update-lerna-manifest/src/update-lerna-manifest.ts#L74)

``` typescript
const decodeDocopt = flow(
    D.decodeDocopt,
    E.mapLeft(errors => PathReporter.report(E.left(errors)).join('\n')),
    E.mapLeft(error => err({ type: 'docopt decode', error })),
)
```

and one for [find-up](https://github.com/sindresorhus/find-up) from the same file (unfortunate type assertion as `findUp` is overloaded)

``` typescript
const findup = flow(
    findUp.sync as (name: string | readonly string[], options?: findUp.Options) => string | undefined,
    O.fromNullable,
    O.map(path.dirname),
    E.fromOption(() => err({ type: 'package not in monorepo' })),
)
```

I use one of these wrapper functions to start my own, more fp-ts pipelines. 

You may be right that there could be a more functional approach I'm missing though. With single arity,  I guess I'd be forced to hard-code the additional arguments in a function, or inject them with `Reader`?

**Comment by imcotton** [comment]
Thanks for the examples, I then double checked the [document][1] of `flow`:

> Performs left-to-right function composition. **The first argument may have any arity**, the remaining arguments must be unary.

Turns out that's the intended behavior, in retrospect I was trying to have it to be dropping replacement of `pipe` from **Ramda**, should have had read doc more closely, sorry for the false alarm.


[1]: https://gcanti.github.io/fp-ts/modules/function.ts.html#flow
