### ISSUE TITLE
newIORef().write() is not working

### ISSUE THREAD

**Issue by StasMelnyk** [gcanti/fp-ts#1384]
### Current Behavior

```javascript
const getNewIORef = newIORef<O.Option<string>>(O.none);
getNewIORef().write(O.some('sss'));
console.info(getNewIORef().read()); // {_tag: "None"}
```

### Expected behavior

```javascript
const getNewIORef = newIORef<O.Option<string>>(O.none);
getNewIORef().write(O.some('sss'));
console.info(getNewIORef().read()); // {_tag: "Some", value: "sss"}
```

### Reproducible example

```javascript
const getNewIORef = newIORef<O.Option<string>>(O.none);
getNewIORef().write(O.some('sss'));
console.info(getNewIORef().read()); // {_tag: "None"}
```

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.x      |
| TypeScript |      3.8.3      |

**Comment by gcanti** [comment]
@StasMelnyk if you rename `someFunc` to `getNewIORef` the current behavior makes much more sense

**Comment by StasMelnyk** [comment]
Yeah, sorry for that :)

**Comment by gcanti** [comment]
I mean that when you call `getNewIORef` you always get a new `IORef`, so `getNewIORef().write(O.some('sss'))` and `getNewIORef().read()` are not related.

Here an example when I use the same `IORef`

```ts
import { pipe } from 'fp-ts/function'
import * as IO from 'fp-ts/IO'
import { newIORef } from 'fp-ts/IORef'
import * as O from 'fp-ts/Option'

const getNewIORef = newIORef<O.Option<string>>(O.none)

const result: IO.IO<O.Option<string>> = pipe(
  getNewIORef,
  IO.chainFirst((ref) => ref.write(O.some('sss'))),
  IO.chain((ref) => ref.read)
)

console.log(result()) // => { _tag: 'Some', value: 'sss' }
```

**Comment by StasMelnyk** [comment]
@gcanti Make sense to me know, thanks for it!
