### ISSUE TITLE
NonEmptyArray#filter returns wrong type

### ISSUE THREAD

**Issue by pedrodim** [gcanti/fp-ts#1388]
### Current Behavior

```ts
type Values = "A" | "B";
const values: NonEmptyArray<Values> = ["A", "B"];
const filterValues = (value: Values): value is "B" => value === "B";

const filteredValues = nonEmptyArray.filter(filterValues)(values);
```
`filteredValues` is `Option<NonEmptyArray<Values>>`

### Expected behavior

`filteredValues` is `Option<NonEmptyArray<"B">>`

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.9.3           |
| TypeScript | 4.1.3           |

**Comment by samhh** [comment]
I can repro:

```ts
declare const p: (x: unknown) => x is string;
declare const xs: NonEmptyArray<unknown>;
const ys = NEA.filter(p)(xs);
```

**Comment by gcanti** [comment]
@pedrodim @samhh thanks, patch released.
