### ISSUE TITLE
[FR] Functor & Bifunctor instances for Separated

### ISSUE THREAD

**Issue by YBogomolov** [gcanti/fp-ts#1389]
### Current Behavior

Currently `Separated` data type from `Compactable` module doesn't have any useful instances — like Functor, Bifunctor, etc.

### Desired Behavior

It would be nice for `Separated` to export instances for Functor and Bifunctor.

### Suggested Solution

`fp-ts` could either:
1. Define and export instances for Functor and Bifunctor for `Separated`. Probably, this will require moving `Separated` to its own module.
2. Change way of defining `Separated` type as just a tuple: `type Separated<L, R> = [L, R]`. This approach will allow reusing instances from `Tuple` module.

### Who does this impact? Who is this for?

Advanced

### Describe alternatives you've considered

My current alternative looks like this file I'm moving between my projects:

```ts
import { pipeable } from "fp-ts/pipeable";
import { Separated } from "fp-ts/Compactable";
import { Bifunctor2 } from "fp-ts/Bifunctor";
import { Functor2 } from "fp-ts/Functor";

export const URI = "Separated";
export type URI = typeof URI;

declare module "fp-ts/HKT" {
    interface URItoKind2<E, A> {
        readonly Separated: Separated<E, A>;
    }
}

export const separated: Bifunctor2<URI> & Functor2<URI> = {
    URI,
    map: <A, B, C>(fa: Separated<A, B>, f: (b: B) => C): Separated<A, C> => ({ ...fa, right: f(fa.right) }),
    mapLeft: <A, B, C>(fa: Separated<A, C>, f: (a: A) => B): Separated<B, C> => ({ ...fa, left: f(fa.left) }),
    bimap: <A, B, C, D>(fa: Separated<A, C>, g: (A: A) => B, f: (c: C) => D): Separated<B, D> =>
        ({ left: g(fa.left), right: f(fa.right) })
};

const { map, mapLeft, bimap } = pipeable(separated);

export {
    map,
    mapLeft,
    bimap
};
```

### Additional context

I would be happy to work on this feature, but I need to discuss the desired design and approach (tuples vs. record encoding of `Separated`).

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |2.9.3|
| TypeScript |4.1.2|

**Comment by gcanti** [comment]
@YBogomolov I'd prefer solution 1 in order to avoid a big breaking change.
