### ISSUE TITLE
An index for `fp-ts` libraries. Does it exist?

### ISSUE THREAD

**Issue by thought2** [gcanti/fp-ts#1396]
Is there a place where libraries that follow the `fp-ts` coding conventions are gathered? I was also thinking if it would make sense to follow a certain naming scheme, using `fp-ts` as a prefix or postfix.

In the end they're just typescript libraries but on the other hand people may want to search for them specifically as they work well together. Another question would be what those "coding conventions" actually are. If not done yet, it would be interesting to have them documented somewhere. There's [this document](https://gcanti.github.io/fp-ts/guides/code-conventions) but is more about how to understand `fp-ts` and would miss some points that would be helpful for library writers.

Any way, yesterday I gave it a try to see what it would take to write and document a `fp-ts` "compatible" library. The outcome was this small port of an existing purescript pseudo random generator: https://github.com/no-day/lcg
It uses `docs-ts` for the documentation, too.

So, I'd be curious to hear if there's a place to gather, announce, discuss new releases in the `fp-ts` eco system.

**Comment by samhh** [comment]
Is this not covered by the [ecosystem](https://gcanti.github.io/fp-ts/ecosystem/) docs page?

**Comment by gcanti** [comment]
Hi @thought2,

> using fp-ts as a prefix or postfix

a prefix should be good (examples: `fp-ts-contrib`, `fp-ts-rxjs`, `fp-ts-laws`)

> There's this document but is more about how to understand fp-ts and would miss some points that would be helpful for library writers

Yeah, if you feel like it we could chat here about what would be helpful for library writers and enrich/amend that document

> if there's a place to gather, announce, discuss new releases in the fp-ts eco system

- gather: I'd say the "ecosystem" docs page
- announce, discuss: check out the `fp-ts` channel on [FP slack](https://fpchat-invite.herokuapp.com/)

**Comment by thought2** [comment]
Thanks for the answers! Did not know about the ecosystem page, the fp-ts slack channel. Will make a PR for the ecosystem page.

Regarding the documentation, here are my suggestions. I can prepare a PR for this if there is agreement

- Adding a link to the slack channel. E.g. in "README.md/community" or "docs/learning-resources.md"
- enhance Coding Conventions
  - Explain the argument structure of a pipeable function. Something like `(...instances) => (...args) => (dataType) => dataType`

**Comment by gcanti** [comment]
> Adding a link to the slack channel. E.g. in "README.md/community" or "docs/learning-resources.md"

Already added to the [README](https://github.com/gcanti/fp-ts/blob/e8d99246ef72c5ae5ee76304fa06d0423522b24f/README.md#help) (branch `2.10`)

> Explain the argument structure of a pipeable function

:+1:
