### ISSUE TITLE
Calling Task.traverseArray on a ReadonlyNonEmptyArray returns a ReadonlyArray

### ISSUE THREAD

**Issue by thewilkybarkid** [gcanti/fp-ts#1404]
### Current Behavior

Calling `Task.traverseArray` on a `ReadonlyNonEmptyArray` returns a `ReadonlyArray`.

### Expected behaviour

That it returns a `ReadonlyNonEmptyArray`.

### Reproducible example

```typescript
import { readonlyNonEmptyArray as RNEA, task as T, function as f } from 'fp-ts';

declare const rats: ReadonlyArray<T.Task<string>>
declare const rneats: RNEA.ReadonlyNonEmptyArray<T.Task<string>>

const ra: T.Task<ReadonlyArray<string>> = f.pipe(rats, T.sequenceArray)
const rnea: T.Task<RNEA.ReadonlyNonEmptyArray<string>> = f.pipe(rneats, T.sequenceArray)
```

[TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzlApgQwCYQHYBsCeAcjgKLgz4CCUUa+caAznAEqEmUA0cMTA1g2YAVbgDMArtgDGMYDkFxRcAL6KoEEHADkosAFoYjLQG4AUKYwopuNKjhScjeLUMAuVuix4qNOgB4hADohfj8nKGBsAHMAPhiLKxs7B2wnZGx0N1Z2SkCWTxwCYmwyMApqWnwA4NDwyNj40xS02ncgkMY+P3zMQp9KsJgI6Li4AF5FQLBgMBQAChdGbiDGFABHcRRpFAq6AEomx2cMtDaazu6cvILvYtLy3yq6kZjxyenZhZPDZcDVja2Uh2jwOQA); [Original source](https://github.com/sciety/sciety/blob/85185d93476ac0519b2e3ecc27bcfe5042d038f9/src/home-page/render-editorial-communities.ts#L30-L33)

### Suggested solution(s)

Overloading if possible (don't think generics would work); otherwise separate functions?

### Additional context

Applies to various other functions where the length of the array doesn't change (eg `T.sequenceArray`).

I've had a quick go with first generics then overloading, but seems a bit more complicated than hoped.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.9.5           |
| TypeScript |  4.1.5          |

**Comment by gcanti** [comment]
In order to avoid a combinatorial explosion of functions I propose to only add the most powerful `traverseReadonlyNonEmptyArrayWithIndex` function

`traverseReadonlyNonEmptyArray` and `sequenceReadonlyNonEmptyArray` can be easily derived:

```ts
traverseReadonlyNonEmptyArray(f) = traverseReadonlyNonEmptyArrayWithIndex((_, a) => f(a))
sequenceReadonlyNonEmptyArray = traverseReadonlyNonEmptyArrayWithIndex((_, a) => a)
```

**Comment by thewilkybarkid** [comment]
Would overloading work? I can take another look into it.

**Comment by gcanti** [comment]
> Would overloading work?

Not sure it's possible, last time I tried I got:

> This overload signature is not compatible with its implementation signature.ts(2394)

Adding a separate function is ok though (for example I could also add a `traverseReadonlyRecordWithKey` in the future).

**Comment by thewilkybarkid** [comment]
> > Would overloading work?
> 
> Not sure it's possible, last time I tried I got:
> 
> > This overload signature is not compatible with its implementation signature.ts(2394)

Took a quick look and you can get around that by making the array type generic too

```ts
export function traverseArrayWithIndex<A, B, C extends ReadonlyNonEmptyArray<A>, D extends ReadonlyNonEmptyArray<B>>(f: (index: number, a: A) => Task<B>): (as: C) => Task<D>;
export function traverseArrayWithIndex<A, B, C extends ReadonlyArray<A>, D extends ReadonlyArray<B>>(f: (index: number, a: A) => Task<B>): (as: C) => Task<D>;
export function traverseArrayWithIndex<A, B>(f: (index: number, a: A) => Task<B>) {
  return (as: ReadonlyArray<A>) => () => Promise.all(as.map((x, i) => f(i, x)()));
}
```

but the change does need to be propagated.

**Comment by thewilkybarkid** [comment]
Looking at https://github.com/gcanti/fp-ts/commit/0fb9ad73c04131b03102c1cd500aa42355f3b07b though, it seems like `RNEA.traverseWithIndex` etc no longer have the performance warning so we could just use that instead...

**Comment by thewilkybarkid** [comment]
```ts
export const traverseArrayWithIndex = <A, B>(f: (index: number, a: A) => Task<B>) => <C extends ReadonlyArray<A>>(
  as: C
): Task<C extends ReadonlyNonEmptyArray<A> ? ReadonlyNonEmptyArray<B> : ReadonlyArray<B>> => () =>
  Promise.all(as.map((x, i) => f(i, x)())) as any
```

works, but type inference for `A` and `B` is lost (e.g. in `traverseArray`).

**Comment by thewilkybarkid** [comment]
```ts
export const traverseArrayWithIndex = <A, B>(f: (index: number, a: A) => Task<B>) => <C>(
  as: ReadonlyArray<A> & {0?: C}
): Task<C extends A ? ReadonlyNonEmptyArray<B> : ReadonlyArray<B>> => () =>
  Promise.all(as.map((x, i) => f(i, x)())) as any
```

works, and retains type inference.
