### ISSUE TITLE
Where to get help

### ISSUE THREAD

**Issue by zedryas** [gcanti/fp-ts#1406]
Hello,

Posting here cause i do not know where else.

I'me trying to dive in fp-ts (with basic functional understanding), and some questions arose from time to time on the pattern "How can i do this' - i've browse receipe but most of the time I do not find my answer.

Si they re a gitter or a discord where i could ask those ?

**Comment by steida** [comment]
@zedryas https://fpchat-invite.herokuapp.com/

**Comment by zedryas** [comment]
Thank  you
