### ISSUE TITLE
Array.chunksOf could return Array<NonEmptyArray<A>>

### ISSUE THREAD

**Issue by anthonyjoeseph** [gcanti/fp-ts#1407]
## 🐛 Bug report

Array.chunksOf could return Array<NonEmptyArray<A>>

### Current Behavior

```ts
export function chunksOf(n: number): <A>(as: ReadonlyArray<A>) => ReadonlyArray<ReadonlyArray<A>> {
  const f = chop(splitAt(n))
  return (as) => (as.length === 0 ? empty : isOutOfBound(n - 1, as) ? [as] : f(as))
}
```

[current](https://github.com/gcanti/fp-ts/blob/3f39202a332f193c1656f6b5fce19dbbbfb0aed7/src/Array.ts#L886)
[3.0.0](https://github.com/gcanti/fp-ts/blob/3.0.0/src/ReadonlyArray.ts#L1080)

### Expected behavior

```ts
const chunksOf: (n: number) => <A>(as: ReadonlyArray<A>) => ReadonlyArray<ReadonlyNonEmptyArray<A>>
```

### Suggested solution(s)

```ts
import * as RNEA from './ReadonlyNonEmptyArray'

export function chunksOf(n: number): <A>(as: ReadonlyArray<A>) => ReadonlyArray<RNEA.ReadonlyNonEmptyArray<A>> {
  return n >= 1
    ? flow(chop(flow(splitAt(n), ([a, b]) => [RNEA.fromReadonlyArray(a), b])), compact)
    : flow(
        RNEA.fromReadonlyArray,
        O.fold(() => empty, of)
      )
}
```

### Additional context

Not sure if this is more correct, but seems doable.

I'm willing to make PRs for this if this is desired

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |  [1.10.0](https://github.com/gcanti/fp-ts/pull/577) -> [current](https://github.com/gcanti/fp-ts/blob/3f39202a332f193c1656f6b5fce19dbbbfb0aed7/src/Array.ts#L886)         |
| TypeScript |       N/A     |

**Comment by gcanti** [comment]
Thank you @anthonyjoeseph, just finished a big refactoring ([PR](https://github.com/gcanti/fp-ts/pull/1412)) involving the `ReadonlyArray` and `ReadonlyNonEmptyArray` which should allow us to improve the `chunksOf` signature. WDYT?

**Comment by anthonyjoeseph** [comment]
Wow this is huge! It looks great. I much prefer your approach of implementing `chop` & `splitAt` & `chunksOf` in ReadonlyNonEmptyArray, and using that to implement everything else
