### ISSUE TITLE
How to filter lefts from an array of TaskEithers?

### ISSUE THREAD

**Issue by hellos3b** [gcanti/fp-ts#1408]
## 📖 Documentation

I have an array of TaskEithers, some may return as a Left, and I would like to return only the rights

Similar to `Array.rights` for Either

```ts
declare const getUserById(id: string): TaskEither<NotFound, User>;

const getProfiles = (ids: string[]) => pipe(
  ids.map(getUserById),
  // filter lefts, TE.rights
  TE.sequenceArray
)
```

I don't see `TE.isRight` or `TE.isLeft`

**Comment by anthonyjoeseph** [comment]
```ts
import * as O from 'fp-ts/Option'
import * as T from 'fp-ts/Task'
import * as RA from 'fp-ts/ReadonlyArray'

const getProfiles = (ids: string[]) => pipe(
  ids.map(getUserById),
  T.sequenceArray,
  T.map(RA.map(O.fromEither)),
  T.map(RA.compact)
)
```

I'd recommend joining the #fp-ts channel on the [functional programming slack workspace](https://fpchat-invite.herokuapp.com) for this kind of question - the community has been supportive and helpful for me!

**Comment by gcanti** [comment]
FYI: `map` + `sequence` = `traverse`

```ts
import { flow } from 'fp-ts/function'
import * as RA from 'fp-ts/ReadonlyArray'
import * as T from 'fp-ts/Task'
import * as TE from 'fp-ts/TaskEither'

export const program = <A, E, B>(
  f: (a: A) => TE.TaskEither<E, B>
): ((as: ReadonlyArray<A>) => T.Task<ReadonlyArray<B>>) => flow(T.traverseArray(f), T.map(RA.rights))
```

**Comment by hellos3b** [comment]
> I'd recommend joining the #fp-ts channel on the [functional programming slack workspace](https://fpchat-invite.herokuapp.com) for this kind of question - the community has been supportive and helpful for me!

Sweet, didn't know this exists. 

Also thanks @gcanti can't believe I've missed that this whole time
