### ISSUE TITLE
Insertion order in e.g. `Map`

### ISSUE THREAD

**Issue by thought2** [gcanti/fp-ts#1410]
### Current Behavior

Currently there is no way to get the keys or entries from a `Map` in the insertion order with `fp-ts`. The function `keys` and `toArray` need an `Ord` instance and thus provide the output ordered.

### Desired Behavior

The native methods `keys` and `entries` give you the insertion order guarantee though.
It would be nice if the library provides wrappers for those functions

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |         2.9.5   |
| TypeScript |        4.1.3    |

**Comment by gcanti** [comment]
See https://github.com/gcanti/fp-ts/issues/1243

**Comment by thought2** [comment]
:+1:
