### ISSUE TITLE
What import to use in package shared between node app and frontend app

### ISSUE THREAD

**Issue by aherrmann13** [gcanti/fp-ts#1417]
I was not able to find any resources in the documentation that lays out how to use the `lib` vs `es6` imports

I would expect to import without lib or es6 in a shared lib (e.g. `import { pipe } from 'fp-ts/function'`).  When this code is transpiled to js and run in node I get the error
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '<proj path>/node_modules/fp-ts/function' imported from <proj path>/dist/validation/item.js
Did you mean to import fp-ts/lib/function.js?
```

(<proj path> is actual path to directory)

However, if this code is consumed by a frontend application I want the es6 version to be used.  I would think this would be done by referencing 'fp-ts/function' in shared lib, and letting webpack or rollup use module instead of main, this does not seem to work with pure TS transpile + running in node.

Is there something I am missing or any documentation that lays out which to use?

**Comment by gcanti** [comment]
> I would expect to import without lib or es6 in a shared lib (e.g. `import { pipe } from 'fp-ts/function'`)

That's correct

**Comment by aherrmann13** [comment]
using `import { pipe } from 'fp-ts/function'` transpiles fine but im getting an error when I run the code in node.  are there any additional steps?  I can create a project with reproducible err to link here if needed

**Comment by gcanti** [comment]
> I can create a minimal project with reproducible err to link here if needed

it would definitely help 👍
