### ISSUE TITLE
Deriving bracket fromMonadThrow

### ISSUE THREAD

**Issue by waynevanson** [gcanti/fp-ts#1418]
## 📖 Documentation

How would we derive `bracket` from `MonadThrow`?
I can't see a way to structurally derive it.

The docs say it can be done for `TaskEither`, but the implementation doesn't use it.

Only thing I'd say I could've overlooked is using `ap`, but it's basically just chain, right?

```ts
export interface BracketT<F> {
  <S, A, B>(
    aquire: Lazy<HKT<F, S>>,
    release: R.Reader<S, (fa: HKT<F, A>) => HKT<F, B>>
  ): (use: R.Reader<S, HKT<F, A>>) => HKT<F, B>;
}

export interface BracketT2<F extends URIS2> {
  <S, E, A, B>(
    aquire: Lazy<Kind2<F, E, S>>,
    release: R.Reader<S, (fa: Kind2<F, E, A>) => Kind2<F, E, B>>
  ): (use: R.Reader<S, Kind2<F, E, A>>) => Kind2<F, E, B>;
}

export function bracketT<F>(F: MonadThrow<F>): BracketT<F>;
export function bracketT<F extends URIS2>(F: MonadThrow2<F>): BracketT2<F>;

export function bracketT<F>(F: MonadThrow<F>): BracketT<F> {
  // implementation...
}
```

**Comment by gcanti** [comment]
`bracket` can be derived from `MonadError`, here's a [PureScript implementation](https://github.com/purescript/purescript-transformers/blob/v3.4.0/src/Control/Monad/Error/Class.purs#L83-L94)

**Comment by waynevanson** [comment]
So fp-ts `MonadThrow` is equivelent to purescripts `MonadThrow`, which supports throwing. We don't have a `MonadCatch`, which supports catching.

In Either's bracket, it looks like this has been done with `isLeft` and `isRight`.

Should we add `MonadCatch` as a typeclass? Means we can derive `bracket` and other `try` combinators.

**Comment by gcanti** [comment]
> Should we add MonadError as a typeclass? Means we can derive bracket and other try combinators.

We could define `bracket` as an helper in `EitherT` instead
