### ISSUE TITLE
constant

### ISSUE THREAD

**Issue by ShalokShalom** [gcanti/fp-ts#1423]
### Current Behavior

Currently, I use const in combination with Object.freeze.
This is not only unhandy, it is also not a deep freeze.

### Desired Behavior

I like a keyword, preferably ```constant``` that combines both deeply frozen objects and the behavior of const.

### Suggested Solution

Implement an equivalent of a truly constant binding in other languages, so that in typescript, a constant behaves like suggested. (constant)

### Who does this impact? Who is this for?

Impacts all living beings in the universe and is considered one of the basics of programming. 🙂 

### Describe alternatives you've considered

Using Fable, Elm, and similar projects.

### Additional context

I have absolutely no idea about Typescripts implementation details and just skimmed over the alternative libraries for this feature and it seems to be non-existent yet, which baffles me. 

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      current      |
| TypeScript |    current    |

Thanks a lot 🤗

**Comment by gcanti** [comment]
> I use const in combination with Object.freeze

Looks something you might do in JavaScript, in TypeScript you can model your data types as immutable

**Comment by ShalokShalom** [comment]
How?
