### ISSUE TITLE
BifunctorWithIndex Typeclass

### ISSUE THREAD

**Issue by waynevanson** [gcanti/fp-ts#1432]
## 🚀 Feature request

Allow encoding of HKT's that may implement `BifunctorWithIndex`.

Have the following functions on it:
- mapLeft
- mapLeftWithIndex
- bimap
- bimapWithIndex

I have seen no prior art and cannot find any online with a quick search.

### Current Behavior

Does not exist.

### Desired Behavior

Make it exist.

### Suggested Solution

```ts
export interface BifunctorWithIndex<F, I, J>
  extends Bifunctor<F>,
    FunctorWithIndex<F, J> {
  readonly mapLeftWithIndex: <E, G>(
    f: (i: I, e: E) => G
  ) => <A>(fa: HKT2<F, E, A>) => HKT2<F, G, A>;
  readonly bimapWithIndex: <E, G, A, B>(
    f: (i: I, e: E) => G,
    g: (i: J, a: A) => B
  ) => (fa: HKT2<F, E, A>) => HKT2<F, G, B>;
}
```

The indicies may or may not be the same in the `mapleftWithIndex` function as with `mapWithIndex`, but this allows flexibility for when that may be the case.

### Who does this impact? Who is this for?

Me, advanced users to implement, any exposure level to use.

### Additional context

A datatype to use this: `FruitTree` (needs a cooler name)
I've started implementing a `tree` that holds a different value only on the ends.

```ts
export interface Fruit<A> {
  value: A
}

export interface Branch<E, A> = {
  value: E,
  forest: Array<>
}

export type FruitTree<E, A> = Branch<E, A> | Fruit<A>

// edges to the node from the start,
// indexed by fa.forest[i]
export type Index = Array<number>


export const BifunctorWithIndex<"URI", Index, Index> ={...} 
```

In a normal tree, this index would be available (if implemented) under `FunctorWithIndex<URI, Array<number>>`

The `Bifunctor` in `FruitTree` can also have an index, thus `BifunctorWithIndex` may be born.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |        2.9.5    |
| TypeScript |          4.2.2  |

**Comment by gcanti** [comment]
@waynevanson this feature request needs more info:

- what's the definition of `BifunctorWithIndex`?
  - what's the signature of `mapLeftWithIndex`?
  - what's the signature of `bimapWithIndex`?
- which data type could possibly implement an instance of `BifunctorWithIndex`?
- is there prior art on something named `BifunctorWithIndex`?

**Comment by waynevanson** [comment]
Sure thing, updated the issue.

On the research, it seems it's an extremely rare case for others to use.

If this doesn't make it into the core libraries, that's okay. I'll be implementing this either way.

**Comment by gcanti** [comment]
@waynevanson yeah, it looks too specific if it applies to only one data type

**Comment by waynevanson** [comment]
Closing as marked out of scope.
