### ISSUE TITLE
Add `getChainValidation` to `Either`

### ISSUE THREAD

**Issue by anthonyjoeseph** [gcanti/fp-ts#1441]
### Current Behavior

To use Do notation on an `Either` with `Validation` behavior, you must use `getValidation` - which is deprecated

### Desired Behavior

Maybe there could be a `getChainValidation` (to complement `getApplicativeValidation` and `getAltValidation`)

### Suggested Solution

```ts
// Either.ts
const getChainValidation<E>(SE: Semigroup<E>): Chain2C<URI, E> = {...}

//Application.ts
import * as A from 'fp-ts/Array'
import * as E from 'fp-ts/Either'
import * as C from 'fp-ts/Chain'
const bindValidation = C.bind(E.getChainValidation(A.getMonoid<string>()))
```

### Who does this impact? Who is this for?

Users of `Validation` who want Do notation

### Describe alternatives you've considered

Users could continue using `getValidation`, or they could use `Do` from fp-ts-contrib ([example](https://paulgray.net/do-syntax-in-typescript/#sequence-s))

### Additional context

I may be missing something - there might be an existing solution that I don't know about

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.10.0-rc.4      |
| TypeScript |       4.1.5     |

**Comment by gcanti** [comment]
You can use the exported `bind` function, its behaviour doesn't change with validation (in fact `C.bind` doesn't use `ap` in its implementation).

**Comment by anthonyjoeseph** [comment]
Thank you!
