### ISSUE TITLE
More ergonomic non empty array constructor

### ISSUE THREAD

**Issue by jleider** [gcanti/fp-ts#1464]
### Current & Desired Behavior

```typescript
import * as NA from "fp-ts/NonEmptyArray";

const t = [1, 2, 3] as const
const fpts29 = NA.cons(t[0], t.slice(1));
const fpts211 = NA.cons(t[0])(t.slice(1));

const proposed = NA.cons(t);
```

### Suggested Solution

Add another override for `cons` or call it `fromTuple` or `fromReadonlyArray`, etc.

```typescript
import * as NA from "fp-ts/NonEmptyArray";

const t1 = [1, 2, 3] as const;

const toNA = <A>(t: readonly [A, ...(readonly A[])]) =>
  NA.cons(t[0], t.slice(1));

const fpts29 = NA.cons(t1[0], t1.slice(1));

// Downside here is that you need to provide <number> to widen the type
// if you dont want your array to be Array<1 | 2 | 3>
const proposed1: NA.NonEmptyArray<1 | 2 | 3> = toNA(t1);
const proposed2: NA.NonEmptyArray<number> = toNA<number>(t1);

```

Prototype: https://codesandbox.io/s/nameless-violet-xh1pj?file=/src/index.ts

### Who does this impact? Who is this for?

Anyone using non-empty array constructor or any of the other array variants using cons constructor and who have tuples they want to convert to non-empty arrays.

This would require TS 4.0 I believe: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |       2.9.5     |
| TypeScript |      4.2      |

**Comment by gcanti** [comment]
Looks like [`fromReadonlyNonEmptyArray`](https://gcanti.github.io/fp-ts/modules/NonEmptyArray.ts.html#fromreadonlynonemptyarray)

**Comment by jleider** [comment]
Oh yeah, that would do it. I didnt notice that that function was added in 2.10 already. Thanks!
