### ISSUE TITLE
FantasyLand style application of a natural transformation

### ISSUE THREAD

**Issue by DylanRJohnston** [gcanti/fp-ts#148]
This is another usability proposal but I'm open to suggestions. I'm making use of TaskEither pretty heavily but I quite often end up with two cases.

First: `TaskEither<L, Either<L, R>>`
Second: `Either<L, TaskEither<L, R>>`

I also have a function `fromEither<L, R>(e: Either<L, R>): TaskEither<L, R>`  which I think you can view as a Natural Transformation.

The first situation I solve by going
`(TaskEither<L, Either<L, R>>).chain(fromEither)`

The second I solve by going
`fromEither(Either<L, TaskEither<L, R>>).chain(identity)`

The "problem" arises in the second case when the `Either<L, TaskEither<L, R>>` is the result of a long chain of computations
```
fromEither(
  foo()
    .chain(method1)
    .chain(method2)
    .chain(method3)
).chain(identity)
```

It makes understanding the function harder as the control flow jumps back up to the top, and then down to the bottom. My proposal is something like this following

```
foo()
  .chain(method1)
  .chain(method2)
  .chain(method3)
  .nat(fromEither)
  .chain(identity)
```

I hope that makes sense.

**Comment by DylanRJohnston** [comment]
Also maybe having `flatten` on the fantasy land monad would be useful as this is what I'm using `chain(identity)` for.

**Comment by DylanRJohnston** [comment]
There's also the more general case of applying an arbitrary function to itself.

```
selfApply(this: A, f: (a: A) => B): B {
  return f(this)
}
```

**Comment by gcanti** [comment]
@DylanRJohnston I wonder, why you end up with `TaskEither<L, Either<L, R>>` / `Either<L, TaskEither<L, R>>` in the first place? Could you please show a real example?

**Comment by DylanRJohnston** [comment]
As a simple example, we fetch messages from Amazon SQS, sometimes these messages are too big and they'll have a field that indicates that the rest of the message needs to be retrieved from S3. Talking to SQS and S3 are asynchronous operations that may fail (Hence the use of TaskEither), and the branching on whether or not the message needs to be fetched from S3 is modelled by the Either. Something like this.

```
const processMessage = ({ Body }: SQS.Message) =>
  right<never, string | undefined>(Body)
    // The SQS message body could be empty, short circuit
    .chain_(fromNullable(SQSErr.EmptyMessage))
    // use io-ts to parse the message string into the SQSMessage
    .chain_(deserializeAndValidate(SQSMessage))
    // This takes two refinements and splits into an Either type
// The type here is Either<SQSErr.EmptyMessage | DeserializationError | ValidationError, Either<RawMessage, S3Message>>
    .map(refinementToEither(isRawMessage, isS3Message))
    .map(foldEither(Future.of, getMessageFromS3))
    .nat(fromEither)
```

**Comment by DylanRJohnston** [comment]
This is my current augmentation of Either with the chain_ and nat methods.

```typescript
import * as either from 'fp-ts/lib/Either'
import { Either, URI as URIEither } from 'fp-ts/lib/Either'
import { HKT2 } from 'fp-ts/lib/HKT'
import { Future, URI as URIFuture } from 'lib/Future'

type NaturalTransformation2<F, G> = <L, A>(fa: HKT2<F, L, A>) => HKT2<G, L, A>

declare module 'fp-ts/lib/Either' {
  export interface Left<L, A> {
    chain_<B, L2>(f: (a: A) => Either<L2, B>): Either<L | L2, B>
    nat(
      this: Either<L, A>,
      f: NaturalTransformation2<URIEither, URIFuture>,
    ): Future<L, A>
    nat<G>(
      this: Either<L, A>,
      f: NaturalTransformation2<URIEither, G>,
    ): HKT2<G, L, A>
  }
  export interface Right<L, A> {
    chain_<B, L2>(f: (a: A) => Either<L2, B>): Either<L | L2, B>
    nat(
      this: Either<L, A>,
      f: NaturalTransformation2<URIEither, URIFuture>,
    ): Future<L, A>
    nat<G>(
      this: Either<L, A>,
      f: NaturalTransformation2<URIEither, G>,
    ): HKT2<G, L, A>
  }
}

function nat<L, A>(
  this: Either<L, A>,
  f: NaturalTransformation2<URIEither, URIFuture>,
): Future<L, A>
function nat<G, L, A>(
  this: Either<L, A>,
  f: NaturalTransformation2<URIEither, G>,
): HKT2<G, L, A> {
  return f(this)
}

either.Right.prototype.chain_ = either.Right.prototype.chain
either.Right.prototype.nat = nat

either.Left.prototype.chain_ = either.Left.prototype.chain
either.Left.prototype.nat = nat

export * from 'fp-ts/lib/Either'
```

**Comment by DylanRJohnston** [comment]
I feel like this create a nice concise readable process flow.

```
const processMessage = ({ Body }: SQS.Message) =>
  right<never, string | undefined>(Body)
    .chain_(fromNullable(SQSErr.EmptyMessage))
    .chain_(deserializeAndValidate(SQSMessage))
    .map(refinementToEither(isRawMessage, isS3Message))
    .map(foldEither(Future.of, getMessageFromS3))
    .nat(fromEither)
    .chain_(identity)
```
vs
```
const processMessage = ({ Body }: SQS.Message) =>
  fromEither(
    right<
      | SQSErr.EmptyMessage
      | DeserializationError
      | ValidationError
      | S3Err.NotABuffer
      | S3Err.GetObject,
      string | undefined
    >(Body)
      .chain(fromNullable(SQSErr.EmptyMessage))
      .chain(deserializeAndValidate(SQSMessage))
      .map(refinementToEither(isRawMessage, isS3Message))
      .map(foldEither(Future.of, getMessageFromS3)),
  ).chain(identity)
```

**Comment by gcanti** [comment]
@DylanRJohnston Unfortunately I can't play with your example (there are some unspecified items). 

What I mean is that often if you end up calling `flatten`, it's possible that something went wrong in the chain of operations (being `map`s the main culprit) with the result of creating nested structures. 

In your specific case 

> branching on whether or not the message needs to be fetched from S3 is modelled by the Either

if you model this logic with an ADT (you could have a third case in the future) instead of using `Either`, how this decision would affect the code above?

**Comment by DylanRJohnston** [comment]
Sorry I'm trying to not post the entire codebase. I agree that having to use flatten is usually a sign you should have used chain instead of map somewhere. But I don't think that is true in this case.

Fundamentally it's because I'm combing operations that are and aren't synchronous, plus using Either's in one context to represent Errors, and in another to represent branching code. I try to slim down the example here:

```
import { TaskEither, fromEither } from './TaskEither'
import { Either, left, right, fold } from 'fp-ts/lib/Either'
import * as T from 'io-ts'

interface DataType1 extends T.TypeOf<typeof DataType1> {}
const DataType1 = T.interface({
  kind: T.literal('DataType1'),
  x: T.number,
})
interface DataType2 extends T.TypeOf<typeof DataType2> {}
const DataType2 = T.interface({
  kind: T.literal('DataType2'),
  x: T.string,
})
type Data = T.TypeOf<typeof Data>
const Data: T.Type<DataType1 | DataType2> = T.union([DataType1, DataType2])

const isData1 = (x: Data): x is DataType1 => x.kind === 'DataType1'
const isData2 = (x: Data): x is DataType2 => x.kind === 'DataType2'

const data1OrData2 = (x: Data): Either<DataType1, DataType2> =>
  isData1(x) ? left(x) : right(x)

const fetchDataB = ({ x }: DataType2) =>
  TaskEither.of<Error, DataType1>(null as any)

const fetchDataA = (x: any) =>
  fromEither(
    (T.validate(x, Data) as Either<T.ValidationError[] | Error, Data>)
      .map(data1OrData2)
      .map(e =>
        e.fold(
          data1 => TaskEither.of(data1),
          fetchDataB,
        ),
      ),
  ).chain(x => x)
```
