### ISSUE TITLE
Extend A.filter function to work with predicates with union type argument and keep narrowed type

### ISSUE THREAD

**Issue by val-o** [gcanti/fp-ts#1484]
## 🐛 Bug report

Hi, thanks for great lib. I noticed strange behavoir while working with filter functions in combination of both predicates and reefinements.
You can see the problem in this TS issue https://github.com/microsoft/TypeScript/issues/43706
Basically, we need to make second overload of `filter` function to have 2 generic parameters so TS can keep narrowed type while working with predicates

Namely, from this:
```
export declare const filter: {
  <A, B extends A>(refinement: Refinement<A, B>): (fa: Array<A>) => Array<B>
  <A>(predicate: Predicate<A>): (fa: Array<A>) => Array<A>
}

```
to this:
```
export declare const filter: {
  <A, B extends A>(refinement: Refinement<A, B>): (fa: Array<A>) => Array<B>
  <A>(predicate: Predicate<A>):<B extends A> (fa: Array<B>) => Array<B>
}

```

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |     2.10       |
| TypeScript |      3.9+      |

**Comment by gcanti** [comment]
@val-o Thanks for reporting, looks like a nice enhancement.

While playing with the proposed change I found an unwanted side effect:

```ts
import { pipe } from 'fp-ts/function'
import * as RA from 'fp-ts/ReadonlyArray'
import * as E from 'fp-ts/Either'

const isPositive = E.exists((n: number) => n > 0)

const eithers: ReadonlyArray<E.Either<string, number>> = []

const rights = pipe(eithers, RA.filter(E.isRight))

export const nice = pipe(rights, RA.filter(isPositive)) // <= now this errors with Argument of type '<E>(ma: Either<E, number>) => boolean' is not assignable to parameter of type 'Predicate<unknown>'
```

As far as I know this is due to the `exists` signature:

```ts
export declare function exists<A>(predicate: Predicate<A>): <E>(ma: Either<E, A>) => boolean
```

where the `E` type parameter is not used in the output type.

Indeed if I change `exists` to

```ts
export declare function exists<A>(predicate: Predicate<A>): (ma: Either<unknown, A>) => boolean
```

the new error goes away, so I guess we should make both changes, but I'm a bit concerned by unexpected regressions like this.
