### ISSUE TITLE
0.4.0 status

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#150]
Hey @gcanti. 0.4.0 is currently available via the `next` dist tag. Do you know when it will hit stable? Is there remaining work to be done?

Thanks!

Olly

**Comment by gcanti** [comment]
In my opinion no, there's no more work to do, just testing. I just would wait for some feedback from @justinwoo who is trying the lastest versions of fp-ts, io-ts and monocle-ts in some of its projects: then if there are no major issues I'll release 0.4.0 soon

**Comment by justinwoo** [comment]
Looks all good to me, my projects all work pretty well with the new versions 👍

**Comment by gcanti** [comment]
Awesome, thanks @justinwoo for testing out. I'll release the stable version asap

**Comment by gcanti** [comment]
Released
