### ISSUE TITLE
Reduce the supported number of arguments to pipe function

### ISSUE THREAD

**Issue by pbadenski** [gcanti/fp-ts#1507]
### Current Behavior

85b51d1 increased number of arguments to pipe function. However, it seems that there's an odd performance cliff in V8  when more 10 "case" statements are used. I am not entirely clear what's going on under the hood and I inquired on v8-users google group for details (https://groups.google.com/g/v8-users/c/_Add2xOVmfU). Performance loss is substantial - I noticed between 2 to 4 times deterioration.

### Reproducible example

```
const foo = (obj: { a: { b: string } }) => {
  return pipe(
    option.fromNullable(obj.a),
    option.map(x => x.b)
  );
}

const bar = (obj) => {
  return pipe(
    foo(obj),
    option.chain(x => option.some(x))
  );
}

let x = bar(obj);
```

Results:
```
pipe; Cases = 10 x 35,191,983 ops/sec ±0.64% (89 runs sampled)
pipe; Cases > 10 x 14,563,165 ops/sec ±0.74% (87 runs sampled)
```

### Suggested solution(s)

Personally I'd be interested in seeing number of supported pipe arguments reduced back to 10, especially since the performance impact seems substantial. I understand that this would be a backwards incompatible change. I would argue that pipe with more than 10 arguments are rather infrequent, but other people may have a different view.

### Additional context

This is especially relevant since non-pipeable methods delegate to pipe, ie:
```
var _chain = function (ma, f) { return function_1.pipe(ma, exports.chain(f)); };
```

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.10.4           |
| TypeScript |      4.1.5      |

**Comment by steida** [comment]
@pbadenski Is it possible to warn with the eleventh arg?

**Comment by pbadenski** [comment]
I actually thought of alternative suggestion - keep 1-9 case hand-rolled, and add default case to handle list of arguments by reducing them with a for-loop (similar to current `sequenceS` and `sequenceT` implementations)

**Comment by kylegoetz** [comment]
Is there a reason it needs to use case at all? When I implemented something like `pipe` years ago, IIRC it was basically just `pipe = [arg1, ..., argn].reduce((acc, fn) => fn(acc), arg0)`.

**Comment by steida** [comment]
@kylegoetz Types

**Comment by kylegoetz** [comment]
@steida export a bunch of declared functions but the actual real function type does not get exported. I thought the codebase already did this for pipe. My mistake.

**Comment by gcanti** [comment]
Related https://github.com/gcanti/fp-ts/pull/1400

**Comment by pbadenski** [comment]
@kylegoetz also `reduce` tend to be massively inefficient..

**Comment by pbadenski** [comment]
@gcanti thoughts on this, specifically proposal in https://github.com/gcanti/fp-ts/issues/1507#issuecomment-841841849? I can prepare a pull request if this is an acceptable solution.

**Comment by pbadenski** [comment]
@gcanti just following up whether you would consider pull request for this?

**Comment by gcanti** [comment]
@pbadenski yes, thanks
