### ISSUE TITLE
`parse` from JSON module doesn't return previous error type information

### ISSUE THREAD

**Issue by AustinBurns** [gcanti/fp-ts#1508]
### Current Behavior

Right now, `J.parse` (from the Json module) returns `Either<unknown, J.Json>` which at first glance seems fine, but in actuality, because `unknown` in TS is a top type, the error type ends up just being `unknown` and you lose all type information of the previous left channel.

For instance, if already in the context of an `Either<E, A>` and then chaining a call to `J.parse` with `E.chainW` (which would end up as `E | unknown` in the left channel), the result is just `Either<unknown, J.Json>`.

### Expected behavior

Allowing the caller to pass in an `onError` function to `J.parse` to be able to determine what the error type should be would allow more flexibility and allow for the possibility of retaining all type information from the previous left channel.

### Reproducible example
https://tsplay.dev/m3Anbw

### Suggested solution(s)

Current `J.parse` implementation:

```
export const parse = (s: string): Either<unknown, Json> => parseJSON(s, identity)
```

Suggested new implementation:

```
export const parse = <E>(onError: (reason: unknown) => E) => (s: string): Either<E, Json> => parseJSON(s, onError)
```

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

1. `v2.10+`.

2. The JSON module was introduced in `v2.10` so it was not available in previous versions

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |     2.10       |
| TypeScript |      4.2.4      |

**Comment by AustinBurns** [comment]
I also don't mind making a PR for this myself.

**Comment by gcanti** [comment]
You can `mapLeft`:

```ts
import { mapLeft } from 'fp-ts/Either'
import { pipe } from 'fp-ts/function'
import { parse } from 'fp-ts/Json'

const result = pipe(
  parse('{}'),
  mapLeft((e) => ...)
)
```

**Comment by AustinBurns** [comment]
Yup, and that's what I tried at first. But the problem still remains that if you have a previous `Either` and you chain on it, you lose the previous type information.

Here is a typescript playground to show what I am talking about (sorry I should have shared this when I originally made the issue):
https://tsplay.dev/m3Anbw

**Comment by gcanti** [comment]
@AustinBurns the following

- `str => E.parseJSON(str, error => 'this is the new Error type')`
- `flow(J.parse, E.mapLeft(() => 'this is the new Error type'))` 
 
are equivalent:

```ts
import { pipe, flow } from 'fp-ts/function'
import * as E from 'fp-ts/Either'
import * as J from 'fp-ts/Json'

// const result: E.Either<string | Error, J.Json>
const result = pipe(
  null,
  E.fromNullable(new Error('This is the previous error type')),
  E.chainW(flow(J.parse, E.mapLeft(() => 'this is the new Error type')))
)
```

**Comment by AustinBurns** [comment]
That is true, and I agree it's a workaround. However, I can definitely see people getting tripped up by that at first (it happened to myself which is how I found the issue) because `unknown` will always type check and all of a sudden the error type has silently changed from what was expected whereas with the proposal it forces the caller to take care of the `unknown` type so that which makes the caller aware that the type would change.

Anyways, since there is a workaround and what is being proposed would be a breaking change I understand that this will most likely stay as is.

**Comment by alpharder** [comment]
This issue makes JSON module completely useless under wide variety of circumstances. `unknown` has to be `SyntaxError`  in the first place.

**Comment by samhh** [comment]
If per the language spec it should always throw a `SyntaxError` I think it'd be reasonable to [assert](https://github.com/samhh/fp-ts-std/blob/0.17.1/src/JSON.ts#L157) that. Same with stringification and `TypeError`.
