### ISSUE TITLE
curried and data-last `concat` instead of just binary function

### ISSUE THREAD

**Issue by kylegoetz** [gcanti/fp-ts#1514]
### Current Behavior

```typescript
export declare function concat<A>(first: Array<A>, second: NonEmptyArray<A>): NonEmptyArray<A>
export declare function concat<A>(first: NonEmptyArray<A>, second: Array<A>): NonEmptyArray<A>
```

### Desired Behavior

```typescript
export declare const concat: <A>(first: Array<A>) => (second: NonEmptyArray<A>) => NonEmptyArray<A>
export declare const concat: <A>(first: NonEmptyArray<A>) => (second: Array<A>) => NonEmptyArray<A>

```

### Suggested Solution

Check if second argument is undefined, and if so, return a partial function.

```typescript
const concat = (arg1, arg2) => {
  if(arg2 === undefined) {
    return (n) => concat(arg1,n)
  }
  // whatever current concat does here, leave here
}
```

If you do it this way, it won't be a breaking change. It will just be an enhancement requiring, presumably, a minor version bump.

### Who does this impact? Who is this for?

So much of fp-ts (and related libraries) are nice, pipeable functions with data-last, but then `concat` isn't, so you have something like:

```
declare const as: any[]

rowsTraversal.filter(_b => eqBuildingUse.equals(b,_b)).composeLens(_assemblies).modify(_as => NEA.concat(_as, as))
```

just having `modify(NEA.concat(as))` would be nice and ergonomic.

### Describe alternatives you've considered

for now I'm just having to explicitly do `modify(as => NEA.concat(as, _as))`

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      ^2.10.2      |
| TypeScript |      ^4.2.4      |

**Comment by gcanti** [comment]
@kylegoetz this should be fixed in `2.11` (you can try the RC by running `npm install fp-ts@rc`)
