### ISSUE TITLE
Functional programming link is invalid

### ISSUE THREAD

**Issue by golergka** [gcanti/fp-ts#1516]
## 📖 Documentation

The link in the README: https://github.com/gcanti/fp-ts/blob/master/functionalprogramming.slack.com seems to return 404 at the moment.

**Comment by golergka** [comment]
Also, when I tried to join at https://functionalprogramming.slack.com it didn't have any way to register as a new user. May be I don't get slack? Or is this community invite-only?

**Comment by golergka** [comment]
@gcanti thanks for merging my PR, but what about my follow-up question here? Is that slack intended to be invitation-only?

**Comment by gcanti** [comment]
@golergka mmhh not sure what's going on, looks like there's no way to get an invite link at the moment
