### ISSUE TITLE
Task only triggers the side effect once even if I run it twice

### ISSUE THREAD

**Issue by stevemao** [gcanti/fp-ts#1520]
## 🐛 Bug report

Task only triggers the side effect once even if I run it twice

```
import { constant, identity, pipe } from 'fp-ts/lib/function'
import * as T from 'fp-ts/Task'
import * as E from 'fp-ts/Either'
import * as TE from 'fp-ts/TaskEither'

const t = TE.fromEither(E.tryCatch(() => console.log("task1"), identity))

const t2 = TE.fromEither(E.tryCatch(() => console.log("task2"), identity))

const run: T.Task<void> = pipe(
    t,
    TE.chain(_ => t2),
    TE.fold(constant(T.of(undefined)), constant(T.of(undefined)))
)

run()
const run2 = run
run2()
```

### Current Behavior

It only prints

```
task1
task2
```

### Expected behavior

Should print

```
task1
task2
```

twice, could be

```
task1
task1
task2
task2
```

### Suggested solution(s)

A workaround:

```import { constant, identity, pipe } from 'fp-ts/lib/function'
import * as T from 'fp-ts/Task'
import * as E from 'fp-ts/Either'
import * as TE from 'fp-ts/TaskEither'

const t = TE.fromEither(E.tryCatch(() => console.log("task1"), identity))

const run: T.Task<void> = pipe(
    t,
    TE.chain(_ => TE.fromEither(E.tryCatch(() => console.log("task2"), identity))),
    TE.fold(constant(T.of(undefined)), constant(T.of(undefined)))
)

run()
const run2 = run
run2()
```

And this prints

```
task1
task2
task2
```

Though `task1` should be printed twice too.

The only difference is I inline `t2`. the code should behave exactly the same as my original example

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

2.10.4. Not sure if it worked before

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |    2.10.4        |
| TypeScript |     4.2.4       |

**Comment by samhh** [comment]
A simpler repro is this:

```ts
TE.fromEither(E.tryCatch(() => console.log('x'), identity))
```

In that it prints the console log immediately, not when the `Task` is evaluated.

I don't think this is a bug. You're treating impure code as if it's pure. More specifically you're not representing the call to `console.log` as `IO`.

You can solve this for example as follows:

```ts
const f = IOE.tryCatch(() => console.log('x'), identity)
const g = TE.fromIOEither(f)
```

(`IOE` would be [fp-ts/IOEither](https://gcanti.github.io/fp-ts/modules/IOEither.ts.html#trycatch).)
