### ISSUE TITLE
Add `let` functions for Do notation

### ISSUE THREAD

**Issue by ar1a** [gcanti/fp-ts#1524]
### Current Behavior

To run some computation outside of a monad, you have to do something like

```ts
pipe(
  Do,
  bind('x', () => of(a + b)),
);
```

### Desired Behavior

```ts
pipe(
  Do,
  let ('x', () => a + b),
);
```

This was present in fp-ts-contrib 
```ts

  let: <N extends string, A>(name: Exclude<N, keyof S>, a: A) => Do0<M, S & { [K in N]: A }>
  letL: <N extends string, A>(name: Exclude<N, keyof S>, f: (s: S) => A) => Do0<M, S & { [K in N]: A }>
```

### Suggested Solution

Create a function for types that have Do notation implementations (`Task`, `Option`, etc) with a let function.

### Environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |     2.10.5     |
| TypeScript |     4.3.2       |

**Comment by thought2** [comment]
I was looking for this, too. I think it would be useful.

As `bind` is exported as standalone function, for `let` we'd need a name that's not a reserved word. (e.g. `let_`)

**Comment by entropitor** [comment]
@gcanti Would you accept a PR that implements this? As I think this is the major reason why fp-ts-contrib's Do notation is better than using do notation from fp-ts.

**Comment by entropitor** [comment]
@gcanti Can I ask why you wouldn't like / accept a PR for this?

**Comment by gcanti** [comment]
@entropitor because `bind` encompasses both functionalities, however since this feature seems pretty popular I changed my mind
