### ISSUE TITLE
Typed flow

### ISSUE THREAD

**Issue by KhraksMamtsov** [gcanti/fp-ts#1527]
## 🚀 Feature request

Hi, thanks for great lib!
What do you think about additional overloads for flow like this?

### Current Behavior
```ts
// flow may be used only in typed context
const optionResult2 = pipe(
  (X.prop),
  flow(
    O.fromNullable,
    O.map(flow(inc, toString, alert)),
    O.getOrElseW(constUndefined)
  )
);
```

### Desired Behavior
```ts
// want use like so, but its impossibe in current typescript
// can't use flow out of typed context
const result = flow(
  O.fromNullable, // Type 'Some<unknown>' is not assignable to type 'Option<number>'.
  O.map(flow(inc, toString)),
  O.getOrElseW(constUndefined)
);
```

### Suggested Solution
```ts
// add several signatures like this
declare function flow<A extends ReadonlyArray<unknown>>(): <B, ..., PreEnd, End>(
  ab: (...a: A) => B,
  ...
  end: (c: PreEnd) => End
) => (...a: A) => End;

// usage

const result = flow<[undefined | number]>()(
  O.fromNullable,
  O.map(flow(inc, toString)),
  O.getOrElseW(constUndefined)
);

result("") // Argument of type '""' is not assignable to parameter of type 'number | undefined'.ts(2345)
result(2) // some("3")
result(undefined) // none

const result = flow()( // - without generic params - fallback to the previous behaviour
  O.fromNullable, // Type 'Some<unknown>' is not assignable to type 'Option<number>'
  O.map(flow(inc, toString, alert)),
  O.getOrElseW(constUndefined)
);

```

### Who does this impact? Who is this for?

Its' allow to create well typed flow out of typed context

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |  latest    |
| TypeScript |  4.3.5     |

**Comment by kylegoetz** [comment]
In the interim, I tend to write mine like this

```typescript
const extractValue = (e:ChangeEvent<HTMLInputEvent>) => e.target.value
declare const transformValue: <A>(a:a) => MyType
declare const updateState: (t:MyType) => void

const onInputChange: (e:ChangeEvent<HTMLInputElement>) => void = flow(
    extractValue, 
    transformValue, 
    updateState
)
```

**Comment by DenisFrezzato** [comment]
@KhraksMamtsov In your example, TypeScript is not able to infer the right type from the usage (because it works from left to right). TypeScript needs a little help and you can fix that by annotating the type of `result` (like in the example made by @kylegoetz).

Your proposed solution needs annotating the types too and I don't think it would improve the DX that much.

**Comment by KhraksMamtsov** [comment]
Manually typed functions may has some inaccuracy unlike auto inferred ones.
[For example:](https://www.typescriptlang.org/play?strict=true#code/JYWwDg9gTgLgBAKjgQwM5wGIAU4DMoQhwDkuYAtDKsQNwBQdAxhAHarwDycAvJlgHQQwMYK3rM28AN64ANhADuAXx59+uAK4tGIsQwns8CgIyqAPAEE4AUwAeMaywAm6AErXkT1rICeFqFDIPmZaANYsiiwAfFEAFACUPFFwZgBCADRwAMJxdHAoAEYAXHCx-OXIJRaJ3MkZeXAFjCWxxXCpNclZ6XSdePIKlpkZ2XHIBZlN8fRMrIa4CuZWdg7Obh5eLL7+gcFhEQrRcX1pmd1wACK5+eMt5fyVcNVJ7T35TS1tHS-dDYxOLWa2T6F16LzkiiGr2ymSusXGk0YmX+030c3gMAgAFUwGBrFAsmhrOYAMo2eyOFxwdhQYAsADmcVsJRJ8RKOLxUEYRLMJOStTgtn4mI5+MJqGsCRQ6GQLB84nRKFksFJ5NWVJpdMZsWZcFZJQABgASKQkpQAQktBpexqktgtVoVkjgmJJMCg5gAcmrKegWBoQAV8UySp62XBbZ6lNaBULXe6tVK0Cg5TMYD48XAsSxRCxeKYAD5wABMcCLAGYy3AACxVgCs9HTmfcqA0shgABUM8TeAAiYyW829qu94uD4dF3vl8cj6szyd18f0JzWRiyZBQYkGeAb+nsnN6bcu6zsFtt+C8EW4sVE+HKmCxeNQeFQenxd80OAAei-cH787-MdLQnP9p2A2cAN7RdgLRZ1mHACBUGAXQWFUCEFEfCA3SgTJkHvTIr05cVrFRH84C7TNiDMb0Vl9OB-UDYMdVDPpRS5HlIwdc0DSiYg4GAP0IB3VAkPpFhxlkYlMRdbsSE1BliH4WZnQUDxQgo6wnDPdtVFiFh91zcN5PpF54MgJCUJmMiNJIaifTWeiAyDKAQzgMMXjY7kJTMTjBx4viBPooTpVE8SCkkl0IBkyjtM7btFOUwxVOQdTuy0k9z1MXg9IM1hw1imyBTMxDkNzT8GGs2TiGMgLBOE0KJKkqKm2JYhXASo9ktSvF0tbdtS14MxXHsjUEwZdI4n0rMDxYfLTMIczSr0OgyLpXB8WpTEGWi4lkA0TEQGQERuVkXw4BW394QAfQABly2aXn-cDJyAocRzAt7JznZ6-2godEvgekIAgJwNKcLIFpKlC0MGABtbNcwAXWOWJzvyfInzedHCJvCUsZue9eis38gZBnbUEmfbIqi+RtukhRaQcAG4E3PqYBaXUEbyl5sEEYRc34Dh+dYMwns+wDII+kDe2+8WoPHfl+kUWIGg4dQCBAT023XcLrCxtXDrAWJioswyelRC7qbgBRgBXHanBZjKdNiXsADZx3iZmbZXMHYo5+6+l5oQUMF4WWFFgcftHSXINl6W-ul93gMV9CVfyNX8EILXTsa-X+EN43IdNvLzeJ621PJr21N8X2nfZ0pkFugOeYEYOBaFlCzGMlOBjTuAM417OdckvOC5NpbZtLiqSeBh2WodvbpLW-FNwd1nz0t667umwyW75kOO9zCPINe6WpYgqOE6iZnSdBtLYph4wzHhmbkYSPuB6z7Xc9V-PkCN8eKF4hTwYEAA)
```ts
const toUpperCase = <S extends string>(x: S): Uppercase<S> => x.toUpperCase() as any;
const alrt = <S extends string>(x: S): `${S}!!!` => `${x}!!!`;
const toStr = <N extends number>(x: N): `${N}` => x.toString() as any;

type Union= 1 | 2 | 3 | 4 | 5;
type ResultType = "1!!!" | "2!!!" | "3!!!" | "4!!!" | "5!!!";
declare const arg: Union;
const testResult = toUpperCase(alrt(toStr(arg))); // "1!!!" | "2!!!" | "3!!!" | "4!!!" | "5!!!"

const composition = flow(toStr, alrt, toUpperCase);
// Type '<N extends number>(x: N) => Uppercase<`${N}!!!`>' is not assignable to type 'string'.
const weakTypedResult = (n: Union): string => composition;

// Type '<N extends number>(x: N) => Uppercase<`${N}!!!`>' is not assignable to type 'ResultType'.
const weakTypedResult1 = (n: Union): ResultType => composition; 

// Type 'string' is not assignable to type 'R'.
const weakTypedResult2 = <R extends string,>(n: Union): R => composition;

// infer stong type automatically 
// (a_0: Union) => "1!!!" | "2!!!" | "3!!!" | "4!!!" | "5!!!"
const goodTypedComposition = fw<[Union]>()( 
    toStr,
    toUpperCase,
    alrt
);

// good types, but too long to write
const result: (x: Union) => O.Option<"1!!!" | "2!!!" | "3!!!" | "4!!!" | "5!!!"> = flow(
  O.fromNullable,
  O.map(composition),
);

// too wide typed result ("6!!!")
const wideTypedResult: (x: Union) => O.Option<"1!!!" | "2!!!" | "3!!!" | "4!!!" | "5!!!" | "6!!!"> = flow(
  O.fromNullable,
  O.map(composition),
);

// weak types
const weaklyTypedResult: (a_0: Union) => O.Option<string> = flow(
  O.fromNullable,
  O.map(composition),
);

// good typed auto inferred result
// (a_0: Union) => O.Option<"1!!!" | "2!!!" | "3!!!" | "4!!!" | "5!!!">
const goodTypedResult = fw<[Union]>()(
  O.fromNullable,
  O.map(composition),
);
```

**Comment by KhraksMamtsov** [comment]
@gcanti what you think?

**Comment by kaladivo** [comment]
I am also trying to solve this in my code. Is there any update on this issue?
