### ISSUE TITLE
Attempted import error: 'hasOwnProperty' is not exported from './internal' (imported as '_').

### ISSUE THREAD

**Issue by euphocat** [gcanti/fp-ts#1548]
## 🐛 Bug report
After upgrading at 2.11.0 I get this error:

`Attempted import error: 'hasOwnProperty' is not exported from './internal' (imported as '_').` from the file `./node_modules/fp-ts/es6/struct.js`

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |    2.11.0        |
| TypeScript |     4.3.5       |

**Comment by nmenke** [comment]
Having the same issue. Looking into node_modules there is indeed not a single export in internal.d.ts

**Comment by gcanti** [comment]
Should be fixed by https://github.com/gcanti/fp-ts/pull/1545
