### ISSUE TITLE
ReadonlyArray.takeRight is missing in docs

### ISSUE THREAD

**Issue by ldrick** [gcanti/fp-ts#1573]
## 📖 Documentation
https://gcanti.github.io/fp-ts/modules/ReadonlyArray.ts.html#takeleft

`RA.takeLeft` and `RA.takeLeftWhile` are documented, unfortunately `RA.takeRight` is not.

**Comment by DenisFrezzato** [comment]
It [is](https://gcanti.github.io/fp-ts/modules/ReadonlyArray.ts.html#takeright) documented, it just has a different category.

I've created a PR: https://github.com/gcanti/fp-ts/pull/1575
