### ISSUE TITLE
async either.tryCatch (for promises/tasks)

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#159]

**Comment by OliverJAsh** [comment]
@gcanti I've been using something like this in my applications. Do you think it could be added to the library?

``` ts
export function eitherTryCatchAsync<E, A>(f: Lazy<Promise<A>>): Promise<Either<E, A>> {
    try {
        return f().then(a => either.right<E, A>(a), e => either.left<E, A>(e));
    } catch (e) {
        return Promise.resolve(either.left<E, A>(e));
    }
}
```

**Comment by gcanti** [comment]
@OliverJAsh the signature is a bit weird

- the input is lazy but the output isn't
- how can you produce an `E`? (indeed since `e: any` then `e => either.left<E, A>(e)` and `Promise.resolve(either.left<E, A>(e))` are basically unsafe casts)

What about

```ts
function tryCatchAsync<E, A>(p: Lazy<Promise<A>>, onerror: (reason: any) => E): Lazy<Promise<Either<E, A>>>
```

**Comment by OliverJAsh** [comment]
@gcanti Good improvements. That works for me!

**Comment by OliverJAsh** [comment]
So:

``` ts
import * as either from 'fp-ts/lib/Either';
import { Lazy } from 'fp-ts/lib/function';

import Either = either.Either;

export const eitherTryCatchAsync = <E, A>(
    f: Lazy<Promise<A>>,
    onError: (reason: any) => E,
): Lazy<Promise<Either<E, A>>> => () => {
    try {
        return f().then(a => either.right<E, A>(a), reason => either.left<E, A>(onError(reason)));
    } catch (e) {
        return Promise.resolve(either.left<E, A>(e));
    }
};
```

**Comment by gcanti** [comment]
I wonder, what the `try..catch` is for? AFAIK both `f()`, `a => either.right<E, A>(a)` can't fail

**Comment by gcanti** [comment]
So basically is this right? https://github.com/gcanti/fp-ts/blob/92bc1ed617597a4ba8246d859d97a470be31b1ad/examples/TaskEither.ts#L75

**Comment by OliverJAsh** [comment]
@gcanti I believe `f` could throw. For example:

``` ts
const someFnThatThrowsSynchronously = () => {
    throw new Error();
}

const fn: Lazy<Promise<string>> = () => {
    someFnThatThrowsSynchronously();
    return Promise.resolve('foo');
}
```

**Comment by gcanti** [comment]
Ah, I see. Though ideally a possible failure should be encoded in the type system (with `Option`/`Either`). 

So shouldn't `fn` be responsible of handling a possible error? Either changing the signature 

```ts
const someFnThatThrowsSynchronously = () => {
    throw new Error();
}

const fn: Lazy<Option<Promise<string>>> = () => {
  try {
    someFnThatThrowsSynchronously();
    return some(Promise.resolve('foo'))
  } catch (e) {
    return none
  }
}
```

or rejecting the promise

```ts
const someFnThatThrowsSynchronously = () => {
    throw new Error();
}

const fn: Lazy<Option<Promise<string>>> = () => {
  try {
    someFnThatThrowsSynchronously();
    return Promise.resolve('foo')
  } catch (e) {
    return Promise.reject(e)
  }
}
```

**Comment by gcanti** [comment]
- Promise<Either<L, A>> — perhaps this could be provided by either? Not sure (*)
- Task<Either<L, A>> — perhaps this could be provided by task? :+1:
- TaskEither<<L, A>>— this is already provided by taskEither :+1:

(*) `Either` would contain a function coupled with a `Promise` implementation (see https://github.com/gcanti/fp-ts/issues/87). @leemhenson what do you think? Any suggestion?

**Comment by stereobooster** [comment]
Hi. I have small question: I need to do fetch and then validate response with `io-ts`. Is there more elegant way to do this, then

```js
  request()
    .then(result =>
      result.fold(
        error => store.dispatch(Failed()),
        data => store.dispatch(Ok(data))
      )
    )
    .catch(error => store.dispatch(Failed()));

export const getJson = (url: string) => {
  return new task.Task(() => fetch(url))
    .map(parseJsonFromResponse)
    .map(requierRootObject);
};

export const request = () => {
  return getJson(`/api/prices.json`)
    .map(decodePriceResponse) //
    .run();
};

// PriceInterface is io-ts type
export const decodePriceResponse = (obj: {}) => t.validate(obj, PriceInterface);
```

**Comment by navinkumarr** [comment]
I was not able to figure out how to use the library to handle async/await for third party libraries that do not use fp-ts. Below function works for me. I am not sure if it is the FP way, however. Can anyone suggest a better approach @OliverJAsh  @gcanti @stereobooster ?

```typescript
export async function eitherTryCatchAsync<E, A>(
  f: () => Promise<A>,
): Promise<either.Either<E, A>> {
  try {
    let result = await f();
    return Promise.resolve(either.right<E, A>(result))
  } catch (reason) {
    return Promise.resolve(either.left<E, A>(reason))
  }
};
```

**Comment by gcanti** [comment]
@navinkumarr usually the FP way is to prefer `Task` to `Promise`

**Comment by abdulkaderjeelani** [comment]
I would prefer to use Observables and use RxJs Bindings

**Comment by mlegenhausen** [comment]
You can just take a look at [fp-ts-rxjs](https://github.com/gcanti/fp-ts-rxjs/blob/master/src/Observable.ts)

There is currently no `tryCatch` function for `rxjs` but you can build your own one:

```ts
const tryCatch = <L, R>(f: () => Promise<R>): Observable<Either<L, R>> =>
  defer(f).pipe(
    map((r) => right<L, R>(r)),
    catchError((l) => of(left<L, R>(l)))
  );
```
