### ISSUE TITLE
Consolidate option.zero and option.none

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#160]
I keep getting tripped up using `option.none` forgetting that it widens the value generic type to `any`. I noticed that `option.zero` is provided to allow a generic to be passed through. I wonder if we could consider consolidating these to help ensure type safety. What do you think?

**Comment by SimonMeskens** [comment]
The difference between option.none and option.zero() is that zero is an identity function and none is a variable. Variables can't be generic. I don't think you can consolidate without turning none into an identity function too, and at that point, what's the difference between zero and none?

**Comment by OliverJAsh** [comment]
Hey @SimonMeskens! I guess I'm questioning when you would choose to use the variable form over the function form, given that the latter is safer?

**Comment by SimonMeskens** [comment]
You can easily use the `none` safely like this:

```ts
option.none as None<A>
```

There's no problem with always wanting to use zero() if you prefer that. The only "downside" is it fires a function each time, which is probably so small of a performance hit, it'd be hard to write code that even feels it.

**Comment by gcanti** [comment]
The current `none` is disappointing

```ts
// compiles...
export const f = (n: number): option.Option<number> => n > 0 ? option.some('a') : option.none
```

The culprit seems this line https://github.com/gcanti/fp-ts/blob/master/src/Option.ts#L33

I guess should be

```ts
static value: Option<never> = new None()
```

**Comment by OliverJAsh** [comment]
I like that solution 👍

**Comment by OliverJAsh** [comment]
I wonder if there is also potential to use `never` in other places, such as the right generic for `either.left`?

**Comment by SimonMeskens** [comment]
The difference between `void` and `never` is that you can assign `null` or `undefined` to `void`, so yeah, we should probably use `never` in all cases.
