### ISSUE TITLE
Add ReaderIO module

### ISSUE THREAD

**Issue by gshokanov** [gcanti/fp-ts#1612]
## 🚀 Feature request
Add `ReaderIO` monad to `fp-ts` along with corresponding chain functions.

### Current Behavior

The current way of describing a side-effect that runs in an environment is to either use a plain `Reader` monad which masks the effectful nature of the computation or use an `IO` monad wrapped in `Reader`, which is painful to use since `fp-ts` lacks the helper functions for this type making it hard to combine/chain it with other types like `ReaderTaskEither`.

Example:

```ts
interface Dependencies {
  a: string;
  b: string;
}

const effectfulReader: Reader<Dependencies, IO<void>>; // uses environment to make an effectful operation

const task: ReaderTask<Dependencies, Error, void>;

const combined = pipe(
  task,
  ???(() => effectfulReader) // fp-ts doesn't have a built-in function to chain this gracefully 
);
```

### Desired Behavior

Provide a way to use a built-in `ReaderIO` type to build and combine computations as well as chain these computations together with other types like `ReaderTaskEither`.

```ts
interface Dependencies {
  a: string;
  b: string;
}

const effectfulReader: ReaderIO<Dependencies, void>; // uses environment to make an effectful operation

const task: ReaderTask<Dependencies, Error, void>;

const combined = pipe(
  task,
  chainReaderIO(() => effectfulReader) // new builtin function in TaskReader module
);
```

### Suggested Solution

Add a `ReaderIO` module and add corresponding chain methods for `ReaderTask` and `ReaderTaskEither` monads.

### Who does this impact? Who is this for?

Users heavily relying on `Reader` monad for dependency injection.

### Describe alternatives you've considered

Using only `Reader` monad and using `IO` wrapped inside a `Reader`.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.11.5      |
| TypeScript |      4.2.4      |

**Comment by samhh** [comment]
FYI it already exists in [fp-ts-contrib](https://gcanti.github.io/fp-ts-contrib/modules/ReaderIO.ts.html).

**Comment by gshokanov** [comment]
Didn't know about this, thank you @samhh! Guess this can be closed then

**Comment by DenisFrezzato** [comment]
I would be in favour to bring `ReaderIO` within `fp-ts`, because we could create various natural transformations (`fromReaderIO`) and combinators (`chainReaderIO`) that right now I've defined in my projects.
