### ISSUE TITLE
Financial contribution

### ISSUE THREAD

**Issue by robstoll** [gcanti/fp-ts#1634]
Hi @gcanti is there a way to support this library financially?

**Comment by jcarrag** [comment]
Our company was just wondering the same thing! (Same goes for [`io-ts`](https://github.com/gcanti/io-ts))

**Comment by steida** [comment]
@gcanti I recently started supporting https://www.patreon.com/martinkl/posts for his CRDT related work. It's not like "I am buying you." It's more like "I would like to support you because what you did or do was immensely helpful for me." I'm posting it here as an inspiration.

**Comment by gcanti** [comment]
Hi all, sponsorships are now enabled :+1:
