### ISSUE TITLE
Compilation errors with 0.4.0?

### ISSUE THREAD

**Issue by LiamGoodacre** [gcanti/fp-ts#164]
I recently updated to fp-ts 0.4.0, and I'm seeing many compilation errors similar to the following:

```typescript
ERROR in [at-loader] ./node_modules/fp-ts/lib/Validation.d.ts:18:22
    TS2420: Class 'Failure<L, A>' incorrectly implements interface 'FantasyAlt<"Validation", A>'.
  Types of property 'alt' are incompatible.
    Type '(fy: Validation<L, A>) => Validation<L, A>' is not assignable to type '(fy: HKT<"Validation", A>) => HKT<"Validation", A>'.
      Types of parameters 'fy' and 'fy' are incompatible.
        Type 'HKT<"Validation", A>' is not assignable to type 'Validation<L, A>'.
          Type 'HKT<"Validation", A>' is not assignable to type 'Success<L, A>'.
            Property 'value' is missing in type 'HKT<"Validation", A>'.
```

This is using typescript@2.4.1 with awesome-typescript-loader.

I have no idea how to proceed.  Any help would be greatly appreciated.

**Comment by gcanti** [comment]
I can't repro with the following setup

- TypeScript@2.4.1
- fp-ts@0.4.0
- webpack@2.6.1
- awesome-typescript-loader@3.2.1

Could you please put up a repo showing the failure?

**Comment by LiamGoodacre** [comment]
Okay I finally worked it out.  When I was using a previous version of fp-ts, I created a new data type and registered it with HKT.  When I updated I hadn't yet updated usages - which meant there where conflicting definitions of HKT with different numbers of type parameters.  Crazy error!
