### ISSUE TITLE
how to use flow and bind function ?

### ISSUE THREAD

**Issue by YuMuuu** [gcanti/fp-ts#1642]
## 📖 Documentation
I discover pipeline + bind example. 

```
  optPlus(a: Option<number>, b: Option<number>): Option<number> {
    return F.flow(
      O.bind("_a", () => a),
      O.bind("_b", () => b),
      O.map(({ _a, _b }) => _a + _b)
    )(a);
  }
```
this code is rigth? or more better  way to write it?

I think there is a better way to use `O.Do`. ?_?

**Comment by samhh** [comment]
There are a few different ways to improve upon this.

Firstly, to attempt to unwrap/invert multiple values [sequenceT](https://gcanti.github.io/fp-ts/modules/Apply.ts.html#sequencet) is arguably preferable to do notation (which `bind` et al emulate).

Secondly, `flow` serves no benefit over `pipe` - if anything it hinders readability - if your code is not "point-free" / "tacit". Whilst it doesn't apply in this case, you'll want to try writing curried functions by default to aid in this endeavour.

Finally, this specific problem can be solved via [O.getMonoid](https://gcanti.github.io/fp-ts/modules/Option.ts.html#getmonoid) and [Num.MonoidSum](https://gcanti.github.io/fp-ts/modules/number.ts.html#monoidsum), whereby its `concat` function corresponds to addition over `Option<number>`.

**Comment by imcotton** [comment]
In **PureScript**, you would `do`

```haskell
optPlus fa fb = do -- this uses bind (>>=) from Monad
    a <- fa
    b <- fb
    pure $ a + b
```

Since `a` and `b` are independent from each other (e.g.: `Promise.all`), you also have `ado`

```purescript
optPlus fa fb = ado -- this uses ap (<*>) from Applicative
    a <- fa
    b <- fb
  in
    a + b
```

Which the same as:

```haskell
optPlus fa fb = plus <$> fa <*> fb
  where
    plus a b = a + b
```


indw
```

**Comment by imcotton** [comment]
Links to documentation:

https://gcanti.github.io/fp-ts/guides/do-notation.html
https://gcanti.github.io/fp-ts/guides/purescript.html#wheres-my-f--fa--fb

**Comment by YuMuuu** [comment]
Happy new year !
Sorry for the late reply.

This is exactly the thing I wanted. thx!
```
const optPlus = (fa: Option<number>, fb: Option<number>) => F.pipe(
    O.Do,
    O.apS('a', fa),
    O.apS('b', fb),
    O.map({ a, b } => a + b),
)
```

And I learned it
-  if anything it hinders readability - if your code is not "point-free" / "tacit".
- unwrap/invert multiple values sequenceT is arguably preferable to do notation (which bind et al emulate).

in future use pipe + sequenceT.


We will also share a monoid implementation example for anyone searching for this issue.
```
import * as O from "fp-ts/lib/Option";
import * as Num from "fp-ts/lib/number";

optPlus(a: Option<number>, b: Option<number>): Option<number> {
  return O.getMonoid(Num.MonoidSum).concat(a, b)
}
```
