### ISSUE TITLE
Npm dependency on repository doesn't work

### ISSUE THREAD

**Issue by SimonMeskens** [gcanti/fp-ts#165]
Without the lib folder present in the repository, having an npm dependency like `"fp-ts": "gcanti/fp-ts"` doesn't work.

I'm not sure if there's a fix for this, besides just committing the lib each time (which most packages do, but yuck).

The way I'm doing it right now, is to use a local file dependency and npm link to install it. This probably means this issue can be closed, but I just wanted to document this.

**Comment by devdoomari** [comment]
you can use circleCI for the job
(e.g. push to master --> circleCI builds & uploads to npm)

For me, I use circleCI to build 'dist' branches before pushing to npm

**Comment by SimonMeskens** [comment]
Thanks for the recommendation, though npm link also works just fine as noted above. I just wanted this issue to exist to document it. I'll close the issue now, others can find this and the solutions presented :)
