### ISSUE TITLE
TE.fromTask: left stays unknown regardless of chained left

### ISSUE THREAD

**Issue by florianbepunkt** [gcanti/fp-ts#1650]
### Current Behavior

```
const ex = pipe(
  T.of('x'),
  TE.fromTask,
  TE.chainW((x) => (x ? TE.left(1) : TE.right(x))),
  (x) => x,
);
```
x in the last line is typed as `TE.TaskEither<unknown, string>`

### Expected behavior

x in the last line should be typed as `TE.TaskEither<number, string>`

### Reproducible example

```
const ex = pipe(
  T.of('x'),
  TE.fromTask,
  TE.chainW((x) => (x ? TE.left(1) : TE.right(x))),
  (x) => x,
);
```

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |        2.2.16    |
| TypeScript |       4.5.4     |

**Comment by 0x706b** [comment]
I think this should get typed correctly if `TE.rightTask` is used instead of `TE.fromTask`

**Comment by florianbepunkt** [comment]
@0x706b Thank you for your fast reply, you're right. Makes sense now, but fromTask just looked deceivingly idiomatic.
