### ISSUE TITLE
Option<TaskEither> question: Option.match/fold evaluates TaskEither<A, B> to Promise<Either<A, B>> 

### ISSUE THREAD

**Issue by pheuberger** [gcanti/fp-ts#1657]
I have a `TaskEither` inside of an `Option` and would like to unwrap that `TaskEither` if `Option` is `some`, or pass down an error should the `Option` be none.

Here's a simplified example:

```typescript
import * as O from 'fp-ts/Option'
import * as TE from 'fp-ts/TaskEither'
import { Either } from 'fp-ts/Either'
import { identity, pipe } from 'fp-ts/function'

const ote = O.of(TE.of<string, string>("value"))
const unwrapped = pipe(ote, O.match(TE.left<string, string>("error"), identity))
unwrapped().then((s: Either<string, string>) => console.log(s))
```

I get the following error:

```
error TS2345: Argument of type '<A>(a: A) => A' is not assignable to parameter of type '(a: TaskEither<string, string>) => Promise<Either<string, string>>'.
  Type 'TaskEither<string, string>' is missing the following properties from type 'Promise<Either<string, string>>': then, catch, [Symbol.toStringTag], finally

const unwrapped = pipe(ote, O.match(TE.left<string, string>("error"), identity))
                                                                        ~~~~~~~~
error TS2349: This expression is not callable.
  Type 'Promise<Either<string, string>>' has no call signatures.

unwrapped().then((s: Either<string, string>) => console.log(s))
```

My question is, why is the return value of the function that is being passed into `O.match`'s `onSome` of type `Promise<Either<A, B>>` instead of `TaskEither<A, B>`?

And, what's the recommended way to get the desired functionality I described initially?

Thanks!
Philipp

**Comment by EricCrosson** [comment]
Remember that `O.match` takes a function for both the `none` and `some` cases. Also recall the `TaskEither` type:

```typescript
type TaskEither<E, A> = () => Promise<Either<E, A>>
```

By writing

```typescript
O.match(TE.left("error"), (a) => a)
```

you have provided a function for the `none` case! But not the function you wanted -- the TaskEither is unwrapped prematurely into its underlying Promise.

Instead, provide a thunk that returns the TaskEither

```typescript
O.match(() => TE.left<string, string>("error"), identity)
```

**Comment by mlegenhausen** [comment]
Small optimization you can also use `O.getOrElse(() => TE.left<string, string>('error'))` so you don't need the `identity` on the some-case.

**Comment by pheuberger** [comment]
Fantastic, thank you so much for your answers, @EricCrosson and @mlegenhausen 🙌 

Now I understand. I forced the TaskEither to evaluate by handing it a `left` and not a thunk 💡 

Also, great point to use `getOrElse`. I somehow glossed over it, thinking it wasn't what I needed. Apparently it was!
