### ISSUE TITLE
TaskEither.tryCatch should either try/catch or be renamed

### ISSUE THREAD

**Issue by AWare** [gcanti/fp-ts#1672]
### Current Behavior

`TE.tryCatch` only handles promises which have been rejected.

### Desired Behavior

It should have the same semantics as a javascript `try`/`catch` construct. 

Or it should be deprecated and renamed to something not misleading, such as `TE.catchRejectedPromise`

### Suggested Solution

Wrapping the code in a try/catch, or using an async function and try/catch block.

### Who does this impact? Who is this for?

All users.

### Describe alternatives you've considered

Wrapping `TE.tryCatch` in a try/catch.

### Additional context

I did read the docs where it said that `r` cannot throw.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |   2.11.8         |
| TypeScript |   4.5.5         |

**Comment by DenisFrezzato** [comment]
See https://github.com/gcanti/fp-ts/pull/1001

**Comment by AWare** [comment]
It is unclear why that PR was rejected, it seems like the following was uncontroversial:
- [tryCatch is for interop with unsafe code ](https://github.com/gcanti/fp-ts/pull/1001#issuecomment-670512313)
- it catches in Either and IOEither
- it was originally intentional(?)

If this is the case, please can this be evaluated as a feature request? Code written with async/await syntax may both throw errors and reject the promise by calling throw, with the differences between them being subtle. 

Otherwise, if the view is that it should not catch, please may this be renamed to not be confusing- especially in light of the libraries other tryCatch functions catching?

**Comment by imcotton** [comment]
I agree it should have catch both errors, I have similar utils setup:

```ts
function try2TE <A> (fn: () => A | Promise<A>) {
    return TE.tryCatch(async () => await fn(), E.toError);
}
```

It actually quite common in **Node.js** environment where lots `promises` variants (e.g. `fs/promises`) also have sync parameters verification stage, thus expected both error to be thrown out.

**Comment by enricopolanski** [comment]
> It actually quite common in **Node.js** environment where lots `promises` variants (e.g. `fs/promises`) also have sync parameters verification stage, thus expected both error to be thrown out.

Could you provide an example of such APIs?

**Comment by imcotton** [comment]
For example:

```js
require('dns').promises.lookup(42).catch(console.error)

// Uncaught:
// TypeError [ERR_INVALID_ARG_TYPE]: The "hostname" argument must be of type string. Received type number (42)
```

Related: https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dns_promises_api

- [resolver.resolve()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolve_hostname_rrtype)
- [resolver.resolve4()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolve4_hostname_options)
- [resolver.resolve6()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolve6_hostname_options)
- [resolver.resolveAny()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolveany_hostname)
- [resolver.resolveCname()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolvecname_hostname)
- [resolver.resolveMx()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolvemx_hostname)
- [resolver.resolveNaptr()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolvenaptr_hostname)
- [resolver.resolveNs()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolvens_hostname)
- [resolver.resolvePtr()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolveptr_hostname)
- [resolver.resolveSoa()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolvesoa_hostname)
- [resolver.resolveSrv()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolvesrv_hostname)
- [resolver.resolveTxt()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_resolvetxt_hostname)
- [resolver.reverse()](https://nodejs.org/docs/latest-v12.x/api/dns.html#dns_dnspromises_reverse_ip)

BTW: I double checked `fs/promises`, it however does not have sync thrown behavior, but in recollect I have bitten once like above therefore I'd rather take safest route to exchange with impure side effects onward.
