### ISSUE TITLE
TaskEither missing properties from HKT: _URI, _A

### ISSUE THREAD

**Issue by Ethan826** [gcanti/fp-ts#1691]
### Current Behavior

Receiving a `ts 2345` error in my IDE (VSCode): 
![image](https://user-images.githubusercontent.com/6303088/161241950-27c7ec10-c7ce-481e-bdd7-2fcbc6d7c750.png)

(This is a stripped-down version of the code that was causing trouble.)

This does not appear to prevent the project from building. I am unable to reproduce this from an empty project: this is inside an NX monorepo project. I can share the `tsconfig` settings if helpful, though generally they are set to strict.

I am uncertain if this relates to https://github.com/gcanti/fp-ts/issues/244. I don't understand HKTs or bivariance yet—I'm still learning a lot about this kind of typed FP. So even if this isn't an `fp-ts` bug, I'm not sure what could be causing this issue (though perhaps I'll just use a `@ts-ignore` in the function body and assert the type in the function signature and move on).

### Expected behavior

The error would not occur, or it would occur in an empty repo or cause an error during compilation.

### Reproducible example

As I said, I can't reproduce this in an empty repo. If helpful I can spend some time setting up a new NX monorepo demo to see if I can reproduce it.

### Suggested solution(s)

If this is an issue in the library, then a fix, but if not, it would helpful to learn more about what this error means and where else to look.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |  2.11.9          |
| TypeScript |  4.5.5          |

**Comment by mikearnaldi** [comment]
Could be due to a duplicated fp-ts version in your node_modules, it usually happens because of module augmentation

**Comment by Ethan826** [comment]
That was it! Sorry for the noise. 

Also while I'm ... making noise, thanks to the contributors and maintainers for this wonderful library! I've been trying to get "escape velocity" in learning this kind of FP and this library and the community and resources that have grown up around it have really made the "penny drop" on a lot of these concepts.

And @mikearnaldi, I'm following the `Effect-TS` project with interest, as Zio is of a lot of interest to me but I'm not too familiar with Scala.
