### ISSUE TITLE
Make IOOption part of fp-ts

### ISSUE THREAD

**Issue by gkamperis** [gcanti/fp-ts#1694]
### Current Behavior

ATM `IOOption` is part of `fp-ts-contrib`

### Desired Behavior

Move `IOOption` as part of `fp-ts`

### Suggested Solution

Move the code to `fp-ts`

### Who does this impact? Who is this for?

`fp-ts-contrib` users will be impacted but migration will be painless.

This is for `fp-ts` users to allow easier and better usage of Option and IO for scenarios that implement if/then patterns.

### Describe alternatives you've considered

`IOEither` can work as a replacement but the `left` in many cases it is not required and causes a bit of noise in the implementation.

### Additional context

Since `Option` and `Either` both exist in `fp-ts` (and correctly so IMHO) I would argue that `IOOption` and `IOEither` - that are also closely related - should also both exist in `fp-ts`.

Currently only `IOEither` is in `fp-ts` and `IOOption` is in `fp-ts-contrib`

### Your environment

N/A

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |            latest |

**Comment by enricopolanski** [comment]
What is the issue with importing from `fp-ts-contrib`?

At some point there cannot be an expectation of implementing every single data type variation to spare the user from using a combinator like `fromEither` or adding a dependency.

**Comment by mlegenhausen** [comment]
I would also like that. For us `IOOption` became interesting cause it is used in the `DOM` module of `fp-ts-std`, but the currently implementation lags a lot of the new module features like `Do` notation and the new natural transformations functions. It would also fill the gap between `Option` and `TaskOption` which was also added from `fp-ts-contrib` to `fp-ts`.

**Comment by gkamperis** [comment]
@enricopolanski It is not really/only a matter of importing mechanism - although simpler imports do help. 

As @mlegenhausen also comments the implementation is also kind of lagging.

I do not want to ruin it for `IOEither` but if it has a reason for existing in `fp-ts` (for me rightly so) I'd have thought `IOOption` has the same :)

**Comment by gcanti** [comment]
See https://github.com/gcanti/fp-ts/pull/1696. Please let me know if something is missing.
