### ISSUE TITLE
fp-ts unnecessarily pollutes VS Code Intellisense candidate list

### ISSUE THREAD

**Issue by ksze** [gcanti/fp-ts#1695]
### Current Behavior

Whenever I type "string" in my type declarations, the `string` from `fp-ts` unnecessarily pollutes the VS Code Intellisense candidate list. This forces me to waste time pressing Esc before continuing typing `,`. Otherwise VS Code would automatically add `import { string } from "fp-ts";` at the top of my ts file, which becomes an unused import.

![image](https://user-images.githubusercontent.com/381556/162349761-e425e23b-4c2b-4a72-874a-7ec0f8f910b8.png)

### Expected behavior

'fp-ts/string' should not show up in the Intellisense candidate list at all.

### Reproducible example

```typescript
const foo = (iDontWantFpTsStringHere: string) => { console.log(''); }
```

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

The versions don't really matter, but if you must know:

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |  2.11.9  |
| TypeScript |  4.6.3          |

**Comment by imcotton** [comment]
Here is the ticket in TS repo: https://github.com/microsoft/TypeScript/issues/48075

**Comment by waynevanson** [comment]
That ticket is closed. Could we close this issue?

**Comment by ksze** [comment]
Yep, I think the issue is fixed (as long as you use a recent version of TypeScript). Let's close it for now.
