### ISSUE TITLE
Error in the tutorial Advanced code examples Part I

### ISSUE THREAD

**Issue by lucas-almeida026** [gcanti/fp-ts#1698]
## 📖 Documentation
I was following the tutorial but I got an error
I think it has to do with the `pipe` function, in the tutorial it's imported from 'fp-ts/lib/pipeable' but sice verion 2.0.0 it's deprecated and the `pipe` function exported from 'fp-ts/function' seems to not be compatible with the code from the example

In the example
```
...
import { pipe } from '../src/pipeable'
...

...
// ask something and get the answer
31 function ask(question: string): T.Task<string> {
32   return pipe(
33     putStrLn(question),
34     T.chain(() => getStrLn)
35   )
36 }
```

In my code:
```
...
import { flow, pipe } from 'fp-ts/function'
...

...
const ask = (question: string): T.Task<string> =>
pipe(
  putStrLn,
  T.chain(() => getStrLn)
)
...
```

Error:
>  Argument of type '<A>(a: A) => Task<void>' is not assignable to parameter of type 'Task<unknown>'

IDE Sugestion:
> Did you mean to call this expression?

[tutorial-ref](https://github.com/gcanti/fp-ts/blob/master/examples/fp-ts-to-the-max-I.ts)

**Comment by gcanti** [comment]
Weird, `pipe` in `fp-ts/pipeable` is just an alias of `pipe` in `fp-ts/function`. 
Anyway I'll update the examples in order to remove the deprecated APIs
