### ISSUE TITLE
add `includes` function in `Array` module

### ISSUE THREAD

**Issue by safareli** [gcanti/fp-ts#1708]
## 🚀 Feature request

It would be nice to add function includes in `Array` module which calls include method on input array.

If this is something that would be accepted I can volunteer to add it

**Comment by mlegenhausen** [comment]
The equivalent for `includes` in `fp-ts` is the [elem](https://github.com/gcanti/fp-ts/blob/master/src/ReadonlyArray.ts#L1032-L1068) function.

**Comment by safareli** [comment]
thanks
