### ISSUE TITLE
TaskEither `orElse` never executed

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/fp-ts#1714]
### Current Behavior

I have the following code:

```ts
pipe(
      TE.fromTask(() => Promise.resolve(E.left('boom'))),
      TE.orElse((e) => {
        logger.error(e);
        return TE.left(e);
      }),
    )();
```

`orElse` is never executed. When I add an intermediary between the first and second items, it does execute.

```ts
pipe(
  TE.fromTask(() => Promise.resolve(E.left('boom'))),
  TE.chain((e) => (E.isRight(e) ? TE.of(e.right) : TE.left(e.left))),
  TE.orElse((e) => {
    logger.error(e);
    return TE.left(e);
  }),
)();
```

### Expected behavior

Expected `orElse` would be executed, even if it's the only other item in the chain.

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

Latest one. It didn't work before either.

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |     2.12.1       |
| TypeScript |   4.x.x         |

**Comment by gcanti** [comment]
That's the expected behaviour, here `x` is a `TaskEither<unknown, Either<string, never>` (instead of `TaskEither<string, never>` I guess)

```ts
// const x: TE.TaskEither<unknown, E.Left<string> | E.Right<never>>
const x = TE.fromTask(() => Promise.resolve(E.left('boom')))
```

**Comment by steida** [comment]
@volkanunsal `() => Promise.resolve(E.left('boom'))` is actually TaskEither already.

```ts
pipe(
  () => Promise.resolve(either.left("boom")),
  taskEither.orElse((e) => {
    console.log(e);
    return taskEither.left(e);
  })
)();
```

**Comment by volkanunsal** [comment]
Ah, of course. That makes sense. Thank you both.

**Comment by steida** [comment]
@volkanunsal You can always use this to quickly check what is a pipe

<img width="631" alt="Screenshot 2022-05-31 at 22 23 41" src="https://user-images.githubusercontent.com/66249/171278270-73c81474-296b-4bec-8b8b-1c4b15ad8769.png">
