### ISSUE TITLE
chainIf(condition, () => ...)

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1715]
## 🚀 Feature request

I often have a situation where I want to chain conditionally. Currently, I am doing it via chain where I have to return something when a condition isn't met.

`taskEither.chainIf(condition, () => ...)`

Am I overlooking something? Thank you

**Comment by steida** [comment]
@gcanti I don't think so, or I am overlooking something. I want `if (foo) taskEither.chain(...)` in a pipe.

**Comment by DenisFrezzato** [comment]
> I want if (foo) taskEither.chain(...) in a pipe.

I guess that translates into
```ts
TE.filterOrElse(() => !foo, ...)
```

**Comment by DenisFrezzato** [comment]
> I don't want a left. Not meeting a condition is not an error

This is clear to me, but `filterOrElse` returns whatever it's provided as a second argument, which is a `TaskEither<E, A>`, not `E`, which seems to be what you're asking.

So this
```ts
          taskEither.chainFirst((timestamp) => {
            if (timestamp && timestamp >= message.timestamp)
              return taskEither.right(undefined);
            const value = crdtValueFromString(message.value);
            return db.exec(`
              INSERT INTO "${message.table}" ("id", "${message.column}")
              VALUES ('${message.row}', '${value}')
              ON CONFLICT DO UPDATE SET "${message.column}" = '${value}'
            `);
          }),
```
could be refactored to
```ts
          taskEither.filterOrElse(
            (timestamp) => !(timestamp && timestamp >= message.timestamp),
            () => {
              const value = crdtValueFromString(message.value);
              return db.exec(`
                INSERT INTO "${message.table}" ("id", "${message.column}")
                VALUES ('${message.row}', '${value}')
                ON CONFLICT DO UPDATE SET "${message.column}" = '${value}'
              `);
            }
          }),
```

**Comment by steida** [comment]
'''ts
it('filterOrElse', async () => {
    U.deepStrictEqual(
      await pipe(
        _.right(12),
        _.filterOrElse(
          (n) => n > 10,
          () => 'a'
        )
      )(),
      E.right(12)
    )
    U.deepStrictEqual(
      await pipe(
        _.right(7),
        _.filterOrElse(
          (n) => n > 10,
          () => 'a'
        )
      )(),
      E.left('a')
    )
  })
'''

Am I blind? I checked tests and it looks like left/right depends on a condition.

**Comment by gkamperis** [comment]
> I want `if (foo) taskEither.chain(...)` in a pipe.

I'd like to understand a bit more :)

`Option`/`Either` "embeds" the `if()` logic.
So if `none`/`left` the chain will not happen.

If you want still something for `!foo` then you can use `alt()` for example to continue processing.

But I do not understand `right(undefined)`.
In general to me `some(undefined)`/`right(undefined)` is a red flag.

Looking at your example, why would you continue if no timestamp?
why return `right(undefined)` only to check in the next step `if(timestamp && )` when you clearly do not want processing to go on?

**Comment by steida** [comment]
Hi @gkamperis. `right(undefined)` is definitely a red flag. 

The logic is simple: Get the timestamp, maybe insert it into a specific table, maybe insert it into the message table, and if the message was inserted then update in-memory merkeTree.

I return `taskEither.right(undefined);` because I don't know how to call chain conditionally. Hence I am asking here, because it's a relatively common requirement.

**Comment by steida** [comment]
The semantic I'm looking for is really that simple: If (condition) then call chain.
I don't want to "break the pipe" with `left`. It's not an error. I feel I am overlooking something, but what? 😅

**Comment by steida** [comment]
As I think about it, I suppose my approach is correct.

If we are waiting for a value for further processing, we have to use `chain`.
If we are using `chain`, we have to return a value or an error.
An error would break the chain, and we don't want to do that, we want to continue.
`filterOrElse` is just sugar for `chain`.

So conditional chain is really `chain(a => condition ? ...` but unnecessary verbose. Look:

```ts
pipe(
  taskEither.right(1),
  taskEither.chain((a) => (a > 1 ? doSomething(a) : taskEither.right(a))),
  // chainIf would be nice
  taskEither.chainIf((a) => a > 1, doSomething)
);
```

**Comment by steida** [comment]
@gkamperis 

```ts
pipe(
  taskEither.right(1),
  taskEither.chain((a) => (a > 1 ? doSomething(a) : taskEither.right(a))),
  // chainIf would be nice
  taskEither.chainIf((a) => a > 1, doSomething)
);
```

**Comment by steida** [comment]
@DenisFrezzato, @gcanti, @pfgray `filterOrElse` uses second argument for Left. I don't understand why you both recommended it for conditional chaining. This is the code I have. Is it the best that we can have? `chainIf` would be nice. What am I overlooking? 

```ts
taskEither.chainFirst((condition) =>
  condition.updateTable
    ? updateTable.exec(
        `
        INSERT INTO "${message.table}" ("id", "${message.column}")
        VALUES (?, ?)
        ON CONFLICT DO UPDATE SET "${message.column}" = ?
        `,
        [message.row, message.value, message.value]
      )
    : taskEither.right(undefined)
),
```

**Comment by imcotton** [comment]
Looks like the following line up is what you were looking for:

```
pipe(
    TE.right(1),
    TE.chainFirst(flow(
        TE.fromPredicate(_p, _e),
        TE.chain(doSomething),
    )),
)
```

I think it's a fine combination in userspace, but not sure it worthwhile to be in the core.

**Comment by steida** [comment]
@imcotton `chainIf` should not fail if a condition isn't met. It just should not chain.

**Comment by imcotton** [comment]
Oh, I got misreading between code snippets, @steida could you confirm that what you actually meant was something like `chainFirstIf` rather than `chainIf` in this [example](https://github.com/gcanti/fp-ts/issues/1715#issuecomment-1146801603)? In such would makes more sensible illustration in `IO` as:



```ts
import { pipe } from 'fp-ts/function'
import { log } from 'fp-ts/Console'
import { randomInt } from 'fp-ts/Random'
import { chainFirst, IO } from 'fp-ts/IO'

import { when } from 'fp-ts-std/IO'



const effect: IO<number> = pipe(
    randomInt(1, 10),
    chainFirst(n => when (n > 5) (log(n))),
//  chainFirstIf(n =>     n > 5,  log),
)
```

Which looks more appealing in contrast with:

```purescript
effect :: Effect Int
effect = do
    n <- randomInt 1 10
    when (n > 5) $ log n
    pure n
```



---
refs:
- https://samhh.github.io/fp-ts-std/modules/IO.ts.html#when
- https://pursuit.purescript.org/packages/purescript-prelude/docs/Control.Applicative#v:when

**Comment by gkamperis** [comment]
> @imcotton `chainIf` should not fail if a condition isn't met. It just should not chain.

@steida  but `doSomething` can return `left`...
`  taskEither.chain((a) => (a > 1 ? doSomething(a) : taskEither.right(a))),`

**Comment by steida** [comment]
@gkamperis Yeah, that's what I am using right now. Just curious whether a shorter form exists.

**Comment by gkamperis** [comment]
@steida I am not suggesting it as a solution. I am referencing it to show that your statement is a bit contradictory.

if the condition is not met it does chain (similar to chainFirst) and if the condition passes it still can return left.
