### ISSUE TITLE
TaskEither left type becomes unknown after doing TE.fromIO

### ISSUE THREAD

**Issue by federico-moretti** [gcanti/fp-ts#1720]
### Current Behavior

If we use `pipe` like `(v) => pipe(v, consoleIO, TE.fromIO)` the left becomes `unknown`, if we use `TE.fromIO(consoleIO(v))` left stays `string`.

### Expected behavior

In both cases it remains `string`.

### Reproducible example

```ts
pipe(
  name,
  O.fromNullable,
  E.fromOption(() => "Name is nullable"),
  TE.fromEither,
  // TE.chainFirst((v) => pipe(v, consoleIO, TE.fromIO)), // this make left value unknown
  TE.chainFirst((v) => TE.fromIO(consoleIO(v))), // this works correctly
  TE.match(
    (e) => e, // this value is unknown if we use pipe
    (v) => `${v} is a valid name`
  )
);
```

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |2.12.1|
| TypeScript |4.6.4|

**Comment by waynevanson** [comment]
It's expected behaviour. Typescript cannot infer the string type on the second generic.

If it exists, maybe try use `TE.fromIOK`

```ts
pipe(
  name,
  O.fromNullable,
  E.fromOption(() => "Name is nullable"),
  TE.fromEither,
  TE.chainFirst(TE.fromIOK(consoleIO)), // this should work correctly
  TE.match(
    (e) => e, // this value is unknown if we use pipe
    (v) => `${v} is a valid name`
  )
);
```

**Comment by 0x706b** [comment]
There is also `TE.rightIO` which should also work

**Comment by waynevanson** [comment]
Or even better, `TE.chainFirstIOK` if it exists!

**Comment by federico-moretti** [comment]
`TE.chainFirstIOK` seems the better solution as it infer everything correctly doing this:

```ts
pipe(
  name,
  O.fromNullable,
  E.fromOption(() => "Name is nullable"),
  TE.fromEither,
  TE.chainFirstIOK(consoleIO),
  TE.match(
    (e) => e, // this value is unknown if we use pipe
    (v) => `${v} is a valid name`
  )
);
```
