### ISSUE TITLE
DTS tests broken

### ISSUE THREAD

**Issue by waynevanson** [gcanti/fp-ts#1722]
### Current Behavior

Here is a small excerpt. Looks like the union is mapped incorrectly for only the first to types in a union.

```ts
ERROR: 99:1   expect  Expected type to be:
  Record<"a" | "b" | "c", number>
got:
  Record<"b" | "a" | "c", number>
```

### Expected behavior

No errors, branch has been pulled straight from master.

### Reproducible example

```
git clone git@github.com:gcanti/fp-ts.git
cd fp-ts
npm i
npm test
```

### Suggested solution(s)

Not sure.

### Additional context

Causes multiple PR's in CI to fail,
Fails locally

### Your environment

branch master with node@12

**Comment by gcanti** [comment]
@waynevanson thanks for the bug report
