### ISSUE TITLE
Array reduce keeps state in successive calls

### ISSUE THREAD

**Issue by wildewouter** [gcanti/fp-ts#1736]
### Current Behavior and Reproducible example

```
import * as A from 'fp-ts/Array';

const func = A.reduce([], (acc: number[], next: number) => {
  acc.push(next)
  return acc
});

console.log(func([1, 2, 3]));
//[ 1, 2, 3 ]
console.log(func([]));
//[ 1, 2, 3 ]
```

### Expected behavior

```
import * as A from 'fp-ts/Array';

const func = A.reduce([], (acc: number[], next: number) => {
  acc.push(next)
  return acc
});

console.log(func([1, 2, 3]));
//[ 1, 2, 3 ]
console.log(func([]));
//[ ]
```

### Suggested solution(s)

State is somehow kept and the state should be cleared after call

### Your environment

Linux Fedora 35

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |  2.11.8 |
| TypeScript | 4.6.3 |

**Comment by gcanti** [comment]
In `declare const reduce: <A, B>(b: B, f: (b: B, a: A) => B) => (fa: Array<A>) => B` the `f` argument is supposed to be a (pure) function

**Comment by wildewouter** [comment]
Allright, thanks for your (very quick) answer. I was using push because V8 handles it more quickly but I will resort to a spread now.
