### ISSUE TITLE
newIORef type wrong?

### ISSUE THREAD

**Issue by AHBruns** [gcanti/fp-ts#1737]
### Current Behavior

```typescript
export declare function newIORef<A>(a: A): IO<IORef<A>>
```

### Expected behavior

```typescript
export declare function newIORef<A>(a: A): IORef<A>
```

### Suggested solution(s)

Maybe I'm confused, but it seems that this type is wrong at the moment.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |  ^2.12.2         |
| TypeScript |     4.7.3       |

**Comment by samhh** [comment]
The current behaviour matches the Haskell signature: https://hackage.haskell.org/package/base-4.16.3.0/docs/Data-IORef.html#v:newIORef

```hs
newIORef :: a -> IO (IORef a)
```

My understanding is that `IORef` holds the mutable reference but the side effects are felt when interacting with it, hence creating, reading, or updating one is done within `IO`.

**Comment by AHBruns** [comment]
I see. That makes sense. I wasn't thinking about creation as an interaction, but it, of course, is. Thanks for the clarification!
