### ISSUE TITLE
applicative do

### ISSUE THREAD

**Issue by hesxenon** [gcanti/fp-ts#1743]
Context: Maybe I'm missing something here by sometimes being incredibly dense. If we can already achieve what I'm describing feel free to close this issue (after telling me how to do it).

## 🚀 Feature request

It'd be nice (I think) to have applicative do notation in fp-ts.

### Current Behavior

Currently I don't see a way to deal with heterogenous types in parallel without losing their "ordering" by typing each "slot" as a union. E.g. afaik it's not possible to do
```typescript
const taskStringAndNumber = record.sequence(task.Applicative)({
  string: task.of("string"),
  number: task.of(1),
}) // errors because number is not assignable to string
```
instead we have to write a custom "aggregator" each time we need this like so
```typescript
const maybeStringAndNumber = pipe(
  task.of((string: string) => (number: number) => ({string, number})), // this is going to become tedious...
  task.ap(task.of("string")),
  task.ap(task.of(1)),
)
```

### Desired Behavior

something like
```typescript
const maybeStringAndNumber = pipe(
  task.Applicative.Do,
  task.bind("string", () => task.of("string")),
  task.bind("number", () => task.of(1)),
)
```
is achievable?

### Suggested Solution

Does the desired behaviour count? Or would you like something along the lines of "add a Do implementation in module x by doing foobar" here?

### Who does this impact? Who is this for?

Everybody who wants to run independent async computations in parallel without losing precision on the resulting type.

### Describe alternatives you've considered

sequencing tuples, but the sequencing only seems to work on fst and tuples are limited to 2-tuples.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.12.2     |
| TypeScript | 4.7.4      |

**Comment by DenisFrezzato** [comment]
You can use `apS[W]`:
```ts
pipe(
  T.of('string'),
  T.bindTo('string')
  T.apS('number', T.of(1))
) // T.Task<Readonly<{ string: string; number: number; }>>
```
or
```ts
pipe(
  T.Do,
  T.apS('string', T.of('string')),
  T.apS('number', T.of(1))
)
```

**Comment by hesxenon** [comment]
perfect, I knew there was something I was missing. Thank you, feel free to
close. (or maybe add it to the docs?)
