### ISSUE TITLE
Question about chainFirst on Array

### ISSUE THREAD

**Issue by thomasvargiu** [gcanti/fp-ts#1757]
I'm not an expert on FP, but is `chainFirst` on Array correct/useful?

Probably it's not a problem, but just confusing.

`chain` function is defined as:
```
chain :: Chain m => m a ~> (a -> m b) -> m b
```

> `chainFirst`:
> Composes computations in sequence, using the return value of one computation to determine the next computation and
> keeping only the result of the first.

Then I expect `chainFirst` should be (returning `m a`):
```
chainFirst :: Chain m => m a ~> (a -> m b) -> m a
```

Ok, `a` and `b` in Array are the same type then theoretically is correct, but...
I think it should be useless but, by definition, shouldn't `chainFirst` execute the computation and return the same first monad value, ignoring values from the computation (`b` values)?

The problem is more evident working with iterables or observables (similar questions on `fp-ts-rxjs`: gcanti/fp-ts-rxjs#68, gcanti/fp-ts-rxjs#54).

```typescript
import * as O from 'fp-ts-rxjs/Observable'

const app = (f: (a: number) => Observable) => pipe(
  from([1, 2, 3]),
  O.chainFirst(a => f(a)),
  // I expect here the observable emitting 1 - 2 - 3
)
```

The problem in the last example is that if `f` returns an empty observable, the `chainFirst` results is an empty observable, if it emits more than 1 value, the result observable will emit more values.

Then probably it should be changed in something like:

```typescript
import * as O from 'fp-ts-rxjs/Observable'

const app = (f: (a: number) => Observable) => pipe(
  from([1, 2, 3]),
  O.chainFirst(a => pipe(
    f(a),
    takeLast(1), // ensure we have just one result
    defaultIfEmpty(0), // ensure we have at least one value
  )),
  // I expect here the observable emitting 1 - 2 - 3
)
```

Currently `chainFirst` derivable from `Chain` is defined as:
```typescript
export function chainFirst<M>(M: Chain<M>): <A, B>(f: (a: A) => HKT<M, B>) => (first: HKT<M, A>) => HKT<M, A> {
  return (f) => (first) => M.chain(first, (a) => M.map(f(a), () => a))
}
```

and obviously this function can't be applied for the requested behavior. 

Finally, some questions:
- is the `chainFirst` on arrays useful? An example?
- can you help us to understand the logic of this function on Arrays?
- the description of the function seems not correct for arrays, should we update it? Should we remove `chainFirst` function?
- is there another way to achieve the same requested result?
- if not, shouldn't be more useful  a `chainFirst`-like function on traversables returning the first value (probably lifting will be difficult, and probably still useless on arrays)?

**Comment by gcanti** [comment]
> shouldn't chainFirst execute the computation and return the same first monad value

It returns the same type (`m a`) not the same value

```ts
import * as RA from 'fp-ts/ReadonlyArray'
import { pipe } from 'fp-ts/function'

pipe(
  [1, 2, 3],
  RA.chainFirst(() => [4, 5]),
  console.log
) // => [ 1, 1, 2, 2, 3, 3 ]

pipe(
  [1, 2, 3],
  RA.chainFirst(() => []),
  console.log
) // => []

pipe(
  [1, 2, 3],
  RA.chain(() => [4, 5]),
  console.log
) // => [ 4, 5, 4, 5, 4, 5 ]
```

**Comment by thomasvargiu** [comment]
@gcanti Thanks! With the first test example the behavior is  more clear.

We use to use `chainFirst` on monads with single values, that's why it was confusing, but probably the `chainFirst` documentation on arrays can be updated including examples.

Then probably the answer for my question is that I need another function for the behavior that I want, something like proposed here: https://github.com/gcanti/fp-ts-rxjs/issues/68, and it will be specific for every monad.

**Comment by gcanti** [comment]
> probably the chainFirst documentation on arrays can be updated including examples.

:+1: working on it
