### ISSUE TITLE
`Map.fromFoldableMap`

### ISSUE THREAD

**Issue by samhh** [gcanti/fp-ts#1760]
There's `Record.fromFoldable` and `Record.fromFoldableMap`, but only `Map.fromFoldable`. Is there a reason for this or has it just not been implemented yet?

**Comment by gcanti** [comment]
Since `fromFoldableMap` is more general than `fromFoldable` in v3 there's only a `fromFoldable` function with the following signature

```ts
export function fromFoldable<F>(
  F: Foldable<F>
): <K, B>(E: Eq<K>, M: Magma<B>) => <A>(f: (a: A) => readonly [K, B]) => (fka: HKT<F, A>) => ReadonlyMap<K, B>
```

I wonder whether it worth backporting that signature to v2

**Comment by samhh** [comment]
Ah lovely :+1: 

It's not urgent, just had a use case come up for it yesterday for the first time. I'll close the issue, up to you if it should be backported - I guess it depends on how far away v3 is.
