### ISSUE TITLE
Discord server link not working

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1776]
<img width="502" alt="Screenshot 2022-09-15 at 20 16 02" src="https://user-images.githubusercontent.com/66249/190479596-9139bca1-75e9-4e59-84ec-9246389623a7.png">

**Comment by mikearnaldi** [comment]
strangely enough I used the invite this morning, can you re-try?

**Comment by alex-ketch** [comment]
For another data point, just used it and it worked.

**Comment by steida** [comment]
It was something wrong with authentication, but now it works. Thank you.
