### ISSUE TITLE
2.13 'lib' import errors in Jest

### ISSUE THREAD

**Issue by thewilkybarkid** [gcanti/fp-ts#1786]
Just tried upgrading [a project](https://github.com/PREreview/prereview.org) to `2.13.0-rc.4` to see what happens, and found that the old-style `fp-ts/lib/` imports in io-ts cause Jest to fail:

```
Test suite failed to run

ENOENT: no such file or directory, open '[...]/node_modules/fp-ts/lib/lib/Either.js'

  at Runtime.readFile (node_modules/jest-runtime/build/index.js:2574:21)
  at Object.<anonymous> (node_modules/io-ts/lib/Decoder.js:27:22)
```

It might happen with other packages too (e.g. logging-ts), but it's probably not reached them yet.

Given the project runs successfully (with Node 16.17.0), this could be a Jest problem (or a problem with our configuration), but I thought it worth flagging here.

**Comment by gcanti** [comment]
Thanks @thewilkybarkid, I think the culprit might be https://github.com/gcanti/fp-ts/commit/87455b8e2b615b66cbdf14c2306bbafd15b8d5b7, I'll revert that change too

**Comment by gcanti** [comment]
@thewilkybarkid ok, I reverted the build change in https://github.com/gcanti/fp-ts/commit/87455b8e2b615b66cbdf14c2306bbafd15b8d5b7, updated the `exports` field accordingly... (/cc @viell-dev)

```json
"exports": {
    ".": {
      "require": "./lib/index.js",
      "import": "./es6/index.js",
      "types": "./lib/index.d.ts"
    },
    "./HKT": {
      "require": "./lib/HKT.js",
      "import": "./es6/HKT.js",
      "types": "./HKT.d.ts"
    },
    "./*": {
      "require": "./lib/*.js",
      "import": "./es6/*.js",
      "types": "./lib/*.d.ts"
    },
    "./es6/HKT": {
      "import": "./es6/HKT.js",
      "types": "./HKT.d.ts"
    },
    "./es6/*": {
      "import": "./es6/*.js",
      "types": "./lib/*.d.ts"
    },
    "./lib/HKT": {
      "require": "./lib/HKT.js",
      "types": "./HKT.d.ts"
    },
    "./lib/*": {
      "require": "./lib/*.js",
      "types": "./lib/*.d.ts"
    }
  }
```

...and released `2.13.0-rc.5` (fingers crossed)

**Comment by thewilkybarkid** [comment]
Thanks for taking a look @gcanti. Unfortunately, I'm still seeing the same problem.

I'm trying to debug, but if you'd like to reproduce it clone https://github.com/prereview/prereview.org, run `npm install fp-ts@rc --legacy-peer-deps` then `npm test` and you should see it.

**Comment by thewilkybarkid** [comment]
Looks like the order of the `exports` map is important: moving `./*` to the end sees it work.

**Comment by thewilkybarkid** [comment]
The same tweak worked on `2.13.0-rc.4` too.

**Comment by gcanti** [comment]
Ahhh interesting, so

```json
"exports": {
    ".": {
      "require": "./lib/index.js",
      "import": "./es6/index.js",
      "types": "./lib/index.d.ts"
    },
    "./HKT": {
      "require": "./lib/HKT.js",
      "import": "./es6/HKT.js",
      "types": "./HKT.d.ts"
    },
    "./es6/HKT": {
      "import": "./es6/HKT.js",
      "types": "./HKT.d.ts"
    },
    "./es6/*": {
      "import": "./es6/*.js",
      "types": "./lib/*.d.ts"
    },
    "./lib/HKT": {
      "require": "./lib/HKT.js",
      "types": "./HKT.d.ts"
    },
    "./lib/*": {
      "require": "./lib/*.js",
      "types": "./lib/*.d.ts"
    },
    "./*": {
      "require": "./lib/*.js",
      "import": "./es6/*.js",
      "types": "./lib/*.d.ts"
    }
}
```

right?

**Comment by thewilkybarkid** [comment]
@gcanti Yep, it must try matching top to bottom.

**Comment by gcanti** [comment]
`2.13.0-rc.6` released, thank you @thewilkybarkid for your help!
