### ISSUE TITLE
Prefer `{}` type to `any` type

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#179]
`any` disables type checking, so any usage of an `any` expression will be unsafe. For example:

``` ts
task.tryCatch(() => Promise.resolve(1), error => {
  // unsafe!
  return error.foo.bar
})
```

For this reason it is preferable to use the empty object type `{}`.

For more information on the differences between `any` and `{}`, and the how they are often misunderstood, see https://github.com/Microsoft/TypeScript/issues/9999#issuecomment-238009695.

Would you be happy for us to change some instances of `any` to `{}`? For example, in the `onrejected` function parameter of `task.tryCatch`:.

This would mean the above example would error unless the user widens the type (e.g. using user-defined type guards):

``` ts
task.tryCatch(() => Promise.resolve(1), error => {
  // compile error
  return error.foo.bar
})
```

**Comment by gcanti** [comment]
LGTM
