### ISSUE TITLE
Handle multiple arguments in functions's `apply`

### ISSUE THREAD

**Issue by valeriobelli** [gcanti/fp-ts#1796]
### Current Behavior

Looking at the `apply` exported by `function`

```typescript
export declare const apply: <A>(a: A) => <B>(f: (a: A) => B) => B
```

it accepts functions with a single parameter of type `A`.

### Desired Behavior

When facing functions with multiple parameters, like in the following example

```typescript
import * as Ord from 'fp-ts/Ord'
import * as N from 'fp-ts/Number'
import { apply, pipe } from 'fp-ts/function'

// For completion, `clamp` returns (low: number, hi: number) => (value: number) => number
pipe(Ord.clamp(N.Ord), apply(1, 10), apply(100)) 
```

I would expect to be able to use `apply` also in these cases. 

### Suggested Solution

I thought that something like

```typescript
export declare const apply: <A extends unknown[]>(...a: A) => <B>(f: (...a: A) => B) => B
```

would work without any additional problem, from my TypeScript and `fp-ts` knowledge. How does it sound to you?

### Who does this impact? Who is this for?

This would impact every `fp-ts` user.

### Describe alternatives you've considered

Another possible solution would be using `map` exported by `Identity`, like in the following example

```typescript
import * as Ord from 'fp-ts/Ord'
import * as N from 'fp-ts/Number'
import * as I from 'fp-ts/Identity'
import { pipe } from 'fp-ts/function'

pipe(Ord.clamp(N.Ord), I.map((clamp) => clamp(1, 10)), I.ap(100))
```

which is a bit more verbose. Is there any other alternative which I'm not aware of?

### Additional context

None.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.13.0-rc.6|
| TypeScript | 4.8.2      |

**Comment by samhh** [comment]
That specific example should really be fixed in v3 instead with everything being curried. But it would have utility outside of this ecosystem.

I think I've found that variadic functions like `flow` have a habit of behaving badly in the presence of overloads, where tsc fails to infer the correct overload. I've not got a specific example in mind, so my apologies for the vagueness - I just wanted to mention this before anything else potentially becomes variadic.

**Comment by valeriobelli** [comment]
Thanks for the answer, @samhh. 

After having reasoned a bit on that, I agree with you. This change on `functions`'s `apply` is beyond the goal of that module, also considering the schedule of `v3`. Moreover, this change would introduce a different behaviour than `Apply`'s `ap` function, which is intended to be used similarly (at least from my understanding). Spreading the same change on this latter function would mean impacting a greater audience with unwanted side effects.

Therefore, we can close this proposal and keep the proposed implementation outside this ecosystem. 🤓
