### ISSUE TITLE
Package subpath './lib/Either' is not defined by "exports" in /app/code/node_modules/fp-ts/package.json

### ISSUE THREAD

**Issue by vivekiyer114** [gcanti/fp-ts#1798]
## 🐛 Bug report

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/Either' is not defined by "exports" in /app/code/node_modules/fp-ts/package.json
--
523 | at applyExports (internal/modules/cjs/loader.js:491:9)
524 | at resolveExports (internal/modules/cjs/loader.js:507:23)
525 | at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
526 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
527 | at Function.Module._load (internal/modules/cjs/loader.js:842:27)
528 | at Module.require (internal/modules/cjs/loader.js:1026:19)
529 | at require (internal/modules/cjs/helpers.js:72:18)
530 | at Object.<anonymous> (/app/code/node_modules/inspectpack/lib/actions/base.js:4:18)
531 | at Module._compile (internal/modules/cjs/loader.js:1138:30)
532 | at Module._compile (/app/code/node_modules/pirates/lib/index.js:136:24)
533 | at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
534 | at Object.newLoader [as .js] (/app/code/node_modules/pirates/lib/index.js:141:7)
535 | at Module.load (internal/modules/cjs/loader.js:986:32)
536 | at Function.Module._load (internal/modules/cjs/loader.js:879:14)
537 | at Module.require (internal/modules/cjs/loader.js:1026:19)
538 | at require (internal/modules/cjs/helpers.js:72:18) {
539 | code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
540 | }

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |       2.13.0     |
| TypeScript |            |

**Comment by gcanti** [comment]
Closing in favour of https://github.com/gcanti/fp-ts/issues/1799
