### ISSUE TITLE
fp-ts 2.13.0 - Package path ./lib/function.js is not exported from package

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1799]
## 🐛 Bug report

Both my Next.js and Node ESM have a problem with fp-ts 2.13.0

`Error Package path ./lib/function.js is not exported from package`

**Comment by gcanti** [comment]
@steida any hint on what could be wrong? Did `2.13.0-rc.6` work fine in your setup?

**Comment by steida** [comment]
`2.13.0-rc.6` does not work too.

**Comment by steida** [comment]
Maybe that multi-package.json architecture does it. I will try to fix it.

**Comment by steida** [comment]
If I delete those exports from root package.json, the Next.js app works.

**Comment by gcanti** [comment]
Well that feature was planned and implemented before the whole v3 "revolution" but I agree with you, I'll revert the package.json change to fix the immediate issue, and then we might investigate further

**Comment by steida** [comment]
@gcanti Yes, both Next.js and Node ESM work. Thank you.

**Comment by gcanti** [comment]
Nice, thank you for the bug report and your time ;)
