### ISSUE TITLE
Returning TE.left() not triggering onLeft in TE.fold

### ISSUE THREAD

**Issue by gabrielgrover** [gcanti/fp-ts#1805]
### Current Behavior

I have the following function

```typescript
export function validate_and_add_comment(
  on_error: (err: BlogError) => void,
  on_success: (c: Comment) => void
) {
  return (data: unknown) =>
    F.pipe(
      validate_comment_input(data),
      E.fold((e) => {
        console.log(`error in either: ${JSON.stringify(e, null, 2)}`);
        return TE.left(e);
      }, add_comment),
      TE.fold(
        (e) => {
          console.log(`error in task either: ${JSON.stringify(e, null, 2)}`);
          return TE.of(on_error(e));
        },
        (comment) => {
          return TE.of(on_success(comment));
        }
      )
    );
}
```

And here is a jest test I have for the function.

```typescript
describe("validate_and_add_comment", () => {
  it("should call on_error for content that is not long enough", (done) => {
    const input = {
      content: "a",
      blogId: 1,
    };

    const on_error = () => {
      done();
    };
    const on_success = jest.fn();

    const add_comment = validate_and_add_comment(on_error, on_success);

    add_comment(input);
  });
});
```

The test eventually times out.  I see the log 
```typescript
console.log(`error in either: ${JSON.stringify(e, null, 2)}`); 
```
located in the `onLeft` callback in the `E.fold`.  I do not see the log in the `onLeft` callback in the `TE.fold`. 

### Expected behavior

I see the log in the `onLeft` call back in the `TE.fold` and the jest test passes.

### Reproducible example

Here is the code `https://github.com/gabrielgrover/improved-octo-spoon/blob/commenting-redux/Blog/api.ts#L84`.  Clone the repo and checkout the `commenting-redux` branch.  Run `yarn test` to see the failing test.

### Suggested solution(s)

Not sure really.  Perhaps I am misunderstanding the functionality of some of the functions from `fp-ts` that I am using in the above code?

N/a

### Your environment

MacBook Pro (16-inch, 2019)

| Software    | Version(s) |
| ----------  | ---------- |
| fp-ts           |      2.13.1   |
| TypeScript |      4.8.4    |

**Comment by mlegenhausen** [comment]
The repo contains errors or the instructions are incomplete...

Nevertheless did I get the project running. The problem is that you do not run you `Task` that is returned by `add_comment`. It is hard to spot as you still depend heavily on callbacks.

Change the last name of you test to

```ts
add_comment(input)();
```

**Comment by gabrielgrover** [comment]
@mlegenhausen Thank you sir!
