### ISSUE TITLE
Documentation bad on Firefox

### ISSUE THREAD

**Issue by SofianeDjellouli** [gcanti/fp-ts#1812]
## 📖 Documentation

Thanks for this awesome package. 

Unfortunately the UI of the docs is not appropriated to Firefox (107.0) on MX Linux as you can see in the screenshot below: 
![image](https://user-images.githubusercontent.com/38258952/203964864-e68b338b-c2d6-4c16-940a-56acf8fb4a45.png)

Icons are too big. Hopefully it's an easy fix.

**Comment by grossbart** [comment]
It looks to me as if no CSS has been loaded at all. Could you check again with all plugins disabled? I suspect that a plugin might block the CSS request (and maybe others).

I'm on Firefox myself and do not see this problem.

**Comment by SofianeDjellouli** [comment]
Ok it now works. No idea why it was not working earlier.
