### ISSUE TITLE
Curried Functions?

### ISSUE THREAD

**Issue by tusharmath** [gcanti/fp-ts#182]
Can you show an example of how we can write curried functions using HTK?

Is there even a way?

**Comment by gcanti** [comment]
Not sure what you mean, like any other function I guess. Are you thinking of a specific example?

**Comment by tusharmath** [comment]
```ts
// currying function
function curry2<P0, P1, R>(fn: (p0: P0, p1: P1) => R) {
  function curried(p0: P0): (p1: P1) => R
  function curried(p0: P0, p1: P1): R
  function curried(...t: any[]) {
    if (t.length === fn.length) return fn.apply(this, t)
    else return curried.bind(this, ... Array.from(arguments)) 
  }
  return curried
}

// some interface
interface Mappable<T> {
  map<S>(fn: (t: T) => S): Mappable<S> 
}

function map <T, S> (fn: (t: T) => S, ob: Mappable<T>): Mappable<S> { 
  return ob.map(fn)
}

const mapC = curry2(map)

// Case 1
mapC(i => i.concat(''), [1]) // considers i as any

// Case 2
map(i => i.concat(''), [1]) // considers i as number
```
[Link]

[Link]: https://www.typescriptlang.org/play/index.html#src=function%20curry2%3CP0%2C%20P1%2C%20R%3E(fn%3A%20(p0%3A%20P0%2C%20p1%3A%20P1)%20%3D%3E%20R)%20%7B%0D%0A%20%20function%20curried(p0%3A%20P0)%3A%20(p1%3A%20P1)%20%3D%3E%20R%0D%0A%20%20function%20curried(p0%3A%20P0%2C%20p1%3A%20P1)%3A%20R%0D%0A%20%20function%20curried(...t%3A%20any%5B%5D)%20%7B%0D%0A%20%20%20%20if%20(t.length%20%3D%3D%3D%20fn.length)%20return%20fn.apply(this%2C%20t)%0D%0A%20%20%20%20else%20return%20curried.bind(this%2C%20...%20Array.from(arguments))%20%0D%0A%20%20%7D%0D%0A%20%20return%20curried%0D%0A%7D%0D%0A%0D%0Ainterface%20Mappable%3CT%3E%20%7B%0D%0A%20%20map%3CS%3E(fn%3A%20(t%3A%20T)%20%3D%3E%20S)%3A%20Mappable%3CS%3E%20%0D%0A%7D%0D%0A%0D%0Afunction%20map%20%3CT%2C%20S%3E%20(fn%3A%20(t%3A%20T)%20%3D%3E%20S%2C%20ob%3A%20Mappable%3CT%3E)%3A%20Mappable%3CS%3E%20%7B%20%0D%0A%20%20return%20ob.map(fn)%0D%0A%7D%0D%0A%0D%0Aconst%20mapC%20%3D%20curry2(map)%0D%0AmapC(i%20%3D%3E%20i.concat('')%2C%20%5B1%5D)%0D%0Amap(i%20%3D%3E%20i.concat('')%2C%20%5B1%5D)%0D%0A

In the above example `Case 1` doesn't detect the type of parameter `i` where as it is available in the `Case 2`

I was wondering if we could use some HKT to represent a curried function.

**Comment by gcanti** [comment]
I don't think HKTs are helpful here. The problem is related to how type inference works in TypeScript, specifically in the following line

```ts
const mapC = curry2(map)
```

`map` is polymorphic but `mapC` isn't

```ts
// inferred type
const mapC: {
    (p0: {}): (p1: {}) => Mappable<{}>;
    (p0: {}, p1: {}): Mappable<{}>;
}
```

though pretty awkward, you can fix that adding an explicit type annotation to `mapC`

```ts
const mapC: {
  <T, S>(p0: (t: T) => S): (p1: Mappable<T>) => Mappable<{}>
  <T, S>(p0: (t: T) => S, p1: Mappable<T>): Mappable<{}>
} = curry2(map)
```

**Comment by tusharmath** [comment]
That's right. Sadly its verbose. Thanks for responding so quickly though 👍
