### ISSUE TITLE
Conditional constructor for Either

### ISSUE THREAD

**Issue by mihajlo-ra92** [gcanti/fp-ts#1825]
### Current Behavior

`const value: E.Either<string, Error> = isTrue(boolValue) ? E.right("It is true") : E.left(new Error("It is not true"));`

### Desired Behavior

I want to make this constructor less verbose.

### Suggested Solution

Implement a conditional constructor for Either.

`Either.cond(predicate, left, right)`

In our example:

`const value: E.Either<string, Error> = E.cond(isTrue(boolValue), new Error("It is not true"), "It is true");`

### Who does this impact? Who is this for?

All users

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |2.13.1|
| TypeScript |4.8.4|

**Comment by rsdavis** [comment]
I think what you are proposing is already available in `E.fromPredicate`. Unless I've missed something
```
const isPositive = (x: number) => x > 0
E.fromPredicate(isPositive, () => new Error())(1)
```

**Comment by mihajlo-ra92** [comment]
> I think what you are proposing is already available in `E.fromPredicate`. Unless I've missed something
> 
> ```
> const isPositive = (x: number) => x > 0
> E.fromPredicate(isPositive, () => new Error())(1)
> ```

You are right, thank you
