### ISSUE TITLE
contains, isDefined, isEmpty, ... for Option

### ISSUE THREAD

**Issue by alexandervanhecke** [gcanti/fp-ts#183]
Hi,
I'm integrating fp-ts into a project, I noticed some member functions I would expect to be present in the Some / None classes were missing, like contains, isDefined, isEmpty (and possibly others).  

I realize it's possible to get this functionality using other functions, like e.g. isNone, isSome, etc.  

Is this a design choice (ie using global functions in which you pass Option instances instead of member functions on Some / None)?  

I'm quite willing to create a pull request for these methods if you want me to. 

wkr,

**Comment by gcanti** [comment]
> Is this a design choice

Yes, namely the members of a type-class instance, for example `{ map, of, ap, chain }` for `Monad`. In addition I've just added the methods I use the most (in particular `fold` and `getOrElse`), feel free to add some useful member function though.

Another option, in case you judge a method just a nice-to-have, is augmenting the base module in your own code

```ts
import * as option from 'fp-ts/lib/Option'

declare module 'fp-ts/lib/Option' {
  interface None<A> {
    someMethod(a: A): boolean
  }
  interface Some<A> {
    someMethod(a: A): boolean
  }
}

option.None.prototype.someMethod = function<A>(a: A) {
  ...
}

option.Some.prototype.someMethod = function<A>(a: A) {
  ...
}
```

**Comment by alexandervanhecke** [comment]
Thanks,
understood.  I just created a pull request for this [#184](https://github.com/gcanti/fp-ts/pull/184), added methods and unit tests for : 
* contains
* isEmpty
* isDefined
* nonEmpty
* forEach
* exists
* orEmpty
