### ISSUE TITLE
Option: `O.sequenceArray` it's not behaving as expected

### ISSUE THREAD

**Issue by iago-silva-unvoid** [gcanti/fp-ts#1837]
## 🐛 Bug report
1. Have an array of options that contains at least one `O.none`.
2. Apply `O.sequenceArray` to that array.

### Current Behavior
It returns `O.none`

<img width="574" alt="Screenshot 2023-02-26 at 14 54 40" src="https://user-images.githubusercontent.com/108419310/221427547-01d840ad-39d4-423a-a781-2f497c35ebef.png">

### Expected behavior
I was expecting that I would have `O.some` values instead of `O.none`

### Reproducible example

```ts
import * as O from 'fp-ts/Option'
import { pipe } from 'fp-ts/lib/function'

const options = [O.some(1), O.none, O.some(3)]
const data = pipe(
  options, 
  O.sequenceArray
)
console.log(data) // { _tag: 'None' }
```

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |       ^2.13.1    |
| TypeScript |    ~4.9.5       |

**Comment by iago-silva-unvoid** [comment]
As a workaround I'm using:
```ts

import * as O from 'fp-ts/Option'
import * as A from 'fp-ts/Array'
import { pipe } from 'fp-ts/lib/function'


const options = [O.some(1), O.none, O.some(3)]
const data = pipe(
  options, 
  A.filter(O.isSome),
  O.sequenceArray
)
console.log(data) //  { _tag: 'Some', value: [ 1, 3 ] }

```

**Comment by samhh** [comment]
That's expected. See the examples for `sequence` in [Haskell's docs](https://hackage.haskell.org/package/base-4.17.0.0/docs/Prelude.html#v:sequence):

```hs
sequence [Left 0, Right 1,Right 2,Right 3,Right 4]
-- Left 0
```

If you only want the `Some` values you probably want `A.compact` or similar instead.

**Comment by iago-silva-unvoid** [comment]
Yep, `A.compact` is the function I was missing, thanks!
