### ISSUE TITLE
Record.lookup returns Some(undefined) if a field is set to undefined

### ISSUE THREAD

**Issue by milespossing-msft** [gcanti/fp-ts#1842]
### Current Behavior

Should an object with a field defined as `undefined` be passed into a lookup for that particular field, the result is `Some(undefined)`.

### Expected behavior

One could at least argue that the result should be `None`

### Reproducible example

```typescript
import * as R from 'fp-ts/Record';
import * as O from 'fp-ts/Option';

const r1: Record<string, any> = {
  field1: 'test',
  field2: 7,
}

const r2: Record<string, any> = {
  field2: 8,
};

const r3: Record<string, any> = {
  field1: undefined,
  field2: 9,
};

const look = R.lookup('field1');

console.log(look(r1)); // { _tag: 'Some', value: 'test' }
console.log(look(r2)); // { _tag: 'None' }
console.log(look(r3)); // { _tag: 'Some', value: undefined }
```

### Suggested solution(s)

Add an extra `Option.chain(Option.fromNullable)` in to the lookup call.

### Additional context

I'm not entirely sure if this is an appropriate bug report. Perhaps this is standard and expected behavior, but this does seem to break the intent of the `Option` type to me.

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
|Node| 14.19|
|typescript| 4.9.4|
|fp-ts| 2.13.1|
|ts-node| 10.9.1|
|OS| MacOS|
|Arch| ARM64|

**Comment by milespossing-msft** [comment]
I'd be willing to make this change if the community agrees with my desired behavior

**Comment by gcanti** [comment]
@milespossing-msft actually this is not a bug, it's the intended behavior
