### ISSUE TITLE
Cannot find module '../src/Monad' / '../src/IxMonad' / '../src/IO' in release 0.4.4

### ISSUE THREAD

**Issue by alexandervanhecke** [gcanti/fp-ts#185]
Hi, 
I just upgraded from 0.4.3 to 0.4.4, there seems to be a problem in the distributed `IxIO.d.ts` file, which references `../src/Monad` (and `IxMonad`, `IO`) instead of referencing `./Monad`.

`(1,23): error TS2307: Cannot find module '../src/Monad'.`
`(2,41): error TS2307: Cannot find module '../src/IxMonad'.`
`(3,20): error TS2307: Cannot find module '../src/IO'.`

downgrading to 0.4.3 for now

**Comment by gcanti** [comment]
Wow, that's embarrassing :) I'll release a fix asap, sorry for the inconvenience

**Comment by gcanti** [comment]
@alexandervanhecke v0.4.5 is out

**Comment by alexandervanhecke** [comment]
@gcanti yep, already using it ;)
