### ISSUE TITLE
Importing "fp-ts/Array" causes copmilation errors on Typescript 4.7.4

### ISSUE THREAD

**Issue by jefshe** [gcanti/fp-ts#1885]
### Current Behavior
Given this simple example:
```typescript
import * as A from "fp-ts/Array";

export function test() {
  return A.map(a => a);
}
```
and my tsconfig:
```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "ES2018",
    "outDir": "./build",
    "sourceMap": true,
    "resolveJsonModule": true
  },

  "include": ["src/**/*"]
}
```

I get the following compile errors when I run tsc:
![image](https://github.com/gcanti/fp-ts/assets/30220932/f3f37780-0781-4f4e-83a6-17eda2004fd6)

Oddly enough importing `TaskEither` and `Either` both compile fine. It's only when I introduce the `Array` import. Is there something I'm missing here?
### Expected behavior

No compliation errors

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts           | 2.16.0         |
| TypeScript |     4.7.4      |

**Comment by gcanti** [comment]
can't repro

the only thing I can think about is

> Make sure to always have a single version of `fp-ts` installed in your project. Multiple versions are known to cause `tsc` to hang during compilation. You can check the versions currently installed using `npm ls fp-ts` (make sure there's a single version and all the others are marked as deduped).

**Comment by jefshe** [comment]
Thank you for looking into this so promptly. Yes it turned out to be related to my mono repo setup. Thanks of the help!
