### ISSUE TITLE
`groupBy` for Array/ReadonlyArray

### ISSUE THREAD

**Issue by aherrmann13** [gcanti/fp-ts#1889]
I noticed that the non-empty array variants have `groupBy` ([ref](https://github.com/gcanti/fp-ts/blob/8c4e31d79d96196738d8b1bbc45a98fc3ff8f3d6/src/ReadonlyNonEmptyArray.ts#L434-L447) and [ref](https://github.com/gcanti/fp-ts/blob/8c4e31d79d96196738d8b1bbc45a98fc3ff8f3d6/src/NonEmptyArray.ts#L413-L426)).  The implementation is the same in both cases and does not depend on the assumption that the list has an element.  Is there a reason this does not exist for Array and ReadonlyArray?

I will submit a pull request with the changes if its fine to add them

**Comment by gcanti** [comment]
@aherrmann13 do you mean adding an alias in the Array and ReadonlyArray modules?

**Comment by aherrmann13** [comment]
I think the implementation would need to be moved-> the NonEmpty variants would contain an alias to the implementation in the more general base variant.  But in general yes that is what I mean.

**Comment by aherrmann13** [comment]
scratch that, I didn't look at the type def carefully enough
