### ISSUE TITLE
Add Endo?

### ISSUE THREAD

**Issue by liam-goodacre-hpe** [gcanti/fp-ts#189]
See https://pursuit.purescript.org/packages/purescript-monoid/3.1.0/docs/Data.Monoid.Endo#t:Endo

**Comment by gcanti** [comment]
Sure, it got stuck in this PR https://github.com/gcanti/fp-ts/pull/64/commits/a944133f525d925797ea2bc61c77783011c40369 I guess I can merge it now

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/fp-ts/releases/tag/0.4.6
