### ISSUE TITLE
Reproduce `Promise.all` behaviour

### ISSUE THREAD

**Issue by albertodiazdorado** [gcanti/fp-ts#1891]
I don't know whether this is a feature request, or whether the feature is already available and I cannot find it. In short, I want the same behavior that I have with `Promise.all` (i.e. reject as soon as one Promise rejects) with `A.sequence(TE.ApplicativePar)` (i.e. return a `Left` value as soon as one of the `TaskEither`'s returns a `Left` value)

### Current Behavior

`A.sequence(TE.ApplicativePar)` only returns once all the `TaskEither`'s have resolved. I have no means of returning early as soon as one of the `TaskEither`'s returns `Left`.

### Desired Behavior

I can choose to return early as soon as one of the `TaskEither`'s returns `Left`.

### Suggested Solution

Sadly, I cannot think of anything. I do not have enough knowledge about the codebase.

### Who does this impact? Who is this for?

TypeScript users in general. `Promise.all` is a very basic JS feature.

### Describe alternatives you've considered

This is very, very sad, but instead of returning `Left` values, I map over them and throw an error instead, such that I can return early in `Promise.all`. This defeats the whole purpose of `fp-ts`.

### Additional context

This is the MWE:
```ts
import * as E from "fp-ts/Either";
import * as TE from "fp-ts/TaskEither";
import * as A from "fp-ts/Array";
import { pipe } from "fp-ts/function";

/**
 * The line 'End of script' is printed only after all the TaskEither resolve,
 * but I'd like to have it as soon as one TaskEither returns Left
 */

const sleep = (n: number) => new Promise(resolve => setTimeout(resolve, n))

const main = async () => {
    const start = Date.now();
    const promiseConfig = [
        { timeout: 2000, throw: true },
        { timeout: 4000, throw: false },
        { timeout: 6000, throw: false },
        { timeout: 8000, throw: false },
    ]

    const promises = promiseConfig.map(async (config, index) => {
        console.log(`Promise ${index} ongoing`)
        await sleep(config.timeout);
        if (config.throw) {
            console.log(`Promise ${index} failed`)
            return E.left(`Promise ${index} failed`);
        }
        console.log(`Promise ${index} resolved`)
        return E.right(undefined)
    });

    const results = await pipe(
        promises,
        A.map(p => () => p),
        A.sequence(TE.ApplicativePar)
    )();

    if (E.isLeft(results)) {
        console.log("Error catched.", { error: results.left })
    }

    console.log(`End of script after ${Date.now() - start} milliseconds`);
}

main();
```

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |   2.16.0         |
| TypeScript |      5.1.6      |

**Comment by patstockwell** [comment]
You might be looking for `getRaceMonoid()` - https://gcanti.github.io/fp-ts/modules/Task.ts.html#getracemonoid

Does something like this work?
```ts
import { monoid as M, task as T } from "fp-ts";

M.fold(T.getRaceMonoid())(taskEithers)
```

**Comment by albertodiazdorado** [comment]
Nice @patstockwell , thanks!
