### ISSUE TITLE
record.modifyAt doesn't infer value type at given key

### ISSUE THREAD

**Issue by hesxenon** [gcanti/fp-ts#1899]
### Current Behavior

`record.modifyAt` infers the value type as a union of all possible types that exist in the given record.

### Expected behavior

`record.modifyAt` should infer the type of the value at the given key.

### Reproducible example

https://codesandbox.io/s/sweet-khorana-p8ltyx?file=/src/index.ts

`pipe({x: 0, y: "foo"}, record.modifyAt("x", (value) => value * 3))` errors as `value` has type `number | string`

### Suggested solution(s)

change the current signature of 
```typescript
<A>(
  k: string,
  f: (a: A) => A
) => <K extends string>(r: Record<K, A>) => Option<Record<K, A>>
```

to

```typescript
<A extends Record<string, any>, K extends keyof A, T>(
  k: K,
  f: (a: A[K]) => T
) => (r: A) => A & {[k in K]: T}
```

### Additional context

I think this would also eliminate the need for `unsafeModifyAt` - as long as its usage is fully typed.

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.16.1           |
| TypeScript | 5.1.6     |

**Comment by hesxenon** [comment]
I didn't even look at struct before and yes, that should be fine for my use case. 

But two things come to mind:
- how is `record.modifyAt` useful at all, if it basically requires "a homogenous array with string indices".
- why would my suggestion be a better fit for struct instead of record? Am I missing some semantics here?

**Comment by samhh** [comment]
Think of `Record` like a dictionary; an alternative to `Map`. You may want to run an endomorphism against a specific key in a dictionary. Struct on the other hand is for product types, like tuples.

For example, you may have a struct representing customers, and a record of those keyed by ID.

```ts
type Person = { name: number; } // a struct
type PeopleById = Record<string, Person>

const people: PeopleById = { samhh: { id: "samhh", name: "Sam" } }

// A use case for `record.modifyAt` might be that I change my name.
const updatedPeople = Rec.modifyAt("samhh", person => ({ ...person, name: "Ashley" }))
```

**Comment by hesxenon** [comment]
I see, that's inline with the naming of typescripts `Record` though I'm not even sure I agree with that based on [even Wikipedias definition](https://en.wikipedia.org/wiki/Record_(computer_science)) on what a record is.

I don't mind closing this issue since of course there's a valid point in keeping `fp-TS` inline with TypeScript but
- struct should probably be extended a bit and receive a more prominent position somehow imho
- maybe (just maybe) there's merit in aligning with the broader definition of record? I honestly don't know...
