### ISSUE TITLE
Will `Effect-TS/effect` be the successor of `fp-ts`?

### ISSUE THREAD

**Issue by rinn7e** [gcanti/fp-ts#1941]
Hi everyone, I just found out about https://github.com/Effect-TS/effect, and from what I understand it is pretty much the same thing as `fp-ts`.

I have been using `fp-ts` for a long time and in many projects, and I was wondering if `effect` is meant to be the successor. If it is, I might start migrating to `effect` instead. 

Thank you beforehand.

**Comment by rinn7e** [comment]
Nevermind, I found a comparison page in https://effect.website/docs/other/fp-ts

Looks like in my use-case, `fp-ts` is better after all 👍

**Comment by mikearnaldi** [comment]
It is the successor of fp-ts to a good extent: https://dev.to/effect/a-bright-future-for-effect-455m

**Comment by falloutphil** [comment]
Hi all,

I've been a bit slow to realise this too!  I've installed effect-ts and although it looks very cool for certain specific use-cases, is it a near drop-in replacement in terms of providing a way to write general fp code in typescript that directly allows the user to write and compose Functors, Applicatives, Monoids, Monads etc like I'm used to in fp-ts?  A cursory look at the effect-ts source code suggests these concepts are not explicitly available like they are in fp-ts, but I might well be misunderstanding, it's more like Zio in Scala than a general purpose fp library?

* Is the goal to now make general fp structures like this available by porting the ideas from fp-ts into effect-ts?  i.e. should I hang-back on fp-ts now, and functionality will come available in effect-ts, or is the fp-ts way of doing things currently now a dead-end?
* Is there any known plan to keep fp-ts going in contexts not covered by effect-ts for people who want a more "traditional" (if that's the right word!) fp experience in typescript?

It might be that I should be ditching fp-ts completely for effect-ts, but I have written a reasonably large amount of code now in fp-ts for my current projects and it works great - so happy to move, but just wanted to understand the best future for monadic code I'd composed myself before making and big decisions!

**Comment by gcanti** [comment]
> write and compose Functors, Applicatives, Monoids, Monads etc like I'm used to in fp-ts?

@falloutphil there's an `@effect/typeclass` package: https://github.com/Effect-TS/effect/tree/main/packages/typeclass

**Comment by falloutphil** [comment]
Thanks so much for the pointer @gcanti - in case it helps anyone it took me a little while to orientate a very simple equivalent example of map use, so thought I'd leave this here in case it saves others a bit of time - once you get a foothold like this it all starts to make sense and converting fp-ts code is fairly intuitive (for me so far, at least!) as mentioned above you need to npm install `@effect/typeclass` as well as `effect`.  All other setup was taken from effect's Quickstart guide.

```typescript
// -*- compile-command: "npx ts-node optional-effect.ts" -*-

import { Covariant as OptionCovariant } from "@effect/typeclass/data/Option";
import { Covariant as ArrayCovariant } from "@effect/typeclass/data/Array";
import { some } from "effect/Option";
import type { Covariant } from "@effect/typeclass/Covariant";
import type { Kind, TypeLambda } from "effect/HKT";

// Generic increment function using the generic Covariant interface
function increment<F extends TypeLambda>(
  covariant: Covariant<F>,
  fa: Kind<F, unknown, unknown, unknown, number>
): Kind<F, unknown, unknown, unknown, number> {
  return covariant.map(fa, (x) => x + 1);
}

// Use the Option-specific Covariant instance
const someValue = some(5);
const incremented = increment(OptionCovariant, someValue);
console.log(incremented); // Output: Some(6)

const arrayValue = [1,2,3,4]
const arrayIncremented = increment(ArrayCovariant, arrayValue)
console.log(arrayIncremented); // [2,3,4,5]
```
