### ISSUE TITLE
sequenceT / TaskEither type problem with 2.16.6

### ISSUE THREAD

**Issue by markanye** [gcanti/fp-ts#1944]
## 🐛 Bug report

With fp-ts 2.16.5 and typescript 5.5.2, this is valid code:

```typescript

import * as TE from "fp-ts/lib/TaskEither";
import { sequenceT } from "fp-ts/lib/Apply";

const doAfter = (delay: number): TE.TaskEither<Error, string> => TE.tryCatch(
  () => new Promise((resolve) => setTimeout(() => resolve('done'), delay)),
  (reason) => new Error(`failed: ${reason}`)
);

export const doAll = sequenceT(TE.ApplicativePar)(doAfter(1000), doAfter(2000));
```

But after upgrading to fp-ts 2.16.6, the last line throws the following typescript error:

`
Argument of type '[TaskEither<Error, string>, TaskEither<Error, string>]' is not assignable to parameter of type 'HKT<"TaskEither", any>[] & { readonly 0: HKT<"TaskEither", any>; }'.
  Type '[TaskEither<Error, string>, TaskEither<Error, string>]' is not assignable to type 'HKT<"TaskEither", any>[]'.
    Type 'TaskEither<Error, string>' is not assignable to type 'HKT<"TaskEither", any>'.ts(2345)
`

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.16.6      |
| TypeScript |      5.5.2      |

**Comment by gcanti** [comment]
@markanye I don't get any errors

**Comment by markanye** [comment]
On closer inspection, you're right. It compiles fine for me too, but is displayed as an error in VSCode.

<img width="760" alt="vscode-error" src="https://github.com/gcanti/fp-ts/assets/1718899/77588d93-63cc-4dea-b791-23352e4375ed">

Oddly, VSCode is configured with the same typescript install that I'm using for compilation. The issue goes away if I downgrade to 2.16.5.

**Comment by gcanti** [comment]
Weird, I'm a VSCode user too, and everything is fine for me
