### ISSUE TITLE
Add a "Using fp-ts" section

### ISSUE THREAD

**Issue by RicSala** [gcanti/fp-ts#1954]
## 📖 Documentation

FP is increasing in popularity in the ts ecosystem, but for most of us is still pretty new.

Such a paradigm change requires some kind of "certainty" that the place you are going to is better than the place you are currently at.

Having a list of projects currently using fp-ts, thus programming functionally, would help a lot for those of us that are still doubtfull to take the leap, giving as a sense of how a good FP codebase looks like.

To whoever is reading this, if you know some well done fp ts project, please add it below.

Cheers

**Comment by gcanti** [comment]
@RicSala there's already a pinned "Who's using fp-ts?" issue
