### ISSUE TITLE
semigroup fantasyland spec

### ISSUE THREAD

**Issue by leemhenson** [gcanti/fp-ts#233]
Hi Giulio

My team and I have been doing some learning with regards to fp-ts and ADTs, also reading along with Tom Harding's blog series. Today we had a good chat about Semigroups, and the point was raised that the Semigroup interface here:

https://github.com/gcanti/fp-ts/blob/master/src/Semigroup.ts#L3-L5

doesn't quite mesh with what Tom wrote here:

http://www.tomharding.me/2017/03/13/fantas-eel-and-specification-4/

> concat :: Semigroup a => a ~> a -> a
>
> A Semigroup’s concat method must take another value of the same type, and return a third value of the same type.

The way we read this is that something can only be called a Semigroup if it returns a Semigroup of the same type, e.g. something with `concat` defined on it. The definition here:

https://github.com/gcanti/fp-ts/blob/master/src/Semigroup.ts#L3-L5

doesn't enforce that. I guess that means either:

a) we have misunderstood what `concat :: Semigroup a => a ~> a -> a` means
b) you were not shooting for exact FantasyLand compliance
c) it is compliant in a way that we don't understand

Or some combination of the above. 😄  Could you explain which it is? Many thanks!

**Comment by gcanti** [comment]
In fp-ts typeclasses are defined following the [static-land](https://github.com/rpominov/static-land) style. In addition, when it makes sense, there's a variant following the fantasy-land style (see for example `Functor` and `FantasyFunctor` here https://github.com/gcanti/fp-ts/blob/master/src/Functor.ts)

> you were not shooting for exact FantasyLand compliance

Yep, fp-ts is not *strictly* compliant neither with FL nor with SL

**Comment by leemhenson** [comment]
Makes sense. Thanks for the explanation!
