### ISSUE TITLE
Suggestion: change getOrElse signature

### ISSUE THREAD

**Issue by raveclassic** [gcanti/fp-ts#242]
Current implementation of `getOrElse` accepts a lazy value (thunk). Typical usecase though is to pass a quick default value so it's tiresome to wrap such value with `constant` each time when passing to `getOrElse`. 

I suggest changing `getOrElse` to accept default value and to introduce another method to accept a thunk because it's also useful to chain heavy computations. Such method (`valueOr`) is proposed in https://github.com/gcanti/fp-ts/pull/240#issuecomment-333767552

These methods would also be more aligned with Scala: [getOrElse](http://www.scala-lang.org/api/2.12.3/scala/Option.html#getOrElse[B>:A](default:=>B):B) and [valueOr](http://typelevel.github.io/cats/api/cats/syntax/EitherOps.html#valueOr[BB>:B](f:A=>BB):BB)

**Comment by gcanti** [comment]
I'm not a Scala expert but IIRC `getOrElse` is lazy

```scala
getOrElse[B >: A](default: => B): B
```

@sledorze am I reading the signature right (`=> B`)? I feel like the Scala compiler does some magic there.

@raveclassic what about adding a `getOrElse_(a: A): A` variant in 0.5.3?

**Comment by raveclassic** [comment]
>I'm not a Scala expert but IIRC getOrElse is lazy

So am I :) But signature of `valueOr` `def valueOr[BB >: B](f: (A) ⇒ BB): BB` more likely accepts a thunk.

> what about adding a getOrElse_(a: A): A variant in 0.5.3?

I would like to avoid such cryptic names. I'm ok to wait a bit for 0.6 with a breaking change.

**Comment by vegansk** [comment]
In Scala `=> B` is the call by name, i.e. lazy value. And when the compiler sees something like `println(upper getOrElse "")` for the call by name, it translates that to `println(upper.getOrElse(() => ""))`

Removing lazyness from `getOrElse` parameter will be the breaking change, but not that hard to fix. The main problem for me is that it will be the breaking change for our team that use ts on frontend and scala on backend :-)

**Comment by sledorze** [comment]
@gcanti you re right, maybe replace the second by getOrElseValue(a: A): A. We should keep getOrElse as is IMHO.

**Comment by sledorze** [comment]
@gcanti you re right, maybe replace the second by getOrElseValue(a: A): A. We should keep getOrElse as is IMHO.

**Comment by sledorze** [comment]
also for the sake of clarify; `call by name` has not exactly a `lazy` semantic in scala; the operation is called as many time as the name appears whereas `lazy` (aka `call by need`) means the operation is computed at most once.

**Comment by raveclassic** [comment]
@sledorze `getOrElseValue` sounds goods!

**Comment by raveclassic** [comment]
I've also checked Java Optional - it has slightly shorter names: lazy `orElseGet` and strict `orElse`. Maybe lazy `getOrElse` and strict `orElse` or even `orValue` or even `valueElse` or even `orElseValue` then? :)

**Comment by sledorze** [comment]
following scala's Option, `orElse` returns an Option, not extraction a value from it.

**Comment by raveclassic** [comment]
Well, seems like Scala does not have a strict version at all and `orElse` is called `alt` here (which is strict BTW). 

But we should pick a name and it will be realy handy if it's short because it's used very often.

**Comment by raveclassic** [comment]
`fp-ts` doesn't fully align with scala or haskell as it was designed for TS at the first place (I believe). 
Scala's `Option#getOrElse` is used in a strict manner even though scala compiler does some tricks so `fp-ts` already differs here. So I think if `fp-ts` should follow Scala, then `getOrElse` signature should be changed, otherwise I don't see any benefits of such following because it's not fully consistent then and we can pick a shorter handy name like `orElse`.

@gcanti What do you think?

**Comment by sledorze** [comment]
The 'trick' the scala compiler is doing is on the syntax level, doing a silent creation of a call by name thunk. (a : => A) syntax.
The semantic of getOrElse is really call by name (so non strict).

**Comment by raveclassic** [comment]
@sledorze That's the point - it is silent and does not affect syntax in any way. I still can't write `optional.getOrElse('')` in TS which is syntactically equivalent to `optional getOrElse ""`, am I right?

**Comment by sledorze** [comment]
I am not after aligning with the syntax but after the behaviour.

**Comment by raveclassic** [comment]
Ok, let's go with `getOrElseValue` for now. I've opened #246 which adds it.

**Comment by gcanti** [comment]
0.6 will contain a few breaking changes, should we revisit this issue? That is

- rename `getOrElseValue` to `getOrElse`
- rename `getOrElse` to `getOrElseL` (like in funfix) or something

**Comment by raveclassic** [comment]
I think `getOrElseValue` is fine, let's stay with it for now.

**Comment by Ebuall** [comment]
What about just getOrValue?
