### ISSUE TITLE
Either<L, A>#equals should accept a Setoid<L> other than a Setoid<A>

### ISSUE THREAD

**Issue by gcanti** [gcanti/fp-ts#247]

**Comment by rilut** [comment]
Is this the correct fix for this? https://github.com/rilut/fp-ts/commit/a6cf7a3834e34ef4ad6763b0d8fbc50fe39266b6

Thanks!

**Comment by sledorze** [comment]
Setoid of L has to be tested against the Left side I guess? How to match the types then ?

**Comment by gcanti** [comment]
The signature should be 

```ts
export const equals = <L, A>(SL: Setoid<L>, SA: Setoid<A>) => (fx: Either<L, A>) => (fy: Either<L, A>): boolean
```

like in `These` https://github.com/gcanti/fp-ts/blob/6cdc0115c95f16926330a795f48aa76f605dc638/src/These.ts#L182

The same for `Validation`.

**Comment by rilut** [comment]
@gcanti is `class Both<L, A>` also needed?

**Comment by rilut** [comment]
Fyi this is my branch: https://github.com/gcanti/fp-ts/compare/master...rilut:fix/either-equals. I'll figure out `chainRec` and `partitionMap`

**Comment by gcanti** [comment]
> does class Both<L, A> also needed?

@rilut No, `Both` is from `These`. `Either` is just the coproduct of `Left` and `Right`.
