### ISSUE TITLE
Futures?

### ISSUE THREAD

**Issue by Istar-Eldritch** [gcanti/fp-ts#256]
I was wondering if there is a nice way to work with Promises and this library. Are you considering adding Futures as a way to wrap them, if not, is there an easy way chain them with the structures provided by this library?

**Comment by gcanti** [comment]
[Task](https://github.com/gcanti/fp-ts/blob/3083091170808f83c7b54b08f94e6b491b1f4d68/docs/api/md/Task.md) wraps a `Promise` and is lazy

**Comment by Istar-Eldritch** [comment]
Awesome, exactly what I was looking for.

Feel free to close this issue :+1:
