### ISSUE TITLE
TypeScript 2.6 support

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#260]
TypeScript 2.6 is currently in release candidate (RC) and almost ready to be released as stable.

Have you experimented with getting fp-ts to work with TypeScript 2.6? I tried upgrading my app and got a lot of errors when enabling the new  `strictFunctionTypes` rule.

https://blogs.msdn.microsoft.com/typescript/2017/10/12/announcing-typescript-2-6-rc/

**Comment by gcanti** [comment]
Relevant: https://github.com/gcanti/fp-ts/issues/244

TLDR: `npm i fp-ts@next`

**Comment by gcanti** [comment]
TypeScript 2.6.1 is out, I'm going to officially release the next version of fp-ts which is currently published in the `next` channel (0.6.1)
