### ISSUE TITLE
Suggestion: Include RemoteData

### ISSUE THREAD

**Issue by raveclassic** [gcanti/fp-ts#264]
@gcanti 

In one of our projects we use `RemoteData` from https://medium.com/@gcanti/slaying-a-ui-antipattern-with-flow-5eed0cfb627b.

It has four states (Initial, Pending, Failure and Success) and implements Monad, Foldable, Alt, Extend and Traversable (this list may be extented though).

Recently another our project required the same type and the most obvious way would be to move the type to a shared library but then it would require fp-ts as a dependency as well which I'd like to avoid.

Therefore I suggest including RemoteData into the core fp-ts. If you agree I can add it here.

Though, I have some doubts wether fp-ts is a right place. What do you think?

**Comment by gcanti** [comment]
> move the type to a shared library

Seems sensible, RemoteData is not core IMO. What's the problem with having a dependency on fp-ts btw?

**Comment by raveclassic** [comment]
@gcanti No problem actually. Just though such type would be helpful for consumers of fp-ts

**Comment by gcanti** [comment]
@raveclassic Have you published `RemoteData`? We could add it to the "Ecosystem" section in the readme

**Comment by raveclassic** [comment]
When adopting to the other project I didn't generalize the failure type for convenience so I didn't publish it anywhere. I can check it once again though.

**Comment by wmaurer** [comment]
Based on various `RemoteData` articles, I have starting applying the concept to one of my new projects - extremely simple and not at all FP - just a sum type and a fold function.

Now I would like to take the concept a step further, especially after reading the following article:
http://fictional.logdown.com/posts/5765399-your-data-is-loading
Interesting to me is the combining of multiple remotes (Applicative)

As a very beginner `fp-ts` user (only using `Option`, `Either`, `array` and some `io-ts`), building a proper RemoteData is rather an intimidating task ...
@raveclassic is there any possibility of you showing your `RemoteData` type? I'd really like to look, learn and adapt it, and even collaborate on it.

Cheers
-Wayne

**Comment by raveclassic** [comment]
@wmaurer  I'd really like to opensource it, because actually there're other independent projects in my company that need it. Still it requires some discussion with my PMO, because right now it's closedsource. I'll try my best to do it tomorrow and find some spare time to generalize failure type and publish.

**Comment by gcanti** [comment]
> I'd mention that I'm considering extending my implementation

That's why I was reclutant to add `RemoteData` to core, I can think of different implementations depending on what you want to model.

For example @wmaurer in your model there's no representation of the following case: an error after a refresh

```ts
{
  tag: 'RefreshingError';
  error: E,
  data: A;
}
```

I wonder if the following model accounts for all cases, since loading, error and data look independent

```ts
interface RemoteData<E, A> {
  loading: boolean
  data: Option<A>
  error: Option<E>
}
```

WDYT?

**Comment by gcanti** [comment]
While we are at it, I'm playing with some `Semigroup` instances which look useful

```ts
import { Option, getMonoid } from 'fp-ts/lib/Option'
import { Semigroup, getLastSemigroup, getRecordSemigroup } from 'fp-ts/lib/Semigroup'
import { getArrayMonoid } from 'fp-ts/lib/Monoid'

interface RemoteData<E, A> {
  loading: boolean
  data: Option<A>
  error: Option<E>
}

const getSemigroup = <E, A>(S: Semigroup<A>): Semigroup<RemoteData<E, A>> =>
  getRecordSemigroup({
    // last loading wins
    loading: getLastSemigroup<boolean>(),
    data: getMonoid(S),
    // last error wins
    error: getLastSemigroup<Option<E>>()
  })

interface MyRemoteData extends RemoteData<string, Array<string>> {}

//
// Loading strategies
//

// last data wins
const refreshSemigroup: Semigroup<MyRemoteData> = getSemigroup(getLastSemigroup())

// concat datas
const incrementalLoadingSemigroup: Semigroup<MyRemoteData> = getSemigroup(getArrayMonoid())
```

**Comment by raveclassic** [comment]
Finally, I was able to find some time to adapt to latest fp-ts/typescript. [Here's](https://www.npmjs.com/package/@devexperts/remote-data-ts) the package and [here's](https://github.com/devex-web-frontend/remote-data-ts) the updated implementation. No docs/tests for now, sorry :)
Feel free to open issues/PRs.

**Comment by gcanti** [comment]
Thanks @raveclassic, would you like to send a PR to add your lib to the "Ecosystem" section in the README?

**Comment by raveclassic** [comment]
Sure, here it is: https://github.com/gcanti/fp-ts/pull/363
