### ISSUE TITLE
Arrows

### ISSUE THREAD

**Issue by masaeedu** [gcanti/fp-ts#268]
It would be good to have the definition of an [arrow](https://en.wikipedia.org/wiki/Arrow_(computer_science)) and perhaps some of the basic utility methods.

I believe the interface should be:

```ts
import { hkt, category } from "fp-ts";

export interface Arrow<A> extends category.Category<A> {
  arr<S, T>(f: (s: S) => T): hkt.HKT2<A, S, T>;
  first<S, T, U>(a: hkt.HKT2<A, S, T>): hkt.HKT2<A, [S, U], [T, U]>;
}
```

Probably be useful to tack on exported equivalents of Haskell's [`second`, `&&&`, `***`, etc.](https://en.wikibooks.org/wiki/Haskell/Understanding_arrows) for convenience.

**Comment by gcanti** [comment]
Looks like arrows can be described as strong categories ([Strong profunctor](https://github.com/purescript/purescript-profunctor/blob/7a60adac85944847cb05e361d62ac53f3cd2ee2e/src/Data/Profunctor/Strong.purs))

**Comment by masaeedu** [comment]
After reading about it a bit more, yeah you're right. Things you need arrows for can be done with co+contra functors,
