### ISSUE TITLE
Suggestions for breaking changes for next release

### ISSUE THREAD

**Issue by raveclassic** [gcanti/fp-ts#290]
This issue tracks suggestions with breaking changes to be included in the next release.

- Ordering: replace string literal union with numeric enum
```typescript
//now 
type Ordering = 'LT' | 'EQ' | 'GT';
//changes to
enum Ordering = {
  LT = -1,
  EQ = 0,
  GT = 1
}
```
This removes the need to manually convert ordering values when using in native comparators.

**Comment by gcanti** [comment]
Here's my list so far

- drop Flow support
- remove toOption in Either (now deprecated)
- remove monoidArray and semigroupArray (now deprecated)

**Comment by raveclassic** [comment]
@gcanti Bye, bye, flow?

**Comment by gcanti** [comment]
@raveclassic yeah, it has been a very nice experiment (Flow is great with respect to type inference and HKT support) but I'm not a Flow user and my professional interest is pretty low. After some weeks of maintenance I think it doesn't worth to keep the definition files here, there's flow-typed for that

Another one:

- rename all phantom fields using dashes

```diff
class Some<A> {
-  // prettier-ignore
-  readonly '_A': A
+  readonly '-A': A
}
```

no prettier comments required and (AFAIK) they don't show up in quick info

**Comment by gcanti** [comment]
@raveclassic I would change to

```ts
export type Ordering = -1 | 0 | 1
```

instead, enums look unsafe

```ts
enum Ordering {
  LT = -1,
  EQ = 0,
  GT = 1
}

declare function f(o: Ordering): void

f(1000) // WAT
```

**Comment by gcanti** [comment]
Anothe proposal: swap arguments of `Functor`, `Chain` (maybe others)

from

```ts
export interface Chain<F> extends Apply<F> {
  chain<A, B>(f: (a: A) => HKT<F, B>, fa: HKT<F, A>): HKT<F, B>
}
```

to

```ts
export interface Chain<F> extends Apply<F> {
  chain<A, B>(fa: HKT<F, A>, f: (a: A) => HKT<F, B>): HKT<F, B>
}
```

Why?

1) more readable

```ts
const chain2 = <A, B>(fa: Option<A>, f: (a: A) => Option<B>): Option<B> => {
  return fa.chain(f)
}

declare const fa: Option<string>
declare const f: (s: string) => Option<string>
declare const g: (s: string) => Option<string>
declare const h: (s: string) => Option<string>

// from
chain(a => chain(b => chain(h, g(b)), f(a)), fa) // <- fa is in last position

// to
chain2(fa, a => chain2(f(a), b => chain2(g(b), h)))
//      ^ fa is in first position
```

2) better suggestions while writing

```ts
declare const fa: Option<string>

const x = chain(a => some(a.)) // no suggestions

const y = chain2(fa, a => some(a.)) // suggestions (substring, etc...)
```

**Comment by gcanti** [comment]
This is controversial: 

- uncurry `Setoid`, `Ord`, `Semigroup`

Why? IME 99.9% of times I'm fine with the uncurried version

Another controversial proposal: remove (useless?) thunks as much as possible

- change `Monoid.empty` from a thunk to a value
- change `Plus.zero` from a thunk to a value
- `Option.fold` should accept a value instead of a thunk for the `None` case
- remove `getOrElseValue` in favour of a `getOrElse` without a thunk
- other?

**Comment by sledorze** [comment]
Ok with swapping, i find it better that way.
We should still have a getOrElse with a thunk what naming are you thinking about?
Same for fold.

**Comment by gcanti** [comment]
> We should still have a getOrElse with a thunk

I'm not sure, have you got a compelling use case? I always find myself using `getOrElseValue`

**Comment by sledorze** [comment]
@gcanti in total honesty I've checked in our code base and we only use `getOrElseValue`.
However, I'm wondering is that's not something any functional programmer would consider as a given.

**Comment by sledorze** [comment]
More generally, what is the main motivation for removing curried versions of functions?
Maintenance overhead ? inference issues ? weight of library ?

**Comment by gcanti** [comment]
@sledorze Thanks for checking, real world usages are what should drive our decisions.

> I'm wondering is that's not something any functional programmer would consider as a given

Don't think so, for example in Purescript the `maybe` function (corresponding to our `getOrElse`) is not lazy. 
Anyway we can re-add a lazy version in the future if we come up with a compelling use case.

In the case of `Setoid`, `Ord`, `Semigroup` again the proposal is based on my experience, I always find myself using them fully saturated. 

I mean, this is far from critical, but if 99% of the times people use them saturated, why imposing the overhead (both sintactically and performance-wise) of the curried version?

In general I would like to clean this library up in order to release a 1.0.0 version.

**Comment by raveclassic** [comment]
@gcanti I'm ok with all suggestions. What about `getOrElse` - `funfix` adds `L` to lazy versions: https://funfix.org/api/core/classes/option.html#getorelsel https://funfix.org/api/core/classes/option.html#orelsel. This is also slightly related to replacing thunks with constants. Sometimes a thunk is useful to explicitly define type argument. Maybe we should leave lazy versions with such postfix?

**Comment by raveclassic** [comment]
@gcanti I'm ok with almost all suggestions.
- numeric union for Ordering is fine
- swapping of arguments is fine
- uncurry something - fine. maybe also uncurry Field?
- changing thunks to constants - well... it's sometimes useful to explicitly define type argument, constants are limited when used inlined
- Option#fold accepting a value - it's always useful to define a failure lazily, the same applies for `getOrElse`

Here's how funfix deals with lazy/strict - it adds `L` to lazy versions: https://funfix.org/api/core/classes/option.html#getorelsel https://funfix.org/api/core/classes/option.html#orelsel. 
Maybe we should leave lazy versions with such postfix?

**Comment by gcanti** [comment]
- changing thunks to constants - well... it's sometimes useful to explicitly define type argument, constants are limited when used inlined
- Option#fold accepting a value - it's useful to process a failure lazily, the same applies to getOrElse

@raveclassic could you please expand on these, maybe with an example?

**Comment by raveclassic** [comment]
About thunks and constants - I rechecked my usecases and it seems that it's fine to rely on type inference.

About fold - here's an example:
```typescript
const foo = some(123);
foo.fold(() => someHeavyOperation(), foo => foo + 2); //here heavy operation is never called
foo.getOrElse(() => someHeavyOperation()); //same here
```

**Comment by raveclassic** [comment]
Maybe we could really add `L` postfix for such cases?
```typescript
const foo = some(123);]
const double = (n: number) => n * 2;
declare function heavy(): number;
foo.fold(0, double);
foo.foldL(heavy, double);
foo.getOrElse(0);
foo.getOrElseL(heavy);
```

**Comment by gcanti** [comment]
Since funxfix already does that, I'm ok with the `L` convention

**Comment by raveclassic** [comment]
@gcanti Is `fp-ts` ready for `1.0`? Maybe another round of `0.x` to collect some more feedback?

**Comment by gcanti** [comment]
@raveclassic so this is my broad agenda

- I'm working on a `1.0.0` branch right now (if anyone want to follow the progress)
- when ready (and of course after some discussions) I'll release a `1.0.0-rc` version in the `next` channel

**BUT**

I'm eager to experiment with these 2 new features

- Conditional types https://github.com/Microsoft/TypeScript/pull/21316
- Type inference in conditional types https://github.com/Microsoft/TypeScript/pull/21496

As soon as they will be merged on master and will be available on `typescript@next`, I'll do some experiments to see if I can come up with a better encoding of HKTs (in the working branch is improved but there's an annoying explosion of interfaces). 

If that's the case, I would postpone the breaking change release (unless we want to tolerate 2 breaking change versions in a row)

**Comment by sledorze** [comment]
@gcanti I can tolerate a lot

**Comment by raveclassic** [comment]
@gcanti me to :)

**Comment by gcanti** [comment]
Another proposal:

here https://github.com/gcanti/fp-ts/blob/c68434cfa907e18727d1989d131bd01cc1f2a4b9/src/Array.ts#L58 you can set the `A` type parameter, but what you forget to do so?

```ts
import { getMonoid } from 'fp-ts/lib/Array'

// const M: Monoid<{}[]>
const M = getMonoid()

M.concat([1], [[2]]) // WAT
```

Proposal: add a `never` default value

```ts
export const getMonoid = <A = never>(): Monoid<Array<A>> => {
  return {
    ...getSemigroup<A>(),
    empty
  }
}

// const M: Monoid<never[]>
const M = getMonoid()

M.concat([1], [[2]]) // error: Type 'number' is not assignable to type 'never'
```

**Comment by raveclassic** [comment]
>Proposal: add a never default value

Always do the same if I need to force explicit type argument

**Comment by gcanti** [comment]
I'm quite excited. The new encoding (*) is pretty verbose but

- type safety is sensibly improved
- I found a way to re-enable strict function type checks on type classes members

(*) https://github.com/gcanti/fp-ts/blob/1449506613c7d19e0d88023dc93ff6c34ffdeba4/src/Functor.ts#L10-L33

**Comment by gcanti** [comment]
Ok, I have an alpha version on branch `next` installable by running

```
npm i gcanti/fp-ts#next
```

Just tested against the following libraries

- io-ts: no breaking changes
- monocle-ts: no breaking changes
- hyper-ts: no breaking changes

Any feedback is much appreciated

**Comment by gcanti** [comment]
Most notable change: instance members are no more exported as top level functions so instead of

```ts
import * as option from 'fp-ts/lib/Option'

const x: option.Option<whatever> = option.map(...)
```

you must write

```ts
import { Option, option } from 'fp-ts/lib/Option'

const x: Option<whatever> = option.map(...)
```

**Comment by raveclassic** [comment]
@gcanti  Does it mean I'm now unable to write `import { map } from 'fp-ts/lib/Option'`? Why?

**Comment by gcanti** [comment]
@raveclassic Because exporting 2 identical `map`s is confusing. 

Should I use `import { map } from 'fp-ts/lib/Option'` or `option.map`?

Also, my example above was just to explain the change but is not realistic, why you ever want to do that instead of leveraging the `map` method?

```ts
import { Option, some, option } from 'fp-ts/lib/Option'

const x: Option<number> = option.map(some(1), double) // ok works but is weird
const x: Option<number> = some(1).map(double) // better
```

**Comment by raveclassic** [comment]
Ah you mean instance members, really I didn't notice, ok then.

**Comment by zerobias** [comment]
It sad to hear that you had introduced features which you did not plan to support. Choosing fp-ts was a mistake, as unexpected breaking changes every two month is not acceptable, I'm going to replace that to funfix in all projects

**Comment by gcanti** [comment]
@zerobias specifically which features are you referring to? Keep in mind that TypeScript is evolving and simulating HKTs is not an easy task. 
What do you propose instead? This issue is still open precisely to accept suggestions.

**Comment by raveclassic** [comment]
@zerobias 
- Please also keep in mind, that fp-ts hasn't reached major 1.0 yet, it's under heavy development, HKTs in TS are a highly experimental, and thus things are likely to change.
- Support for flow has been announced as an experiment and if you do need it, flow typings can be easily moved to its registry.
- Because fp-ts is still under 1.0, semver allows breaking changes in minor releases with major 0. After reaching 1.0 API is likely to stabilize.

**Comment by gcanti** [comment]
> (rename all phantom fields using dashes) no prettier comments required and (AFAIK) **they don't show up in quick info**

Just checked with TypeScript 2.7.1 and this is no more true, so maybe I should revert this breaking change and keep the current encoding with underscores. What do you think?

**Comment by raveclassic** [comment]
@gcanti I haven't started the update yet, so it's absolutely ok for me.

**Comment by gcanti** [comment]
> Support for flow has been announced as an experiment

Ah right, maybe he was referring to Flow support. So let me clarify a couple of things about Flow

### Current version

Current version is pretty good and Flow is fully supported (all modules have defintions files).
Also I *guess* that is working without issues (Flow users have been pretty quiet..) so nothing forces you to upgrade.

### Next version

@zerobias if you (or somebody else) are interested in the next version, "drop Flow support" doesn't mean that fp-ts won't be usable with Flow, it just means that I don't want to maintain the related definition files in this repo. There's a simple solution though: the standard practice is pushing a definition file to flow-typed. Actually since adding Flow support costed me several days of hard work in November, I would be glad to see such an addition to flow-typed. Indeed if someone is willing to tackle this task I can even offer my help for the migration (which by the way can be incremental starting from the most common data structures like Maybe / Either).

Finally for what concerns API changes it really depends on what are you using. For example casual users of Maybe, Either, IO, Task, State, etc... will hardly notice any change at all.

**Comment by gcanti** [comment]
https://github.com/gcanti/fp-ts/releases/tag/1.0.0
