### ISSUE TITLE
Add laws: property testing backed by testcheck

### ISSUE THREAD

**Issue by gcanti** [gcanti/fp-ts#291]
Example: https://github.com/gcanti/money-ts/blob/c90c3205464ad700dcbc6245b8df0df1ccb549e6/test/util.ts#L136

**Comment by jasonkuhrt** [comment]
Could https://github.com/leebyron/testcheck-js be leveraged?

**Comment by sledorze** [comment]
@jasonkuhrt that's what is already use AFAIK

**Comment by gcanti** [comment]
See https://github.com/gcanti/fp-ts-laws
