### ISSUE TITLE
Missing of in Flow declarations

### ISSUE THREAD

**Issue by goodmind** [gcanti/fp-ts#304]
I think you missed `of` method in all flow declarations

**Comment by gcanti** [comment]
`of` (like `map`, `ap`, `chain`, etc...) is contained in the [`option` instance](https://github.com/gcanti/fp-ts/blob/c408233418de7c1f0f729992a863eadcb6aa9047/src/Option.js.flow#L119)

```
import type { Option } from 'fp-ts/lib/Option'
import { option } from 'fp-ts/lib/Option'
const x: Option<number> = option.of(1)
```

Same for the other data types (when possible)
