### ISSUE TITLE
Idea: documentation website

### ISSUE THREAD

**Issue by stereobooster** [gcanti/fp-ts#313]
There is https://github.com/gcanti/fp-ts/tree/master/docs/api/md, but it would be nice to have this as a website

Example: https://funfix.org/api/core/classes/try.html

**Comment by jasonkuhrt** [comment]
Maybe we can generate the markdown files from source-code types and above-function documentation parsed with support for e.g. markdown.

@gcanti Could you scope out what an ideal solution for you would look like and what level of help you're willing to accept toward that end?

**Comment by gcanti** [comment]
@jasonkuhrt the md files are generated from the source (command `npm run docs`)

**Comment by jasonkuhrt** [comment]
Then we can add a layer on top like Gitbook. I don't think a whole bespoke website is _necessary_.

**Comment by WittBulter** [comment]
try this [repo](https://github.com/DhyanaChina/simpler-paper)?
generate html from md source.

**Comment by piq9117** [comment]
after we fill up the docs we can take the `md` files and feed it to a static site generator like [hakyll](https://jaspervdj.be/hakyll/)

**Comment by grossbart** [comment]
@gcanti worked on generating better API documentation recently (https://github.com/gcanti/docs-ts), which inspired me to start writing docs: https://github.com/gcanti/fp-ts/pull/779

There's still a lot of work ahead, but I'm closing this issue now because we're getting there, slowly but surely 😄
