### ISSUE TITLE
Sometimes TypeScript cannot infer from curried instances

### ISSUE THREAD

**Issue by gcanti** [gcanti/fp-ts#316]
Repro

```ts
import { semigroupString } from 'fp-ts/lib/Semigroup'
import { getApplicative } from 'fp-ts/lib/Validation'
import { liftA2 } from 'fp-ts/lib/Apply'

// F: Applicative2C<"Validation", string>
const F = getApplicative(semigroupString)

const f = liftA2(F) // error: Argument of type 'Applicative2C<"Validation", string>' is not assignable to parameter of type 'Apply<"Validation">'

const f2 = liftA2<'Validation', string>(F) // TypeScript cannot infer 'Validation', string here
```

Proposed fix: add phantom fields to `Functor2C`, `Functor3C`

```diff
export interface Functor2C<F extends URIS2, L> {
  readonly URI: F
+ readonly _L: L
  map: <A, B>(fa: Type2<F, L, A>, f: (a: A) => B) => Type2<F, L, B>
}
```

@sledorze by chance did you hit this during your porting to 1.0.0?

**Comment by sledorze** [comment]
@gcanti no I've not had this issue.
Note, however, that we're just starting to use type classes as we wanted a stable version before doing so.
Also I need to do a proper explanation to the team.

**Comment by gcanti** [comment]
Ok, while we are at it here's some explanation: what I call "curried type classes" are interfaces that describe instances for higher kinded types (with kind => 2) which are able to retain type infos. 

One neat example is `Validation<L, A>`. If we think at higher kinded types as type level functions `L -> A -> Validation<L, A>` then we can also think at curried type level functions: `string -> A -> Validation<string, A>` where `L` is "partially applied". In order to get an instance for `Applicative` for `Validation<L, A>` we must provide an instance of `Semigroup<L>`. However is imperative for type safety to retain that info in the following operations

```ts
getApplicative = <L>(S: Semigroup<L>): Applicative2C<URI, L>
```

Here I'm using `Applicative2C` so that you can't mix and match validations with different `L` types

```ts
// F: Applicative2C<"Validation", string>
const F = getApplicative(semigroupString)
F.ap(success<string, (n: number) => number>((n: number) => n * 2), success<boolean, number>(1)) // static error: Type 'boolean' is not assignable to type 'string'
```

This is a great improvement with respect to `fp-ts@0.6.x`.

Does it make sense?

**Comment by sledorze** [comment]
@gcanti oh yes! It is crystal clear, I now understand the usage of 'C'.
That's great, we have solid foundations here :)
