### ISSUE TITLE
`either.tryCatch`: `onerror` param?

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#323]
`task.tryCatch` has an `onrejected` param. This is useful because it allows you to define the type of the error:

``` ts
export declare const tryCatch: <L, A>(f: Lazy<Promise<A>>, onrejected: (reason: {}) => L) => Task<Either<L, A>>;
```

However, `either.tryCatch` does not have this. Instead, it assumes the error type will be `Error`—but as we know, that's not always the case in JS!

Would you accept a PR to add an `onerror` param to `either.tryCatch`?

**Comment by gcanti** [comment]
@raveclassic I think @OliverJAsh was referring to, for example, throwing a string

```ts
console.log(
  tryCatch(() => {
    throw 'myerror'
  }).fold(e => e.message.trim(), () => 'ok')
) // runtime error: Cannot read property 'trim' of undefined
```

**Comment by raveclassic** [comment]
@gcanti Yeah, I get it. I've also looked at the generated code when extening Error and it seems like TS correctly emits call to `setPrototypeOf`, so I think it's safe to check `e instanceof Error`

**Comment by raveclassic** [comment]
accidentaly closed, sorry, reopening

**Comment by raveclassic** [comment]
type refinement is done in #325

**Comment by OliverJAsh** [comment]
I like the idea of refining the type generally as in #325, but I don't know how useful this is in practice. Often, only you know how to refine the type when wrapping a specific function in `tryCatch`. For example, if a non-`Error` object is thrown, you might want to do some duck typing and then extract properties from it:

``` js
tryCatch(() => myFn(), thrown => {
  if ('statusCode' in thrown) {
    return new Error(`Bad response: ${thrown.statusCode});
  } else if (thrown instanceof Error) {
    return thrown;
  } else {
    return new Error('Unexpected error');
  }
});
```

Currently, we try to stringify all thrown values, which may result in `[object Object]` :-(

**Comment by raveclassic** [comment]
@OliverJAsh How can type-checker be sure about `thrown` type? You can declare any type there which will lead to runtime error.

**Comment by OliverJAsh** [comment]
It's not completely safe, but you can use user-defined type guards:

``` ts
type ObjectWithStatusCode = { statusCode: number }
const thrownIsObjectWithStatusCode = (thrown: {}): thrown is ObjectWithStatusCode => typeof thrown === 'object' && 'statusCode' in thrown;

(thrown: {}) => {
  // We'd need to use user-defined type guards here, to refine the type
  if (thrownIsObjectWithStatusCode(thrown)) {
    return new Error(`Bad response: ${thrown.statusCode}`);
  } else if (thrown instanceof Error) {
    return thrown;
  } else {
    return new Error('Unexpected error');
  }
}
```

I'm not sure what other options there are.

**Comment by raveclassic** [comment]
Here's some discussion on what would be a perfect solution: https://github.com/Microsoft/TypeScript/issues/13219

**Comment by raveclassic** [comment]
As a workaround `fp-ts` could add a type argument to `tryCatch` defaulting to `Error` to avoid explicit `{}` as callback's argument type:
```typescript
declare function tryCatch<A, L = Error>(thunk: Lazy<A>): Either<L, A>;
```
This would give proper type-safety but would require declaring both type arguments.

**Comment by gcanti** [comment]
What about

```ts
const toError = (e: {}): Error => {
  if (e instanceof Error) {
    return e
  } else {
    return new Error(String(e))
  }
}

/** @function */
export const tryCatch = <A>(f: Lazy<A>, onerror: (e: {}) => Error = toError): Either<Error, A> => {
  try {
    return right(f())
  } catch (e) {
    return left(onerror(e))
  }
}
```

This is backward compatible, has a handy default (for interop with _sane_ libraries), solves the existing bug and allows for custom refinements

**Comment by OliverJAsh** [comment]
@gcanti I like it

**Comment by raveclassic** [comment]
Since `onerror` is considered optional (#326) this is not a breaking change anymore.

**Comment by OliverJAsh** [comment]
Fixed by https://github.com/gcanti/fp-ts/commit/557eda55052ec6d288455b7827c47e5c4d36824b. Thanks!
