### ISSUE TITLE
Pointfree either map with v1

### ISSUE THREAD

**Issue by davetayls** [gcanti/fp-ts#332]
I have updated to v1 and it looks like I now have to do the following to map an either in a pointfree style (see `eitherMap` below). 

Am I missing something and is there a nicer way to do this?

```typescript
import { compose, curry, flip } from 'fp-ts/lib/function'
import { Either, either, fromNullable } from 'fp-ts/lib/Either'

const concat = (s1: string) => (s2: string) => s1 + s2
const eitherMap = flip(curry(either.map))

export const eitherHello = compose(
  eitherMap(concat('hello ')),
  fromNullable('yo!')
)

console.log(eitherHello(null)) // Left('yo!')
console.log(eitherHello('world!')) // Right('hello world!')
```

**Comment by gcanti** [comment]
@davetayls the following line (from your snippet) gives me an error

```ts
const eitherMap = flip(curry(either.map))
/*
Argument of type '<L, A, B>(fa: Either<L, A>, f: (a: A) => B) => Either<L, B>' is not assignable to parameter of type 'Function9<{}, {}, {}, {}, {}, {}, {}, {}, {}, Either<{}, {}>>'.
  Types of parameters 'fa' and 'a' are incompatible.
    Type '{}' is not assignable to type 'Either<{}, {}>'.
      Type '{}' is not assignable to type 'Right<{}, {}>'.
        Property '_tag' is missing in type '{}'.
*/        
```

**Comment by davetayls** [comment]
@gcanti - it compiles locally in this repo (apart from annoying `Promise` and `Set` errs)

This is my little playground:
https://github.com/davetayls/exploring-fp-ts-series/blob/master/src/pointfree/composing.ts#L30

**Comment by gcanti** [comment]
What's `"configuration"` in your `tsconfig.json`? Shouldn't be `"compilerOptions"`?

**Comment by davetayls** [comment]
ah! how did I not see that, thanks! I'll dig into those errors. Is this the way you would implement this or would it be better if i just create a manual curried `eitherMap` function

**Comment by gcanti** [comment]
The problem is deeper: `compose`, `curry`, `flip`, `pipe`, etc... don't work with polymorphic functions (TypeScript design)

**Comment by davetayls** [comment]
I see, that's a shame. Thanks for looking at this tho

**Comment by martindrq** [comment]
this may be another alternative:

```js
function eitherMmap<L, A, B>(f: (a: A) => B): (fa: Either<L,A>) => Either<L,B>{
    return (fa) => either.map(fa, f);
}

**Comment by dakom** [comment]
is that the recommended approach, and no generic `map()` function?
