### ISSUE TITLE
Using Option (and others) in angular templates

### ISSUE THREAD

**Issue by Superpat** [gcanti/fp-ts#337]
A lot of stuff can go wrong when generating the data for my angular page, and so I'd like to use Options and Results to wrap the data, but I'm confused as to the best way to do this.

I get all my data from an `Observable<Option<{arbitraryObject}>>` What would be the best way to use the data in the wrapped object? 

I'd be able to do this pretty easily in React, but angular has me stomped for now. I know I can use *ngFor on the Observable, but what about the Option?

**Comment by Superpat** [comment]
A quick fix I thought about was writing a function to transform an Option to an Array and use that in the template.

**Comment by mlegenhausen** [comment]
In our projects we use an `option` pipe that simply calls `toUndefined()` on the option value. You can use it as follows:

```ts
import { Pipe, PipeTransform } from '@angular/core';
import { Option } from 'fp-ts/lib/Option';

@Pipe({
  name: 'option'
})
export class OptionPipe implements PipeTransform {
  transform(value: Option<any>): any {
    return value.toUndefined();
  }
}
```

in your templates

```html
<div *ngFor="let ovalue of values$ | async">
  <ng-container *ngIf="ovalue | option as value; else loading">
    {{ value }}
  </ng-container>
  <ng-template #loading>
    Loading...
  </ng-template>
</div>
```

**Comment by Superpat** [comment]
So I must be doing something wrong, because I keep getting a value is null error when transform is called on the observable option.

I have one function that returns an Observable<Option<Object>> and I bind it the exact same way as in your second example. What should that ovalues be ? Right now it's a property of my class and I bind it to my observable function in the constructor.

**Comment by Superpat** [comment]
I can get it to sort of work when I manually subscribe to my observable in the class but for some reason my `<ng-template #loading>` does not show when my option is none and the `<ng-container>` doesnt rerender when it becomes some.

I've tested the state of the option with `console.log`

**Comment by Superpat** [comment]
Nevermind, got the manually subscribed option to work, angular was swallowing an error in one of it's templates.

**Comment by wmaurer** [comment]
There should be nothing stopping you using an `Option` in your template, either with an `Observable` or without. You can call `isSome` to check if it's `Some` or `None`.

Without an `Observable`:

```
    <div *ngIf="myOption.isSome()">
        {{ myOption.value }}
    </div>
```

With an `Observable`:
```
    <div *ngIf="(myOption$ | async).isSome()">
        {{ (myOption$ | async).value }}
    </div>
```

Angular templates are not Typescript of course, so it's not typesafe. Also, accessing the encapsulate value (via `myOption.value`) is not so nice.

I've written a number of structural directives (`ifSome`, `ifNone`, `ifLeft`, `ifRight`) which make this a little bit nicer. I've published them as [ngx-fp-ts](https://github.com/wmaurer/ngx-fp-ts).

**Comment by Superpat** [comment]
It all works now, errors on my side.. 
But that ngx-fp-ts library is cool, I'll check it out.
