### ISSUE TITLE
Question: Why doesn't Task include it's own error handling?

### ISSUE THREAD

**Issue by Emilios1995** [gcanti/fp-ts#340]
I'm aware that you can use TaskEither or EitherT with a Task. But I'm curious what's the reason you decided not to implement Task like in folktale or Fluture, where Task is a binary type (`Task<error, success>`) ?

**Comment by gcanti** [comment]
Because looks more flexible / composable, you can have a `Either` based error handling (`TaskEither`), or a `Option` based error handling (`Task<Option<A>>`), `Task<Validation<L, A>>` etc... or even no error handling at all, not every async computation (necessarily) needs error handling

```ts
// terminal.ts

import { createInterface } from 'readline'
import { Task } from 'fp-ts/lib/Task'

export const getLine: Task<string> = new Task(
  () =>
    new Promise(resolve => {
      const rl = createInterface({
        input: process.stdin,
        output: process.stdout
      })
      rl.question('', answer => {
        rl.close()
        resolve(answer)
      })
    })
)

export const putStrLn = (message: string): Task<void> =>
  new Task(
    () =>
      new Promise(res => {
        res(console.log(message))
      })
  )
```

**Comment by grossbart** [comment]
I added an FAQ entry about this (soon to be merged), so I'll close this issue.
