### ISSUE TITLE
Option's fromNullable() confuses TS

### ISSUE THREAD

**Issue by damncabbage** [gcanti/fp-ts#358]
`Option`'s `fromNullable` has TS thinking the resulting Option's value is possibly equivalent to a `new Some(null)` or `new Some(undefined)`:

```typescript
import { option } from 'fp-ts';

console.log(
  option
    .fromNullable(null) // or undefined
    .map(x => x.toUpperCase())
    //        ^ tsc: TS2531: Object is possibly 'null'.
    //          (or 'undefined', if we have fromNullable(undefined).)
    .fold("default", x => x)
);
// This prints out "default".
```

Everything works as expected when you actually run the code, though.

(Tested on TypeScript 2.7.2, 2.8.)

**Comment by gcanti** [comment]
That's because in this case type of the input is just `null` (instead of `A | null` for some `A`)

```ts
// likely you have something typed like this
declare const x: string | null

console.log(
  option
    .fromNullable(x)
    .map(x => x.toUpperCase())
    .fold('default', x => x)
)
```

alternatively you can add a hint

```ts
console.log(
  option
    .fromNullable<string>(null)
    .map(x => x.toUpperCase())
    .fold('default', x => x)
)
```

**Comment by damncabbage** [comment]
Ah, okay. I'm guessing TypeScript is both too aware (always `null`) and oblivious (not realising the `null` is eliminated via the type guard) to give us a sensible result for this input-is-`null` case.

Thanks for your patience; closing this issue.

**Comment by camsjams** [comment]
In recent code, using TypeScript `v3.7.2` and fp-ts `v2.3.0`

```javascript
declare const x: string | null

console.log(
  option
    .fromNullable(x)
    .map(x => x.toUpperCase())
    .fold('default', x => x)
)
```

Throws a TypeScript warning:
```
Property 'map' does not exist on type 'Option<string>'.
  Property 'map' does not exist on type 'None'.ts(2339)
```

Likewise the error message appears on these code samples too:
https://davetayls.me/blog/2018/05/20/fp-ts-01-working-with-nullable-values

@gcanti @damncabbage any insight here?

**Comment by steida** [comment]
Because you are using fp-ts 2, and your code is for fp-ts 1.

**Comment by camsjams** [comment]
Thanks! Yea after looking through the repo for the last few hours I've figured something major changed.

How would one translate this to fp-ts@2+?

**Comment by steida** [comment]
@camsjams Something like this. Read issues, please.

```
import * as O from 'fp-ts/lib/Option';
import { pipe } from 'fp-ts/lib/pipeable';

return pipe(
    error,
    O.fold(constNull, error => {
      const message = intl.formatMessage(messages[error]);
      return <FormErrorMessage>{message}</FormErrorMessage>;
    }),
  )
```

**Comment by camsjams** [comment]
Thanks @steida that's helpful.

For people that don't want to be fooled by outdate blog posts on Dev.to and the like, please review:
https://github.com/gcanti/fp-ts/pull/881
https://gcanti.github.io/fp-ts/introduction/upgrade-to-v2.html
