### ISSUE TITLE
is one of the goals of fp-ts to have polymorphic functions

### ISSUE THREAD

**Issue by dagda1** [gcanti/fp-ts#359]
is one of the goals of fp-ts to have polymorphic functions?

What I am looking for and what led me here wa a way of being able to have a `concat` function for example like you have for `Semigroup` and be able to  call that at runtime with different types:

```
concat({one: 1, two: 2}, {two: 'two', three: 3})).to.deep.equal({one: 1, two: 'two', three: 3}

concat(append([1,2,3], [4,4,4])).to.deep.equal([1,2,3,4,4,4]);
```

The code is a level above anything I have ever seen before and I am still trying to get my head around the function overloading and curried functions.

Is there any provision for this type of thing in `fp-ts`?

**Comment by gcanti** [comment]
@dagda1 in fp-ts instances are implemented ad static dictionaries (you may wanto to check out [static-land](https://github.com/rpominov/static-land) for an overview). You can define a generic `concat` function which is able to handle several types but you must inject the right dictionary by hand (since AFAIK there's no principled way to do this automatically)

```ts
import { Semigroup, getArraySemigroup, semigroupSum } from 'fp-ts/lib/Semigroup'

// generic concat
const concat = <A>(S: Semigroup<A>): ((x: A, y: A) => A) => S.concat

import { StrMap, getMonoid } from 'fp-ts/lib/StrMap'

console.log(
  concat(getMonoid<number | string>())(
    new StrMap({
      one: 1,
      two: 2
    }),
    new StrMap({
      two: 'two',
      three: 3
    })
  )
) // StrMap { value: { one: 1, two: 'two', three: 3 } }

console.log(concat(getArraySemigroup<number>())([1, 2, 3], [4, 4, 4])) // [ 1, 2, 3, 4, 4, 4 ]
```

**Comment by dagda1** [comment]
This is great and I think fp-ts looks utterly amazing.

I wonder if you could explain how the function overloading explains in `Foldable` [here](https://github.com/gcanti/fp-ts/blob/283fb67bc6182132c6a04a7719d0e4a96d5fcae2/src/Foldable.ts#L116).

It is not obvious to me what the differences are between `Foldable3`, `Type3` etc. , I'd love to understand better how this works.

**Comment by gcanti** [comment]
@dagda1 take a look at [How HKT, URI2HKT, URIS and Type work](https://github.com/gcanti/fp-ts/blob/master/docs/HKT.md)

**Comment by dagda1** [comment]
many thanks
