### ISSUE TITLE
How to unbox lifted TaskEither

### ISSUE THREAD

**Issue by davetayls** [gcanti/fp-ts#367]
I'm using `TaskEither` with `liftA2` but my resulting function also returns a `TaskEither` which leads to me having to much nesting `TaskEither<Error, TaskEither<Error, value>>`

How would I code this so that I end up with a single `TaskEither`, I've tried `chain` but that doesn't solve the left side which doesn't error when the inner task either errors.

```typescript
const doSomething = (a: number) => (b: number) => taskEither.of(a + b)
const liftedSomething = liftA2(taskEither)(doSomething)
const calcSomething = liftedSomething(taskEither.of(1))(taskEither.of(2))

calcSomething
  .fold(
          (e) => console.log('left', e),
          (d) => console.log('right', d)  
  )
  .run()
```

This logs

```
right TaskEither { value: new Task(undefined) }
```

But I'm wanting

```
right 3
```

Also, if an error happens inside `doSomething` so that the return value is a `taskEither` `Left` then it still will log 'right'

Any help would be gratefully received!

**Comment by gcanti** [comment]
> But I'm wanting `right 3`

@davetayls looks like you may want to define `doSomething` as

```ts
const doSomething = (a: number) => (b: number) => a + b
```

instead of

```ts
const doSomething = (a: number) => (b: number) => taskEither.of(a + b)
```

**Comment by davetayls** [comment]
thanks @gcanti - this was simplified, `doSomething` is more like. Maybe this example is more useful

```typescript
const doSomething = (a: number) => (b: number) => doSomeOtherAsyncTask(a, b)
```

So it doesn't have a simple result and could also fail

**Comment by gcanti** [comment]
You could flatten the result (if the left types are compatible)

```ts
import { flatten } from 'fp-ts/lib/Chain'

const calcSomething = flatten(taskEither)(liftedSomething(taskEither.of(1))(taskEither.of(2)))
```

or simply

```ts
const calcSomething = liftedSomething(taskEither.of(1))(taskEither.of(2)).chain(identity)
```

**Comment by davetayls** [comment]
Yes, `flatten` is exactly what I was looking for, thanks @gcanti 👍
