### ISSUE TITLE
get (general) Ordering for products

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts#371]
I think the main reason it does not exist yet (but passing via tuples) is that product entries are unordered.
However we may consider having an Ord defined on the record keys and have a easier/general solution to that.
@gcanti ok with that?

**Comment by gcanti** [comment]
Not sure how it would be useful, usually you define an order based on a specific field

```ts
interface Person {
  name: string
  age: number
}

const byAge: Ord<Person> = contramap(p => p.age, ordNumber)

const byName: Ord<Person> = contramap(
  p => p.name,
  ordString
)
```

or a group of fields with a priority

```ts
const byAgeAndThenByName = fold(getSemigroup<Person>())(byAge, [byName])
```

**Comment by sledorze** [comment]
@gcanti I'm mainly concerned with the cost of computation.
For instance, relying on Ordering being a semigroup is the way to go but I'm not sure about the runtime cost (maybe I've become paranoid lately, I should do proper benchmark).
Closing for now
