### ISSUE TITLE
Deserialization for webworkers

### ISSUE THREAD

**Issue by pbadenski** [gcanti/fp-ts#374]
When transferring data between webworkers classes are converted to objects. After the transfer it is then necessary to "reassociate" data with methods. This can likely only be supported for selected monads (although I never used IO and Task, I understand that they couldn't be transferred as messages).

Minimal naive implementation for Either:
```javascript
var fpTs = require("fp-ts")

const serialized = JSON.parse(JSON.stringify(fpTs.either.left(1)));
// serialized == Object {_tag: "Left", value: 1}

let deserialized;
switch (e._tag) {
  case "Left":
    deserialized = fpTs.either.left(e.value);
    // deserialized == Left {_tag: "Left", value: 1}
  case "Right":
    deserialized = fpTs.either.right(e.value);
}
```

From my perspective deserialization would ideally support any object and convert it recursively to monad where possible. For instance this object:
```javascript
{ _tag: "Left", value: { _tag: "Some", value: { a: { _tag: "None" }, b: 2 } } }
````

**Comment by gcanti** [comment]
You may want to check out [io-ts](https://github.com/gcanti/io-ts) and [io-ts-types](https://github.com/gcanti/io-ts-types)

Example

```ts
import { Option, some, none } from 'fp-ts/lib/Option'
import { left, Either } from 'fp-ts/lib/Either'

// let's say we want to transfer this 
const x: Either<Option<Option<number>>, string> = left(some(none))

import * as t from 'io-ts'
import { createOptionFromNullable } from 'io-ts-types/lib/fp-ts/createOptionFromNullable'
import { createEitherFromJSON } from 'io-ts-types/lib/fp-ts/createEitherFromJSON'

// a suitable runtime type (i.e. a decoder / encoder) for `Either<Option<Option<number>>, string>`
const T = createEitherFromJSON(createOptionFromNullable(createOptionFromNullable(t.number)), t.string)

// encoding
console.log(T.encode(x)) // { type: 'Left', value: null }

// decoding
console.log(T.decode({ type: 'Left', value: null }))
/*
right({
  "value": {
    "value": {
      "_tag": "None"
    },
    "_tag": "Some"
  },
  "_tag": "Left"
})
*/
```

**Comment by pbadenski** [comment]
Will have a look. This looks good enough for my current use case. One limitation I see it requires describing deserializer. I imagine in a perfect world I could give it an object and by looking at it's structure it would "just figure it out".

For the sake of completeness: @JAForbes pointed me to this: https://gitlab.com/JAForbes/static-sum-type

**Comment by gcanti** [comment]
> give it an object and by looking at it's structure it would "just figure it out"

In general is not possible

```ts
const T = createEitherFromJSON(createOptionFromNullable(createOptionFromNullable(t.number)), t.string)
const T2 = createEitherFromJSON(createOptionFromNullable(t.number), t.string)

console.log(T.decode({ type: 'Left', value: null }))
/*
right({
  "value": {
    "value": {
      "_tag": "None"
    },
    "_tag": "Some"
  },
  "_tag": "Left"
})
*/
console.log(T2.decode({ type: 'Left', value: null }))
/*
right({
  "value": {
    "_tag": "None"
  },
  "_tag": "Left"
})
*/
```

Both `T` and `T2` are able to decode `{ type: 'Left', value: null }` but you end up with different data structures

**Comment by grossbart** [comment]
I added an FAQ entry in the docs about this (soon to be merged), so I'm closing this issue.
