### ISSUE TITLE
Sequence `TaskEither`s of different Right types

### ISSUE THREAD

**Issue by davetayls** [gcanti/fp-ts#375]
I have a series of `TaskEither`s and I want to run them in parallel and chain the result. I've been using `sequence` which seems to be working well until they return different types.

I have also tried using `lift` but because I ended up with nesting `TaskEither`s and the code looked pretty unreadable.

This code looks nice but TypeScript is complaining about the `TaskEither`s returning different types.

Here is a simplified example. The `TaskEither`s would actually be DB or API calls and return object types rather than simple types.

```typescript
const teString = of('You are')
const teNumber = of(1)
sequence(taskEither, array)([
  teString,
  teNumber
]).chain(([greeting, age]) => {
  return of(`${greeting} ${age}`)
})
```

Here is the error I get

```
Error:(55, 29) TS2345: Argument of type '(TaskEither<{}, string> | TaskEither<{}, number>)[]' is not assignable to parameter of type 'TaskEither<{}, string>[]'.
  Type 'TaskEither<{}, string> | TaskEither<{}, number>' is not assignable to type 'TaskEither<{}, string>'.
    Type 'TaskEither<{}, number>' is not assignable to type 'TaskEither<{}, string>'.
      Type 'number' is not assignable to type 'string'.
```

The nice thing about using sequence is that we can pass in as many async values as we need, and it's easy to understand. Is there a similar option where the resulting types aren't expected to be the same?

**Comment by gcanti** [comment]
I think that the cheapest solution is @raveclassic 's [`combine`](https://github.com/gcanti/fp-ts/issues/322#issuecomment-366228609)

```ts
const sequenceTaskEitherArray = sequence(taskEither, array)

export function mult<L, A>(a: TaskEither<L, A>): TaskEither<L, [A]>
// this is the standard Monoidal mult https://github.com/gcanti/fp-ts/blob/78917aada5d30f177090141202a3dff7fcd0c77b/src/Monoidal.ts#L15
export function mult<L, A, B>(a: TaskEither<L, A>, b: TaskEither<L, B>): TaskEither<L, [A, B]>
export function mult<L, A, B, C>(
  a: TaskEither<L, A>,
  b: TaskEither<L, B>,
  c: TaskEither<L, C>
): TaskEither<L, [A, B, C]>
export function mult<L, A, B, C, D>(
  a: TaskEither<L, A>,
  b: TaskEither<L, B>,
  c: TaskEither<L, C>,
  d: TaskEither<L, D>
): TaskEither<L, [A, B, C, D]>
export function mult<L, A>(...list: TaskEither<L, A>[]): TaskEither<L, A[]> {
  return sequenceTaskEitherArray(list)
}

// usage

const teString = taskEither.of('You are')
const teNumber = taskEither.of(1)
const result = mult(teString, teNumber).map(([greeting, age]) => `${greeting} ${age}`)
```

**Comment by raveclassic** [comment]
Yeah, I'm using the same approach with [RemoteData](https://github.com/devex-web-frontend/remote-data-ts/blob/master/src/remote-data.ts#L580)

**Comment by davetayls** [comment]
Thanks @gcanti - this is working perfectly 👍 - in the middle of the v1 upgrade across our repos!
