### ISSUE TITLE
Question: getting maximal type safety when using Option

### ISSUE THREAD

**Issue by boaz-chen** [gcanti/fp-ts#377]
Hi there,

I recently encountered this very nice library mainly looking for a solution to avoid working with null/undefined as much as possible, but also for its other fp capabilities. So I decided to start by using Option as much as possible in my project.

I was a little disappointed to find out that even when using Option, I don't get full "protection" from the compiler. For example, when taking this code:

```
interface IData {
    amount: number;
}

function f(data: IData): void {
    if (data) {

    }
}
```

and converting it to this code:

```
function fWithOption(data: Option<IData>): void {
    if (data) { // I want the compiler to shout at me here

    }
}
```

I didn't get any compilation warning/error for forgetting to change the `if (data)` to `if (data.isSome())`.

Is there a way to achieve that in TypeScript? I did turn on the "strict" and "strictNullChecks".

Thanks,
Boaz

**Comment by raveclassic** [comment]
Well, it's JavaScript with its implicit casts. Here it casts your `data` object to `boolean` and it's a valid condition from the perspective of the language.

General recommendation though is to stop using such `if`s and other imperative instructions and replace them with operations on data instead.

**Comment by gcanti** [comment]
@boaz-chen you can use this tslint rule https://palantir.github.io/tslint/rules/strict-boolean-expressions/

**Comment by boaz-chen** [comment]
Thanks guys.
