### ISSUE TITLE
Can't find Flow definition files

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/fp-ts#388]
I seem to recall that Flow definitions had been added here last year. Now I can't find them. Were they removed?

Or are they being generated from TypeScript definitions?

**Comment by raveclassic** [comment]
Yeah, flow support was [dropped](https://github.com/gcanti/fp-ts/issues/290#issuecomment-359801053)

**Comment by volkanunsal** [comment]
Any plans to add the flow types to flow-typed? I've been waiting for months to use this in a project, and I finally got a chance. I guess I can downgrade and keep using 0.6.8.

**Comment by grossbart** [comment]
I added an FAQ section to the documentation (soon to be merged) with a short statement about `fp-ts` not supporting Flow types anymore, so I will close this issue for now.
