### ISSUE TITLE
A question about how to approach a tree traversal where the types are not known ahead of time

### ISSUE THREAD

**Issue by dagda1** [gcanti/fp-ts#395]
I am interested to know how to approach the hypothetical situation of say you are parsing a tree of data and each parent could contain an array or and an object.

What I want to do is parse the tree and use something like Monoid's concat to combine all the data into a data structure.

I am pretty unsure how to approach this from a strictly typed perspective.  How would I know which function from Semigroup.ts to call when that decision is made at runtime?  Is there a way without using conditional logic to get `getArraySemigroup` or `getRecordSemigroup` or whatever?

Or if you look at `fold` in `Monoid`:

`assert.deepEqual(fold(array, monoidString)(['a', 'b', 'c']), 'abc')`

You really need to know ahead of time what type of array you are dealing with.

**Comment by raveclassic** [comment]
You could implement monoid for any type if you know how to concat it and what's the starting element:
```typescript
type Data = object | Array<any>;
const monoid: Monoid<Data> = {
  concat: a => b => {
    //here you need to check the types of a and b at runtime (statically the type is Data)
    //and define the logic of concatenation of objects and arrays
    //for example:
    return JSON.stringify(a) + JSON.stringify(b);
  },
  //neutral element
  empty: () => '' //string for stringified JSON concatenation
}
```

Then you can just use `fold` as usual: `fold(array, monoid)([[1, 2, 3], {foo: 'bar'}]);

**Comment by dagda1** [comment]
@raveclassic thank you for that answer.  One thing I do not understand is if I want fold to work on objects and arrays, then why am I passing the array structure as the first argument?

`fold(array, monoidData)([[1, 2, 3], {foo: 'bar'}])`

**Comment by raveclassic** [comment]
Actually you don't need to. If your tree structure has a [Foldable](https://github.com/gcanti/fp-ts/blob/8a66b79ac870f7e9543b2f5db4dd9e05fcd816d1/src/Foldable.ts#L14) implementation you can pass its instance to [fold](https://github.com/gcanti/fp-ts/blob/8a66b79ac870f7e9543b2f5db4dd9e05fcd816d1/src/Foldable.ts#L149) as the first argument:
```typescript
const URI = 'Tree'
type Tree<A> = {} //define your Tree structure for items of type A
type Data = object | Array<any> //define your Data type
declare const tree: Foldable<URI> //define `reduce` implementation for your Tree - this is the instance of Foldable for Tree
declare const monoidData: Monoid<Data> //define `concat` and `empty` for your Data - this is the instance of Monoid for Data
declare const foo: Tree<Data> //single tree
//fold is imported from Foldable
const result = fold(tree, monoidData)(foo) //this is result based on reduce implementation for Tree and concat/empty implementation for Data
```

**Comment by dagda1** [comment]
Thank you again, one last question, where does `URI` come from?  I've been scratching my head on this one, for me this would be the higher kinded type with `A` being the type parameter or ground type.

Where does the name `URI` come from?

**Comment by raveclassic** [comment]
You're welcome :)
URI describes an opaque type for a trick called [light-weight higher kinded polymorphism](https://www.cl.cam.ac.uk/~jdy22/papers/lightweight-higher-kinded-polymorphism.pdf). It is defined as both a constant and a string literal type and used as a "key" in HKT "storage". You can  also check the [docs](https://github.com/gcanti/fp-ts/blob/master/docs/HKT.md)
