### ISSUE TITLE
Why Task has only one type parameter?

### ISSUE THREAD

**Issue by raqystyle** [gcanti/fp-ts#406]
I am a bit confused why Task has only type argument. I think it would useful if it had two arguments: one for error, another for result. Maybe (although, definitely) I am missing something. Is there an alternative to describe an async operation and types for both cases?

**Comment by gcanti** [comment]
https://github.com/gcanti/fp-ts/issues/340

**Comment by raqystyle** [comment]
@gcanti  thanks!
