### ISSUE TITLE
Move to an Org

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts#414]
*-ts libraries are very Great and represent a lot of value.
However, having all those wonderful libs under a personal account vs an organisation may refrain some companies from using those.

@gcanti what's your stance on that subject?

**Comment by gcanti** [comment]
Does it really matter? They are all on npm and all code is MIT-licensed. 
As a counterexample, [tcomb](https://github.com/gcanti/tcomb) is still on my account and hit 700.000 downloads per month.

I'm fine with the current situation

**Comment by sledorze** [comment]
Ok thanks for giving your stance on it
