### ISSUE TITLE
Question: Generalization of combine

### ISSUE THREAD

**Issue by raveclassic** [gcanti/fp-ts#421]
Currently we can use `sequence(someApplicativeInstance, array)` to turn a list of that applicatives inside out. But its signature requires inner values of that applicatives to be of the same type, so that you can't write:
```typescript
sequence(option, array)([some(1), some('2')]);
sequence(either, array)([right(1), right('2')]);
sequence(remoteData, array)([success('123'), success(123)]);
```
The only way is to write [a bunch of overloads](https://github.com/gcanti/fp-ts/issues/322#issuecomment-366228609).

So the question is if we can generalize it for a list of any applicatives without touching `sequence`? The closest HKT I've found is `Monoidal` but it's limited only to two arguments. (besides I think it may be  theoretically incorrect to use it, I'm not very strong with the theory).
Another way would be to add `combine` to `Array` module generalizing to `Applicative` and adding those overloads there. But it will require to add 1-10 overloads for each HKT, HKT2 etc.

UPD: Referencing Monoidal I mean I don't know if it is legal to change mult to accept a spread or a list instead of only two args.

**Comment by raveclassic** [comment]
@gcanti Any ideas? I'd like to know opinion on this

**Comment by gcanti** [comment]
I didn't comment because I have no smart ideas besides the bunch of overloadings thing.

Theoretically the abstraction which allows you to combine effects with multiple types is `Applicative`, via `liftAn` functions or equivalent.
`Monoidal` is an alternative and equivalent definition of `Applicative`

**Comment by raveclassic** [comment]
So what do you think fits best? Adding separate `combine` to `Array` module with nesessary overloads or changing `Monoidal`'s `mult` to accept a spread or a list of values instead of only two arguments? Or is it out of scope of `fp-ts` at all?

**Comment by gcanti** [comment]
I think that `combine` should be added to `Apply`. 

Its implementation could use `liftAn`

```ts
interface Combine<F> {
  <A, B>(fa: HKT<F, A>, fb: HKT<F, B>): HKT<F, [A, B]>
  <A, B, C>(fa: HKT<F, A>, fb: HKT<F, B>, fc: HKT<F, C>): HKT<F, [A, B, C]>
  <A, B, C, D>(fa: HKT<F, A>, fb: HKT<F, B>, fc: HKT<F, C>, fd: HKT<F, D>): HKT<F, [A, B, C, D]>
}

interface Combine1<F extends URIS> {
  <A, B>(fa: Type<F, A>, fb: Type<F, B>): Type<F, [A, B]>
  <A, B, C>(fa: Type<F, A>, fb: Type<F, B>, fc: Type<F, C>): Type<F, [A, B, C]>
  <A, B, C, D>(fa: Type<F, A>, fb: Type<F, B>, fc: Type<F, C>, fd: Type<F, D>): Type<F, [A, B, C, D]>
}

// more overloadings here...
export function combine<F extends URIS>(F: Apply1<F>): Combine1<F>
export function combine<F>(F: Apply<F>): Combine<F>
export function combine<F>(F: Apply<F>): <A>(...args: Array<HKT<F, A>>) => HKT<F, Array<A>> {
  let l2: any
  let l3: any
  let l4: any
  return (...args): any => {
    switch (args.length) {
      case 2:
        l2 = l2 || liftA2(F)(a => b => [a, b])
        return l2(args[0])(args[1])
      case 3:
        l3 = l3 || liftA3(F)(a => b => c => [a, b, c])
        return l3(args[0])(args[1])(args[2])
      default:
        l4 = l4 || liftA4(F)(a => b => c => d => [a, b, c, d])
        return l4(args[0])(args[1])(args[2])(args[3])
    }
  }
}
```

**Comment by raveclassic** [comment]
Yeah, I'm writing exactly the same typings right now :) 
The only thing I don't get in your version is how N arguments are handled. There's no `liftAN`. 
I'm using  `Array`'s `traverse` with `identity` (same as `sequence`)

**Comment by raveclassic** [comment]
I've opened [PR](https://github.com/gcanti/fp-ts/pull/425), take a look

**Comment by gcanti** [comment]
I mean `liftA`(n) where `n = 2, 3, 4`

> I've opened PR, take a look

As stated above, I think that `combine` should be defined in the `Apply` module as it takes an `Apply` instance (`traverse` requires an `Applicative`)

**Comment by raveclassic** [comment]
What about `n >= 5`? 
Yeah we can still use `sequence(applicative, array)` but then there're two different APIs for `n < 5` and `n >= 5` which seems to be inconsistent.

**Comment by raveclassic** [comment]
> combine handles tuples, not arrays.

Why not? Tuple is a particular case of array, isn't it? Even more it's more like a refinement of an array which falls backs to an array of one type.

> If you need to handle up to 5 arguments we can add liftA5.
The number of arguments is capped by the number of corresponding overloadings, we can't handle infinite tuples.

Agree, but what if I need 6? Adding overloading seems more lightweight than adding functions.

> AFAIK you can't, the implementation of traverse uses of

I mean't that if I have an array of 5 items I'll use sequence and when lte 4 - combine. Rather confusing.

**Comment by gcanti** [comment]
> Tuple is a particular case of array, isn't it?

I'd say no, they are pretty different type-wise. 
Actually we are discussing `combine` *because* they are so different.

```ts
// requires Applicative, handles arrays
sequence: Array<F<A>> -> F<Array<A>>
```

```ts
// requires Apply, handles tuples (from 2 up to 4 at the moment)
combine: [F<A>, F<B>] -> F<[A, B]>
combine: [F<A>, F<B>, F<C>] -> F<[A, B, C]>
combine: [F<A>, F<B>, F<C>, F<D>] -> F<[A, B, C, D]>
```

**Comment by gcanti** [comment]
Also `combine` is too generic, we could call this function `sequenceT`

Reference: https://hackage.haskell.org/package/tuple-0.3.0.2/docs/src/Data-Tuple-Sequence.html#SequenceT

**Comment by gcanti** [comment]
> Adding type overloadings seems more lightweight than adding functions

What about this implementation? It doesn't depend on `liftA`(n) so we can just add more overloadings when needed

```ts
// must be exported, now is private
import { curried } from '../src/function'

interface SequenceT<F> {
  <A, B>(fa: HKT<F, A>, fb: HKT<F, B>): HKT<F, [A, B]>
  <A, B, C>(fa: HKT<F, A>, fb: HKT<F, B>, fc: HKT<F, C>): HKT<F, [A, B, C]>
  <A, B, C, D>(fa: HKT<F, A>, fb: HKT<F, B>, fc: HKT<F, C>, fd: HKT<F, D>): HKT<F, [A, B, C, D]>
}

interface SequenceT1<F extends URIS> {
  <A, B>(fa: Type<F, A>, fb: Type<F, B>): Type<F, [A, B]>
  <A, B, C>(fa: Type<F, A>, fb: Type<F, B>, fc: Type<F, C>): Type<F, [A, B, C]>
  <A, B, C, D>(fa: Type<F, A>, fb: Type<F, B>, fc: Type<F, C>, fd: Type<F, D>): Type<F, [A, B, C, D]>
}

const tupleConstructors: { [key: string]: (a: any) => any } = {}

export function sequenceT<F extends URIS>(F: Apply1<F>): SequenceT1<F>
export function sequenceT<F>(F: Apply<F>): SequenceT<F>
export function sequenceT<F>(F: Apply<F>): (...args: Array<HKT<F, any>>) => HKT<F, Array<any>> {
  return (...args) => {
    const len = args.length - 1
    const f =
      tupleConstructors[len] || (tupleConstructors[len] = curried((...args: Array<any>): Array<any> => args, len, []))
    let r = F.map(args[len], f)
    for (let i = len - 1; i >= 0; i--) {
      r = F.ap(r, args[i])
    }
    return r
  }
}
```

**Comment by raveclassic** [comment]
> What about this implementation? It doesn't depend on liftA(n) so we can just add more overloadings when needed

Nice!

I always wonder how many useful things one can find on hackage :) I'll update PR soon

**Comment by raveclassic** [comment]
Seems like `sequenceT` does not support empty tuples...
That's why I used `Applicative` with `of`

**Comment by raveclassic** [comment]
@gcanti Can we move `sequenceT` to `Applicative`, change constraint and just return `F.of([])` in case when `...args` is an empty array?

**Comment by gcanti** [comment]
Not sure I'm follow, you can't even declare an empty tuple in TypeScript. 
Actually `sequenceT` doesn't make much sense also for tuples with length `1`

```ts
// start from tuple 2
interface SequenceT<F> {
  <A, B>(fa: HKT<F, A>, fb: HKT<F, B>): HKT<F, [A, B]>
  <A, B, C>(fa: HKT<F, A>, fb: HKT<F, B>, fc: HKT<F, C>): HKT<F, [A, B, C]>
  <A, B, C, D>(fa: HKT<F, A>, fb: HKT<F, B>, fc: HKT<F, C>, fd: HKT<F, D>): HKT<F, [A, B, C, D]>
}

export function sequenceT<F>(F: Apply<F>): SequenceT<F>
// signature with Array is not exposed, it's just an implementation detail
export function sequenceT<F>(F: Apply<F>): (...args: Array<HKT<F, any>>) => HKT<F, Array<any>> {
  ...
}
```

**Comment by raveclassic** [comment]
> signature with Array is not exposed, it's just an implementation detail

My bad, that happened because I did expose it.
I've updated PR

**Comment by raveclassic** [comment]
Note that I had to reverse the arguments in your implementation for tests to pass

**Comment by raveclassic** [comment]
fixed in https://github.com/gcanti/fp-ts/pull/425
