### ISSUE TITLE
Error when assiging `Identity<string>` to type `Functor<string>`

### ISSUE THREAD

**Issue by orlandohohmeier** [gcanti/fp-ts#428]
**Do you want to request a _feature_ or report a _bug_?**

I believe it's a bug...

**What is the current behavior?**

I get the following error when trying to assign an `Identity<string>` to a variable typed as `Functor<string>` which given that Identity _implements_ the Functor type should work just fine.

```
TS2322: Type 'Identity<string>' is not assignable to type 'Functor<string>'.
Property 'URI' is missing in type 'Identity<string>'.
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

```ts
function f(a: Functor<string>) {
  return a;
}

const foo: Functor<string> = new Identity("bar");
const baz: Functor<string> = f(new Identity("bar"));
```
https://codesandbox.io/s/xrwvy901yq

Please note that this is not only an issue with `Identity` but most probably a general issues with all HKT.

**What is the expected behavior?**

I would expect that it's possible to assign an `Identity<T>` to a variable or argument typed as `Functor<T>`  as I otherwise have to tie my implementation to specific _lower_ level types. 

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**

I'm using version `1.4.1` with TypeScript `2.8.3`. I can't tell whether it worked in earlier versions.

**Comment by gcanti** [comment]
`Identity` is not a `Functor` (*), it's a data structure which admits a `Functor` instance, which is contained in the named export `identity` https://github.com/gcanti/fp-ts/blob/3e9fdeb9faf804676de1268a6fb6b510a6e4344b/src/Identity.ts#L123

(*) theoretically, types/data structures **are** not functors, can **have** a functor instance

**Comment by gcanti** [comment]
In general instances must be passed to functions manually, see for example the `lift` function in the `Functor` module

https://github.com/gcanti/fp-ts/blob/3e9fdeb9faf804676de1268a6fb6b510a6e4344b/src/Functor.ts#L108

Have you got a real use case we can discuss?

**Comment by orlandohohmeier** [comment]
Thanks for the pointer! I was trying to implement a _lens_ type as follows:  

```ts 
export type Lens<S, T, A, B> = (f: (value: A) => Functor<B>) => (subject: S) => Functor<T>
```

The first argument is a function (e.g. `Applicative.of`) that must return a data structure which admits a `Functor` so that I can map over the value. This allows me to either pass `Identity` for setting and  `Const` for getting, see the example usage for details.

## Example

```ts
export function view<S, A>(lens: Lens<S, A, A, A>, subject: S): A {
  return lens((value: A) => new Const<A, any>(value))(subject).fold(identity);
}

export function over<S, A, B>(
  lens: Lens<S, S, A, B>,
  modifier: (value: A) => B,
  subject: S
) {
  return (lens((value: A) => new Identity<B>(modifier(value)))(
    subject
  ) as Identity<S>).fold(identity);
}

export function set<S, B>(lens: Lens<S, S, B, B>, value: B, subject: S) {
  return over(lens, constant(value), subject);
}

// Create an array index lens
export function index<S extends any[], T extends any[]>(
  i: number
): Lens<S, S, any, any> {
  return f => subject => {
    return f(subject[i]).map(value => {
      const clone = subject.slice(0);
      clone.splice(i, 1, value);
      return clone;
    });
  };
}


console.log(
  view(
    compose(index(1), index(0)),
    [["foo", "bar", "baz"],["a","b", "c"]]
  )
);

console.log(
  Lens.over(
    compose(index(0), index(1)),
    (s:string) => s.toUpperCase(),
    [["foo", "bar", "baz"],["a","b", "c"]]
  )
);
```
