### ISSUE TITLE
Either: get / extract / unbox

### ISSUE THREAD

**Issue by mustafaekim** [gcanti/fp-ts#429]
Hi, I'am quite new to FP and as far as I've read, extracting value from any type of monad is not favored. That's ok in the long run, however, for a smooth transition I am expecting to be able to extract the value from the Either monad. Can't I, really ? :)

**Comment by gcanti** [comment]
You can't, you should use `fold`, `getOrElse` or `getOrElseL` which are safe.

However you can easily define your own unsafe `get` 

```ts
const get = <L, A>(fa: Either<L, A>): A =>
  fa.getOrElseL(() => {
    throw new Error('get called on Left')
  })
```

(I don't recommend it though)

**Comment by mustafaekim** [comment]
Oh ok. So when do you use isRight() ? Even if you become sure that it is a right, you cant extract the value

Is there any easy-to-follow code examples, like a tutorial or a small project I can understand the mindset?

**Comment by gcanti** [comment]
`isRight` (both the method and the function) is defined as a custom type guard so you can do

```ts
declare const fa: Either<string, number>
if (fa.isRight()) {
  // const n: number
  const n = fa.value
}
```

since TypeScript is able to refine `fa`. IMO it must be used sparingly because that way you are not forced to handle the failing case.

**Comment by mustafaekim** [comment]
Oh that's interesting, if isRight() returns true, value property is just there. 

Well, I've read so many articles/books that favor that to reach the boxed value directly, so I will try my best. Thanks

**Comment by benjaminbollen** [comment]
`.value` no longer exists in `Right<T>`; other ways to unpack the value?

**Comment by seyfer** [comment]
Note: the first answer from @gcanti above can be used in `pipe` like

```
const getSomeValue = pipe(
 yourFunctionWhichProduceEither(),
 //or you had a type change, lets say from IOEither to TaskEither, then you run this Task and got Either<A,B>
 getOrElseL(() => {throw new Error('get called on Left')})
);

//...

const value = getSomeValue();
```

something like that
