### ISSUE TITLE
Distribute some types from /examples

### ISSUE THREAD

**Issue by leemhenson** [gcanti/fp-ts#446]
I've just started using `ReaderTaskEither` and have had to copy-pasta it into my project. It seems like a pretty reasonable thing to include in the normal distribution, and I guess several others in `/examples` could have that case made for them too. Is there a particular reason why they are kept out?

**Comment by gcanti** [comment]
I agree on `ReaderTaskEither` (see https://github.com/gcanti/fp-ts/issues/251)

**Comment by leemhenson** [comment]
i'll knock up a pr

**Comment by leemhenson** [comment]
@gcanti I basically _lifted_ the reader and taskEither tests 😉
