### ISSUE TITLE
Is there a more elegant way to write this?

### ISSUE THREAD

**Issue by boaz-chen** [gcanti/fp-ts#461]
Hey,

I have the following function which validates a contract and returns a model off of it. I would like to return an informative error string in case the conversion failed due to unexpected values in the contract.

Currently I have the following:

```
type Color = 'Red' | 'Green' | 'Blue'

interface PersonContract {
    name: string
    favoriteColor: string
}

interface Person {
    name: string,
    favoriteColor: Color
}

function personFromContract(contract: PersonContract): Either<string, Person> {
    return fromNullable<string>('No contract was provided')(contract)
        .chain(person => {
            if (person.favoriteColor !== 'Red' &&
                person.favoriteColor !== 'Green' &&
                person.favoriteColor !== 'Blue') {
                return left(`Unexpected color in contract: ${person.favoriteColor}`)
            }

            return right<string, Person>({
                name: person.name,
                favoriteColor: person.favoriteColor
            })
        })
}
```

But I feel that the following would be a more appropriate use of Either's functions.

```
function personFromContract(contract: PersonContract): Either<string, Person> {
    return fromNullable('No contract was provided')(contract)
        .filterOrElse(person => !(person.favoriteColor !== 'Red' &&
            person.favoriteColor !== 'Green' &&
            person.favoriteColor !== 'Blue'),
            `Unexpected color in contract: no color to refer to :(`)
        .map<Person>(person => ({
            name: person.name,
            favoriteColor: person.favoriteColor as Color
        }))
}
```

Is there a way to avoid the explicit if and return right/left in the first piece of code and still keep the value available for the error string? It kind of reminds me RxJs where the Observable has a `do ` operator for side effects, where you could stash a temporary value in the closure and then use it later, but I'm not sure I like that approach if there's a more functional approach.

Thanks,
Boaz

**Comment by mlegenhausen** [comment]
I would recommend `io-ts` for this job. It is not only useful for validation of input/output data it can also be used to transform/validate data of similar shape.

So your example can be reduced to

```ts
const Person = t.interface({
  name: t.string,
  favoriteColor: t.union([t.literal('Red'), t.literal('Green'), t.literal('Blue')])
});
type Person = t.TypeOf<typeof Person>;

const personFromContract = (contract: PersonContract): Either<string, Person> => 
  Person.decode(contract).mapLeft(() => `Unexpected color in contract: ${contract.favoriteColor}`);
```

**Comment by sledorze** [comment]
You may use keyof instead of union, better error message and way faster

**Comment by mlegenhausen** [comment]
@sledorze thanks for the hint I adjusted my example.

**Comment by mlegenhausen** [comment]
@boaz-chen I would also recommend to active `strict` mode in your typescript project, cause your `null`-check at the start of the `personFromContract` Function should already be catched by `tsc`.

**Comment by boaz-chen** [comment]
Thanks for the great info guys.

**Comment by gcanti** [comment]
FYI I'm writing a PR which adds a `fromRefinement` function to `Either` in order to simplify the definition of `validateColor`

```ts
// const validateColor: (a: string) => Either<string, Color>
const validateColor = fromRefinement(isColor, s => `Unexpected color in contract: ${s}`)
```
