### ISSUE TITLE
Using of Free monad with Monad2/Monad3 types

### ISSUE THREAD

**Issue by Iorg** [gcanti/fp-ts#470]
**Do you want to request a _feature_ or report a _bug_?**
Bug (or misunderstanding some concepts).

**What is the current behavior?**
Currently if we try to use `free.foldFree` function with `Monad2` type (ex. Either) we have the type error (see example below).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**
Consider `examples/Free.ts` from the sources, as an example. Change function `interpretIdentity` to use `Either` type:
```ts
function interpretEither<A>(fa: InstructionF<A>): Either<string, A> {
  switch (fa._tag) {
    case 'Forward':
      return either.of(fa.more(computation.forward(fa.position, fa.length)))
    case 'Backward':
      return either.of(fa.more(computation.backward(fa.position, fa.length)))
    case 'RotateRight':
      return either.of(fa.more(computation.right(fa.position, fa.degree)))
    case 'Show':
      console.log('interpretEither', fa.position)
      return either.of(fa.more)
  }
}

free.foldFree(either)(interpretEither, program1(start))
          // ^^^^^^^
          /**
           * Argument of type 'Monad2<"Either"> & Foldable2<"Either"> & Traversable2<"Either"> & Bifunctor2<"Either"> & Alt2<"Ei...' is not assignable to parameter of type 'Monad<"Either">'.
            Types of property 'ap' are incompatible.
              Type '<L, A, B>(fab: Either<L, (a: A) => B>, fa: Either<L, A>) => Either<L, B>' is not assignable to type '<A, B>(fab: HKT<"Either", (a: A) => B>, fa: HKT<"Either", A>) => HKT<"Either", B>'.
                Types of parameters 'fab' and 'fab' are incompatible.
                  Type 'HKT<"Either", (a: A) => B>' is not assignable to type 'Either<{}, (a: A) => B>'.
                    Type 'HKT<"Either", (a: A) => B>' is not assignable to type 'Right<{}, (a: A) => B>'.
                      Property '_tag' is missing in type 'HKT<"Either", (a: A) => B>'.
           */
```

**What is the expected behavior?**
Need to be possible to use `either` with `free.foldFree`.

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**
`fp-ts@1.6.1`
`typescript@1.8.3`

**Comment by gcanti** [comment]
@Iorg thanks for the bug report, looks like some overloadings are missing here: https://github.com/gcanti/fp-ts/blob/45bd550014f1989df9d6d8178fbce93a45160757/src/Free.ts#L138

**Comment by Iorg** [comment]
@gcanti, thanks for the fix! I tried one - it works perfect :-)
