### ISSUE TITLE
Alias Option to Maybe for Haskell/PureScript Users?

### ISSUE THREAD

**Issue by joshburgess** [gcanti/fp-ts#471]
Just curious: Would you be willing to alias the Option type to provide the Haskell/PureScript/etc. naming convention in a separate export? `Maybe`, `Just`, & `Nothing` instead of `Option`, `Some`, & `None`?

I know this could be done outside of the library. I'm just curious whether or not you're open to including it in the library.

--------------------------------------------------------

**Do you want to request a _feature_ or report a _bug_?**

Feature: Allow using Maybe/Just/Nothing instead of Option/Some/None.

**What is the current behavior?**

Uses Scala/OCaml/F#/etc. Option naming convention.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

N/A

**What is the expected behavior?**

N/A

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**

N/A

**Comment by gcanti** [comment]
Hi @joshburgess, since is just a naming convention I'd prefer to leave the situation as it is
