### ISSUE TITLE
pipeP, composeP, pipeK, and composeK?

### ISSUE THREAD

**Issue by DylanRJohnston** [gcanti/fp-ts#477]
I'd like to see these utility functions from ramda.js in this library. They're the same as the standard pipe and compose functions but P being specialised to promises and K being specialised to kliesli arrows.

Should be straightforward to implement if cumbersome to type out (All the variadic overloading). I'd be willing to write the pull request but I'm unsure of what file they should live in? `function`?

**Comment by gcanti** [comment]
I wouldn't promote the usage of bare promises, so no `composeP` / `pipeP`.

`composeK` / `pipeK` are more interesting, they should live in the `Chain` module I guess. 

However I expect that they won't play well with polymorphic functions. 

What's the use case (with respect to just using `chain`)?

```ts
import { tail, head } from 'fp-ts/lib/Array'
import { option, Option } from 'fp-ts/lib/Option'
import { URIS, Type } from 'fp-ts/lib/HKT'
import { Chain1 } from 'fp-ts/lib/Chain'

declare function composeK<M extends URIS>(
  M: Chain1<M>
): <A, B, C, D>(cd: (c: C) => Type<M, D>, bc: (b: B) => Type<M, C>, ab: (a: A) => Type<M, B>) => (a: A) => Type<M, D>

const f1 = composeK(option)(head, tail, tail)
//                          ^ error here

// this is ok
const f2 = <A>(as: Array<A>) =>
  tail(as)
    .chain(tail)
    .chain(head)
```

**Comment by DylanRJohnston** [comment]
Yeah good point. After further investigation the type inference on composeK and pipeK isn't very good. It's probably better off to just use `.chain` as you suggest.
