### ISSUE TITLE
instance transformations to other monads

### ISSUE THREAD

**Issue by leemhenson** [gcanti/fp-ts#483]
Sometimes I find myself doing things like writing chains of computation using `Task` that ends up being converted to `TaskEither`, and then later converted to `ReaderTaskEither`.  In these cases, I end up having to prepend the "machinery" to get the right output type, which kind of obscures the actual "meat" of the function:

```ts
// code compatible with fp-ts@1.x
fromTaskEither<E>(
  new TaskEither(
    right<Error, number>(
      task.of(1).map(n => n * 2)))))
```

Sometimes I wonder if it would be nicer to gradually keep upping the complexity of monad, something like:

```ts
// code compatible with fp-ts@1.x
task.of(1)
      .map(n => n * 2)
      .toTaskEither<Error>()
      .mapLeft(e => e.name)
      .toReaderTaskEither<E>()
```

That would require instance methods like `toTaskEither` being adding where appropriate, but it strikes me that it would also help with things like inference. I guess though circular refs between modules would be an issue?

**Comment by raveclassic** [comment]
@leemhenson Circular references can be avoided with module augmentation + prototype patching (you can add `Task.prototype.toTaskEither` in `TaskEither` module instead of `Task`. Although it's definitely not the best way but you can achieve it easily in your codebase.

**Comment by raveclassic** [comment]
@leemhenson There's also a nice quick implementation of pipe which could be useful: https://github.com/Microsoft/TypeScript/issues/17718#issuecomment-390807228

**Comment by leemhenson** [comment]
@raveclassic thanks for the ideas! I will try out the first one I think. The pipe impl you linked to looks pretty much like https://github.com/gcanti/fp-ts/blob/master/src/Identity.ts#L41 !

**Comment by gcanti** [comment]
Update for `fp-ts@2.x`

```ts
// code compatible with fp-ts@2.x
import { pipe } from 'fp-ts/lib/pipeable'
import * as RTE from 'fp-ts/lib/ReaderTaskEither'
import * as T from 'fp-ts/lib/Task'
import * as TE from 'fp-ts/lib/TaskEither'

pipe(
  T.of(1),
  T.map(n => n * 2),
  TE.rightTask,
  TE.mapLeft((e: Error) => e.name),
  RTE.fromTaskEither
)
```
