### ISSUE TITLE
Question: how do I reduce Validation<Error, IEnumerable<Validation<Error, T>>> to Validation<Error, IEnumerable<T>>?

### ISSUE THREAD

**Issue by Zordid** [gcanti/fp-ts#486]
I am really having a hard time trying to find documentation about how to work with Validation...

I have a structure where a Validation hosts a list of Validations of T. I want to get rid of the inner Validations and all possible errors to propagate to the outer Validation, leaving a Validation<Error, IEnumerable<T>>.

So my structure as it is is:
`Validation<Error, IEnumeration<Validation<Error, T>>>`
The outer validation hosts a possible parsing error of a JSON whereas the inner validations are probable inner problems with missing properties.

The result I need is a simple:
`Validation<Error, IEnumeration<T>>`
Where the "inner failed validations", if any, are collapsed to the "outer validation" and make the whole thing fail. If all "inner validations" are in the success state, they should just disappear to T.

How is that possible? Can anybody help? Thanks!

**Comment by gcanti** [comment]
@Zordid You need a `Semigroup` for the error

```ts
import { array } from 'fp-ts/lib/Array'
import { Semigroup, getArraySemigroup } from 'fp-ts/lib/Semigroup'
import { sequence } from 'fp-ts/lib/Traversable'
import { failure, getApplicative, Validation, success } from 'fp-ts/lib/Validation'

const f = <E>(S: Semigroup<E>): (<A>(x: Validation<E, Array<Validation<E, A>>>) => Validation<E, Array<A>>) => {
  const A = getApplicative(S)
  const sequenceValications = sequence(A, array)
  return x => x.fold(e => failure(e), sequenceValications)
}

//
// usage example
//

type MyValidation<T> = Validation<string[], T>

const x1: MyValidation<Array<MyValidation<number>>> = failure(['a'])
const x2: MyValidation<Array<MyValidation<number>>> = success([
  failure<string[], number>(['b']),
  failure<string[], number>(['c'])
])
const x3: MyValidation<Array<MyValidation<number>>> = success([
  success<string[], number>(1),
  failure<string[], number>(['d'])
])
const x4: MyValidation<Array<MyValidation<number>>> = success([
  success<string[], number>(2),
  success<string[], number>(3)
])

const ff = f(getArraySemigroup<string>())

console.log(ff(x1)) // failure(["a"])
console.log(ff(x2)) // failure(["b", "c"])
console.log(ff(x3)) // failure(["d"])
console.log(ff(x4)) // success([2, 3])
```
