### ISSUE TITLE
High CPU load in VSCode

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts#49]
Often when editing code using fp-ts, vscode go crazy on CPU during several seconds.
This is a reduced case, it can last way longer with more involved code.

Minimal repro repo:
https://github.com/sledorze/vscode-hanging

Main code showing the issue :

> import {
>   Validation
> } from 'fp-ts/lib/Validation';
> 
> import {
>   array,
>   validation,
> } from 'fp-ts';
> 
> export function pouet(
>   xs: number[],
>   f: (x: number) => Validation<string[], number>
> ): void {
>   array.traverse(validation. .getApplicativeS(array))(f, xs); // Long hanging due to this space!
> }

**Comment by gcanti** [comment]
Thanks @sledorze, the issue seems deeper: using your example and TypeScript v2.3.1 even the compiler crashes, I filed an issue https://github.com/Microsoft/TypeScript/issues/15443

**Comment by OliverJAsh** [comment]
Do you know if there's any workaround for this whilst we wait for the upstream fix?

**Comment by sledorze** [comment]
Write correct first only (correct and typechecks :) )
Other than that, i needed to kill the process and restart vscode

Le lun. 1 mai 2017 11:50, Oliver Joseph Ash <notifications@github.com> a
écrit :

**Comment by sledorze** [comment]
Fixed in typescript@next
https://github.com/Microsoft/TypeScript/pull/15863

**Comment by gcanti** [comment]
@OliverJAsh just tried your `ts-2.4-memory-issue` repo, with `typescript@next` all errors show up instantly!

**Comment by OliverJAsh** [comment]
@gcanti :-D
