### ISSUE TITLE
[Question] How to migrate deprecated fp.option.of()

### ISSUE THREAD

**Issue by guoyunhe** [gcanti/fp-ts#494]
Hi, I am working on a project using older fp-ts and we are migrating to fp-ts 1.x now. Here are a lot of `fp.option.of()` but the `of` function has been dropped. How should I migrate it? Thanks!

**Comment by gcanti** [comment]
You can use `option.of`

```ts
import { option } from 'fp-ts/lib/Option'

const x = option.of(1)
// x: Option<number>
```

or `some` ( which is the same)

```ts
import { some } from 'fp-ts/lib/Option'

const x = some(1)
// x: Option<number>
```

p.s.
Do not import modules like this: `import * as fs from 'fp-ts'`, you are importing the whole library, i.e. even data structures you are not interested in

**Comment by guoyunhe** [comment]
Thanks!
