### ISSUE TITLE
Question about Option's Foldable / `reduce` implementation

### ISSUE THREAD

**Issue by babakness** [gcanti/fp-ts#495]
Hello, great library! Just a brief question:

I've noticed that `Option`'s `foldable`

https://github.com/gcanti/fp-ts/blob/3284938baa782bb8760e7b75dfd41955c6157e4e/src/Option.ts#L259

 is in the opposite order of FantasyLand Foldable

https://github.com/fantasyland/fantasy-land#foldable

`u.reduce(f, x)`

I'm might be totally misunderstanding that.

**Comment by gcanti** [comment]
Type inference goes from left to right, so this signature helps typing the reducer

```ts
some('foo').reduce(0, (b, a) => ) // b is inferred as number, a as string
```

**Comment by babakness** [comment]
I tried this with Typescript 2.9

```typescript
function test<A>( x: (a) => A, y: A ): A {
  return y
}

test( _ => 'a' ,1 )
```
I get the error

`Type 'string' is not assignable to type '1'.`

Also with currying

```typescript
function test<A>( x: (a) => A ): (b:A) => A {
  return (y: A) => y
}
test( _ => 'a')( 1 )

```

I get the error

`Argument of type '1' is not assignable to parameter of type 'string'.`

**Comment by babakness** [comment]
@sledorze  Well, my original comment:

> I've noticed that `Option`'s `foldable`
> 
> https://github.com/gcanti/fp-ts/blob/3284938baa782bb8760e7b75dfd41955c6157e4e/src/Option.ts#L259
> 
>  is in the opposite order of FantasyLand Foldable
> 
> https://github.com/fantasyland/fantasy-land#foldable
> 
> `u.reduce(f, x)`

I wanted to know why not comply with the fantasy-land `reduce`. I believe that @gcanti meant that the reverse order is because of typing inference. However, with the orders reverse, typing inference still seems to work, ask you can see, the errors demonstrate that with a complaint `reduce` it will produce the desired errors if the types do not match as specified.

Maybe I'm misunderstanding something? Thanks

**Comment by sledorze** [comment]
@babakness the actual order favors developper experience, meaning it is easier to fill in the reducer initial value and then fill in the reduce function as all type parameters have been discovered by the compiler.
Using the opposite order would still type check correctly but developper experience is not as nice because when writing the reduce function, all type params have not been discovered yet.

**Comment by raveclassic** [comment]
Related https://github.com/gcanti/fp-ts/issues/204

**Comment by gcanti** [comment]
Closing this as @sledorze's answer explains the rationale of the current choice
