### ISSUE TITLE
Merge getCompactable/getFilterable?

### ISSUE THREAD

**Issue by gcanti** [gcanti/fp-ts#503]
@raveclassic in `Either` (and `Validation`) there are

```ts
getCompactable<L>(ML: Monoid<L>): Compactable2C<URI, L>
getFilterable<L>(ML: Monoid<L>): Filterable2C<URI, L>
```

note that the type constraint is the same (a monoid for `L`). 
I wonder, doesn't make sense to merge them and keep only `getFilterable`?

**Comment by raveclassic** [comment]
Well I tried to separate everything. The point is not in the same constraint but in that the relation between `compact`/`separate` and `Filterable` is not immideately clear. I mean why should I call `getFilterable` if I only need `compact`?

In fact there's going to be one more `getWitherable` in one of the next PRs :)
