### ISSUE TITLE
Better practice for URI's

### ISSUE THREAD

**Issue by bioball** [gcanti/fp-ts#505]
Suggestion:

I think URI's should match their module path. For example, for fp-ts-rxjs, the URI of the Observable should be `"fp-ts-rxjs"`.  Similarly, the URI's in this lib should be something like `"fp-ts/lib/Either"` if it's the `Either` type.

Otherwise, we're kinda asking for naming conflicts. For example, if there were two implementations of fp-ts bindings to observables that both registered the "Observable" URI; which one would `URI2HKT<"Observable">` evaluate to?

**Comment by bioball** [comment]
Re: symbols: good idea, but I don't think TypeScript is able to do type narrowing based on symbol attributes.

```ts
const Option = Symbol('fp-ts/lib/option');
type Option = typeof Option; // this resolves to just `unique symbol`
```

**Comment by bioball** [comment]
Ok, went ahead and submitted a PR!

**Comment by bioball** [comment]
So the scenario that I think will arise is this:

1. Author A and B both write bindings to fp-ts independent of one another, and both use the same name for their URI's (e.g. `"Observable"` or `"List"` or something)
2. I write some app that somehow includes both Author A and Author B's packages in my dependency tree
3. My typings are now messed up, and there's not really a way to fix it.

I'm not really that concerned that somebody is going to conflict with some core fp-ts module, but that two 3rd party libs will conflict with each other. So, why not encourage some sort of convention around this?

**Comment by gcanti** [comment]
I agree, we should encourage (in the README?) some sort of convention and maybe piggyback on unique package identifiers, for example 

> you are free to choose any internal convention on your URIs as long as they are prepended by the name of your package

Example funfix

https://github.com/funfix/funfix/blob/0c315b6fe7a6c3cefc9e16f28278e85b88bebb58/packages/funfix-core/src/disjunctions.ts#L324

**Comment by bioball** [comment]
Yeah, prepending with package identifiers would work great. The PR I submitted (#506) actually adheres to that convention!

Re: readme example: I'd probably change the wording to something like this, since what people decide to publish is basically not enforceable:

> you are free to choose any internal convention on your URIs, but we encourage you to prepend it with your npm package name

**Comment by gcanti** [comment]
> The PR I submitted (#506) actually adheres to that convention

Yes but I'm not convinced that we should rename all core URIs. Take `Array` or `Either` or `Option`, they are used in the definition of some type classes, doesn't make much sense importing alternative implementations. Also, as I explained in my previous comment, there's no risk of collisions if everybody follows the convention above.

**Comment by bioball** [comment]
Cool, yeah, I don't feel strongly about it one way or another. I think if you followed the convention in fp-ts, it'd encourage others to also follow the convention, but I also don't think it's a huge deal.
