### ISSUE TITLE
Suggestion: Sortable typeclass

### ISSUE THREAD

**Issue by raveclassic** [gcanti/fp-ts#512]
I'd like to suggest to introduce new typeclass `Sortable` to describe structures that can be sorted using some `Ord`. Obvious candidates are `Array`, `NonEmptyArray`, `BinaryTree` (not existent in fp-ts), `StrMap` (?).

Such typeclass would make possible generalization of `span`, `takeWhile`, `dropWhile`, `group` and others.
Example:
```typescript
export interface Sortable<F> {
  sort: <A>(O: Ord<A>) => (fa: HKT<F, A>) => HKT<F, A>
}

function span<F>(
  F: Filterable<F> & Sortable<F>
): <A>(ord: Ord<A>) => (fa: HKT<F, A>, p: Predicate<A>) => Separated<HKT<F, A>, HKT<F, A>> {
  return O => {
    const sort = F.sort(O)
    return (fa, p) => {
      const sorted = sort(fa)
      let collectLeft = true
      return F.partition(sorted, a => {
        if (collectLeft) {
          if (p(a)) {
            return false
          }
          collectLeft = true
        }
        return true
      })
    }
  }
}
```

What do you think? I think this would be very handy but it should be carefully thought out.

**Comment by user471** [comment]
Why does `span` need sorting? Haskell span do this
`span (< 3) [1,2,3,4,1,2,3,4] == ([1,2],[3,4,1,2,3,4])`
But with sorting it would be 
`span (< 3) [1,2,3,4,1,2,3,4] == ([1,1,2,2],[3,3,4,4])

**Comment by gcanti** [comment]
@user471 you are right. Also I can't find prior art for `Sortable`

**Comment by raveclassic** [comment]
@user471 Maybe I'm wrong with naming. Sortable can describe a structure with some defined order. An array by default can be described as a `Sortable` with some "neutral" `Ord`:
```typescript
const getNeutralOrd = <A = never>(): Ord<A> => ({
  equals: constTrue,
  compare: constant<Ordering>(0)
})
const neutralOrd = getNeutralOrd<number>()
assert.deepEqual(sort(getNeutralOrd<number>())([3, 2, 1, 2, 3]), [3, 2, 1, 2, 3])
```
Then if you pass `ordNumber` to `sort` you'll get such array sorted.

@gcanti Why not? It seems logical that some functions like `takeWhile` can be generalized for any structure with some defined order, isn't it?

**Comment by gcanti** [comment]
@raveclassic if you use that `Ord` then `span` doesn't make much sense anymore: in order to be pure the predicate must return either always `true` or always `false`

```ts
const predicate = (a: number) => a < 3

console.log(neutralOrd.equals(1, 3)) // true
// but
console.log(predicate(1) === predicate(3)) // false
```

Hence `span` would return trivial results.

**Comment by user471** [comment]
> Sortable can describe a structure with some defined order
There are `Foldable` and `Traversable` with defined order. Why don't use them?

**Comment by raveclassic** [comment]
Well changing `span` signature to accept `Filterable<F> & Foldable<F>` would help so that helpers in https://github.com/gcanti/fp-ts/pull/510 could be defined. @gcanti What do you think?

**Comment by gcanti** [comment]
> changing signatures to accept Filterable<F> & Foldable<F> would help

Not sure how, could you please elaborate?

**Comment by raveclassic** [comment]
Let's look at `span`. 
It can require a structure to be `Foldable` (to keep its elements in some order). Also looks like it shouldn't require the structure to be `Filterable` because `partition` doesn't take order into account.

So I'd define it as the following:
```typescript
export function span<F, A>(
  F: Applicative<F> & Foldable<F>,
  M: Monoid<A>
): (fa: HKT<F, A>, p: Predicate<A>) => Separated<HKT<F, A>, HKT<F, A>> {
  return (fa, p) => {
    let collectLeft = true
    const initial: Separated<HKT<F, A>, HKT<F, A>> = {
      left: F.of(M.empty),
      right: F.of(M.empty)
    }
    return F.reduce(fa, initial, (acc, a) => {
      if (collectLeft) {
        if (p(a)) {
          return {
            left: F.map(acc.left, left => M.concat(left, a)),
            right: acc.right
          }
        }
        collectLeft = false
      }
      return {
        left: acc.left,
        right: F.map(acc.right, right => M.concat(right, a))
      }
    })
  }
}
```

Same applies for other functions.

**Comment by raveclassic** [comment]
Let's look at `span` once again :)
It should require a structure to be `Foldable` (to keep its elements in order) and it look like it should require it to be `Filterable` because `partition` doesn't take order into account.

So here's implementation based on `reduce`:
```typescript
export function span<F extends URIS>(
  F: Applicative1<F> & Foldable1<F>
): <A>(M: Monoid<Type<F, A>>) => (fa: Type<F, A>, p: Predicate<A>) => Separated<Type<F, A>, Type<F, A>>
export function span<F>(
  F: Applicative<F> & Foldable<F>
): <A>(M: Monoid<HKT<F, A>>) => (fa: HKT<F, A>, p: Predicate<A>) => Separated<HKT<F, A>, HKT<F, A>>
export function span<F>(
  F: Applicative<F> & Foldable<F>
): <A>(M: Monoid<HKT<F, A>>) => (fa: HKT<F, A>, p: Predicate<A>) => Separated<HKT<F, A>, HKT<F, A>> {
  return <A>(M: Monoid<HKT<F, A>>) => (fa: HKT<F, A>, p: Predicate<A>): Separated<HKT<F, A>, HKT<F, A>> => {
    let collectLeft = true
    const initial: Separated<HKT<F, A>, HKT<F, A>> = {
      left: M.empty,
      right: M.empty
    }
    return F.reduce(fa, initial, (acc, a) => {
      if (collectLeft) {
        if (p(a)) {
          return {
            left: M.concat(acc.left, F.of(a)),
            right: acc.right
          }
        }
        collectLeft = false
      }
      return {
        left: acc.left,
        right: M.concat(acc.right, F.of(a))
      }
    })
  }
}

const spanArrayOfNumbers = span(array)(getArrayMonoid<number>())
```

**Comment by gcanti** [comment]
@raveclassic how would you use such a function? I can see it applied only to arrays. `StrMap`s don't admit an `Applicative` instance. `NonEmptyArray`s don't admit a `Monoid` instance (in fact `span`, `takeWhile`, `dropWhile` etc... don't make sense for non empty arrays).

**Comment by raveclassic** [comment]
@gcanti There're plenty of structures satisfying these constraints, for example Finger Trees and many efficient persistent data structures build on top of them. Though they are definitely out of scope of fp-ts I think it'd useful to have functions generalized for them as well.

**Comment by gcanti** [comment]
> There're plenty of structures satisfying these constraints

Maybe (do Finger Trees admit an Applicative instance?).

> I think it'd useful to have functions generalized for them

Not sure, for a particular data structure you may want to implement a more efficient version than a general one (as happened with `group`).

Anyway closing this as we can agree that we don't need a `Sortable` type class and I need more evidences that such functions can be generalized *and* useful in practice.
