### ISSUE TITLE
Why not a universal `map`?

### ISSUE THREAD

**Issue by babakness** [gcanti/fp-ts#514]
Hi, I'm learning about this library and its great. I have a question (for my own understanding)--why is there a different `map` in each type?

```ts
function map<A,B,F extends URIS>(fn: Function1<A,B>, functor:HKT<F,A> & Functor<A>) : Type<F,B>
```

Wouldn't this satisfy insuring that the functor parameters is a `Functor` implementing `map` and also return a the same type as the accepted functor?

**Comment by raveclassic** [comment]
Each ADT has it's own instance of `Functor` (different implementation of `map`). Generic `map` is useless because all that it can do is to call `map` on passed instance of `Functor`:
```typescript
export function map<F>(F: Functor<F>): <A, B>(fa: HKT<F, A>, f: (a: A) => B) => HKT<F, B> {
  return F.map
}
```

**Comment by gcanti** [comment]
@babakness I suspect you are using the word "Functor" meaning a type constructor which implements a `map` method (like in [Fantasy Land](https://github.com/fantasyland/fantasy-land#functor))

```ts
function map<A,B,F extends URIS>(fn: Function1<A,B>, functor:HKT<F,A> & Functor<A>) : Type<F,B>
//                                                   ^--- here
```

`fp-ts` implements functors as static dictionaries instead (like in [Static Land](https://github.com/rpominov/static-land/blob/master/docs/spec.md#functor)) so, as noted by @raveclassic, having a generic `map` function doesn't make much sense.

**Comment by babakness** [comment]
@gcanti I see, thanks. I did have that misunderstanding. I do see some type constructors in the library too. I'm actually learning a lot of Typescript working through this library. :-)

**Comment by tusharmath** [comment]
I have a similar use case — 

```ts
import {IO} from './node_modules/fp-ts/lib/IO'
import {Option} from './node_modules/fp-ts/lib/Option'

interface CacheIO {
  get(cache: string, req: Request): IO<Option<Response>>
}

export function cacheFirst(req: Request, cache: CacheIO) {
  return cache.get('sw-cache', req)
 
   // doesn't work because it expects an IO<Response> but its 
    .chain(optResponse => optResponse) getting Option<Response>
}

```

What is the correct way of using `chain` such that it can unwrap both `IO` and `Option` ?
