### ISSUE TITLE
Suggestion: Make instances of existing ADTs extendable

### ISSUE THREAD

**Issue by raveclassic** [gcanti/fp-ts#520]
Currently instance of typeclass for an ADT is defined as constant in the module of such ADT. This makes it impossible to extend existing ADT instance with additional typeclasses because TS doesn't allow merging of interfaces for constants in module augmentation.

I suggest to move typeclass methods to class body and to still export constant which would be an instance of that class. Here's an example:

```typescript
// Array.ts
export class ArrayInstance
  implements
    Monad1<URI>,
    Foldable1<URI>,
    Unfoldable1<URI>,
    Traversable1<URI>,
    Alternative1<URI>,
    Plus1<URI>,
    Extend1<URI>,
    Compactable1<URI>,
    Filterable1<URI>,
    Witherable1<URI> {
  readonly URI = URI

  readonly map = map
  readonly compact = compact
  readonly separate = separate
  readonly filter = filter
  readonly filterMap = filterMap
  readonly partition = partition
  readonly partitionMap = partitionMap
  readonly of = of
  readonly ap = ap
  readonly chain = chain
  readonly reduce = reduce
  readonly unfoldr = unfoldr
  readonly traverse = traverse
  readonly zero = zero
  readonly alt = alt
  readonly extend = extend
  readonly wither = wither
  readonly wilt = wilt
}

export const array = new ArrayInstance() //non-breaking

// Awesome.ts
import { URI, ArrayInstance } from './Array'
import { HKT, URIS, Type } from './HKT'

// typeclass
export interface Awesome<F> {
  readonly URI: F
  readonly makeItAwesome: <A>(fa: HKT<F, A>) => void
}
export interface Awesome1<F extends URIS> {
  readonly URI: F
  readonly makeItAwesome: <A>(fa: Type<F, A>) => void
}

// generic version
export function makeItAwesome<F extends URIS>(F: Awesome1<F>): <A>(fa: Type<F, A>) => void
export function makeItAwesome<F>(F: Awesome<F>): <A>(fa: HKT<F, A>) => void {
  return fa => F.makeItAwesome(fa)
}

// instance for Array
const awesomeArray: Awesome1<URI> = {
  URI,
  makeItAwesome: <A>(as: Array<A>) => 'Yeah!'
}
declare module './Array' {
  interface ArrayInstance extends Awesome1<URI> {}
}
Object.assign(ArrayInstance.prototype, awesomeArray)

// test.ts
import { makeItAwesome } from './Awesome'
import { array } from './Array'

const result = makeItAwesome(array)([123]) // exists
const result2 = array.makeItAwesome([123]) // also exists
```

Such approach also imitates purescript where if you import a module with typeclass you also get all defined instances.

The suggestion can be split into two parts:
  - non-breaking: to replace all instance constants with classes
  - breaking: to move all instances to the relevant typeclass modules (discussible, could be a plan for fp-ts@2.0)

**Comment by gcanti** [comment]
> This makes it impossible to extend existing ADT instance with additional typeclasses

This is a good thing, otherwise we open the door to possible conflicts (both library A and B define a `makeItAwesome` function and augment `array`). There are safer ways to get the same result, namely intersections

```ts
import { HKT, URIS, Type } from 'fp-ts/lib/HKT'
import { URI, array as A } from 'fp-ts/lib/Array'

export interface Awesome<F> {
  readonly URI: F
  readonly makeItAwesome: <A>(fa: HKT<F, A>) => void
}
export interface Awesome1<F extends URIS> {
  readonly URI: F
  readonly makeItAwesome: <A>(fa: Type<F, A>) => void
}

// export a Awesome instance for Array and let the user
// do the merging...
export const awesomeArray: Awesome1<URI> = {
  URI,
  makeItAwesome: <A>(as: Array<A>) => 'Yeah!'
}

// ...or offer a built-in merged instance
export const array: typeof A & Awesome1<URI> = {
  ...A,
  ...awesomeArray
}
```

> move all instances to the relevant typeclass modules

This would be awkward, also you end up with circular dependencies and/or unwanted runtime dependencies.

**Comment by raveclassic** [comment]
> This is a good thing, otherwise we open the door to possible conflicts (both library A and B define a makeItAwesome function and augment array).

This is not a problem, rxjs 5 safely uses such approach and all augmentations are checked by compiler so that the last wins.

> There are safer ways to get the same result, namely intersections

This seems confusing and leads to API fragmentation. Typically user doesn't want to sneak around the codebase and different libraries trying to find satisfying instance. I think it's just easier to use a single constant defined in ADT's module as a storage for all typeclass implementations.

**Comment by gcanti** [comment]
> the last wins

This doesn't look like a solution though, what if I want both instances? Also the word "last" implies an order, it's not clear who wins and why.
Using module augmentation was a bad design choice, indeed rxjs 6 changed the way operators are used/imported. 

> This seems confusing and leads to API fragmentation

Why?

> I think it's just easier to use a single constant defined in ADT's module

This is not possible in general, for example when you must provide a type constraint (`Validation.getApplicative`) or when you have multiple possible instances for the same type class (the 4 semigroups of `Option<A>`).
