### ISSUE TITLE
Importing `fp-ts/lib/Array` augments HKT with `Option`

### ISSUE THREAD

**Issue by babakness** [gcanti/fp-ts#524]
When in my codebase I import `fp-ts/lib/Array`, which seems necessary for augmenting the HKT system with global `Array`

```ts
declare global {
  interface Array<T> {
    _URI: 'Array'
    _A: T
  }
}
```

Works for that purpose; but doing this also introduces `Option` to the system which seem superfluous.  Perhaps this Array augmentation occurred in `fp-ts/lib/HKT` instead; or more generally, global augmentations are done in a `HKT-starter.ts` file?

**Comment by babakness** [comment]
Its related to https://github.com/gcanti/fp-ts/issues/519

Using `fp-ts` as a standard for emulating Higher-Kinded Types. It seems necessary to augment `Array` globally as part of using the `HKT` system. If a function accepts a `Functor` it probably also accepts an `Array` yet the Array type first needs to be augmented to become compatible with the system.

**Comment by gcanti** [comment]
> It seems necessary to augment Array globally as part of using the HKT system

It's necessary only if you are using some instances from the `Array` module.

**Comment by babakness** [comment]
If I'm writing my own library and want to describe a function that takes a functor, operates on it, then returns that functor, then I will need something like HKTs. If I want said library to work within an ecosystem, I'll reference 'fp-ts/lib/HKT' *and* 'fp-ts/lib/Array' because I want to also accept `Array`. I don't see why its necessary to also get `Option` augmented in this scenario.
