### ISSUE TITLE
`get` method on `Either` interface - gets value from a `Right`, throws for a `Left`

### ISSUE THREAD

**Issue by mmkal** [gcanti/fp-ts#525]
**Do you want to request a _feature_ or report a _bug_?**
Feature request

**What is the current behavior?**
`Either<L, A>` has a `getOrElse` method which can be used to get the right-ish value.

**What is the expected behavior?**
A `get` method like in scala's `Option`s, `Try`s etc. This would return the value if the `Either` is a `Right`, and throw if it's a `Left`.

The current (hacky) workaround for this is doing something like 
```typescript
const num = t.number.decode(123).getOrElseL(val => ThrowReporter.report(left(val)) as any);
```

with the `.get` method it'd be more like
```typescript
const num = t.number.decode(123).get;
```

Presumably this would require having a statically defined default thrower for `Left`s - which I think is a nice solution - fp-ts could provide one, but if the user wants to use something else to make sure errors are parseable by custom logging ingestion tool, the "thrower" could be set on app startup.

**Comment by gcanti** [comment]
This is by design, fp-ts is a (pure) functional library, functions/methods shouldn't throw.
Related: https://github.com/gcanti/fp-ts/issues/429

**Comment by mmkal** [comment]
That's fair, I suspected as much. Most situations I've wanted to use this are either in AWS lambdas in case I want everything to come crashing down, or when I'm dealing with async APIs where I've struggled to be able to chain/map Validation objects around in combination with promises - which is why I opened this, which would provide a more functional-programming solution:  https://github.com/gcanti/fp-ts/issues/526
