### ISSUE TITLE
Type<URI1, A> is assignable to Type<URI2, A>

### ISSUE THREAD

**Issue by mattmccutchen** [gcanti/fp-ts#536]
**Do you want to request a _feature_ or report a _bug_?** Report a bug (or possibly a design limitation).

**What is the current behavior?** If `URI1` and `URI2` are two different type variables constrained by `URIS`, then `Type<URI1, A>` is assignable to `Type<URI2, A>`, thanks to the following code in TypeScript [`src/compiler/checker.ts`](https://raw.githubusercontent.com/Microsoft/TypeScript/93722c89426425972d08aa2220311ed411a4d9eb/src/compiler/checker.ts) line 11462 (the file is too big to link to it directly on GitHub):

```ts
                else if (target.flags & TypeFlags.IndexedAccess) {
                    // A type S is related to a type T[K] if S is related to C, where C is the
                    // constraint of T[K]
                    const constraint = getConstraintForRelation(target);
                    if (constraint) {
                        if (result = isRelatedTo(source, constraint, reportErrors)) {
                            errorInfo = saveErrorInfo;
                            return result;
                        }
                    }
                }
```

This is a major gap in the type safety of the HKT library.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**
https://codesandbox.io/s/v3ljrprol

**What is the expected behavior?** `Type<URI1, A>` is not assignable to `Type<URI2, A>`.

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?** Tested on codesandbox (link above).  I'd assume that all versions are affected.

**Comment by gcanti** [comment]
@mattmccutchen thanks for the detailed report

> This is a major gap in the type safety of the HKT library

any practical example of this?

**Comment by mattmccutchen** [comment]
> any practical example of this?

I realize I may have misunderstood the intent of the HKT library.  If it is used only in overload signatures as described in HKT.md, maybe the problem never comes up and this issue can be considered invalid.  My observation was only that the HKT library does not constitute a general-purpose system for working safely with higher-kinded types in TypeScript because of the lax assignability checking.  If desired, the problem can probably be fixed by using a conditional type, similar to what I've done [here](https://bitbucket.org/espalier-spreadsheet/espalier/src/5a582831912434caaf703f6dcc5b9e18d7dfa2c7/src/lib/type-funcs.ts?at=master&fileviewer=file-view-default#type-funcs.ts-41), but I'm not sure exactly what would be needed for backward compatibility in the context of fp-ts.
