### ISSUE TITLE
StrMap empty

### ISSUE THREAD

**Issue by cjduncana** [gcanti/fp-ts#546]
**Do you want to request a _feature_ or report a _bug_?**

Request a feature

**What is the current behavior?**

If I want to create an empty `StrMap`, I have to use its constructor: `new StrMap({})`.

**What is the expected behavior?**

I wish to have a function that automatically does this: `const empty = () => new StrMap({})`. The benefit comes from not having to know the implementation of `StrMap` to use it. I do not need to know that `StrMap` is constructed from JS objects to be able to use it.

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**

I'm currently using fp-ts@^1.7.1.

**Comment by cjduncana** [comment]
I noticed that this is already available [here](https://github.com/gcanti/fp-ts/blob/master/src/StrMap.ts#L69), it's only a matter of exposing it.

**Comment by gcanti** [comment]
If it's "empty" with respect to some `Semigroup` you can use `getMonoid`

```ts
import { getMonoid } from 'fp-ts/lib/StrMap'

const { empty } = getMonoid()
```

**Comment by cjduncana** [comment]
It works! Thanks! 👍
