### ISSUE TITLE
Alternative approach to higher-kinded types

### ISSUE THREAD

**Issue by pelotom** [gcanti/fp-ts#547]
Hi @gcanti, I've been playing with a simple encoding of HKTs using conditional types to substitute virtual type variables within a saturated type. Reference project here:

https://github.com/pelotom/hkts

It's attractive to me in that it doesn't require defining your type constructors in any special way; you can take any given `type Foo<A> = ...` for example and then abstract over `Foo`. Would this be a useful approach for `fp-ts`? Would love to hear your thoughts!

**Comment by gcanti** [comment]
Hi @pelotom, thanks for sharing. 

How do you define a `Monad` instance for `Either`?

**Comment by pelotom** [comment]
>How do you define a `Monad` instance for `Either`?

Good question. The only thing I can think to do is have a parameterized instance creator

```ts
const RightMonad = <L>() => Monad<Either<Fixed<L>, _>>({
  pure: right,
  bind: (ma, f) => (ma.tag === 'left' ? ma : f(ma.right)),
});

const either: Either<string, number> = right(42);
const result = RightMonad<string>().map(either, n => n + 1);
expect(result).toEqual(right(43));
```

The new `Fixed` operator is needed to instruct `$` to leave bound type parameters unmolested. What do you think, is there a better approach?

**Comment by masaeedu** [comment]
It's a shame that you can't just say:

```
type EitherMonad = <L> Monad<Either<Fixed<L>, _>>
```

The ability to introduce foralls is restricted to functions.

**Comment by masaeedu** [comment]
It's a shame that you can't just say:

```
type EitherMonad = <L> Monad<Either<Fixed<L>, _>>
```

The ability to introduce foralls is restricted to functions.

**Comment by pelotom** [comment]
@masaeedu 

> It's a shame that you can't just say:
> 
> ```
> type EitherMonad = <L> Monad<Either<Fixed<L>, _>>
> ```
> The ability to introduce foralls is restricted to functions.

Yes, it is... I hope your issue https://github.com/Microsoft/TypeScript/issues/17574 gets some attention!
