### ISSUE TITLE
Import/Use EitherT

### ISSUE THREAD

**Issue by mkeshav** [gcanti/fp-ts#553]
Can you pls show me an example of using EitherT with Task and Either?

If I have 2 functions that return Task<Either[?, ?]> how do i apply the MTL EitherT

**Comment by gcanti** [comment]
```ts
import { Task, task } from 'fp-ts/lib/Task'
import { Either } from 'fp-ts/lib/Either'
import { getEitherT } from 'fp-ts/lib/EitherT'

const eitherTTask = getEitherT(task)

declare const foo: Task<Either<string, string>>
declare function bar(s: string): Task<Either<string, number>>

// result: Task<Either<string, number>>
const result = eitherTTask.chain(bar, foo)
```

Also, see [`TaskEither`](https://github.com/gcanti/fp-ts/blob/fd0ccf39bb52622f93e01fb7b9bcb6c955d634fe/src/TaskEither.ts)
