### ISSUE TITLE
do/for comprehension

### ISSUE THREAD

**Issue by mkeshav** [gcanti/fp-ts#565]
Is it possible to do monad stacking with for comprehension using fp-ts

**Comment by alex-ketch** [comment]
Not _quite_ 1 to 1 usage, but have you seen the do-notation example in the [new docs](https://github.com/gcanti/fp-ts/blob/master/fp-ts-for-purescripters.md#do-notation)?

**Comment by RPallas92** [comment]
@mkeshav 
https://github.com/gcanti/fp-ts/issues/261#issuecomment-414619797

**Comment by raveclassic** [comment]
https://github.com/gcanti/fp-ts/issues/261
