### ISSUE TITLE
Sourcemaps published to npm are unresolvable.

### ISSUE THREAD

**Issue by scotttrinh** [gcanti/fp-ts#566]
**Do you want to request a _feature_ or report a _bug_?**
🐛 Bug

**What is the current behavior?**
Sourcemap-aware tooling tries to follow the `sources` link in each module's `Foo.map.js`, but since it points to `../src/Foo.ts` and that isn't published, it spits out a warning.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**
Noticed when building with Webpack and testing with the Webpack Development Server, but the issue is pretty straightforward.

**What is the expected behavior?**
I can see two solutions:
1. Exclude the sourcemaps.
2. Publish the source to npm.

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**
N/A

---

I'd be happy to provide a PR, but just want some direction as to which mitigation strategy is preferred, or if there is some other way I haven't considered!

**Comment by gcanti** [comment]
> I'd be happy to provide a PR

@scotttrinh yes please, there's an old, related issue if you want to chime in https://github.com/gcanti/fp-ts/issues/223
