### ISSUE TITLE
StrMap collect does not respect the traversal order of object properties in ES6

### ISSUE THREAD

**Issue by mlegenhausen** [gcanti/fp-ts#568]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
`StrMap.collect` does not respect the order in which keys were added.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**
```js
const obj = { b: '1', a: '2' };
assert.deepEqual(Object.keys(obj), collect(new StrMap(obj), (k) => k));
```

I use `collect` to build my `keys` and `values` functions for `StrMap`. Both are  "broken" since b81f5e606c1d7591033ad4649386f0b2e1a6ede0.

**What is the expected behavior?**
Cause no order is documented or could be specified [the traversal order of object properties in ES6](http://2ality.com/2015/10/property-traversal-order-es6.html) should be used.

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**
`>= 1.7.0`

**Comment by gcanti** [comment]
> Cause no order is documented or could be specified

Actually keys are sorted when appropriate (see `collect`, `reduce`, `toArray`)

> StrMap.collect does not respect the order in which keys were added

That's correct, otherwise

```ts
const x = new StrMap({ a: 1, b: 2 }) 
const y = new StrMap({ b: 2, a: 1 })

// x is equals to y but collect(x) is not equal to collect(y)
```
