### ISSUE TITLE
Tagless Final Example

### ISSUE THREAD

**Issue by tusharmath** [gcanti/fp-ts#571]
**Question**

Is it technically possible to use tagless-final with fp-ts? I fried my brain all day to make it work. If it is, can you showcase an example?

PS: Thank you for getting functional bits to typescript.

**Comment by sledorze** [comment]
Please
https://gist.github.com/gcanti/85bb38c5cf2cd6fb5a1decf7c04624c2

**Comment by gcanti** [comment]
Check this out https://github.com/gcanti/fp-ts/blob/master/examples/mtl.ts
Also https://gist.github.com/gcanti/453e5419fbcabe078d933ab21f0df8bf

**Comment by grossbart** [comment]
I added this question and the linked documents to the FAQ section of the documentation, closing this now.
