### ISSUE TITLE
deprecate IOEither.tryCatch in favour of IOEither.tryCatch2v

### ISSUE THREAD

**Issue by gcanti** [gcanti/fp-ts#625]
Signature

```ts
export const tryCatch2v = <L, A>(f: Lazy<A>, onerror: (reason: {}) => L): IOEither<L, A> => {
  ...
}
```

**Comment by raveclassic** [comment]
@gcanti Why `{}` as the type for the `reason` argument?

**Comment by mlegenhausen** [comment]
I think it can be changed to `unknown`?

**Comment by gcanti** [comment]
Yes, I'm waiting for https://github.com/gcanti/fp-ts/pull/612 to be merged though

**Comment by raveclassic** [comment]
I think the argument can be ommited for now, it has no value with the type `{}`.

**Comment by gcanti** [comment]
https://github.com/gcanti/fp-ts/pull/630
