### ISSUE TITLE
Support ReadonlyArray

### ISSUE THREAD

**Issue by RoryDungan** [gcanti/fp-ts#626]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
Currently [array](https://github.com/gcanti/fp-ts/blob/master/docs/Array.md) functions do not work with TypeScript 2.0's [ReadonlyArray](https://www.typescriptlang.org/docs/handbook/interfaces.html#readonly-properties). 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**
The following code will produce an error:
```js
import { findFirst } from 'fp-ts/lib/Array';

const testArray: ReadonlyArray<number> = [1, 2, 3, 4, 5];
const three = findFirst(testArray, (n: number) => n === 3);
```

```
Argument of type 'ReadonlyArray<number>' is not assignable to parameter of type 'number[]'.
  Property 'pop' is missing in type 'ReadonlyArray<number>'.
```

**What is the expected behavior?**
Since fp-ts Array functions do not mutate the array, they shouldn't require mutation methods like `pop` to be present on their input arrays. ReadonlyArray is a very useful feature because it helps ensure that arrays are never mutated across the whole app as well as in code that uses fp-ts, and supporting this would also make it easier to adopt fp-ts in an existing project that uses ReadonlyArray.

Supporting ReadonlyArray *should* be as simple as switching the function definitions across to use ReadonlyArray instead of Array. This won't break support for regular Arrays because the Array type contains all the properties of ReadonlyArray. 

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**
I tested using fp-ts 1.10.0, Typescript 3.1.4, Node 10.13.0 and Windows 10.

**Comment by gcanti** [comment]
> This won't break support for regular Arrays because the Array type contains all the properties of ReadonlyArray

@RoryDungan That's true for the input but what about the output?

```ts
// fp-ts
declare function copy<A>(as: ReadonlyArray<A>): ReadonlyArray<A>

// your codebase
declare function length(a: Array<number>): number

declare const as: Array<number>
length(copy(as)) // error
```

I guess we could add an overloading

```ts
declare function copy<A>(as: Array<A>): Array<A>
declare function copy<A>(as: ReadonlyArray<A>): ReadonlyArray<A>

length(copy(as)) // ok
```

See https://github.com/gcanti/fp-ts/pull/544 for a previous discussion.
