### ISSUE TITLE
Add some more NonEmptyArray functions

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts#627]
Implement `index`, `findFirst`, `findIndex`, `insertAt`, `updateAt`, `filter` for NonEmptyArray

I may issue a PR.

@gcanti Ok with all of those?

**Comment by gcanti** [comment]
@sledorze sure, thanks

**Comment by sledorze** [comment]
Need that for:
https://github.com/gcanti/monocle-ts/issues/66

@gcanti , may it be possible to issue a release once accepted?
