### ISSUE TITLE
Curry undocumented

### ISSUE THREAD

**Issue by janat08** [gcanti/fp-ts#640]
In API section on github

**Comment by joshburgess** [comment]
@janat08 It does exist. See here: https://github.com/gcanti/fp-ts/blob/master/src/function.ts#L298-L312

**Comment by gcanti** [comment]
Closing (https://gcanti.github.io/fp-ts/modules/function.ts.html#curry-function)

**Comment by antonkatz** [comment]
Actually, it no longer exists. Or am I just dumb?

**Comment by steida** [comment]
@antonkatz Auto currying is not type-safe with TypeScript. The recommended solution is manual currying.

**Comment by matulek** [comment]
Couldn't this help to bring this one back: https://v10i.dev/p/auto-currying-in-typescript ?

**Comment by kaspar-p** [comment]
Is there an explanation why it is not safe, or some documentation around that fact?
