### ISSUE TITLE
Streamx bindings (cyclejs)

### ISSUE THREAD

**Issue by janat08** [gcanti/fp-ts#641]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

**What is the expected behavior?**

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**

**Comment by gcanti** [comment]
@janat08 bindings are usually published as separate libraries

Examples

- [fp-ts-rxjs](https://github.com/gcanti/fp-ts-rxjs) - fp-ts bindings for RxJS
- [fp-ts-most](https://github.com/joshburgess/fp-ts-most) - fp-ts bindings for @most/core

**Comment by janat08** [comment]
I was asking that one be made
