### ISSUE TITLE
Chainable monad type

### ISSUE THREAD

**Issue by mmkal** [gcanti/fp-ts#672]
**Do you want to request a _feature_ or report a _bug_?**
feature

**What is the current behavior?**
no simple monad type which boxes a value up, allows chaining and retrieving of the value (as far as I know - if this exists then this can become a documentation request!)

Doing this with vanilla js requires using an array in a hacky way:
```js
const str = 'TheRainInSpain'

const sentence = [str]
  .map(toSnakeCase)
  .map(s => s.replace(/_/g, ' ')
  .map(upperFirst)
  [0]

console.log(sentence) // 'The rain in spain'
```

Or hard-to-read reversing of functions:
```js
const str = 'TheRainInSpain'

const sentence = upperFirst(
  toSnakeCase(str)
    .replace(/_/g, ' ')
)

console.log(sentence) // 'The rain in spain'
```

**What is the expected behavior?**
it could look something like this:
```js
const str = 'TheRainInSpain'

const sentence = box(str)
  .map(toSnakeCase)
  .map(s => s.replace(/_/g, ' ')
  .map(upperFirst)
  .value

console.log(sentence) // 'The rain in spain'
```
where `box` is defined something like
```typescript
export interface Box<T> {
  value: T
  map<U>(f: (val: T) => U): Box<U>
}
export const box = <T>(value: T): Box<T> => ({
  value,
  map: f => box(f(value)),
})
```

**Comment by gcanti** [comment]
Looks like the [Identity](https://github.com/gcanti/fp-ts/blob/master/src/Identity.ts) functor
