### ISSUE TITLE
Use Symbol.iterator

### ISSUE THREAD

**Issue by bioball** [gcanti/fp-ts#674]
ES6 has support for [custom iterators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator).

It'd be great if we could implement `Symbol.iterator`, so we could write code like so:

```ts
const foo: Option<string> = getFooSomeHow();
const bar: Option<string> = getBarSomeHow();

const fooBar = [...foo, ...bar];
```

**Comment by joshburgess** [comment]
@bioball What would happen in the case of `foo` or `bar` being `None` in the above example? Would the spread operator simply spread nothing into the array?

**Comment by bioball** [comment]
In that case, the spread operator expands it to nothing, and `fooBar` would end up being an empty array.

**Comment by joshburgess** [comment]
Hmmm, I think it's an interesting proposal, but it's also sort of outside of the norm of how most languages use the Maybe/Option type...

You could also write something like this and use it as a wrapper for such cases:

```
export const toSpreadable = <A>(opt: Option<A>) => opt.fold([] as A[], x => [x])

...

const fooBar = [...toSpreadable(foo), ...toSpreadable(bar)]
```

**Comment by gcanti** [comment]
Note: `toSpreadable` is a natural transformation and can be derived from the `Foldable` instance

```ts
import { toArray } from 'fp-ts/lib/Foldable2v'
import { option } from 'fp-ts/lib/Option'

const toSpreadable = toArray(option)
```

**Comment by joshburgess** [comment]
Cool!
