### ISSUE TITLE
Library enhancement with typescript Predicates?

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts#68]
I am wondering how well it would fit into fp-ts to take advantage of narrowing with native predicate types.
For instance, I'm often using that kind of type-safe function:

```
const filterPredicate = <T, U extends T>(pred: (x: T) => x is U, arr: Array<T>): Array<U> =>
  arr.filter(pred) as Array<U>

```

If we adapt for for higher kinds, I don't really know how we would name it.

What do you think @gcanti ?

**Comment by gcanti** [comment]
> I don't really know how we would name it

"Refinement"?

Is this what you're aiming for?

```ts
// function.ts module
export type Refinement<A, B extends A> = (a: A) => a is B
```

```ts
// Array.ts module
import { Refinement } from './function'

export function refine<A, B extends A>(refinement: Refinement<A, B>, as: Array<A>): Array<B> {
  return as.filter(refinement) as Array<B>
}
```

Usage

```ts
it('refine', () => {
  const as = [some(1), none]
  const refinement = isSome
  // result :: Array<Some<number>>
  const result = arr.refine<Option<number>, Some<number>>(refinement, as)
  assert.deepEqual(result, [some(1)])
})
```

However expressing both type annotations seems quite awkward, maybe we could curry `refine`

```ts
export function refine<A>(as: Array<A>): <B extends A>(refinement: Refinement<A, B>) => Array<B> {
  return <B extends A>(refinement: Refinement<A, B>) => as.filter(refinement) as Array<B>
}

// only the refinement type annotation here
const result = arr.refine(as)<Some<number>>(refinement)
```

**Comment by sledorze** [comment]
@gcanti there no such need to type annotations IFF your predicates (refinements) already implement those, like so:

```
export function isCartCreated(x: CartEvent): x is CartCreated {
  return x.type === 'CartCreated'
}

```

usage:

```
    const arr: domain.CartEvent[] = []
    pred.filter(domain.isCartCreated, arr) // domain.CartCreated[]

    pred.filter(pred.or(domain.isCartCreated, domain.isItemAdded), arr) // (domain.CartCreated | domain.ItemAdded)[]

```
or being a combinator, here some code :

```
type TypePredicate<T, U extends T> = (x: T) => x is U

const filter = <T, U extends T>(pred: TypePredicate<T, U>, arr: Array<T>): Array<U> =>
  arr.filter(pred) as Array<U>

const or = <T, U extends T, V extends T>(pred1: TypePredicate<T, U>, pred2: TypePredicate<T, V>): TypePredicate<T, U | V> =>
  (x: T): x is (U | V) => pred1(x) || pred2(x)

const and = <T, U extends T, V extends T>(pred1: TypePredicate<T, U>, pred2: TypePredicate<T, V>): TypePredicate<T, U & V> =>
  (x: T): x is (U & V) => pred1(x) && pred2(x)

```

**Comment by gcanti** [comment]
> there no such need to type annotations

Weird.. could you try your code against a higher kind like `Option`? Without type annotations I get

```ts
const as: Array<Option<number>> = [some(1), none]
const refinement = isSome
// result :: Some<{}>[] // <= {} instead of number
const result = arr.refine(refinement, as)
```

**Comment by sledorze** [comment]
Oh sorry, I was overlooking your example, yes, you need it to modify it for such case.
(I was not using generic types in my use cases - yet)

```
const filter = <T>(arr: Array<T>) => <U extends T>(pred: TypePredicate<T, U>): Array<U> =>
  arr.filter(pred) as Array<U>

// Usage

    const arr = [option.some(5), option.some(12), option.empty<number>()]

    filter(arr)(option.isSome) // option.Some<number>[]
```

Too bad the args are not the other way around..
Still, in FantaisyLand, that's very cool..

**Comment by sledorze** [comment]
@gcanti so questions:

- Should we integrate those in fp-ts (I'm really in favor to make it!)
- May we follow a specific naming pattern for such type narrowing functions?

I don't think (due to the signature constraints) that we should try to change and overload existing functions (like filter)

**Comment by gcanti** [comment]
> Should we integrate those in fp-ts?

Yes, we could adapt those combinators for both predicates and refinements

```ts
export type Refinement<T, U extends T> = (x: T) => x is U
export type Predicate<A> = (a: A) => boolean

export function or<A, B1 extends A, B2 extends A>(p1: Refinement<A, B1>, p2: Refinement<A, B2>): Refinement<A, B1 | B2>
export function or<A>(p1: Predicate<A>, p2: Predicate<A>): Predicate<A>
export function or<A>(p1: Predicate<A>, p2: Predicate<A>): Predicate<A> {
  return a => p1(a) || p2(a)
}
```

> May we follow a specific naming pattern for such type narrowing functions?

My proposal is `refine` / `Refinement`, seems the correct term based on a quick search (for example [Refinement types](https://en.wikipedia.org/wiki/Refinement_(computing))). Btw I'm using the same term in `tcomb` and `io-ts` for the same feature.

**Comment by gcanti** [comment]
> I don't think (due to the signature constraints) that we should try to change and overload existing functions (like filter)

I agree, in general I'm against default values and overloadings, except those which are required in order to get better type inference
