### ISSUE TITLE
TS2307: Cannot find module 'fp-ts'. v.1.12.1

### ISSUE THREAD

**Issue by dandrei** [gcanti/fp-ts#680]
Using `fp-ts` v.1.12.1 on Win10 with JetBrains WebStorm. For some reason, the `fp-ts` imports aren't being resolved by the IDE in `.ts` files, but work fine in `.js` files.

When I say "aren't being resolved", I mean the IDE underlines `'fp-ts'` with a red squiggly line and says `TS2307: Cannot find module 'fp-ts'`.

But the code transpiles and executes fine, even though the IDE complains about not being able to find the module.

Any clue as to what's going on?

**Comment by baetheus** [comment]
This is likely a module resolution problem in your project tsconfig.json. Could you post that here?
