### ISSUE TITLE
Rename `Record` to `Dict`?

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#685]
**Do you want to request a _feature_ or report a _bug_?**
Naming suggestion

**What is the current behavior?**
The `Record` module seems to model a "dictionary" type, where the keys are unknown (`Record<string, A>`).

If I understand correctly, the name "record" usually refers to an object with known keys, and "dictionary"/"map" refers to an object with unknown keys.

If that's correct, perhaps we should rename the `Record` module to `Dict{,ionary}`?

It would be fine to continue using TypeScript's built-in `Record` helper to model the dictionary (`Record<string, A>`), as this is just an alias for `{ [K in string]: A }`. Alternatively, you could define the dictionary type using an index signature instead of mapped types: `{ [key: string]: A }`. I'm not sure if there's much difference.

**Comment by gcanti** [comment]
I don't like it either, but that's how the built-in type is called

**Comment by OliverJAsh** [comment]
Hmm, true! I resolved to only using the built-in type `Record` for actual records (where the key is not just `string`), and then for dictionaries using index signatures (instead of mapped types which `Record` is an alias for);

``` ts
type Dict<T> = { [index: string]: T }
```

**Comment by gcanti** [comment]
> where the key is not just `string`

some functions could take into account that, e.g. `size`, `isEmpty`, `map`...

Example

```ts
export function map<K extends PropertyKey, A, B>(fa: Record<K, A>, f: (a: A) => B): Record<K, B>
export function map<A, B>(fa: Record<string, A>, f: (a: A) => B): Record<string, B>
export function map<A, B>(fa: Record<string, A>, f: (a: A) => B): Record<string, B> {
  return mapWithKey(fa, (_, a) => f(a))
}
```

```ts
declare const x: Record<'a' | 'b', number>

// y: Record<"a" | "b", boolean>
const y = R.map(x, n => n > 2)
```

**Comment by giogonzo** [comment]
@gcanti this would help, I had to do some similar casts when `map`ping over a record with known keys . How could `size`, `isEmpty` have benefits instead?

**Comment by giogonzo** [comment]
Real world example:
```ts
const inlineErrors : InlineErrors<K> = mapWithKey( // type InlineErrors<K extends string> = Record<K, Option<string>>;
  this.props.inlineErrors,
  (key: K, error) => error.filter(() => shouldShowInlineErrorForKey(key)) // without the `key: K` annotation, TS would complain (since `shouldShowInlineErrorForKey` expects a `K`)
);
```

**Comment by gcanti** [comment]
> How could size, isEmpty have benefits instead?

Never mind, I thought that it wouldn't type-check, but I was wrong:

```ts
function size<A>(d: { [key: string]: A }): number {
  return Object.keys(d).length
}

declare const x2: Record<'a' | 'b', number>
declare const x1: Record<1 | 2, number>

size(x1) // no error
size(x2) // no error
```

**Comment by joshburgess** [comment]
It would be nice if they allowed us to support constrained domains in the index signature itself. I hope it's something TS will support one day.

IMO, we should should be able to do this:

`[key: 'a' | 'b']: A }`

**Comment by OliverJAsh** [comment]
Is `Record` supposed to be used to models dictionaries (unknown keys) _and _records_ (known keys)?
