### ISSUE TITLE
`insert` of `Record` should be a `noop` if the value at the key already exists (strict equals)

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts#711]
Note: We may also optimise `filterWithIndex` and `filterMapWithIndex`

**Comment by sledorze** [comment]
@gcanti I think you've partially implemented that in 
https://github.com/gcanti/fp-ts/pull/720/commits/306cf6a0b7d55cd9b6d1bf03235d685a1afcfda0

**Comment by sledorze** [comment]
I've finally optimised `traverseWithKey` and `filterWithIndex`
I'm done on it

**Comment by gcanti** [comment]
Closing via https://github.com/gcanti/fp-ts/pull/720
