### ISSUE TITLE
Option.of: Should it ever return a none?

### ISSUE THREAD

**Issue by mattgrande** [gcanti/fp-ts#713]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behavior?**

Calling `option.of(null)` or `option.of(undefined)` returns `Some(null)` and `Some(undefined)` respectively.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

N/A

**What is the expected behavior?**

I would have guessed that it would return `None` in those cases, but I may be way out to lunch here.

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**

All of them, as far as I can tell.

-----

If there's support for this, I'd like to update `option.of` to return a `none` when `null` or `undefined` is passed to it... But I honestly don't know if I'm breaking the rules by doing so.

Code here: https://github.com/gcanti/fp-ts/blob/master/src/Option.ts#L461-L463

I am willing to do a PR, but wanted to have a discussion before doing so.

**Comment by gcanti** [comment]
That's the correct behavior for `of`, you may want [fromNullable](https://gcanti.github.io/fp-ts/Option.html#fromnullable)

**Comment by mattgrande** [comment]
That's exactly what I want, thank you!
