### ISSUE TITLE
Compilation error when using Chain.flatten

### ISSUE THREAD

**Issue by cdimitroulas** [gcanti/fp-ts#731]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
I have encountered a problem with type inference when using `Chain.flatten` which I believe may be a bug. Not sure if this is a limitation of Typescript itself though.
I am very new to functional programming and `fp-ts` so forgive me if what I am doing is nonsense - any tips would be appreciate if you find that this is the case :sweat_smile: 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**
```ts
import { flatten } from "fp-ts/lib/Chain";
import * as either from "fp-ts/lib/Either";
import * as func from "fp-ts/lib/function";
import * as taskEither from "fp-ts/lib/TaskEither";

interface IThing {
  name: string;
}

const fetchSomething = (): taskEither.TaskEither<any, IThing> => {
  return taskEither.tryCatch(
    () => Promise.resolve({ name: "Thing" }),
    (e: any) => {
      throw e;
    }
  );
};

const doSomething = (thing: IThing): either.Either<any, IThing> => {
  // fake stuff to do
  return either.right(thing);
};

const doSomethingElseAsync = <T extends IThing>(whatever: T): taskEither.TaskEither<any,T> => {
  return taskEither.tryCatch(() => Promise.resolve(whatever), (e: any) => { throw e })
}

const handler = (): taskEither.TaskEither<any, IThing> =>
  func.pipe(
    () => fetchSomething()
      .map(doSomething)
      .map(taskEither.fromEither),
    flatten(taskEither.taskEither),
    val => val.map(doSomethingElseAsync),
    flatten(taskEither.taskEither) // <-- This throws a compiler error
    //  converting it to this works: (v) => flatten(taskEither.taskEither)(v)
  )(0);

handler();
```

The compilation error is:
```
Argument of type '<L, A>(mma: TaskEither<L, TaskEither<L, A>>) => TaskEither<L, A>' is not assignable to parameter of type '(d: {}) => TaskEither<{}, {}>'.
  Types of parameters 'mma' and 'd' are incompatible.
    Type '{}' is missing the following properties from type 'TaskEither<{}, TaskEither<{}, {}>>': value, _A, _L, _URI, and 19 more.
```

**What is the expected behavior?**
Should compile without error

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**
`fp-ts`:  1.13.0

**Comment by gcanti** [comment]
@cdimitroulas thanks for the detailed bug report. 

This is a limitation of Typescript, `pipe` (and `compose`) doesn't play well with **polymorphic** functions like `flatten(taskEither.taskEither)` which expands to

```ts
<L, A>(mma: TaskEither<L, TaskEither<L, A>>) => TaskEither<L, A>
```

My suggestion is to try to avoid free-point style. 

Btw you can use `chain` instead of `map` so you don't end up with nested `TaskEither`s

```ts
const handler = (): TaskEither<any, IThing> =>
  fetchSomething()
    .chain(thing => fromEither(doSomething(thing)))
    .chain(doSomethingElseAsync)
```

**Comment by cdimitroulas** [comment]
Yes thanks for the tip on `chain` and `map` - someone on StackOverflow just gave me the same tip so I have been using this instead and was able to avoid using `pipe` due to that.

Feel free to close the issue if this is a known TS issue and is not related to fp-ts :)

**Comment by cdimitroulas** [comment]
@gcanti is there a place (e.g Slack, Discord) I can reach you to discuss more about point-free style in TS? Don't want to pollute this GitHub issue with unrelated comments

**Comment by gcanti** [comment]
@cdimitroulas the functional slack? https://fpchat-invite.herokuapp.com/
