### ISSUE TITLE
NonEmptyArray can be simplified

### ISSUE THREAD

**Issue by yawaramin** [gcanti/fp-ts#735]
**Do you want to request a _feature_ or report a _bug_?** Feature

**What is the current behavior?** `NonEmptyArray` is a new class that wraps an array

**What is the expected behavior?** `NonEmptyArray` is an alias: `type NonEmptyArray<A> = A[] & {0: A};`

This has the following benefits:

- Takes advantage of the type system
- No extra allocation
- Less maintenance (no need to reimplement array functionality for a wrapper)

Edit: this idea courtesy of https://levelup.gitconnected.com/typesafe-frontend-development-89c7600f2759

**Comment by sledorze** [comment]
That looks indeed very interesting.
I'm unsure if there's some possible quirks (I'm more and more type-level suspicious with typescript).

**Comment by yawaramin** [comment]
@sledorze there may be some quirks but theoretically it is sound based on the fact that arrays are objects with their indices as properties and thus non-empty arrays _must_ have a property `0`. The implementation would really just need the type definition and a couple of helper functions to 'lift' regular arrays into non-empty arrays at the type level:

```typescript
type NonEmptyArray<A> = A[] & { 0: A };

/** User-defined type guard */
function isNonEmptyArray<A>(array: A[]): array is NonEmptyArray<A> {
    return array.length > 0;
}

/** Exception-throwing conversion function */
function nonEmptyArray<A>(array: A[]): NonEmptyArray<A> {
    if (isNonEmptyArray(array)) return array;
    throw new TypeError(`${array} is empty`);
}
```

**Comment by sledorze** [comment]
@yawaramin let's not throw some exceptions please; keep things value level.. (Option)

**Comment by sledorze** [comment]
I'm seeing where you want to go, but in the end, your proposal is just a predicate and a type alias (I've should have read more carefully).

What we're implementing provides alternatives to traditional js Array and also definitions for Type classes which a (albeit lightweight) alias representation cannot help with.

However, optimising the internal representation of NonEmptyArray may be something to consider.

**Comment by yawaramin** [comment]
@sledorze sure, throwing a TypeError is just one possible way to do it. You could also return an `Option<NonEmptyArray<A>>` or a `Result` or whatever. As to your second point, I don't see why `NonEmptyArray` needs to have an alternative _implementation;_ looking at the current code it seems that it just indirectly uses the existing JS Array implementation. And if you provide typeclass instances for `A[]` then shouldn't those instances automatically apply to `A[] & {0: A}`? After all the latter is just a subtype of the former.

**Comment by sledorze** [comment]
@yawaramin Its indeed possible you're right.

However as soon as you use the direct js Api, then you're back with an Array (and not a NonEmptyArray) OR you use a static-land API (static methods) so there's not less maintenance as we'll have to provide those methods anyway.

This leaves us with:

* Takes advantage of the type system
* Less allocations 

I do not see 'Takes advantages of the type system' as a feature but a mean.

So the advantage would be Less allocations with the tradeoff of API discoverability.

I'm half sold on it (and not sure if I covered everything).

Note: Maybe there's also a type level opportunity to address more cases generically (at least one element, at least two element, etc..)

Could it become a `fp-ts-contrib` feature to test it?

**Comment by yawaramin** [comment]
@sledorze that is a valid point indeed. I was hoping that it could be overcome at the type level. For example:

```typescript
type NonEmptyArray<A> = A[] & {
    0: A,
    map: <B>(
        callbackfn: (value: A, index: number, array: A[]) => B,
        thisArg?: any,
    ) => NonEmptyArray<B>,
};
```

I was thinking this intersection type would 'override' the `Array` type's `map` type definition to return a `NonEmptyArray`, that way we maintain the static guarantee of the type as long as we keep calling methods on it which are guaranteed to not make it empty.

However, it looks like my 'override' didn't take effect and the `Array` type's `map` type was used here:

```typescript
function test(): NonEmptyArray<number> {
    const result = nonEmptyArray([1]).map(x => x + 1);
    return result;
//  ^^^^^^^^^^^^^^
}
```

I'll see if I can find a way to make it hold.

**Comment by yawaramin** [comment]
OK, just figured it out :-) the trick is to use an actual interface, not a type alias:

```typescript
interface NonEmptyArray<A> extends Array<A> {
  0: A,
  map: <B>(
      f: (a: A, index: number, array: NonEmptyArray<A>) => B,
      thisArg?: any,
  ) => NonEmptyArray<B>,
};

/** User-defined type guard */
function isNonEmptyArray<A>(array: A[]): array is NonEmptyArray<A> {
  return array.length > 0;
}

/** Exception-throwing conversion function */
function nonEmptyArray<A>(array: A[]): NonEmptyArray<A> {
  if (isNonEmptyArray(array)) return array;
  throw new TypeError(`${array} is empty`);
}

function test(): NonEmptyArray<number> {
  const result = nonEmptyArray([1]).map(x => x + 1);
  return result;
}
```

This proves that we can provide safe types for all the relevant JS Array API method calls, and preserve the `NonEmptyArray` return type, _without_ reimplementing any of the methods themselves. So here are the full advantages I can think of:

- Take advantage of the type system
- Avoid the extra allocation
- Preserve all type safety guarantees without reimplementing another layer of function calls, less maintenance work

That said, this approach would not be a drop-in replacement for the current implementation as that currently has a superset of `Array` functionality. So it is probably a good candidate for contrib.

**Comment by sledorze** [comment]
@yawaramin is that a good time to close it? (in favor of a contrib issue?)

**Comment by yawaramin** [comment]
Sure, I'll explore contrib and figure out how best to add it there 👍

**Comment by gcanti** [comment]
If it's working fine we could deprecate the `NonEmptyArray` module in favour of a new `NonEmptyArray2v` module

**Comment by sledorze** [comment]
@gcanti I'm not sure to get what you're proposing here.
If we follow the current proposal, it means going full staticLand (like for `Map` actually), is it what you're thinking?

**Comment by sledorze** [comment]
oups, wrong button :)

**Comment by gcanti** [comment]
@sledorze if this works

```ts
interface NonEmptyArray<A> extends Array<A> {
  0: A,
  map: <B>(
      f: (a: A, index: number, array: NonEmptyArray<A>) => B,
      thisArg?: any,
  ) => NonEmptyArray<B>,
};
```

we could drop some methods and use the native ones:

- toArray (can be dropped)
- toArrayMap (can be dropped)
- concatArray (replaced by `concat` + overloading)
- map (overloading)
- mapWithIndex (native `map`)
- ap, ap_ (**removed**, goes to the instance)
- chain (**removed**, goes to the instance)
- concat (overloading)
- reduce (native)
- reduceWithIndex (native `reduce`)
- foldr, foldrWithIndex (native `reduceRight`)
- extend (**removed**, goes to the instance)
- extract (**removed**, goes to the instance)
- min (**removed**, goes to a static function)
- max (**removed**, goes to a static function)
- last (**removed**, goes to a static function)
- sort (overloading)
- reverse (overloading)
- length (native `length`)
- lookup (**removed**, goes to a static function)
- index (**removed**, goes to a static function)
- findFirst (**removed**, goes to a static function)
- findLast (**removed**, goes to a static function)
- findIndex (**removed**, goes to a static function)
- findLastIndex (**removed**, goes to a static function)
- insertAt (**removed**, goes to a static function)
- updateAt (**removed**, goes to a static function)
- filter (overloading)
- filterWithIndex (native `filter`)
- some (native)
- every (native)

That's a breaking change, so a new `NonEmptyArray2v` module (if we decide that it worths it).

**Comment by sledorze** [comment]
Crystal clear.

Also providing `head` and `tail`.

**Comment by sledorze** [comment]
Just about native methods, please bear in mind that kind of issues:
https://github.com/gcanti/fp-ts/issues/675

**Comment by gcanti** [comment]
Closing via https://github.com/gcanti/fp-ts/pull/763

@yawaramin @YBogomolov thanks for the idea
