### ISSUE TITLE
Change module system to UMD (from commonjs)

### ISSUE THREAD

**Issue by jjoekoullas** [gcanti/fp-ts#736]
**Do you want to request a _feature_ or report a _bug_?**
Feature - wider compatibility

**What is the current behavior?**
tsconfig.json - module is set to commonjs.  This means applications using AMD cannot use fp-ts.  This is easy to rectify by changing the module in tsconfig to UMD.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**
Build an application that uses AMD, install fp-ts, attempt to import and run anything within fp-ts.  An error that "exports" is not defined.

**What is the expected behavior?**
Able to use fp-ts in an AMD application.

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**
All

**Comment by gcanti** [comment]
> Build an application that uses AMD, install fp-ts, attempt to import and run anything within fp-ts. An error that "exports" is not defined

@jjoekoullas could you please put up a small repo containing a repro of this?

**Comment by jjoekoullas** [comment]
@gcanti https://github.com/jjoekoullas/fp-ts-amd

**Comment by gcanti** [comment]
Thanks @jjoekoullas 

- I put up branch with `"module": "umd"` and `lib` committed in
- cloned your repo
- changed `package.json` with

```diff
-    "fp-ts": "^1.13.0",
+    "fp-ts": "gcanti/fp-ts#umd",
```

- run `npm i`

Looks like is working as expected now. 

Could you please double check?

**Comment by jjoekoullas** [comment]
Yup, that works.

By the way, if you end up merging that branch into master, you can close https://github.com/gcanti/fp-ts/pull/737.  They're the same, aside from vendoring /lib/ as well.

**Comment by gcanti** [comment]
Closing via https://github.com/gcanti/fp-ts/pull/737
