### ISSUE TITLE
Webpack throwing error on build 

### ISSUE THREAD

**Issue by TheWix** [gcanti/fp-ts#745]
**Do you want to request a _feature_ or report a _bug_?**
Bug
**What is the current behavior?**
Cannot use the library

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**
Import a module like Either or Option
When I load the page I get this error:
Uncaught Error: Cannot find module './ChainRec'
    at webpackEmptyContext (app.js:11)
    at vendors.js:9477
    at vendors.js:9465
    at Object../node_modules/fp-ts/lib/Either.js (vendors.js:9474)
    at __webpack_require__ (bootstrap:781)
    at fn (bootstrap:149)
    at Object.<anonymous> (app.js:5064)
    at Object../src/middlewaire/airlineMiddleware.ts (app.js:5100)
    at __webpack_require__ (bootstrap:781)
    at fn (bootstrap:149)

With these warnings:
./node_modules/fp-ts/lib/Either.js 14:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
./node_modules/fp-ts/lib/ChainRec.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
./node_modules/fp-ts/lib/function.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
./node_modules/fp-ts/lib/Setoid.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**What is the expected behavior?**
I don't get a build error 

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**
fp-ts: 1.14.0
typescript: 3.2.2
browsers affected: Chrome and Firefox
OS: Windows

**Comment by mavax** [comment]
We are experiencing the same issue with v1.14.0.

**Comment by gcanti** [comment]
@TheWix I think that [switching to UMD](https://github.com/gcanti/fp-ts/commit/4e3aa83aadb877474d5af9dc88761e854e5854f9) might be the culprit.
I'll revert that change and release a patch.

/cc @jjoekoullas

**Comment by gcanti** [comment]
@TheWix @mavax patch released, could you please try it out?

**Comment by mavax** [comment]
@gcanti It works with v1.14.1, thanks!

**Comment by TheWix** [comment]
Confirmed. Thanks @gcanti!

**Comment by gcanti** [comment]
Nice, thanks for the report / feedback, closing.
