### ISSUE TITLE
Documentation: Links in Comparison with Ramda broken

### ISSUE THREAD

**Issue by thomascothran** [gcanti/fp-ts#752]
**Do you want to request a _feature_ or report a _bug_?**

Documentation bug

**What is the current behavior?**

The links in the [comparison with Ramda](https://github.com/gcanti/fp-ts/blob/master/ramda.md) are broken.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

Navigate to the [comparison with Ramda](https://github.com/gcanti/fp-ts/blob/master/ramda.md) and click any of the links on the right hand side of the comparison table.

**What is the expected behavior?**

The links should take you to the page for, e.g., Array.

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**

This worked prior to the new documentation going live.

**Cause**

It looks like the `ts` extension was added to the documentation filenames. For example, `docs/Array.ts.md` was previously `docs/Array.md`. The [comparison with Ramda](https://github.com/gcanti/fp-ts/blob/master/ramda.md) still points at older link.

I'm happy to submit a PR. The new docs look great!

**Comment by gcanti** [comment]
opss, good catch

> I'm happy to submit a PR. The new docs look great!

Thanks!
