### ISSUE TITLE
Question: How to use sequenceT with ApplicativeComposition?

### ISSUE THREAD

**Issue by raveclassic** [gcanti/fp-ts#767]
Hi, I'm trying to implement a type `type LiveData<L, A> = Stream<RemoteData<L, A>>` where `Stream` is a `most.js` observable (may be any other `Apply`).

I can easily get a `const sequenceTRD = sequenceT(remoteData)` but I'm stuck with a type alias `LiveData` because I can't define an instance of `Apply` for it, it clashes with an instance of `Stream`.
```typescript
type LiveData<L, A> = Stream<RemoteData<L, A>>
type URI = 'LiveData';
declare module 'fp-ts/lib/HKT' {
  interface URI2HKT2<L, A> {
    LiveData: LiveData<L, A>
  }
}
const liveData: Apply<URI> = {} //error
```

But there's a way to get applicative composition: `const streamRD = getApplicativeComposition(stream, remoteData)` where `stream` and `remoteData` are instances of `Applicative`.

Any thoughts on that? Maybe we could tweak `sequenceT` type signature somehow to accept `ApplicativeComposition` as well as `Apply`? Or maybe there's a proper way to handle such cases, perhaps with monad transformers?

**Comment by raveclassic** [comment]
I should also note that introducing a wrapper with a separate URI is not desirable.
```typescript
const URI = 'LiveData'
type URI = typeof URI
declare module 'fp-ts/lib/HKT' {
  interface URI2HKT2<L, A> {
    LiveData: LiveData<L, A>
  }
}
class LiveData<L, A> {
  readonly _URI!: URI
  readonly _L!: L
  readonly _A: A

  constructor(readonly stream$: Stream<RemoteData<L, A>>) { }
}
``` 

I'd like to keep the possibility to use `most.js` operators/functions with `LiveData` transparently.

**Comment by gcanti** [comment]
> I can't define an instance of Apply for it, it clashes with an instance of Stream

@raveclassic not sure what you mean, could you post a repro?

**Comment by raveclassic** [comment]
@gcanti Sure. Will take some time though

**Comment by raveclassic** [comment]
Well... Looks like my problem is solved with upgrading to latest `fp-ts@1.14.3` and `typescript@3.3.3`.
Here's the code:
```typescript
import { Option, option } from 'fp-ts/lib/Option';
import { Either, either } from 'fp-ts/lib/Either';
import { getApplicativeComposition } from 'fp-ts/lib/Applicative';
import { Apply2, sequenceT } from 'fp-ts/lib/Apply';

export const URI = 'Alias';
export type URI = typeof URI;

export type Alias<L, A> = Option<Either<L, A>>;
declare module 'fp-ts/lib/HKT' {
    interface URI2HKT2<L, A> {
        Alias: Alias<L, A>;
    }
}

const optionEither = getApplicativeComposition(option, either);

const map = <L, A, B>(fa: Alias<L, A>, f: (a: A) => B): Alias<L, B> => optionEither.map(fa, f);

// the error was here around `URI`
export const alias: Apply2<URI> = {
    URI,
    map: optionEither.map,
    ap: optionEither.ap,
};

const sequenceTAlias = sequenceT(alias);
declare const a: Alias<Error, number>;
declare const b: Alias<Error, string>;
const result = alias.map(sequenceTAlias(a, b), ([a, b]) => a + b); // Option<Either<Error, string>> - everything is fine
```

**Comment by gcanti** [comment]
@raveclassic that's because I removed some type-level checks in this commit

https://github.com/gcanti/fp-ts/commit/9735d77a29f3e2fabcee96694e907bc697008f70

Moreover I _think_ that we can get rid of all the readonly phantom fields defined in the data structures (`_A`, `_L`, etc...)

**Comment by raveclassic** [comment]
@gcanti Yeah, those `['_URI']` were the reason of errors.

**Comment by karthikiyengar** [comment]
Sorry for raising this issue from the dead:

```
const sequence = sequenceT(getApplicativeComposition(io, option));
const result = sequence(
  getItem("a"), // IO<Option<string>> (from fp-ts-local-storage)
  getItem("b"),
  getItem("c")
);
```
This dies with `error TS2345: Argument of type 'ApplicativeComposition11<"IO", "Option">' is not assignable to parameter of type 'Apply<{}>'.`

Anything I'm missing here?

**Comment by karthikiyengar** [comment]
@gcanti was kind enough to provide further explanation on Slack:

```
import { getApplicativeComposition, Applicative1 } from 'fp-ts/lib/Applicative'
import { IO, io } from 'fp-ts/lib/IO'
import { Option, option } from 'fp-ts/lib/Option'

declare module 'fp-ts/lib/HKT' {
  interface URI2HKT<A> {
    IOOption: IO<Option<A>>
  }
}

const URI = 'IOOption'
type URI = typeof URI

const { map, of, ap } = getApplicativeComposition(io, option)

// Applicative instance for IO<Option<A>>
const ioOption: Applicative1<URI> = {
  URI,
  map,
  of,
  ap
}
```

We have to define the augmented Applicative instance for our composed ADTs for it to work.
