### ISSUE TITLE
add AIO (Aff monad)

### ISSUE THREAD

**Issue by gcanti** [gcanti/fp-ts#78]
Reference implementation: https://github.com/slamdata/purescript-aff

**Comment by sledorze** [comment]
Hummm.. I see that Issue opened but some commits have been made.

Also a new Aff has been done in the slamdata repo recently.
It looks a bit more involved than what is in fp-ts repo currently

I'm wondering if it's not too much effort to maintain a port vs create some externs (if possible)
I am wondering what's your approach to this situation ?

**Comment by gcanti** [comment]
> Also a new Aff has been done in the slamdata repo recently

Yeah, I have to dig into that, and maybe write a standalone package. Closing this for now
