### ISSUE TITLE
add findFirstMap and findLastMap to Array

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts#788]
@gcanti do we want something more general? (`Foldable2v`)

**Comment by gcanti** [comment]
@sledorze what's `findFirstMap` / `findLastMap`?

**Comment by sledorze** [comment]
```typescript
  describe('findFirstMap', () => {
    it('`findFirstMap(arr, fun)` is equivalent to map and `head(mapOption(arr, fun)`', () => {
      fc.assert(
        fc.property(fc.array(fc.integer()), arr =>
          optionStringSetoid.equals(findFirstMap(arr, fun), head(mapOption(arr, fun)))
        )
      )
    })
  })

  describe('findLastMap', () => {
    it('`findLastMap(arr, fun)` is equivalent to `last(mapOption(arr, fun))`', () => {
      fc.assert(
        fc.property(fc.array(fc.integer()), arr =>
          optionStringSetoid.equals(findLastMap(arr, fun), last(mapOption(arr, fun)))
        )
      )
    })
  })
```

**Comment by sledorze** [comment]
```typescript
export const findFirstMap = <A, B>(arr: A[], f: (a: A) => Option<B>): Option<B> => {
  const len = arr.length
  for (let i = 0; i < len; i++) {
    const v = f(arr[i])
    if (v.isSome()) {
      return v
    }
  }
  return none
}

export const findLastMap = <A, B>(arr: A[], f: (a: A) => Option<B>): Option<B> => {
  const len = arr.length
  for (let i = len - 1; i >= 0; i--) {
    const v = f(arr[i])
    if (v.isSome()) {
      return v
    }
  }
  return none
}
```

**Comment by gcanti** [comment]
@sledorze I see.

> do we want something more general? (Foldable2v)

Not sure, a `Foldable2v.findFirstMap` would always scan the whole data structure, a specialized version for `Array` seems more optimized

**Comment by sledorze** [comment]
@gcanti that was my conclusion, and also I discovered that foldable2v `findFirst` must also scan the whole structure via its `reduce`.

https://github.com/gcanti/fp-ts/blob/master/src/Foldable2v.ts#L469

So would you accept a PR for those specialized versions of findFirstMap and findLastMap ?

Note: It looks like we generally don't have a way to implement an efficient `findFirst` solution generically in `fp-ts` (or basically anything that can stop eagerly).

**Comment by gcanti** [comment]
> So would you accept a PR for those specialized versions of findFirstMap and findLastMap ?

👍
