### ISSUE TITLE
sequenceT in v1.15.0 causes type exceptions

### ISSUE THREAD

**Issue by christianbradley** [gcanti/fp-ts#790]
Caused by #766 

It seems the new mapped types for sequenceT cause exceptions when working directly with the unknown type `F` - verified does not cause this exception in `v1.14.4`

Some suggestions to resolve:

1) Restore the previous interface for `sequenceT` but add a final case that falls back upon Mapped Tuple Types
2) Add `sequenceT2`, `sequenceT3`, or `sequenceTn` methods to utilize previous style

## Example
_Error caused in `factory` during call to `create`_

```ts
import { Apply1, sequenceT } from 'fp-ts/lib/Apply'
import { log } from 'fp-ts/lib/Console'
import { Type, URIS } from 'fp-ts/lib/HKT'
import { IO, io } from 'fp-ts/lib/IO'

export interface Entity<TData>
    extends Readonly<{
        uri: [string, string]
        data: TData
        createdAt: Date
        updatedAt: Date
    }> {}

export type Uri = [string, string]

export interface UserData extends Readonly<{ email: string }> {}
export interface User extends Entity<UserData> {}

export type Factory<F extends URIS, T, R> = (data: T) => Type<F, R>

export const uri = (domain: string, id: string): Uri => [domain, id]

export const create = <TData>(uri: Uri, data: TData, t: Date): Entity<TData> => ({
    uri,
    data,
    createdAt: t,
    updatedAt: t
})

export const factory = <F extends URIS>(F: Apply1<F>, fDate: Type<F, Date>) => <TData>(
    fUri: Type<F, Uri>
): Factory<F, TData, Entity<TData>> => (data: TData) =>
    F.map(sequenceT(F)(fUri, fDate), ([uri, t]) => create(uri, data, t))

const ioTestDate = new IO(() => new Date('2018-01-01T00:00:00Z'))
const ioTestEntity = factory(io, ioTestDate)

const ioTestUserUri = new IO(() => uri('user', 'user1'))
const testUserFactory: Factory<'IO', { email: string }, User> = ioTestEntity(ioTestUserUri)

testUserFactory({ email: 'me@example.com' })
    .chain(log)
    .run()
```

## Expected Output 
```
{ uri: [ 'user', 'user1' ],
  data: { email: 'me@example.com' },
  createdAt: 2018-01-01T00:00:00.000Z,
  updatedAt: 2018-01-01T00:00:00.000Z }
```

## Actual Result
```
src/example.ts(33,59): error TS2345: Argument of type 'Type<F, [string, string]> extends Type<F, infer A> ? A : never' is not assignable to parameter of type '[string, string]'.
  Type '{}' is missing the following properties from type '[string, string]': 0, 1, length, pop, and 28 more.
```

**Comment by gcanti** [comment]
@christianbradley thanks for the report, a smaller repro

```ts
import { Apply1, sequenceT } from 'fp-ts/lib/Apply'
import { Type, URIS } from 'fp-ts/lib/HKT'

declare function f(s: string, n: number): boolean

export function factory<F extends URIS>(
  F: Apply1<F>,
  fs: Type<F, string>,
  fn: Type<F, number>
): Type<F, boolean> {
  return F.map(sequenceT(F)(fs, fn), ([s, n]) => f(s, n)) // Type '{}' is not assignable to type 'string'
}
```

Looks like TypeScript is checking the implementation against all the type constructors listed in `URIS` and then fails to resolve `Type<F, string> extends Type<F, infer A> ? A : never`.

When `F` is generic my advice is working with `HKT` instead of `Type`, `Type2`, etc...

```ts
import { Apply, Apply1, sequenceT } from 'fp-ts/lib/Apply'
import { HKT, Type, URIS } from 'fp-ts/lib/HKT'

export function factory<F extends URIS>(
  F: Apply1<F>,
  fs: Type<F, string>,
  fn: Type<F, number>
): Type<F, boolean>
export function factory<F>(F: Apply<F>, fs: HKT<F, string>, fn: HKT<F, number>): HKT<F, boolean> {
  return F.map(sequenceT(F)(fs, fn), ([s, n]) => f(s, n)) // ok
}
```

**Comment by christianbradley** [comment]
@gcanti  Thanks for the tip! 

Do you have any thoughts on modifying sequenceT towards backwards compatibility with <=v1.14.4?

**Comment by gcanti** [comment]
@christianbradley that would kinda defeat the very purpose of switching to mapped tuples in order to remove tons of overloadings. Also keep in mind that working with `HKT` is actually a best practice, otherwise TypeScript will do more work than necessary to type check your code.

**Comment by scink** [comment]
but it's a breaking change in the minor update, isn't it?
i've got some broken code after update as well

**Comment by gcanti** [comment]
@scink could you please post a repro?

**Comment by scink** [comment]
we have a library with utils, for example this
https://github.com/devex-web-frontend/dx-platform/blob/master/packages/utils/src/adt/option.utils.ts
and if you try to use `sequenceTOption`, you get an error. after compiling `.d.ts` for this file looks like this
![Screen Shot 2019-04-04 at 18 50 35](https://user-images.githubusercontent.com/15276485/55569632-8f7af400-570a-11e9-9d80-762adfc07d4c.png)
error looks like this
![Screen Shot 2019-04-04 at 18 52 37](https://user-images.githubusercontent.com/15276485/55569818-e4b70580-570a-11e9-83ca-e448d11bcc66.png)

**Comment by gcanti** [comment]
@scink at the first glance it seems a different problem, `SequenceT1` doesn't exists anymore (which explains the first error message), where does it come from? And why TypeScript is trying to use a missing type while outputting the declaration file? `dx-platform` is a multi package project, is it possible that you have multiple versions of `fp-ts`?

**Comment by scink** [comment]
`SequenceT1` really doesn't exist anymore, and that happened in https://github.com/gcanti/fp-ts/commit/5572016696e311481e10c819e368233559a29d84#diff-064161239b32665d744731717b85998c
as i understand, that came with some minor update (1.15.0, i believe) but it contains breaking changes.

an error comes from the file `option.utils.d.ts`, compiled for `option.utils.ts` i linked above.
![Screen Shot 2019-04-04 at 19 14 48](https://user-images.githubusercontent.com/15276485/55571857-0adea480-570f-11e9-9cd6-38483952bec1.png)

there is only 1 version of `fp-ts` in `dx-platform`, `1.12.0`. `fp-ts` is in peer dependencies, so package uses project version, that doesn't have what it needs.

**Comment by gcanti** [comment]
@scink what I meant is that in your source:

```ts
import { sequenceT } from 'fp-ts/lib/Apply';
import { Option, option } from 'fp-ts/lib/Option';

export const sequenceTOption = sequenceT(option);

export type OptionType<FA extends Option<any>> = FA extends Option<infer A> ? A : never;
```

you are not using the `SequenceT1` type explicitly. 

Since that type doesn't exists anymore, how can TypeScript write `import("fp-ts/lib/Apply").SequenceT1<"Option">` in the defintion file to type the constant `sequenceTOption`? 

Seems impossible if it's actually using version `1.15.0`.

So my supposition is that TypeScript is somehow pulling `SequenceT1` from a previous version of `fp-ts` where that type still exists.

@christianbradley I was playing again with this repro

```ts
import { Apply1, sequenceT } from 'fp-ts/lib/Apply'
import { Type, URIS } from 'fp-ts/lib/HKT'

declare function f(s: string, n: number): boolean

export function factory<F extends URIS>(
  F: Apply1<F>,
  fs: Type<F, string>,
  fn: Type<F, number>
): Type<F, boolean> {
  return F.map(sequenceT(F)(fs, fn), ([s, n]) => f(s, n)) // Type '{}' is not assignable to type 'string'
}
```

I think I found a fix using the `[]` syntax for conditional types (which prevents distribution)

```diff
export function sequenceS<F extends URIS>(
  F: Apply1<F>
): <R extends Record<string, Type<F, any>>>(
  r: EnforceNonEmptyRecord<R>
-) => Type<F, { [K in keyof R]: R[K] extends Type<F, infer A> ? A : never }>  
+) => Type<F, { [K in keyof R]: [R[K]] extends [Type<F, infer A>] ? A : never }>
```

**Comment by gcanti** [comment]
@scink rereading this 

> there is only 1 version of fp-ts in dx-platform, 1.12.0. fp-ts is in peer dependencies, so package uses project version, that doesn't have what it needs.

I think I missed your point. You are saying that:

- `dx-platform` is compiled with `fp-ts@1.12.0`
- but is consumed by another project that uses `fp-ts@1.15.0` and here you are getting an error

is it right?

**Comment by scink** [comment]
Yes, that's right

**Comment by gcanti** [comment]
@scink I released a patch (`1.15.1`) could you please try it out?

**Comment by scink** [comment]
@gcanti, yes, it work. thank you!

**Comment by gcanti** [comment]
Nice. Closing this, thanks for the feedback
