### ISSUE TITLE
Simper functions for primitive types similar to lodash

### ISSUE THREAD

**Issue by user753** [gcanti/fp-ts#795]
For example when I have an array with numbers or strings I would like to white something like this
```
uniqStrict([1, 1, 2, 2])
uniqStrict(["a", "a", "b", "b"])
```
instead of 
```
uniq(setoidNumber)([1, 1, 2, 2, 3, 3])
uniq(setoidString)(["a", "a", "b", "b"])
```
and also
```
uniqStrictBy([{foo: 1},{foo: 1}, {foo: 2}, {foo: 2})], x => x.foo)
```
Could `fp-ts` have functions like that or maybe it could be a separate package?

**Comment by gcanti** [comment]
@user753 what's the signature of `uniqStrict`?

**Comment by user753** [comment]
@gcanti 
```
type Primitive = number | string | boolean
declare function uniqStrict<T extends Primitive>(array: T[]): T[]
declare function uniqStrictBy<T, K extends Primitive>(array: T[], f: Function1<T, K>): T[]
```

**Comment by raveclassic** [comment]
Looks like `contramap`:
```typescript
type Item = { foo: unknown }
const setoidItem: Setoid<Item> = contramap(item => item.foo, setoidStrict)
```

**Comment by user753** [comment]
@raveclassic Yes, it's possible to use `contramap`, but it's just too much code compare to lodash.
Personally I don't like `lodash` because it's js library so it has some weird typings but I cannot find a good alternative.

**Comment by raveclassic** [comment]
Well, `fp-ts` core is too generic for such helpers. I guess `fp-ts-contrib` could be a better place for them.
