### ISSUE TITLE
`fromLeft` is not in `taskEither` variable

### ISSUE THREAD

**Issue by ryota-ka** [gcanti/fp-ts#805]
**Do you want to request a _feature_ or report a _bug_?**

feature

**What is the current behavior?**

`fromLeft` is missing in `taskEither` variable.
https://github.com/gcanti/fp-ts/blob/33b3ca2fead28601e35e73b2e51952b6575e4f90/src/TaskEither.ts#L386-L396

A function with a general name like `fromLeft` tends to be defined in several modules.
(Currently `fromLeft` seem to be defined in `IOEither`, `ReaderTaskEither`, and `TaskEither`.)

This causes users somewhat confused when importing such a function (particularly when using auto-import), and it makes it more difficult to grasp which module the function is imported from at a glance.

**What is the expected behavior?**

`fromLeft` (and other functions, also) is exported as a property of `taskEither` variable.

```typescript
import { TaskEither, taskEither } from 'fp-ts/lib/TaskEither';

const TaskEither<L, A> = taskEither.fromLeft(...);
```

And/or, `fromLeft` is defined as a static method of `TaskEither` class.

```typescript
import { TaskEither } from 'fp-ts/lib/TaskEither';

const TaskEither<L, A> = TaskEither.fromLeft(...);
```

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**

v1.15.0

**Comment by giogonzo** [comment]
Hi @ryota-ka, `taskEither` (and any other fp-ts instances) only contains the properties and methods required by the instances it implements (`Monad2<URI> & Bifunctor2<URI> & Alt2<URI> & MonadIO2<URI> & MonadTask2<URI>` in this case). Other utility functions are exported top-level by TaskEither as well as any other module.

If it helps, if dealing with imports from different fp-ts files, I'm usually doing something
```
import * as TE from 'taskEither'
// use TE.taskEither for the instance
// TE.TaskEither for the type
// TE.fromLeft for the helpers
// etc.
```

**Comment by gcanti** [comment]
`fromLeft` can be abstracted by introducing `MonadThrow`, I'll send a PR

**Comment by gcanti** [comment]
PR: https://github.com/gcanti/fp-ts/pull/810

@ryota-ka you will be able to use `throwError` as a property of `taskEither`

```ts
import { TaskEither, taskEither } from 'fp-ts/lib/TaskEither';

//              same as fromLeft ---v
const TaskEither<L, A> = taskEither.throwError(...);
```

**Comment by gcanti** [comment]
Closing via https://github.com/gcanti/fp-ts/pull/810
