### ISSUE TITLE
Drop phantom fields?

### ISSUE THREAD

**Issue by gcanti** [gcanti/fp-ts#806]
@sledorze @raveclassic the internals of `fp-ts` don't rely on the presence on those phantom fields anymore (`_A`, `_L`, etc...), do we want to try to remove them ~and ship version `1.16`~ in future releases? This would allow to test this change in the wild (and overall it's quite easy to revert in case of issues)

**Comment by raveclassic** [comment]
Yeah, let's try to drop them. However I won't be able to test the changes in production env/projects _soon_.

**Comment by sledorze** [comment]
I can try on our code base this week.
It will surely breaks some stuff.
:)
