### ISSUE TITLE
Record's `toArray` is sorting output when it maybe shouldn't.

### ISSUE THREAD

**Issue by quicksnap** [gcanti/fp-ts#825]
Code causing issue: https://github.com/gcanti/fp-ts/blame/b3e87a1a925aef6cfcdf4846a366efd922b3d5a4/src/Record.ts#L39

**Do you want to request a _feature_ or report a _bug_?**
Unsure.

**What is the current behavior?**
`toArray` causes `sort()` before output.

**What is the expected behavior?**
No sort? Maybe?

# Detail:

Record keys in JS having ordering, and that ordering is maintained in `Object.entries`/`Object.keys` etc.

When calling `toArray` on an object, the key ordering isn't maintained, due to aforementioned `sort()` code.

While relying on record entry ordering is not a great practice, should `toArray` buck against the behavior of `Object.entries`?

**Comment by quicksnap** [comment]
Also, unnecessary `sort` adds a little bit of a performance drawback.

**Comment by gcanti** [comment]
@quicksnap `sort` is necessay otherwise `toArray` (and `collect`) wouldn't be coherent with record equality

```ts
import { getSetoid } from 'fp-ts/lib/Record'
import { setoidNumber } from 'fp-ts/lib/Setoid'

function collect<A, B>(d: Record<string, A>, f: (k: string, a: A) => B): Array<B> {
  const out: Array<B> = []
  const keys = Object.keys(d) // .sort()
  for (const key of keys) {
    out.push(f(key, d[key]))
  }
  return out
}

function toArray<A>(d: Record<string, A>): Array<[string, A]> {
  return collect(d, (k, a: A) => [k, a])
}

const S = getSetoid(setoidNumber)

const x: Record<string, number> = { a: 1, b: 2 }
const y: Record<string, number> = { b: 2, a: 1 }

// `x` is equal to `y`...
console.log(S.equals(x, y)) // => true

// ...but `toArray(x)` is NOT equal to `toArray(y)`

console.log(toArray(x)) // [ [ 'a', 1 ], [ 'b', 2 ] ]
console.log(toArray(y)) // [ [ 'b', 2 ], [ 'a', 1 ] ]
```

**Comment by sledorze** [comment]
@quicksnap `fp-ts` is geared towards correctness, in the mathematical sense.

**Comment by jleider** [comment]
I realize this is an old bug but I just ran into this issue as well which was completely unexpected. 

The reasoning behind the `sort` makes sense in this context.  However in the context of a normal JS object its unexpected. I think most of the confusion could be cleared up by a simple mention in the docs that `toArray` performs a `sort` and does not respect the native JS object ordering, maybe with a suggestion to use `Object.entries` in cases where maintaining the native order is important.

**Comment by gcanti** [comment]
> which was completely unexpected

@jleider I think that it's unexpected because nothing in its signature signals that the keys need to be ordered, we should explicitly ask an `Ord` to the user IMO (which by the way would allow for an hacky way to get the insertion order by passing the trivial `Ord`)

**Comment by jleider** [comment]
> we should explicitly ask an `Ord`

Yes that is a great idea. I like it.
