### ISSUE TITLE
Contribution request: any / all functions for Foldable

### ISSUE THREAD

**Issue by quicksnap** [gcanti/fp-ts#826]
**Do you want to request a _feature_ or report a _bug_?**

Feature

# Detail

Would be great to have fp-ts equivalent to https://lodash.com/docs/#some and https://lodash.com/docs/#every

FP-equivalent names would be `exists/some/any` and `all/every`

Willing to accept a contribution for this? @joshburgess or I can work something into our codebase and issue a PR against here as well.

**Comment by quicksnap** [comment]
Mentioned in title: This would be in `Foldable`

**Comment by gcanti** [comment]
@quicksnap ok. 

A couple of comments:

- `some` / `every` should go in `Foldable2v` (`Foldable` is deprecated)
- `some` won't be optimized (scans the whole data structure instead of bail out at the first `false`)

**Comment by gcanti** [comment]
> some / every won't be optimized (they will scan the whole data structure instead of bail out at the first true / false)

I think it's better to provide individual and optimized functions related to the particular data structure at hand, closing this.
