### ISSUE TITLE
How to perform group/reduce operations on non empty arrays while keeping a non empty array return type

### ISSUE THREAD

**Issue by Eldow** [gcanti/fp-ts#831]
Hi,

I am facing a case where I want to group two non empty arrays into one. I need to apply some inner operations when there are conflicts between the elements of the arrays, so Maps or Records combined with semigroup looked like the way to go. But i can't find a way to turn my resulting map back into a NonEmptyArray.

Example :

``` typescript

interface BookPrice {
  supplier: BookSupplier,
  price: number
}

interface Book {
  author: Author
  prices: [BookPrice]
}

const booksA = make({
    author: 'Zola', 
    prices: make({ supplier: 'Fnac', price: 40 }, [{ supplier: 'Sunbelt', price: 30 }])
  }, [
  { 
    author: 'Verlaine', 
    prices: make({ supplier: 'Amazon', price: 20 }, [])
}])

const booksB = make({
  author: 'Zola',
  prices: make({ supplier: 'Amazon', price: 35 }, [])
}, [])

const allBooks = booksA.concat(booksB)

const semigroupBook: Semigroup<Book> = {
  concat(a, b) => {
    ...a,
    prices: a.prices.concat(b.prices)
  }
}
```

I did an attempt using Map and fromFoldable to concat my prices and then using values to get back my non empty array of books 
``` typescript

const mapByAuthor = map.fromFoldable(authorSetoid, array)
const booksMap = mapByAuthor(
  allBooks.map(g => [g.author, g]),
  semigroupBook.concat
)

values(ordBooksByAuthor)(booksMap) // returns an array
```

I also tried using non empty array's groupBy built-in function, but I face the same problem with it to get back to a non empty array
``` typescript

  const booksRecord = nonEmptyArray.groupBy(allBooks, g => g.author))
  const withReducedPrices = record.map(booksRecord, (value) => value.reduce(semigroupBook.concat))

```
I can't find a way to turn my records or maps built from non empty arrays back to non empty arrays.
Is there any way of achieving this kind of operation without losing the non empty array type ?

Thank you for reading !

**Comment by cyberixae** [comment]
I also run into some similar situations. Maybe with arrays or partials or both. Can't remember exactly. I was hoping to find some tools which would convert the array or partial into an either that would separate the two cases and let you deal with them separately. However, I wasn't able to find such tools.

In my head such tools would look roughly as follows
```
fromPossiblyEmptyArray([1, 2, 3]).fold{
  (arr: []) => ...
  (arr: NonEmpty<...>) => ...
}

fromPossiblyEmptyPartial({ foo: 123 }).fold{
  (arr: {}) => ...
  (arr: NonEmpty<...>) => ...
}
```

**Comment by Eldow** [comment]
There still is `fromArray` that will allow you to fold on an Option.

eg.
``` typescript
const optionalNonEmptyArray = fromArray([1, 2, 3]) 
// --> Option<NonEmptyArray<number>>

const eitherNonEmptyArray = fromOption(new Error('The array is empty'))(optionalNonEmptyArray) 
// --> <Either<Error, NonEmptyArray<number>>>
```

And I'm totally fine doing this after filtering an array, or doing removal operations.

In my case, I would like operations that implicitly are not capable of transforming non empty arrays into arrays (on my example, some sort of group by) to not destroy the typing and therefore forcing to do unnecessary operations. It could maybe be possible with a non empty map type where the values function would return a non empty array.

**Comment by gcanti** [comment]
I'll add a overloading to NEA.group managing non empty arrays

Before

```ts
export function group<A>(E: Eq<A>): (as: Array<A>) => Array<NonEmptyArray<A>>
```

After

```ts
export function group<A>(
  E: Eq<A>
): {
  (as: NonEmptyArray<A>): NonEmptyArray<NonEmptyArray<A>>
  (as: Array<A>): Array<NonEmptyArray<A>>
}
```

Example

```ts
//
// fp-ts@2.x
//

import * as E from '../src/Eq'
import * as NEA from '../src/NonEmptyArray'
import { pipe } from '../src/pipeable'
import * as S from '../src/Semigroup'

type BookSupplier = string
type Author = string

interface BookPrice {
  supplier: BookSupplier
  price: number
}

interface Book {
  author: Author
  prices: NEA.NonEmptyArray<BookPrice>
}

const booksA: NEA.NonEmptyArray<Book> = [
  {
    author: 'Zola',
    prices: [
      { supplier: 'Fnac', price: 40 },
      { supplier: 'Sunbelt', price: 30 }
    ]
  },
  {
    author: 'Verlaine',
    prices: [{ supplier: 'Amazon', price: 20 }]
  }
]

const booksB: NEA.NonEmptyArray<Book> = [
  {
    author: 'Zola',
    prices: [{ supplier: 'Amazon', price: 35 }]
  }
]

const allBooks = NEA.concat(booksA, booksB)

const eqBook: E.Eq<Book> = pipe(
  E.eqString,
  E.contramap(book => book.author)
)

const semigroupBook: S.Semigroup<Book> = {
  concat: (a, b) => ({
    ...a,
    prices: NEA.concat(a.prices, b.prices)
  })
}

// groups: NEA.NonEmptyArray<NEA.NonEmptyArray<Book>>
const groups = NEA.group(eqBook)(allBooks)

// books: NEA.NonEmptyArray<Book>
export const books = pipe(
  groups,
  NEA.map(group => S.fold(semigroupBook)(NEA.head(group), NEA.tail(group)))
)
```
