### ISSUE TITLE
Using tuples with sequences

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#84]
I have a tuple of two options, one containing string and one containing number. I want to sequence them, and then access the sequenced tuple type from functions such as `map`.

Example:

``` ts
{
    const typecheck = <T>(t: T) => t;

    type OptionTuple2 = tuple.Tuple<option.Option<string>, option.Option<number>>;
    const optionTuple2 = typecheck<OptionTuple2>([
        option.some('foo'),
        option.some(1),
    ]);

    const sequenceOptionArray = traversable.sequence(option, array);
    sequenceOptionArray(optionTuple2); // errors
    sequenceOptionArray<[string, number]>(optionTuple2); // errors
    sequenceOptionArray<string | number>(optionTuple2); // works
}
```

Ideally, when mapping over the result of `sequenceOptionArray`, the type of the value in the sequenced `Option` would be the sequenced tuple:

``` ts
const sequenced = sequenceOptionArray(optionTuple2);
sequenced.map(([ str, num ]) => str)
```

Do you have any idea if this is possible with TypeScript?

**Comment by gcanti** [comment]
> Do you have any idea if this is possible with TypeScript?

Is not possible in *theory*. 

You can't sequence a tuple with `array`'s applicative. That should explain why you get 2 errors and why `sequenceOptionArray<string | number>(optionTuple2)` works, I guess TypeScript is interpreting the tuple as a `Array<number | string>` in that case.

With tuples sequencing works only on the second coordinate

```ts
const x1 = tuple.traverse(option)(x => x, ['a', option.some(2)]) // some(['a', 2])
const x2 = tuple.traverse(option)(x => x, ['a', option.none]) // none
```

**Comment by OliverJAsh** [comment]
Aha, I was using the array applicative instead of tuple. I get those two things confused in my head because TypeScript re-uses arrays for tuples.

> With tuples sequencing works only on the second coordinate

``` ts
{
    type OptionTuple2 = tuple.Tuple<option.Option<string>, option.Option<number>>;
    const optionTuple2 = typecheck<OptionTuple2>([
        option.some('foo'),
        option.some(1),
    ]);

    const traversed = tuple.traverse(option)(x => x, optionTuple2)

    traversed.map(([ str, num ]) => str)
}
```

In this example, `str` has type `Option<string>` (incorrect) whereas num has type `number` (correct). 

Is there any way to fix this, so traversing a tuple uses all the coordinates?

**Comment by OliverJAsh** [comment]
Re-read your response—I think I understand now. The types are correct: tuple’s traverse only works on the second coordinate? I would be interested to hear why that is.

For context, I have two Options with different value types, and I want to map over the sequenced Option to access those different values. It seems there is no way to do this whilst retaining correct type inference?

**Comment by gcanti** [comment]
> tuple’s traverse only works on the second coordinate? I would be interested to hear why that is

With respect to types arrays and tuples are very different

- `Array<A>` is a type contructor with kind `* -> *` <= you can interpret this symbol as a type level function: you put a type in (the first `*`) then you get a type out (the second `*`)
- `Tuple<A, B>` is a type constructor with kind `* -> * -> *`: you put a type in (the first `*`) then you put another type in (the second `*`) and then you get a type out (the third `*`)

Now the fundamental thing to know is that functor instances can **only** be defined for type constructors of kind `* -> *`, there must be only one type parameter. So

- `Array<A>` is ok, one type parameter
- `Option<A>` is ok, one type parameter
- `Either<L, A>` is NOT ok, **two** type parameters

`Either<L, A>` has kind `* -> * -> *`, how can we define a functor instance? There are two free type parameter! The trick is to choose a type parameter and then to consider that type as fixed. It's like partially applying the type level function: if you fix `L` (the first `*` in `* -> * -> *`) you get a kind `* -> *` and now you can try to find a functor instance. Indeed the `map` defined for `Either` works on the `A` type parameter while `L` is fixed

```ts
// here L is fixed, can't change while mapping
export function map<L, A, B>(f: (a: A) => B, fa: Either<L, A>): Either<L, B> {
  ...
}
```

The same thing happens for tuples: a `Tuple<A, B>` has kind `* -> * -> *` so we need to fix a type parameter, in this case `A` and try to define a functor instance that works on `B` (i.e. the second coordinate)

```ts
export function map<A, B, C>(f: (b: B) => C, ab: Tuple<A, B>): Tuple<A, C> {
  return [ab[0], f(ab[1])]
}
```

> I have two Options with different value types, and I want to map over the sequenced Option to access those different values. It seems there is no way to do this whilst retaining correct type inference?

You can achieve the same thing by lifting the tuple constructor in the `Option` context and then mapping the result

```ts
import * as option from 'fp-ts/lib/Option'
import { Option } from 'fp-ts/lib/Option'
import * as tuple from 'fp-ts/lib/Tuple'
import { liftA2 } from 'fp-ts/lib/Apply'

type Tuple2 = tuple.Tuple<string, number>

type Tuple2Option = tuple.Tuple<option.Option<string>, option.Option<number>>

// tuple constructor
const toTuple2 = (a: string, b: number): Tuple2 => [a, b]

// lifted tuple constructor
const maybeToTuple2 = liftA2(option, (a: string) => (b: number) => toTuple2(a, b))

// helper Tuple2Option -> Option<Tuple2>
const toOptionTuple2 = (t: Tuple2Option) => maybeToTuple2(t[0], t[1])

const tuple2Option = [
  option.some('foo'),
  option.some(1)
] as Tuple2Option

const x = toOptionTuple2(tuple2Option)
x.map(([ str, num ]) => str)
```

Being able to lift a function is actually the reason why `traverse` and `sequence` require an `applicative` instance, see for example the implementation of `traverse` for arrays https://github.com/gcanti/fp-ts/blob/ffa791d5f0cb53dc47f196d71d94de9a6f264cad/src/Array.ts#L64

**Comment by OliverJAsh** [comment]
Ahh, this makes sense.

I took your example, generalised it a bit, and also made equivalent functions for `Either` and `EitherT`. Posting here in case it's useful to anyone:

``` ts
import { option, tuple, apply, either, eitherT, task, hkt } from 'fp-ts';

// tuple constructor
const toTuple2 = <A, B>(a: A, b: B): tuple.Tuple<A, B> => [a, b];

//
// Option
//

// lifted tuple constructor
const maybeToTuple2 = <A, B>(fa: option.Option<A>, fb: option.Option<B>) => (
    apply.liftA2(option, (a: A) => (b: B) => toTuple2(a, b))(fa, fb)
);

type Tuple2Option<A, B> = tuple.Tuple<option.Option<A>, option.Option<B>>;

export const toOptionTuple2 = <A, B>(t: Tuple2Option<A, B>) => maybeToTuple2(t[0], t[1]);

//
// Either
//

// lifted tuple constructor
const eitherToTuple2 = <L, A, B>(fa: either.Either<L, A>, fb: either.Either<L, B>) => (
    apply.liftA2(either, (a: A) => (b: B) => toTuple2(a, b))(fa, fb)
);

type Tuple2Either<L, A, B> = tuple.Tuple<either.Either<L, A>, either.Either<L, B>>;

export const toEitherTuple2 = <L, A, B>(t: Tuple2Either<L, A, B>) => eitherToTuple2(t[0], t[1]);

//
// EitherT
//

// TODO: Replace with getStaticMonad
const eitherTApplicative = {
    URI: eitherT.URI as eitherT.URI,
    of: eitherT.of(task),
    map<L, A, B>(f: (a: A) => B, fa: eitherT.EitherT<task.URI, L, A>) {
        return eitherT.map(f, fa);
    },
    ap<L, A, B>(
        fab: eitherT.EitherT<task.URI, L, (a: A) => B>,
        fa: eitherT.EitherT<task.URI, L, A>,
    ) {
        return eitherT.ap(fab, fa);
    },
};

// lifted tuple constructor
const eitherTToTuple2 = <M extends hkt.HKTS, L, A, B>(
    fa: eitherT.EitherT<M, L, A>,
    fb: eitherT.EitherT<M, L, B>,
) => (
    apply.liftA2(eitherTApplicative, (a: A) => (b: B) => toTuple2(a, b))(fa, fb)
);

export type Tuple2EitherT<M extends hkt.HKTS, L, A, B> = (
    tuple.Tuple<eitherT.EitherT<M, L, A>, eitherT.EitherT<M, L, B>>
);

export const toEitherTTuple2 = <M extends hkt.HKTS, L, A, B>(
    t: Tuple2EitherT<M, L, A, B>,
) => eitherTToTuple2(t[0], t[1]);
```

**Comment by gcanti** [comment]
Another interesting generalisation: applicative functors are equivalent to strong lax monoidal functors 

- https://wiki.haskell.org/Typeclassopedia#Alternative_formulation
- https://bartoszmilewski.com/2017/02/06/applicative-functors/

The definition of `Monoidal` in PureScript

```purescript
class Functor f => Monoidal f where
  unit :: a -> f a 
  mult :: f a -> f b -> f (a,b)
```

And in TypeScript

```ts
import { HKT, HKTS } from 'fp-ts/lib/HKT'
import { StaticFunctor } from 'fp-ts/lib/Functor'
import { StaticApplicative } from 'fp-ts/lib/Applicative'

export interface StaticMonoidal<F extends HKTS> extends StaticFunctor<F> {
  readonly URI: F
  unit(): HKT<void>[F]
  mult<A, B>(fa: HKT<A>[F], fb: HKT<B>[F]): HKT<[A, B]>[F]
}
```

Note that `mult` is the operation we are interested in. We can define a `fromApplicative` function which transform a `Applicative` to a `Monoidal`

```ts
const toTuple = <A>(a: A) => <B>(b: B): [A, B] => [a, b]

export function fromApplicative<F extends HKTS>(applicative: StaticApplicative<F>): StaticMonoidal<F> {
  return {
    URI: applicative.URI,
    map: applicative.map,
    unit(): HKT<void>[F] {
      return applicative.of(undefined)
    },
    mult<A, B>(fa: HKT<A>[F], fb: HKT<B>[F]): HKT<[A, B]>[F] {
      return applicative.ap<B, [A, B]>(applicative.ap<A, (b: B) => [A, B]>(applicative.of(toTuple), fa), fb)
    }
  }
}
```

Finally

```ts
import * as tuple from 'fp-ts/lib/Tuple'
import * as option from 'fp-ts/lib/Option'
import * as either from 'fp-ts/lib/Either'
import * as task from 'fp-ts/lib/Task'
import * as eitherT from 'fp-ts/lib/EitherT'

function multTuple<F extends HKTS>(applicative: StaticApplicative<F>): <A, B>(tuple: [HKT<A>[F], HKT<B>[F]]) => HKT<[A, B]>[F] {
  const mult = fromApplicative(applicative).mult
  return <A, B>(tuple: [HKT<A>[F], HKT<B>[F]]) => mult(tuple[0], tuple[1])
}

type Tuple2 = tuple.Tuple<string, number>

type Tuple2Option = tuple.Tuple<option.Option<string>, option.Option<number>>

const tuple2Option = [
  option.some('foo'),
  option.some(1)
] as Tuple2Option

console.log(multTuple(option)(tuple2Option)) // Some(["foo",1])
console.log(multTuple(option)([option.some('foo'), option.none])) // None

console.log(multTuple(either)([either.right('foo'), either.right(1)])) // Right(["foo",1])
console.log(multTuple(either)([either.right('foo'), either.left('error')])) // Left("error")

const eitherTaskApplicative = eitherT.getStaticMonad(task)
const of = eitherTaskApplicative.of as <L, A>(a: A) => eitherT.EitherT<task.URI, L, A>
const left = eitherT.left(task)

multTuple(eitherTaskApplicative)([of('foo'), of(1)]).value.run().then((x: any) => console.log(x)) // Right(["foo",1])
multTuple(eitherTaskApplicative)([of('foo'), left(task.of('error'))]).value.run().then((x: any) => console.log(x)) // Left("error")
```

**Comment by OliverJAsh** [comment]
Hi @gcanti, I'm upgrading to fp-ts 0.3 and I noticed that `EitherT` has changed signature, so the examples above no longer work.

Do you have any idea how to rewrite this code to work with the new signatures?

``` ts
import { tuple, apply, eitherT, hkt } from 'fp-ts';

// tuple constructor
const toTuple2 = <A, B>(a: A, b: B): tuple.Tuple<A, B> => [a, b];

// lifted tuple constructor
const eitherTToTuple2 = <M extends hkt.HKTS, L, A, B>(
    fa: eitherT.EitherT<M, L, A>,
    fb: eitherT.EitherT<M, L, B>,
) => (
    apply.liftA2(eitherT, (a: A) => (b: B) => toTuple2(a, b))(fa, fb)
);

type Tuple2EitherT<M extends hkt.HKTS, L, A, B> = (
    tuple.Tuple<eitherT.EitherT<M, L, A>, eitherT.EitherT<M, L, B>>
);

export const toEitherTTuple2 = <M extends hkt.HKTS, L, A, B>(
    t: Tuple2EitherT<M, L, A, B>,
) => eitherTToTuple2(t[0], t[1]);
```

**Comment by OliverJAsh** [comment]
Got it in the end, using your [`TaskEither` example](https://github.com/gcanti/fp-ts/blob/4ef68b556576ca48d5b0042c9fe9b7cf67375b66/examples/TaskEither.ts):

``` ts
import { tuple, apply } from 'fp-ts';
import * as eitherTTask from '../TaskEither';

// tuple constructor
const toTuple2 = <A, B>(a: A, b: B): tuple.Tuple<A, B> => [a, b];

// lifted tuple constructor
const eitherTTaskToTuple2 = <L, A, B>(
    fa: eitherTTask.TaskEither<L, A>,
    fb: eitherTTask.TaskEither<L, B>,
) => (
    apply.liftA2(eitherTTask, (a: A) => (b: B) => toTuple2(a, b))(fa, fb)
);

type Tuple2EitherTTask<L, A, B> = (
    tuple.Tuple<eitherTTask.TaskEither<L, A>, eitherTTask.TaskEither<L, B>>
);

export const toEitherTTaskTuple2 = <L, A, B>(
    t: Tuple2EitherTTask<L, A, B>,
) => eitherTTaskToTuple2(t[0], t[1]);

```

**Comment by gcanti** [comment]
@OliverJAsh `TaskEither` seems pretty common and useful, I wonder if we should move it from examples to standard lib as per you suggestion some times ago

**Comment by OliverJAsh** [comment]
Just coming back to this. I frequently find I need tuple constructors of n arity together with the equivalent lifted tuple constructor for a given data type, for example: `optionToTuple{2,3,4}`, `validationToTuple{2,3,4}`, and so on.

I wonder if it would be useful to define a common collection of these somewhere, so users don't have to invent these for themselves. What do you think?

For example, this is just a start:

``` ts
import * as validation from 'fp-ts/lib/Validation';
import * as option from 'fp-ts/lib/Option';
import * as apply from 'fp-ts/lib/Apply';

//
// tuple constructors
//

type Tuple2<A, B> = [A, B];
const toTuple2 = <A, B>(a: A, b: B): Tuple2<A, B> => [a, b];

type Tuple3<A, B, C> = [A, B, C];
const toTuple3 = <A, B, C>(a: A, b: B, c: C): Tuple3<A, B, C> => [a, b, c];

//
// lifted tuple constructors
//

const optionToTuple2 = <A, B>(
    fa: option.Option<A>,
    fb: option.Option<B>,
) =>
    apply.liftA2(option)((a: A) => (b: B) => toTuple2(a, b))(fa)(
        fb,
    );
const optionToTuple3 = <A, B, C>(
    fa: option.Option<A>,
    fb: option.Option<B>,
    fc: option.Option<C>,
) =>
    apply.liftA3(option)((a: A) => (b: B) => (c: C) => toTuple3(a, b, c))(fa)(
        fb,
    )(fc);

const validationToTuple2 = <L, A, B>(
    fa: validation.Validation<L, A>,
    fb: validation.Validation<L, B>,
) =>
    apply.liftA2(validation)((a: A) => (b: B) => toTuple2(a, b))(fa)(
        fb,
    );
const validationToTuple3 = <L, A, B, C>(
    fa: validation.Validation<L, A>,
    fb: validation.Validation<L, B>,
    fc: validation.Validation<L, C>,
) =>
    apply.liftA3(validation)((a: A) => (b: B) => (c: C) => toTuple3(a, b, c))(
        fa,
    )(fb)(fc);
```
