### ISSUE TITLE
feature proposal: absurd function for never type

### ISSUE THREAD

**Issue by ryota-ka** [gcanti/fp-ts#847]
**Do you want to request a _feature_ or report a _bug_?**

fearure

---

It might be helpful for us to have `absurd` function somewhere (perhaps in `function.ts`?), especially when folding `Either<never, A>` to `A`.

```typescript
function absurd<A>(_: never): A {
    throw new Error('absurd');
}
```

**Comment by raveclassic** [comment]
The goal of this project is to provide a complete typesafe solution without any runtime errors.

If you need to fold an Either, you can use fold/getOrElse.

**Comment by DylanRJohnston** [comment]
@raveclassic this is useful for proving totality of switch statements when using ADTs.

```
const absurd = <A>(_: never): A => { throw new Error('The impossible happened') }

type ADT =
  | { tag: 'foo', foo: number }
  | { tag: 'bar', bar: string }
  | { tag: 'baz', baz: boolean }

const prettyPrint = (adt: ADT): string => {
  switch (adt.tag) {
    case 'foo': return `Foo(${adt.foo}: number)`
    case 'bar': return `Bar(${adt.bar}: string)`
    case 'baz': return `Baz(${adt.baz}: boolean)`
    default: return absurd(adt)
  }
}
```

**Comment by DylanRJohnston** [comment]
It's also a common staple of functional programming languages, and is also useful for stubbing out unimplemented paths during development. 

Haskell has `undefined :: a` and `absurd :: Void -> a` from [Data.Void](https://hackage.haskell.org/package/void-0.6.1/docs/Data-Void.html). Idris has `absurd : Uninhabited t => t -> a`, so does Purescript [Data.Void](https://github.com/purescript/purescript-prelude/blob/master/src/Data/Void.purs) `absurd :: forall a. Void -> a`. You get the idea, it's a logical piece of the Curry Howard isomorphism and Principle of explosion, where anything is provable from False.

**Comment by DylanRJohnston** [comment]
https://www.fpcomplete.com/blog/2017/07/to-void-or-to-void

**Comment by masaeedu** [comment]
Hi there. Given the implicit structural subtyping in TypeScript, isn't this just the identity function on `never`?

```ts
const id: <A>(a: A) => A = x => x

const absurd: <A>(_: never) => A = id
```

PS @raveclassic, surprisingly enough *not* having such a function exist would be the type unsafe alternative, because this would mean all our categorical abstractions are operating on something that isn't actually a proper category!
