### ISSUE TITLE
TypeScript hangs after upgrade from 1.17.0 to 1.17.1

### ISSUE THREAD

**Issue by alexkvak** [gcanti/fp-ts#849]
I cannot reproduce this issue outside my project but when I upgrade fp-ts from 1.17.0 to 1.17.1 tsc hangs and fails with out of memory error.

Could you help me to understand how can I find the problem place in my code?

TypeScript: v3.4.4
fp-ts: v1.17.1
nodejs: v11.14.0
OS: MasOS 10.14.4

**Comment by mlegenhausen** [comment]
Please run `npm ls fp-ts` and look if you have multiple versions of `fp-ts` installed.

**Comment by alexkvak** [comment]
```
├── fp-ts@1.17.1
├─┬ io-ts@1.8.5
│ └── fp-ts@1.15.0
└─┬ retry-ts@0.0.1
  └── fp-ts@1.17.0
```

**Comment by mlegenhausen** [comment]
You should also update `io-ts` and `retry-ts` you need to make sure that only one version of `fp-ts` is installed. You should see a (deduped) beside the sub `fp-ts` dependencies.

**Comment by alexkvak** [comment]
@mlegenhausen thanks for help!
