### ISSUE TITLE
Feature request: provide wrappers for fetch, setTimeout, setInterval, ...

### ISSUE THREAD

**Issue by cyberixae** [gcanti/fp-ts#856]
Window​OrWorker​Global​Scope contains some commonly used methods like `fetch()`, `setTimeout()`, `clearTimeout()`, `setInterval()`, `clearInterval()`. It would be nice if fp-ts provided typed alternatives for some of the most popular methods out of the box. See https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope

**Comment by mlegenhausen** [comment]
See https://github.com/gcanti/fp-ts/pull/533#issuecomment-407306324 for discussion which functionality will be added to `fp-ts`.

* `fetch()` is not a language standard function it depends on the engine you run on.
* `setTimeout()` is already implemented. See: https://github.com/gcanti/fp-ts/blob/db3f8255f6a8ada178189e1d31f1c96b8cadd3ac/src/Task.ts#L154-L163
* `setInterval()`, `clearInterval()` and `clearTimeout()` is hard to implement without introducing new concepts. The best would be to go with [rxjs](https://rxjs-dev.firebaseapp.com/) and [fp-ts-rxjs](https://github.com/gcanti/fp-ts-rxjs) if you want to stick to pure functional programming.

**Comment by cyberixae** [comment]
Ok. Thanks for letting me know.

**Comment by steida** [comment]
fetch example is here https://github.com/gcanti/fp-ts/blob/master/docs/recipes/interoperability.md
