### ISSUE TITLE
Broken in browsers that don't support ES6 syntax natively

### ISSUE THREAD

**Issue by butchler** [gcanti/fp-ts#863]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

The `module` field in `package.json` points to a file that uses ES6 syntax, not just ES Module syntax. This causes syntax errors when trying to run the code in a browser that does not support ES6, such as IE11.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

1. Bundle `fp-ts` with a bundler such as Webpack or Rollup (it is possible to configure bundlers to ignore the `module` field in `package.json`, but the default configuration gives it preference over the `main` field)
2. Try to run the resulting bundle in a browser that does not support ES6 syntax natively, such as IE11
3. Should result in a syntax error

**What is the expected behavior?**

According to https://github.com/rollup/rollup/wiki/pkg.module:

> pkg.module will point to a module that has ES2015 module syntax but otherwise only syntax features that the target environments support.

The `module` field should point a file that uses `import`/`export` syntax, but no other ES6 features.

More details here: https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

> If you're using things like arrow functions and classes (or more exotic features like decorators and object spread), you should transpile them if you want your library to work in environments that don't support those features. Otherwise, whoever uses your library will have to transpile it themselves, including configuring their transpiler to handle your code, which might involve esoteric transforms and conflicting versions of Babel.

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**

Browsers: IE11 and any other browser that don't support ES6 syntax natively
Previous version: It worked in previous versions of `fp-ts` that did not expose an ES6 version (i.e. before this issue was resolved: https://github.com/gcanti/fp-ts/issues/813)

**Comment by FruitieX** [comment]
Hmm, darn, looks like this should've been set to `es5`: https://github.com/gcanti/fp-ts/blob/master/tsconfig.es6.json#L5

**Comment by gcanti** [comment]
Patch released in v1.17.4, @butchler thanks for the bug report

**Comment by butchler** [comment]
Thank you for the quick fix!

**Comment by wereHamster** [comment]
It is very unfortunate that now the files in es6 are not actually es6. In the long run people will have to start transpiling their node_modules dependencies. d3-array for example publishes their "module" entry point as ES6 code (uses for..of syntax).

Furthermore, the webpack config generated by [create-react-app will transpile all dependencies (even those outside the project folder) with babel](https://github.com/facebook/create-react-app/blob/da06c230c230b55c471e260efd9378af565e738e/packages/react-scripts/config/webpack.config.js#L460-L498). Projects which use actual ES6 dependencies work out of the box.

**Comment by steida** [comment]
@wereHamster Any idea how to fix it?

**Comment by wereHamster** [comment]
@steida revert #865.

**Comment by butchler** [comment]
I'm not sure who actually uses is, but this article recommends using the `esnext` field in package.json for delivering untranspiled source code to package consumers: https://2ality.com/2017/06/pkg-esnext.html

The disadvantage is that users who want to take advantage of the untranspiled source code would have to do a little bit of extra configuration to tell webpack to use the `esnext` field. (`create-react-app` could do this by default, but does not seem to right now.)

The advantage is that packages could release untranspiled versions of the code for users that want it without breaking things for users that haven't configured webpack to transpile `node_modules` (probably most people who aren't using a recent enough version of `create-react-app`).

**Comment by wereHamster** [comment]
That article has been published in 2017, and pkg.esnext still hasn't been widely adopted. Most packages use only pkg.main and pkg.module.

The npm documentation about package.json doesn't specify what syntax the "main" entry point should use. It's up to the package authors to decide, and many authors now increasingly favour modern browsers over supporting legacy browsers (IE11).

It's more future proof to publish modern code and point people to guides how to configure their tools if they really need to support old browsers. I don't want to be held back by IE (I've been there…)

**Comment by butchler** [comment]
I guess the main problem with the `esnext` approach is that it creates extra work for package authors, who would have to configure transpiling and expose two different versions of the code.

I'm not opposed to package authors not going out of their way to support older browsers, but that should probably be considered a breaking change as far as semver :)
