### ISSUE TITLE
Question about limiting concurrency

### ISSUE THREAD

**Issue by gnomff** [gcanti/fp-ts#864]
Our team is starting to learn fp-ts, and we are starting with some basic async examples (mostly pulled from [here](https://github.com/gcanti/fp-ts/blob/master/docs/recipes/async.md)) Running a set of Tasks in sequence is great, but what is the idiomatic way to restrict concurrency? For example, Promise.map (in bluebird) allows you to set a concurrency limit like {concurrency: 4}. Maybe something like `.sequence(task)(maxConcurrency)(tasks)`

One solution might be to split the array into chunks, and then iterate the chunks, using sequence and flatMap. However, that would mean every Task in each chunk would have to complete before moving on to the next chunk - one long running task could hold up the whole operation.

**Comment by mlegenhausen** [comment]
You can take a look at this discussion: https://github.com/gcanti/fp-ts/issues/574

**Comment by gnomff** [comment]
Ah, ok so p-map looks like the way to go. Thanks!
