### ISSUE TITLE
Add continuation monad (transformer)

### ISSUE THREAD

**Issue by masaeedu** [gcanti/fp-ts#866]
The idea below will probably need a little bit of "typescriptification" to make it practical, but here's the gist:

```typescript
type Cont<R, A> = (f: (a: A) => R) => R

type of = <R, A>(a: A) => Cont<R, A>
const of: of = a => cb => cb(a)

type chain = <R, A, B>(amb: (a: A) => Cont<R, B>) => (ma: Cont<R, A>) => Cont<R, B>
const chain: chain = amb => ma => cb => ma(a => amb(a)(cb))

type lift2 = <R, A, B, C>(f: (a: A) => (b: B) => C) => (fa: Cont<R, A>) => (fb: Cont<R, B>) => Cont<R, C>
const lift2: lift2 = f => fa => fb => chain(a => chain(b => of(f(a)(b)))(fb))(fa)

type delay = (d: number) => <A>(a: A) => Cont<undefined, A>
const delay: delay = d => a => cb => setTimeout(() => { cb(a) }, d)

const v1 = delay(500)("Hello")
const v2 = delay(500)("World")

const result = lift2(s1 => s2 => `${s1}, ${s2}!`)(v1)(v2)

result(x => { console.log(x) })
// after 1 second, "Hello, World!"
```

This is useful for working with Node JS APIs and such. Most NodeJS APIs are actually just `Cont<undefined, [E, undefined] | [undefined, A]>`, where that weird inner type is just an awkward encoding of `Either`. They can be massaged fairly straightforwardly into `EitherT<E, Cont<undefined>, A>`.

You might want to use Kleisli arrows `(a -> IO r) -> IO r` to model effectfulness if you want to be super strict (I just use a different arrow type to distinguish impure functions from pure functions). If you go this route you'll probably want to implement `ContT` so you can work with `ContT<R, IO, _>`.

**Comment by giogonzo** [comment]
@joshburgess has put up a version [here](https://github.com/joshburgess/fp-ts-cont). It could probably be moved into `-contrib` if desired, or linked in the [ecosystem](https://gcanti.github.io/fp-ts/introduction/ecosystem) docs.
@masaeedu feel free to reopen if this doesn't match your proposal above
