### ISSUE TITLE
Question: Learning Semigroups

### ISSUE THREAD

**Issue by baetheus** [gcanti/fp-ts#869]
Hello all,

I'm trying to learn how to better utilize semigroups in some frontend code. I've run into a common scenario where I have something like the following:

```ts
interface Person {
  personId: Option<number>;
  name: string;
  numberOfLimbs: number;
}

const people: Person[] = [
  {
    personId: some(0),
    name: 'Tom',
    numberOfLimbs: 4,
  },
  {
    personId: some(1),
    name: 'Tina',
    numberOfLimbs: 4,
  },
  {
    personId: some(2),
    name: 'Taylor',
    numberOfLimbs: 3,
  },
];

const existingPerson: Person = {
  personId: some(0),
  name: 'Tom',
  numberOfLimbs: 2,
};

const newPerson: Person = {
  personId: none,
  name: 'Xavier',
  numberOfLimbs: 5,
};
```

What I'd like to be able to do is create a semiGroup like the one from getArraySemigroup but with a different merge strategy, where:

```ts
semigroupPeople.concat(people, [existingPerson, newPerson]);
```

 will replace the 'Tom' instance by matching personId and add newPerson to the array since it doesn't match any existing, resulting in:

```ts
const result: Person[] = [
  {
    personId: some(0),
    name: 'Tom',
    numberOfLimbs: 2,
  },
  {
    personId: some(1),
    name: 'Tina',
    numberOfLimbs: 4,
  },
  {
    personId: some(2),
    name: 'Taylor',
    numberOfLimbs: 3,
  },
  {
    personId: none,
    name: 'Xavier',
    numberOfLimbs: 5,
  }
];
```

I have a good number of structures to create this semigroup for, and I'd like to avoid writing a concat function for each of them. Does anyone have advice for a direction to go in here?

**Comment by baetheus** [comment]
My first attempt is this:

```ts
import { Semigroup } from 'fp-ts/lib/Semigroup';
import { Setoid } from 'fp-ts/lib/Setoid';

export const getMergeArraySemigroup = <T, K extends keyof T>(
  k: K,
  { concat }: Semigroup<T>,
  { equals }: Setoid<T[K]>
): Semigroup<T[]> => ({
  concat: (as, bs) =>
    bs.reduce((acc, b) => {
      if (acc.find(a => equals(a[k], b[k]))) {
        return acc.map(a => concat(a, b));
      }
      return acc.concat(b);
    }, as),
});
```

But it looks very inefficient to me.

**Comment by mlegenhausen** [comment]
Why not use a data structure that support uniqueness like a `Set` and simply define the `Setoid` instance?

**Comment by mlegenhausen** [comment]
In generell I would not recommend to make an `id` optional. I would reconsider the data model. If you struggle with your business code reconsider the data structures to make your life easier.

```ts
interface NewPerson {
  name: string;
  numberOfLimbs: number;
}

interface ExistingPerson extends NewPerson {
  id: number;
}

interface Model {
  persons: Record<number, ExistingPerson>;
  // Normally you have only one NewPerson at a time consider Option<NewPerson>
  newPerson: NewPerson;
}
```

Use a `Record` for easier lookup and manipulation and transform to an array when you need to display your data.

**Comment by baetheus** [comment]
@mlegenhausen I think Set might be the wrong structure for my particular case, since I would have no way to index multiple objects with none as ids (ie. new objects that my backend has not yet assigned an id to). Not to mention that there is overhead in writing array to set transforms. I also simplified the problem domain substantially (which you couldn't have known). The object hierarchy I'm working is is very nested, so working with the already serialized array is definitely easiest.

**Comment by mlegenhausen** [comment]
> The object hierarchy I'm working is is very nested, so working with the already serialized array is definitely easiest.

Backend data is normally not in a format you want. That's why libraries like [normalizr](https://github.com/paularmstrong/normalizr) were invented. Split your data up in your entities and make them accessable by a unique key. Use this key for fast lookups.

**Comment by baetheus** [comment]
@mlegenhausen I understand how to break up data into smaller entities, I already have lenses to create any view of the data I want. My goal here is to learn about semigroups and merging strategies. Like I said before, a Set or a Record is inadequate in this case, as I will be carrying multiple "new" entities that lack ids, hence the option type.

I appreciate your input though! Do you have any commentary on the semigroup factory I posted? I was thinking that it might be better to switch to Setoid<T> instead of Setoid<T[K]>. In which case it might be better to make the function signature:

```
getMergeArraySemigroup = <T, K extends keyof T>(
  k: K,
  { concat, equals }: Semigroup<T> & Setoid<T>
): Semigroup<T[]>

**Comment by mlegenhausen** [comment]
I think you break some laws:

```
getOptionSetoidNoneUnequal(setoidString).equals(none, none) === false
```

Which breaks the first `Setoid` law:

> 1. Reflexivity: `S.equals(a, a) === true`

**Comment by baetheus** [comment]
@mlegenhausen getArrayUpsertSemigroup doesn't actually break associativity, I thought it did at first as well, but a little napkin math showed that it doesn't. It does not, however, commute. It looks like you're probably right about the reflexivity of that option setoid. I guess I'll have to find another solution there.

**Comment by baetheus** [comment]
@mlegenhausen Since I needed two people with personId: none to be considered different it sufficed to use object comparison when defining a Setoid for Person. Also, I found that the semigroup behavior I needed required

```ts
lastArraySemigroup.concat([a1, b1, c1], [b2, c2])
```

be equivalent to:

```ts
[lastSemigroup.concat(b1, b2), lastSemigroup.concat(c1, c2)]
```

Here is the working solution for this particular use:

```ts
import { fromNullable } from 'fp-ts/lib/Option';
import { Semigroup } from 'fp-ts/lib/Semigroup';
import { Setoid } from 'fp-ts/lib/Setoid';

export const getArrayLastSemigroup = <T>({
  concat,
  equals,
}: Semigroup<T> & Setoid<T>): Semigroup<T[]> => ({
  concat: (as, bs) =>
    bs.map(b => {
      const match = fromNullable(as.find(a => equals(a, b)));
      return match.fold(b, a => concat(a, b));
    }, []),
});
```

**Comment by baetheus** [comment]
I think I've figured out as much as I need to for now. Thanks for the help @mlegenhausen!
