### ISSUE TITLE
task with other promise implementations

### ISSUE THREAD

**Issue by leemhenson** [gcanti/fp-ts#87]
Hi.

We're using Bluebird as our promise implementation in a project, and I'd like to use `Task` in there too. Alas, `Task` enforces standard ES6 promises. At the moment, I've basically copied the entire `Task.ts` file into my own project and `s/Promise/Bluebird/` and `s/Task/BTask/`. This is working fine for me, but obviously I'd be better off if `fp-ts` supported either promise library natively. 

I think supporting both seems tricky though, unless you know of some magic generics incantation or something.....

Any ideas? 

Cheers

**Comment by tycho01** [comment]
Don't the implementations fit the same type descriptions, that is, `Promise` as well as `PromiseLike`? In that sense the type level should be agnostic toward the implementation.

**Comment by leemhenson** [comment]
We dropped Bluebird so I've no need for this.
