### ISSUE TITLE
Difference between `HKT<URI, A>` and `Type<URI, A>`

### ISSUE THREAD

**Issue by amaurymartiny** [gcanti/fp-ts#882]
**Do you want to request a _feature_ or report a _bug_?**

None of the above. It's only a question.

**What is the question?**

I would like to know how to use `HKT.ts`. My use case is the following:

```typescript
// I have already done module augmentation on `Observable` and `Promise` to add _URI and _A,
// as well as module augmentation on './HKT.ts' to fill the `URI2HKT` mapping
// So `URIS` contains now `'Observable' | 'Promise'`


abstract class MyClass<URI extends URIS>{
  abstract run(): HKT<URI, number>;
}

// concrete classes
class MyObservableClass extends MyClass<'Observable'> {
  run(): Observable<number> {
    return of(2);
  }
}

class MyPromiseClass extends MyClass<'Promise'> {
  run(): Promise<number> {
    return Promise.resolve(2);
  }
}
```

My question comes from the `abstract run(): HKT<URI, number>;`, should it be

```typescript
abstract run(): Type<URI, number>;
```
? I feel those 2 are interchangeable.

IIRC there was a `HKT.md` file that explained this, but I can't seem to find it anymore.

**Additional Comments**

Have you considered creating a fp-ts Gitter/Slack/Spectrum for questions like this? I was looking for such a platform, not to pollute this issue tracker, but didn't find one.

**Comment by gcanti** [comment]
> IIRC there was a HKT.md file that explained this, but I can't seem to find it anymore.

Here it is: https://gcanti.github.io/fp-ts/recipes/HKT

> I have already done module augmentation on `Observable` and `Promise` to add _URI and _A,
as well as module augmentation on './HKT.ts' to fill the `URI2HKT` mapping
So `URIS` contains now `'Observable' | 'Promise'`

Actually the module augmentation on `HKT.ts` should be sufficient now.

> I feel those 2 are interchangeable

AFAIK that's because you also augmented `Observable` and `Promise` with `_URI` and `_A`. 
If you don't do that, you must use `Type`.

Repro:

```ts
import { Type, URIS } from 'fp-ts/lib/HKT'
import { Observable, of } from 'rxjs'

declare module 'fp-ts/lib/HKT' {
  interface URI2HKT<A> {
    Observable: Observable<A>
    Promise: Promise<A>
  }
}

abstract class MyClass<URI extends URIS> {
  abstract run(): Type<URI, number>
}

class MyObservableClass implements MyClass<'Observable'> {
  run(): Observable<number> {
    return of(2)
  }
}

class MyPromiseClass extends MyClass<'Promise'> {
  run(): Promise<number> {
    return Promise.resolve(2)
  }
}
```

**Comment by amaurymartiny** [comment]
Got it.
