### ISSUE TITLE
@obsolete method not flagged in default export function

### ISSUE THREAD

**Issue by leighman** [gcanti/fp-ts#885]
Using `fp-ts` `1.19.0` with `tslint` `5.15.0` and `typescript` `3.5.1`

I enable the `@obsolete` rule. Notice that some `@obsolete` methods are not picked up.

Seems to be to do with the fact that the method is called inside an inline default export function.

No error shown:
```
import * as t from "io-ts"

export default () =>
  t.string.decode("string").map(x => x)
```

Error shown:
```
import * as t from "io-ts"

const x = () =>
  t.string.decode("string").map(x => x)
```

**Comment by gcanti** [comment]
@leighman looks like the official `@deprecated` rule has the same issue

```ts
import { contramap, ordString } from 'fp-ts/lib/Ord'

// error: contramap is deprecated
export const x = () => contramap((x: { a: string }) => x.a, ordString)

// no error
export default () => contramap((x: { a: string }) => x.a, ordString)
```

(`@obsolete` is just a copy of that rule with some replacements)

**Comment by leighman** [comment]
Ah, okay! Will have a look at the upstream rule if I get a chance.
