### ISSUE TITLE
Add readonly modifier to function arguments

### ISSUE THREAD

**Issue by takaki** [gcanti/fp-ts#891]
### Current Behavior

`fp-ts` can't use for variable with const assertion.

For example,

```
import { map } from "fp-ts/lib/Array";

const readonly = [1, 2, 3] as const;

const n0 = map((n: number) => n * 2)(readonly);  // error
const n1 = map((n: number) => n * 2)([...readonly]);  // working but...

```

### Suggested Solution

In function definition, it use `Array<A>` for argument definition.
Please change it to `readonly Array<A>`.

There are also same problems in Map and other data types.

**Comment by jollytoad** [comment]
I'm hitting problems with ReadonlyArrays too, using the TypeScript API, for example...

```
pipe(
        program.getSourceFiles(),
        filter(sourceFile => !sourceFile.isDeclarationFile),
        chain(({ statements }) => statements),
        chain(visitStatement(program))
    );
```

both `program.getSourceFiles()`, and `statements` cause me problems in the above pipe as they are ReadonlyArrays (or derive from ReadonlyArrays in the case of statements)

so instead I'm forced to cast...

```
pipe(
        program.getSourceFiles() as ts.SourceFile[],
        filter(sourceFile => !sourceFile.isDeclarationFile),
        chain(({ statements }) => statements as unknown as ts.Statement[]),
        chain(visitStatement(program))
    );
```

which is some pretty horrible casting

**Comment by gcanti** [comment]
We can't do that (we should also change the return types and would be a breaking change).
Best solution would be to define a `ReadonlyArray` module.
