### ISSUE TITLE
Array.chunksOf does not satisfy what is written in its doc

### ISSUE THREAD

**Issue by Stouffi** [gcanti/fp-ts#897]
### Current Behavior

Array.chunksOf doc states that 
> `chunksOf(n)([])` is `[]`, not `[[]]`. This is intentional, and is consistent with a recursive definition of `chunksOf`; it satisfies the property that
 >
 > ```ts
 > chunksOf(n)(xs).concat(chunksOf(n)(ys)) == chunksOf(n)(xs.concat(ys)))
 > ```
 > whenever `n` evenly divides the length of `xs`.

But `chunksOf(n)([])` returns actually `[[]]` and the above property is not satisfied

Moreover, the tests against this function are also contradictory with the doc

```ts
assert.deepStrictEqual(chunksOf(1)([]), [[]])
assert.deepStrictEqual(chunksOf(2)([]), [[]])
assert.deepStrictEqual(chunksOf(0)([]), [[]])
```

### Expected behavior

If the implementation is correct, then the doc should be corrected accordingly.

Otherwise the implementation should be fixed to satisfy the doc.

### Reproducible example

Here are some failing tests using `fc` as `fast-check`

```ts
it('respects the law: chunksOf(n)(xs).concat(chunksOf(n)(ys)) == chunksOf(n)(xs.concat(ys)))', () => {
  fc.assert(
    fc.property(
      fc.array(fc.integer()).filter(xs => xs.length % 2 === 0), // Ensures `xs.length` is even
      fc.array(fc.integer()),
      fc.integer(1, 1).map(x => x * 2), // Generates `n` to be even so that it evenly divides `xs`
      (xs, ys, n) => {
        const as = chunksOf(n)(xs).concat(chunksOf(n)(ys))
        const bs = chunksOf(n)(xs.concat(ys))
        isDeepStrictEqual(as, bs)
      }
    )
  )
})
it('returns an empty array if provided an empty array', () => {
  assert.deepStrictEqual(chunksOf(2)([]), [])
})
```

### Suggested solution(s)

In the case the doc is correct and the implementation is to be fixed:

We can change chunksOf to
```ts
export function chunksOf(n: number): <A>(as: Array<A>) => Array<Array<A>> {
  return as => as.length === 0 ? [] : (isOutOfBound(n - 1, as) ? [as] : chop(splitAt(n))(as))
}
```
and add tests above

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |   1.19.2         |
| TypeScript |   3.5.2         |

**Comment by gcanti** [comment]
@Stouffi thanks for the bug report

> In the case the doc is correct and the implementation is to be fixed

:+1: `chunksOf` is a porting of http://hackage.haskell.org/package/split-0.2.3.3/docs/Data-List-Split.html#v:chunksOf, I'd stick with it

**Comment by gcanti** [comment]
https://github.com/gcanti/fp-ts/releases/tag/1.19.4
