### ISSUE TITLE
Take a tutorial link not working?

### ISSUE THREAD

**Issue by zifahm** [gcanti/fp-ts#901]
## 📖 Documentation
https://gcanti.github.io/fp-ts/basics/
The link for taking a tutorial is not working. Or has it changed to some where else?

**Comment by gcanti** [comment]
@zifahm old link (it was just a placeholder), thanks for reporting

**Comment by damiangreen** [comment]
The url https://gcanti.github.io/fp-ts/basics/ in the readme is  still 404ing****

**Comment by giogonzo** [comment]
@damiangreen that link does not exist - as you can see in the linked diff 30b35c4 the one that links to the beginning of the introduction is https://gcanti.github.io/fp-ts/introduction/core-concepts
