### ISSUE TITLE
Either.fromNullable is not lazy

### ISSUE THREAD

**Issue by Eoksni** [gcanti/fp-ts#918]
### Current Behavior

```ts
fromNullable<E>(e: E):              <A>(a: A | null | undefined) => Either<E, A>
fromOption: <E>(onNone: () => E) => <A>(ma: Option<A>)           => Either<E, A>
```

The API is inconsistent - `fromNullable` accepts a strict value and `fromOption` accepts a thunk. 

### Expected behavior

I believe the new approach is that laziness is preferred approach so `fromNullable` should be lazy as well. Also these functions conceptually almost the same so should behave the same.

### Suggested solution(s)

I mean... it's a breaking change and is not a bug per se. Probably not worth to fix it, but may be its ok since v2 is still fresh.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |     2.0.3       |
| TypeScript |     3.5.3       |

**Comment by gcanti** [comment]
tagged with v3 as a reminder
