### ISSUE TITLE
State Monad

### ISSUE THREAD

**Issue by baetheus** [gcanti/fp-ts#922]
## 📖 Documentation
Is it possible someone could add a few examples for the State monad and State monad transformer to the docs? I'm pretty dumb and teasing out the usage from the types hurts my head.

**Comment by steida** [comment]
I googled a lot of articles, go for it too.

**Comment by gcanti** [comment]
@baetheus I added to the documentation a link to this nice post about the State monad: https://paulgray.net/the-state-monad/
