### ISSUE TITLE
Record API is problematic

### ISSUE THREAD

**Issue by anttih** [gcanti/fp-ts#923]
### Current Behavior

The `Record` API seems to implement a `Map` like API which handles partiality, but the `Record` type itself is not partial. This is evident when looking at the type signature of `lookup`:

```typescript
function lookup<A>(k: string, r: Record<string, A>): Option<A>
```

The input record type says that it maps every string to a value, but then indicates in the return value that the key might not be found. Any access to this record using the JS dot notation or normal object access will compile, even for non-existing keys.

The API works fine if you treat your records as maps, but you must always remember to use the provided API.

### Expected behavior

The datatype for the `Record` API should match it's intended use case.

### Suggested solution(s)

I don't know what should be done. Maybe one option would be to bring back `StrMap` as 

```typescript
type StrMap<A> = Partial<Record<string, A>>
```

**Comment by user753** [comment]
@anttih How is this different from 'array'? For safety you also need to use the provided API.
