### ISSUE TITLE
Datum and DatumEither

### ISSUE THREAD

**Issue by baetheus** [gcanti/fp-ts#931]
## 📖 Documentation
I'm hoping to get some community feedback (and to shamelessly advertise) on an fp-ts 2+ compatible Monad that I wrote to replace RemoteData.

While [RemoteData](https://github.com/devex-web-frontend/remote-data-ts) is very useful, it stopped being a viable adt for my frontend applications some time ago due to the lack of a refresh type and recently because it has not been updated for fp-ts@2+. I've had a very similar ADT for some time that I called AsyncData, but lately I've wanted to learn how Monad Transformers work and to improve the flexibility of the RemoteData concept.

I built [@nll/datum](https://github.com/nullpub/datum) to extend the idea of Option to include a pending state. `Datum<A>` can be thought of as an `Option<A>` with an additional type denoting "refreshing" (so Option's 2 types become 4). Specifically, `None` is associated with `Initial` and `Pending` while `Some<A>` is associated with `Refresh<A>` and `Replete<A>`.

Like `TaskEither`, I left error handling to the inner `Either` monad by leveraging `getEitherM`. I added a few helper functions for mapping to `Replete<Left<E>>` and `Replete<Right<A>>` in `failure` and `success` respectively.

My goals were to address the issues I mentioned for `RemoteData` while adhering to as much of the code style and idiomatic usage of fp-ts as I could. If you have any critiques I would be very appreciative. Thanks!

**Comment by gcanti** [comment]
@baetheus nice

> and to shamelessly advertise

FYI there's an [ecosystem](https://github.com/gcanti/fp-ts/blob/12a9fb3b5a1b2aa36e329f01a6d719e7ffdbcfbb/docs/introduction/ecosystem.md) doc, would you like to send a PR?

**Comment by raveclassic** [comment]
Cool! 

BTW `RemoData` is on its way to `fp-ts@2.0`. Refreshing state conflicts with our understanding of the original idea however after dropping methods in favor of top-level functions it should be really easy to add any number of states on top of the core.

**Comment by raveclassic** [comment]
FYI `RemoteData@2.0` has just been release with full support for `fp-ts@2.x`
https://www.npmjs.com/package/@devexperts/remote-data-ts/v/2.0.0

**Comment by gcanti** [comment]
> FYI there's an [ecosystem](https://gcanti.github.io/fp-ts/introduction/ecosystem.html) doc

@baetheus closing this, feel free to send a PR
