### ISSUE TITLE
Attempt at "Do notation" syntax

### ISSUE THREAD

**Issue by Herlevsen** [gcanti/fp-ts#934]
Hi,

I just want to start of by saying that i am fairly new to functional programming and fp-ts, so forgive me if there is some obvious flaw in my code or if my understanding of "Do notation" is off.

I just had a crack at "Do notation". I Have only implemented it for the Option data type, and therefore i don't know if this will work as well for other data types. The implementation uses an exception to short circuit, and i'm unsure what implications this might have?

Personally i think the syntax is more neat than other ones i've seen.

Looks like this:
```ts
binding(bind => {
    const number1 = bind(some(5))
    const number2 = bind(some(10))
    return some(number1 + number2)
}
```
The type of number1 and number2 is type safe and inferred as number by the compiler. Same goes for the return type of course.

The syntax is inspired by the Kotlin fp library, arrow.

The branch is available here
https://github.com/Herlevsen/fp-ts/tree/monad-binding

I've added 3 tests at the bottom of test/Option.ts.

What do you think?

Thanks

**Comment by gcanti** [comment]
@Herlevsen check out [fp-ts-contrib's `Do`](https://github.com/gcanti/fp-ts-contrib/blob/c94199e82fbf5c840a3bd4fb31653207ad053626/src/Do.ts)

**Comment by Herlevsen** [comment]
@gcanti Thanks. I did have a look at it, but I think the syntax is a bit strange. Specifically using string literals and also the "scope object". However a nice thing is that it seems to be working for any monad.

Can i ask you, what you personally think of the syntax of both versions? And how it ideally would like with better typescript support?

**Comment by raveclassic** [comment]
@Herlevsen It would be ideal to have some kind of HKT for generators in typescript: https://github.com/microsoft/TypeScript/issues/2983#issuecomment-338435221 - this is the most clean syntax available in TS/ES

**Comment by mattiamanzati** [comment]
@Herlevsen How will work your proposal when using things like IO and Task?
Do from fp-ts-contrib does work with that too! :)
