### ISSUE TITLE
Mutate the thing being folded?

### ISSUE THREAD

**Issue by dakom** [gcanti/fp-ts#936]
I see that it works, but is it _really_ allowed, or should I be using a different function?

```
let will_be_doubled = O.some(21);
const tripled = O.fold(
    () => 1,
    (value: number) => {
        //mutating here!
        will_be_doubled = O.some(value * 2);
      	return value * 3;
    }
)(will_be_doubled);
```

Of course I could just separate it into two calls - i.e. `tripled = O.fold(...)` and then `will_be_doubled = O.fold(...)` but I'd rather keep the logic of both of those together.

Kinda like how pattern matching in Rust allows: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1436593744a2fb97168c91cb48d41686

**Comment by pfgray** [comment]
`option.fold` can be thought of as a pattern match that's specific to `Option`.

Mutation in any form is unsafe, so I suppose it's more of a question of what you're trying to accomplish.

Note that `fold` doesn't need to evaluate to just one value. You can combine multiple values in a single tuple value for convenience:
```ts
import * as O from "fp-ts/lib/Option";

let op = O.some(21);
const [doubled, tripled] = O.fold(
  () => [1, 1],
  (value: number) => {
    return [value * 2, value * 3];
  }
)(op);

console.log(doubled, tripled);
```
