### ISSUE TITLE
Expose `pipe` method (like on RxJS `Observable`s)

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#937]
### Current Behavior

```ts
pipe(myOption, map(fn));
```

### Desired Behavior

```ts
myOption.pipe(map(fn));
```

### Suggested Solution

Expose a `pipe` method on types, like RxJS provides on `Observable`s.

E.g. in RxJS we can do

``` ts
myObservable.pipe(map(fn));
```

### Who does this impact? Who is this for?

All users

### Additional context

This helps with readability (subjective, I know), as the code reads left-to-right.

**Comment by mlegenhausen** [comment]
Just think the other way around you can use the `fp-ts` `pipe` with RxJS

```ts
pipe(myObservable, map(fn))
```

**Comment by gcanti** [comment]
> Expose a pipe method on types, like RxJS provides on Observables.

@OliverJAsh this is not possible (data types are not classes anymore)
