### ISSUE TITLE
Either.chainLeft

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#94]
I have an `Either` where, if its a `Right` instance, I want to map the inner value and transform the `Either` instance to a `Left`. I am currently using `fold` to do this, but wondered if there was a better pattern. Perhaps `chainLeft` would make sense here, like `mapLeft`?

``` ts
const e = either.left<string, string>('foo')
e
  .fold(
    left => either.left<string, string>(left),
    right => either.left<string, string>(mapFn(right))
  )
```

**Comment by OliverJAsh** [comment]
Ah, sorry. I'm being stupid.

**Comment by OliverJAsh** [comment]
What I actually needed was the ability to chain a Validation. I see two ways of doing this:

- `.fold`
- convert validation to `Either`, perform chaining using `.chain`, and then convert back to a `Validation`.

```
const v = validation.failure<string, string>('foo')
v
  .fold(
    failure => validation.failure<string, string>(failure),
    success => validation.failure<string, string>(mapFn(success)),
  )
```

**Comment by OliverJAsh** [comment]
Here's what I ended up with:

``` ts
export const chainValidation = <L, A, B>(
    leftSemigroup: semigroup.StaticSemigroup<L>,
    validationInstance: validation.Validation<L, A>,
    chainFn: (a: A) => validation.Validation<L, B>,
) => (
    validationInstance.fold(
        failure => validation.failure<L, B>(leftSemigroup, failure),
        chainFn,
    )
);
```

**Comment by marcotoniut** [comment]
I arrived here actually seeking `chainLeft`, or a more robust alternative to Either, TaskEither and ReaderTaskEither's `alt` that gives access to the left value for the morphism. Is there a reason for why this shouldn't exist?

**Comment by gcanti** [comment]
> alt that gives access to the left value

@marcotoniut see [orElse](https://gcanti.github.io/fp-ts/modules/Either.ts.html#orelse)

**Comment by marcotoniut** [comment]
Well, that makes sense... Thank you.
