### ISSUE TITLE
`getOrElseValue`

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#940]
I understand there used to be a `getOrElseValue` function, but it was removed. Is there any chance of bringing this back, or was it removed for a good reason? (I searched around but couldn't find a reason.)

**Comment by DenisFrezzato** [comment]
In `1.x` there was `getOrElse` and `getOrElseL` both for `Option` and `Either`. In `2.x` there is just `getOrElse` (which is lazy). Am I missing something about your question?

**Comment by giogonzo** [comment]
I can't find any conversation to link right now, but the rationale was more or less "the lazy version is more general (as it supports all the cases where params are needed), no need to keep both versions in the few cases where a constant version could be added (e.g. `None`)".

I find myself using `constant(value)` in `fold`/`getOrElse` where I need a constant return

**Comment by OliverJAsh** [comment]
I was asking why the non-lazy variant was removed. @giogonzo That makes sense, thanks. It's easy enough for users to define a custom operator which combines `getOrElse` + `constant`.
