### ISSUE TITLE
v2 migration guide references non-existent tslint rule

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#941]
https://github.com/gcanti/fp-ts/blob/28292e1b5956d49069148818f7c6348a61e81a2e/docs/introduction/upgrade-to-v2.md#tslint-rule

There is no `rules` folder anywhere AFAICS? /cc @grossbart

**Comment by grossbart** [comment]
Thanks for pointing this out and sorry it took a while to answer: I [added a link to the docs](https://github.com/gcanti/fp-ts/commit/3ff89e56cec2468bf332cdccc02f34f86c1fa29f) that points to the rule. Because it's for migration purposes only, it's only available in the `1.19.x` branch.
