### ISSUE TITLE
Encoding an UpStar & DownStar

### ISSUE THREAD

**Issue by YBogomolov** [gcanti/fp-ts#947]
I'm trying to encode UpStar and DownStar in order to define profunctor instances for them, and I'm having a hard time. Right now I was able to do this:

```ts
export type UpStar<F, A, B> = (a: A) => HKT<F, B>;
export type UpStar1<F extends URIS, A, B> = (a: A) => Kind<F, B>;

export const URI = 'UpStar';
export type URI = typeof URI;

declare module 'fp-ts/lib/HKT' {
  interface URItoKind3<R, E, A> {
    UpStar: UpStar<R, E, A>;
  }
}

export function getUpStarPF<F extends URIS>(F: Functor1<F>): Profunctor3<URI> {
  return {
    URI,
    // Argument of type 'HKT<R, A>' is not assignable to parameter of type 'Kind<F, A>'.
    //                              ↓
    map: (era, ab) => (e) => F.map(era(e), ab),
    //                           and here: ↓
    promap: (era, de, ab) => (d) => F.map(era(de(d)), ab),
  };
}
```

The problem is that UpStar needs a `Functor<F>` instance in order to define a profunctor. `F` should have kind `* → *`, but UpStar itself should be `* → * → * → *`, if I understand everything correctly. I need somehow to specify that I would like to return an instance for `Profunctor<UpStar<F>>`.

@gcanti what do you think, is it possible to define such construct in TypeScript at all?

**Comment by giogonzo** [comment]
@YBogomolov I spent a few minutes trying to grasp this, without much success. I'll just add my 2 cents here

Reading up at https://hackage.haskell.org/package/profunctors-3.3.0.1/docs/src/Data-Profunctor.html#UpStar, you are trying to encode e.g.
```hs
------------------------------------------------------------------------------
-- UpStar
------------------------------------------------------------------------------

-- | Lift a 'Functor' into a 'Profunctor' (forwards).
newtype UpStar f d c = UpStar { runUpStar :: d -> f c }

instance Functor f => Profunctor (UpStar f) where
  dimap ab cd (UpStar bfc) = UpStar (fmap cd . bfc . ab)
```
right?

I don't really get what's the actual meaning/usage of the tool, but speaking in fp-ts encoding:
`UpStar` is a newtype (not a typeclass), so I would skip the URI/HKT dance and encode it as:
```ts
import { HKT, URIS2, Kind2 } from "fp-ts/lib/HKT";

export interface UpStar<F> {
  <D, C>(d: D): HKT<F, C>
}
export interface UpStar2<F extends URIS2> {
  <D, L, C>(d: D): Kind2<F, L, C>;
}
```
then to express the `Functor f => Profunctor (UpStar f)` constraint, you'll need to enter value level and use a function receiving the instance needed, like in your example:
```ts
import { Functor, Functor2 } from "fp-ts/lib/Functor";
import { Profunctor, Profunctor2 } from "fp-ts/lib/Profunctor";

export function getUpStarProfunctor<F extends URIS2>(
  F: Functor2<F>,
  u: UpStar2<F>
): Profunctor2<F>;
export function getUpStarProfunctor<F>(
  F: Functor<F>,
  u: UpStar<F>
): Profunctor<F> {
  return {
    URI: F.URI,
    map: F.map,
    promap: // ???
  };
}
```

about implementing `promap`, I can't really parse the haskell implementation 😅. But I'm sure you'll have to use `u()` and `F.map` somehow

**Comment by YBogomolov** [comment]
@giogonzo Thank you for the tip! But, I'm afraid, it doesn't work for me to full extent. In the expression `Functor f => Profunctor (UpStar f)` only `Functor` is a constraint, while `(UpStar f)` bit is just a way of saying that `f: (a: A) => HKT<F, B>`.

I was able to express thing I want by defining a specialized `ProfunctorUpStar` like so:

```ts
import { Functor1 } from 'fp-ts/lib/Functor';
import { Kind, URIS } from 'fp-ts/lib/HKT';

export type UpStar<F extends URIS, A, B> = (a: A) => Kind<F, B>;

export interface ProfunctorUpStar<F extends URIS> extends Functor1<F> {
  readonly promap: <A, B, C, D>(fbc: UpStar<F, B, C>, ab: (e: A) => B, cd: (a: C) => D) => UpStar<F, A, D>;
}

export function getProfunctorUpStar<F extends URIS>(F: Functor1<F>): ProfunctorUpStar<F> {
  return {
    URI: F.URI,
    map: F.map,
    promap: (fbc, ab, cd) => (a) => F.map(fbc(ab(a)), cd),
  };
}
```

I will explore the possibility to generalize this, and if I succeed, I would be glad to submit a PR. For now, I think, we can close this.

**Comment by YBogomolov** [comment]
I couldn't sleep until I do this, sorry 😅

Here's a gist with correct Profunctor implementation for UpStar and DownStar. I was right – I needed to separate URIs for `UpStar` and `F` inside it.

https://gist.github.com/YBogomolov/a19f52c3242367674f673c96938f2500

**Comment by YBogomolov** [comment]
As a reason for reopening this issue – does such "currying" of generic interfaces bring any value? Will it make sense to make `Profunctor3` and `Profunctor4` curried like I did in [gist](https://gist.github.com/YBogomolov/a19f52c3242367674f673c96938f2500)?
