### ISSUE TITLE
[Node 12] Tests fail, as Node.js has different error message for circular references detection

### ISSUE THREAD

**Issue by YBogomolov** [gcanti/fp-ts#949]
#### Steps to reproduce

1. Install Node.js v12.
2. Install all dependencies using `npm ci`.
3. Run `npm test` in the root of the project.

#### Actual result
1. One test from Either suite fails with the following diff:

```
 FAIL  test/Either.ts (20.551s)
  ● Either › stringifyJSON

    assert.deepStrictEqual(received, expected)

    Expected value to deeply and strictly equal to:
      {"_tag": "Left", "left": [TypeError: Converting circular structure to JSON]}
    Received:
      {"_tag": "Left", "left": [TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Object'
        --- property 'ref' closes the circle]}

    Difference:

    - Expected
    + Received

      Object {
        "_tag": "Left",
    -   "left": [TypeError: Converting circular structure to JSON],
    +   "left": [TypeError: Converting circular structure to JSON
    +     --> starting at object with constructor 'Object'
    +     --- property 'ref' closes the circle],
      }

      172 |     const circular: any = { ref: null }
      173 |     circular.ref = circular
    > 174 |     assert.deepStrictEqual(
          |            ^
      175 |       _.stringifyJSON(circular, _.toError),
      176 |       _.left(new TypeError('Converting circular structure to JSON'))
      177 |     )

      at Object.<anonymous> (test/Either.ts:174:12)
```

#### Expected result

Tests pass successfully.

### Reproducible example

Current `master` branch HEAD.

### Suggested solution(s)

I see two possible ways to fix this:
1. Check that error wrapped in `Left` is `TypeError` via `instanceof`.
2. Fold over the result of calling `stringifyJSON` and in left branch check the message for inclusion of substring `"Converting circular structure to JSON"`.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.0.5      |
| TypeScript | 3.6.2       |

**Comment by DenisFrezzato** [comment]
In my opinion, the test can check both the `instanceof` and its message.

In some cases, I found myself folding the either and run the assertions within the branch the test covers and in the other branch I put an assertion like `assert.strictEqual(leftOrRightValue, undefined)` in order to make the test fail (I don't know if this is the best way, though).

**Comment by YBogomolov** [comment]
In order to solve this issue reliably, one needs to:

1. Provide a short assertion for left part, as it is used as an example in the documentation for `Either`.
2. Construct this assertion in such way that it works for both v12, v10 and possibly v8, as it is still in the maintenance schedule.

The solution with folding over stringification result is a bit cumbersome, as it makes the example in comments for `stringifyJSON` method quite big and ugly:

```ts
/**
 * Converts a JavaScript value to a JavaScript Object Notation (JSON) string.
 *
 * @example
 * import { stringifyJSON, toError, right, fold } from 'fp-ts/lib/Either'
 * import { pipe } from 'fp-ts/lib/pipeable' // <- added
 *
 * assert.deepStrictEqual(stringifyJSON({ a: 1 }, toError), right('{"a":1}'))
 * const circular: any = { ref: null }
 * circular.ref = circular
 * // was just: 
 * // assert.deepStrictEqual(stringifyJSON(circular, toError), left(new TypeError('Converting circular structure to JSON')))
 * // and now it should be written as:
 * pipe(
 *   stringifyJSON(circular, toError),
 *   fold(
 *     e => assert.strictEqual(e.message.includes('Converting circular structure to JSON'), true),
 *     () => assert.fail('Should not be Right')
 *   )
 * )
 *
 * @since 2.0.0
 */
export function stringifyJSON<E>(u: unknown, onError: (reason: unknown) => E): Either<E, string> {
  return tryCatch(() => JSON.stringify(u), onError)
}
```

**Comment by DenisFrezzato** [comment]
An alternative came up to my mind:

```typescript
const stringifiedRes = stringifyJSON(circular, toError)
assert.strictEqual(
  isLeft(stringifiedRes) &&
    stringifiedRes.left.message.includes(
      'Converting circular structure to JSON'
    ),
  true
)
```

I'm just throwing an idea out here, actually I prefer the solution with `fold`.

**Comment by gcanti** [comment]
Reopening this (issue mismatch in the linked commit, #949 instead of #941)

**Comment by grossbart** [comment]
Oh no, that‘s why it didn‘t close the other one … Thanks and sorry!
