### ISSUE TITLE
Playground

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#958]
## 📖 Documentation

It would be great to have a playground. Even a link to code sandbox would be great.

**Comment by grossbart** [comment]
It would be nice indeed, maybe you're right and a link to a single codesandbox.io would be a good start.

It would also be nice to be able to load all the examples into such a tool, but that would need a bit more infrastructure and it is somewhat important that all the examples can continue to be type-checked as they are now, so it's easier to do library upgrades. We could use this thread to start collecting options – most of those that I know, with the exception of codesandbox.io, don't really support TypeScript.

**Comment by steida** [comment]
I made one https://codesandbox.io/s/eloquent-lake-fe5lx
