### ISSUE TITLE
'instanceof' usage is unreliable

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts#96]
For instance, checking is an Either is Left or Right with 'instanceOf' can lead to false negatives.
Indeed, in some contexte, two definitions of the same classe can be loaded and the test is failing.

Check:
http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/

**Comment by gcanti** [comment]
It's a vestige of my first experiments (back then `Option` was implemented with subclassing) thanks for pointing out. 

`instanceof` is used in the following unions

- `Either`
- `Option`
- `These`
- `Validation`

We could switch to valued `_tag`s (currently they are phantom)

```diff
export class Left<L, A>
-  readonly _tag: 'Left'
+  readonly _tag = 'Left'
}
```

Oddly enough PureScript generates *a lot* of `instanceof` checks https://github.com/purescript/purescript/issues/2577

**Comment by sledorze** [comment]
@gcanti What's your gut ETA to know if the new crazy work should land onto master? I'm pondering if we should wait or not the new implementation of HKT to fix that one.

**Comment by gcanti** [comment]
@sledorze not sure, anyway if you are not experimenting an actual issue we can wait for v0.3

**Comment by sledorze** [comment]
@gcanti I found it out from an actual issue, I've not found out why it happens but I have clearly seen a value displaying Left("dummy") and return false to isLeft (and also isRight)..
(Context is a nodeJs app)

**Comment by gcanti** [comment]
ok, then I'll release a patch (0.2.9) in the meanwhile https://github.com/gcanti/fp-ts/pull/97

**Comment by DylanSp** [comment]
Can some note about this be put in the docs? I ran into what I think is this bug recently, due to using `instanceof` to narrow an `Either` from `io-ts` to a `Left` or `Right`; using `isLeft()` and `isRight()` fixed the issue.
