### ISSUE TITLE
bracket behavior

### ISSUE THREAD

**Issue by muradm** [gcanti/fp-ts#963]
According to documentation:

> Make sure that a resource is cleaned up in the event of an exception. The release action is called regardless of whether the body action throws or returns.

Consider the following playground for `TaskEither.bracket`:
```
import { constVoid } from 'fp-ts/lib/function';
import * as E from 'fp-ts/lib/Either';
import * as TE from 'fp-ts/lib/TaskEither';

describe('test', () => {

  type E = Error
  type A = string
  type B = number

  test.only('bracket', async () => {
    return await TE.bracket<E, A, B>(
      () =>
        new Promise<E.Either<E, A>>((resolve, reject) => {
          console.log('acquire connection...');
          resolve(E.right('connection'));
          // resolve(E.left(new Error('gracefully failed to acquire')));
          // reject(new Error('unexpectedly failed to acquire'));
        }),
      (res: A) => () =>
        new Promise<e.Either<E, B>>((resolve, reject) => {
          console.log('working on connection...');
          // resolve(E.right(res.length));
          // resolve(E.left(new Error('gracefully failed to compute')));
          reject(new E('unexpectedly failed to compute'));
        }),
      (res: A, result: E.Either<E, B>) => () =>
        new Promise<E.Either<E, void>>((resolve, reject) => {
          console.log('releasing connection...');
          resolve(E.right(constVoid()));
          // resolve(E.left(new Error('gracefully failed to release')));
          // reject(new Error('unexpectedly failed to release'));
        })
    )()
      .then(E.fold(
        err => console.log('graceful error:', err.message),
        result => console.log('result', result),
      ))
      .catch(err => console.log('unexpected error:', err.message));
  });
});
```
### Current Behavior

1. When `use` promise rejects, `release` is not called. However, when `use` resolves to `Left<E>` `release` is called. Of course one would say that `E` might not be of type `Error`, so promise rejected with some unexpected error which is not necessarily will match to second argument `result` of release part. Does that mean that user has to make sure that final `catch` to promise is handled? If so then documentation is misleading by saying `throws or returns`.

2. When both `use` and `release` parts fail with `Left<E>`, final `then` receives `Left<E>` of `release` part. Which is not very useful. `bracket` has two errors on hands, error from `use` and error from `release`. While most likely error of `release` would be a consequence of error from `use`, user gets only error from `release` part. Then it is hard to reason about problem caused failure of execution. Scala cats-effect is clear on this matter in the [docs](https://typelevel.org/cats-effect/datatypes/io.html#bracket):
> if the use action throws an error and then the release action throws an error as well, the reported error will be that of use, whereas the error thrown by release will just get logged (via System.err)

### Suggested solution(s)

For item 2 above, I would suggest to follow similar behavior as scala cats-effect, and provide the error of `use` part to user, rather than error from `release` part. PR #962 submitted.

For item 1 above ¯\_(ツ)_/¯

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |  2.1.0          |
| TypeScript |   3.4.5         |

**Comment by giogonzo** [comment]
Hi @muradm, I believe the confusion here arises from one big underlying assumption that is not well conveyed to the newcomer by the docs as of now:

`fp-ts` expects to work with pure function implementations - always.

For this reason, `throw new Error()` as well as `Promise.reject()` is always unexpected and unhandled by the library itself.

If dealing with 3rd parties libraries / APIs where the above is not true, explicit fp-ts APIs are available to resume the computation assuming it's pure and the above assumption holds from there onwards. As described in ["Interoperability with non-functional code"](https://gcanti.github.io/fp-ts/recipes/interoperability.html):

- `Either.tryCatch`/`Option.tryCatch` will catch thrown errors (as in `try {} catch {}`)
- `TaskEither.tryCatch` will catch promise rejections


> If so then documentation is misleading by saying throws or returns.

Kind of agree on this one. I think some more effort could be put into documenting the above assumption clearly somewhere (maybe it's already there, I didn't double check the whole docs) and providing links to it in some "strategic" documentation bits (probably all the functions that are related somehow to `Promise` or `MonadThrow`)

---

Re point 2. instead, my opinion is that logging by default would be a very arbitrary decision if embedded into the library. The signature of `release` makes it clear that:
- it is able to perform other side effects (in `IO` or `Task` respectively), like logging if desired
- it can fail as well (`Either`) - and the failure can then be handled by the caller as desired

**Comment by muradm** [comment]
@giogonzo, totally agree on first point. It is more about knowing environment operating on and related consequences. Documentation is still same, at least was yesterday :)

------

For point 2, as mentioned before, in the event both `use` and `release` failures, result is the `left` side of `release`.  Here the problem with reasoning. Intention is to compute `B` from `use`, but failure of `release` to be reasoned. Of course, both signatures, not only `release`, but also `use` allows one to execute other effects. But in this case, one will be ending with putting `bracket` within `bracket`, so that `use => bracket, release => bracket` or alike. In this case, I think, the point of `bracket` is getting lost, if user will have to handle every case within `use` and `release`.

I was checking scalaz ZIO as well. Although it does not specify explicitly in documentation as scala cats does, from signature of their `bracket` I would expect same behavior. In the event of failing both `use` and `release`, final `ZIO` should resolve to the failure of `use` rather than failure of `release`.

May be we can swallow release without log in the same way. Here is PR for this as well #964.

**Comment by giogonzo** [comment]
Reading up on a few doc pages, [the Bracket typeclass from cats-effect](https://typelevel.org/cats-effect/typeclasses/bracket.html) just says:

> Important note, throwing in release function is undefined since the behavior is left to the concrete implementations (ex. cats-effect Bracket[IO], Monix Bracket[Task] or ZIO).

But then, as you say, both the cats `IO` and [Monix `Task`](https://monix.io/api/3.0/monix/eval/Task.html#bracket[B](use:A=>monix.eval.Task[B])(release:A=>monix.eval.Task[Unit]):monix.eval.Task[B]) implementations make the arbitrary choice of logging/reporting the error:

> NOTE on error handling: one big difference versus try {} finally {} is that, in case both the release function and the use function throws, the error raised by use gets signaled and the error raised by release gets reported with System.err for Coeval or with Scheduler.reportFailure for Task.

Personally, I'd still find very confusing (and potentially undesired) "logging+swallowing", I'm not sure why that was the choice in the Scala world 🤔 

For `fp-ts`, the reference implementation is usually the purescript counterpart. Unfortunately [the docs](https://pursuit.purescript.org/packages/purescript-aff/5.0.0/docs/Effect.Aff#v:bracket) are vague on this:

> Guarantees resource acquisition and cleanup. The first effect may acquire some resource, while the second will dispose of it. The third effect makes use of the resource. Disposal is always run last, regardless. Neither acquisition nor disposal may be cancelled and are guaranteed to run until they complete.

and I'm not really able to parse the implementation to understand how it behaves in this regard.
Are you able to shed some light on this?

Re fp-ts, my previous understanding was that `release` "can't fail", i.e. every error originating inside of it must be handled internally (or ignored).
But this technically is not true as of now, since the `E` (error/left type) is fixed by current fp-ts signature to the same that `acquire` and `use` have.
This would be the case instead if `release` had a signature like `(a: A, e: Either<E, B>) => IO<void>` for `IOEither` or similarly `(a: A, e: Either<E, B>) => Task<void>` for `TaskEither`

@gcanti ?

**Comment by gcanti** [comment]
IMO `bracket` is fine as it is: if `release` never fails then you get the result of `use`, otherwise you are free to return:

- `release`'s error
- `use`'s error
- both (if you can combine them)

**Comment by muradm** [comment]
> Personally, I'd still find very confusing (and potentially undesired) "logging+swallowing", I'm not sure why that was the choice in the Scala world thinking

Same here. On the other hand, one should keep in mind that in case of both `use` and `release` failure, by default depending on implementation one of the failures would be swallowed. Also this **updated** PR, has logging removed as suggested.

> For fp-ts, the reference implementation is usually the purescript counterpart. Unfortunately the docs are vague on this:
> > Guarantees resource acquisition and cleanup. The first effect may acquire some resource, while the second will dispose of it. The third effect makes use of the resource. Disposal is always run last, regardless. Neither acquisition nor disposal may be cancelled and are guaranteed to run until they complete.

> and I'm not really able to parse the implementation to understand how it behaves in this regard.
> Are you able to shed some light on this?

Never touched purescript, however [source](https://github.com/purescript-contrib/purescript-aff/blob/ac1fff841121158b7307f719b69a64e7df625986/src/Effect/Aff.purs#L291-L291) looks clear on this:
```
bracket ∷ ∀ a b. Aff a → (a → Aff Unit) → (a → Aff b) → Aff b
```
Basically says that result shape of bracket is `Aff b`, which is result of last effect in definition (`use` effect). I would expect the error of `use` if both `use` and `release` fail, i.e. same behavior as cats, Monix, ZIO.

> Re fp-ts, my previous understanding was that `release` "can't fail", i.e. every error originating inside of it must be handled internally (or ignored).

Above is also a point, so that if `release` "can't fail" (is there anything in the world that "can't fail"? :) ) why not swallow it if it fails with `use` failed?

> But this technically is not true as of now, since the `E` (error/left type) is fixed by current fp-ts signature to the same that `acquire` and `use` have.
> This would be the case instead if `release` had a signature like `(a: A, e: Either<E, B>) => IO<void>` for `IOEither` or similarly `(a: A, e: Either<E, B>) => Task<void>` for `TaskEither`
> 
> @gcanti ?

**Comment by muradm** [comment]
> IMO `bracket` is fine as it is: if `release` never fails then you get the result of `use`, otherwise you are free to return:
> 
>     * `release`'s error
> 
>     * `use`'s error
> 
>     * both (if you can combine them)

Could you please show an example, how can I return `use`'s error when both fail using current bracket?

**Comment by muradm** [comment]
> For `fp-ts`, the reference implementation is usually the purescript counterpart. Unfortunately [the docs](https://pursuit.purescript.org/packages/purescript-aff/5.0.0/docs/Effect.Aff#v:bracket) are vague on this:
> 
> > Guarantees resource acquisition and cleanup. The first effect may acquire some resource, while the second will dispose of it. The third effect makes use of the resource. Disposal is always run last, regardless. Neither acquisition nor disposal may be cancelled and are guaranteed to run until they complete.
> 
> and I'm not really able to parse the implementation to understand how it behaves in this regard.
> Are you able to shed some light on this?

Just naively tested [purescript-aff](https://github.com/purescript-contrib/purescript-aff), using its test cases, behavior as mentioned, when both `use` and `release` throwError, error from `use` is returned.

**Comment by gcanti** [comment]
@muradm

```ts
import * as E from 'fp-ts/lib/Either'
import { bracket, IOEither, mapLeft, right, left } from 'fp-ts/lib/IOEither'
import { pipe } from 'fp-ts/lib/pipeable'

const mybracket: typeof bracket = (acquire, use, release) =>
  bracket(acquire, use, (a, result) =>
    pipe(
      release(a, result),
      mapLeft(e => (E.isLeft(result) ? result.left : e))
    )
  )

//
// tests
//

const acquire = right(true)
const successfulUse = () => right(1)
const failingUse = () => left('use')
const successfulRelease = () => right(undefined)
const failingRelease = () => left('release')

import * as assert from 'assert'

assert.deepStrictEqual(mybracket(acquire, successfulUse, successfulRelease)(), E.right(1))
assert.deepStrictEqual(mybracket(acquire, successfulUse, failingRelease)(), E.left('release'))
assert.deepStrictEqual(mybracket(acquire, failingUse, successfulRelease)(), E.left('use'))
assert.deepStrictEqual(mybracket(acquire, failingUse, failingRelease)(), E.left('use'))
```

More generally

```ts
import { Semigroup, getFirstSemigroup } from 'fp-ts/lib/Semigroup'

function generalbracket<E>(
  S: Semigroup<E> // <-- merging strategy
): <A, B>(
  acquire: IOEither<E, A>,
  use: (a: A) => IOEither<E, B>,
  release: (a: A, e: E.Either<E, B>) => IOEither<E, void>
) => IOEither<E, B> {
  return (acquire, use, release) =>
    bracket(acquire, use, (a, result) =>
      pipe(
        release(a, result),
        mapLeft(e => (E.isLeft(result) ? S.concat(result.left, e) : e))
      )
    )
}

// now we can derive mybracket
const mybracket2: typeof bracket = generalbracket(getFirstSemigroup())

assert.deepStrictEqual(mybracket2(acquire, successfulUse, successfulRelease)(), E.right(1))
assert.deepStrictEqual(mybracket2(acquire, successfulUse, failingRelease)(), E.left('release'))
assert.deepStrictEqual(mybracket2(acquire, failingUse, successfulRelease)(), E.left('use'))
assert.deepStrictEqual(mybracket2(acquire, failingUse, failingRelease)(), E.left('use'))
```
