### ISSUE TITLE
export eqStrict 

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#965]
Why `const eqStrict = { equals: strictEqual }` isn't exported? It seems it should be.

**Comment by gcanti** [comment]
Because is meaningful only with primitives.

The following function is not pure with respect to eqStrict

```ts
interface Person {
  name: string
}

function makePerson(name: string): Person {
  return { name }
}
```

**Comment by steida** [comment]
Hmm, I am using `readonly` modifier everywhere, so it's meaningful on an object, but I will have to probably remove it because it sucks with arrays, there is no Mutable type and casting sucks, so then it will be meaningful only with primitives. Ok, thank you for the answer.

**Comment by larskinn** [comment]
It's still useful to have something like this for primitives, though. For instance, I've defined this in my fp-ts utilities:

eq.ts
```ts
export type StrictComparable = string | number | boolean;
// Untested, but could probably instead be type Primitive = string | number | bigint | boolean | null | undefined | symbol;

export const eqStrict = <A extends StrictComparable>() => eq.fromEquals<A>(eq.strictEqual);

export const byId = <A, B extends StrictComparable>(f: (a: A) => B) => eq.contramap(f)(eqStrict());
```

array.ts
```ts
export function distinct<A extends StrictComparable>(): (as: A[]) => A[] {
    return flow(array.uniq(eqStrict()));
}

export function distinctBy<A, B extends StrictComparable>(f: (a: A) => B): (as: A[]) => A[] {
    return flow(array.uniq(byId(f)));
}
```
