### ISSUE TITLE
Missing sequenceT and sequenceS for Kind4

### ISSUE THREAD

**Issue by pbadenski** [gcanti/fp-ts#969]
### Current Behavior

`sequenceT` and `sequenceS` are missing signatures for Kind4 - so for instance they can't be used with KleisliIO from https://github.com/YBogomolov/kleisli-ts

**Comment by pfgray** [comment]
@pbadenski , thanks for reporting! Looks like `StateReaderTaskEither` is another HKT4 is doesn't work with!

**Comment by gcanti** [comment]
Thanks @pbadenski, released in https://github.com/gcanti/fp-ts/releases/tag/2.1.1
