### ISSUE TITLE
Short variable names style guide

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#971]
## 📖 Documentation

It's not obvious how all those xyz names are generated. Is `ma` Monad type of A?

A little guide would be helpful.

**Comment by giogonzo** [comment]
@steida can you provide a list of examples that are confusing? I can try to add them to https://github.com/gcanti/fp-ts/blob/master/docs/introduction/code-conventions.md in a new "variable naming conventions" section, although I believe there will be some exceptions around the codebase

**Comment by giogonzo** [comment]
To answer your question up to now

> Is ma Monad type of A?

yes. If I'm not wrong the "rule" is in general `fa` if the value is a `Functor<A>` (or similarly `fab` for `Functor<(a: A) => B>`), `ma` for any other typeclass, that typically will be indeed a `Monad<A>`

**Comment by steida** [comment]
And what is `as`?

**Comment by giogonzo** [comment]
if `a: A` is usually a generic parameter of type `A`, `as` is an `Array<A>`

**Comment by steida** [comment]
Yeah, but why `as`? Why not `a`?

```ts
export function init<A>(as: Array<A>): Option<Array<A>> {
  const len = as.length
  return len === 0 ? none : some(as.slice(0, len - 1))
}
```

**Comment by steida** [comment]
Btw, is there any guide when to write function declaration and when arrow function?

**Comment by giogonzo** [comment]
I think `function` is preferred and used for all (at least vast majority) of the exported functions. Also I think it looks nicer in the docs. `const` is sometimes used for internal functions and/or preferred for brevity. I'm not sure whether there are more meaningful conventions in the codebase other than these

**Comment by steida** [comment]
I have this rule: "Use function declaration for all functions with name whenever possible. Otherwise, use arrow function."
