### ISSUE TITLE
fp-ts eslint plugin

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#972]
## 🚀 Feature request

It could be helpful to detect "code smells" and recommend concrete `fp-ts` features.

For example, whenever null or undefined is used, recommend Option.
I suppose many things from this blog post can be detected.

https://dev.to/gcanti/interoperability-with-non-functional-code-using-fp-ts-432e

Related to https://github.com/jfmengels/eslint-plugin-fp

**Comment by raveclassic** [comment]
This should possibly moved to `fp-ts-contrib` [issue tracker](https://github.com/gcanti/fp-ts-contrib/issues)
