### ISSUE TITLE
Should we never throw?

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#973]
## 📖 Documentation

One thing is not obvious to me. How an application or lib should behave when a developer is going to break its state. Not everything can be type-checked. In my case, the user can select some text out of boundaries depending on some typed JSON structure. With Option, we can fail silently. Sure. But in my case, I prefer to fail soon fail cheap approach. Technically, it should not happen unless a developer will call some fn with the wrong value. 

I believe in such case it's OK to throw probably dev only error. Am I correct?

Otherwise, I would have to use Option everywhere in my app, and I believe Option should be mainly for function result, not for function arguments. Am I correct?

**Comment by pigoz** [comment]
Can you post an example? Ideally, you'd make sure not to break the state. fp-ts has a companion library (io-ts) that can check at runtime your inputs are correct.

**Comment by steida** [comment]
@pigoz Check setText function. Of course, it can silently fail, but I would rather tell a developer why the app "does nothing" because I believe it's better for DX.

```ts
export type EditorNodeID = Brand<string, 'EditorNodeID'>;

export interface EditorNode {
  readonly id: EditorNodeID;
}

export interface EditorText extends EditorNode {
  readonly text: string;
}

export interface EditorElement extends EditorNode {
  readonly children: (EditorElementChild)[];
}

export type EditorElementChild = EditorElement | EditorText;

export interface EditorState {
  readonly element: EditorElement;
  readonly selection: Option<EditorSelection>;
  readonly hasFocus: boolean;
}

export function setText(text: string): Endomorphism<EditorState> {
  return state => {
    // TODO: Replace toNullable with something.
    const selection = toNullable(state.selection);
    // https://github.com/gcanti/fp-ts/issues/973
    if (selection == null)
      throw new Error('Text can not be set without a selection.');
    return {
      ...state,
      element: setTextElement(text, selection)(state.element),
    };
  };
}
```

**Comment by steida** [comment]
@mlegenhausen I am using both absurd and io-ts. The problem I have is different. Check the previous comment.

**Comment by pigoz** [comment]
@steida to be honest, I think a library should never throw exceptions. If possible I'd change the signature of setText, to return an `Either<string, EditorState>`, or `These<string, EditorState>`, so something like this:

```ts
import * as E from "fp-ts/lib/Either";

export function setText(
  text: string
): Endomorphism<E.Either<string, EditorState>> {
  return state =>
    pipe(
      E.fromOption(() => "Text can not be set without a selection.")(
        state.selection
      ),
      E.map(selection => ({
        ...state,
        element: setTextElement(text, selection)(state.element)
      }))
    );
}                        
```

Not tested, hopefully I didn't mess up the pipe, my app is still on `fp-ts@1.x` :)

**Comment by steida** [comment]
Thank you. I am creating a new contentEditable editor, https://github.com/evolu-io/evolu and I would love leverage fp-ts as much as possible.

Maybe throwing is bad idea, and I should use console.warn for dev instead.

**Comment by pigoz** [comment]
> Maybe throwing is bad idea, and I should use console.warn for dev instead.

That's a better behavior IMHO

**Comment by steida** [comment]
OK, I got it. Thank for all the answers.

**Comment by mlegenhausen** [comment]
@steida maybe you should reconsider your datamodell. `selection` is of type `Option` means all editor elements can at some point be selectable? If not you should move selection to the element (`EditorText`) itself and remove the `Option` monad.

Beside this `setText` looks like a lense and a lense should never fail. Using a lens on a data modell that is in the wrong state should simple return the old `state`. `console.warn` could be a solution but is in term of `fp-ts` it is a side effect.

**Comment by steida** [comment]
```ts
export interface EditorSelection {
  readonly anchor: EditorPath;
  readonly focus: EditorPath;
}

export type EditorPath = number[];
```

**Comment by raveclassic** [comment]
@steida The trick here is to think in a different paradigm
>  but I would rather tell a developer why the app "does nothing"

Rather than thinking that `setText` "does something" we should think that _given some value of type EditorState, setText produces another value of the same type EditorState_ and here we should also think about error handling - how should application behave if `setState` fails. Either application does something with that error, logs, sends to analytics, whatever, then we should _explicitly_ declare such behaviour in `setState`'s type signature (how it is suggested by @pigoz). Otherwise if it's not declared then `setState` never fails and this means that it handles cases with "invalid" state.

This approach of being explicit in declaring all possible behaviour is essential for functional programming. So, long story short, yeah, __we should never throw__.

**Comment by mlegenhausen** [comment]
> Explicitly declare the possibility of failure in setText's type signature (how it is suggested by @pigoz). Otherwise if it's not declared then setText never fails and this means that it handles cases with "invalid" state.

That's one of the main advantages of FP you can see "everything" by looking at the signature of a function. Throwing is so intransparent and has never worked in all the year I wrote OOP code.

Another idea I normally tend when I see this code is to split the concers. It seems more of a "validate and set" function. Maybe you can try to move the validation out by only allowing some sort of state.

```ts
interface EditorSelectedState {
  state: 'selected'
}
interface EditorUnselectedState {
  state: 'unselected'
}
type EditorState = EditorSelectedState | EditorUnselectedState

declare function setText(text: string): Endormorphism<EditorSelectedState>;
```

This moves the burden of being in the correct state out of the setter.

**Comment by steida** [comment]
> maybe you should reconsider your datamodell. selection is of type Option means all editor elements can at some point be selectable? If not you should move selection to the element (EditorText) itself and remove the Option monad.

Yep. It's like DOM Selection, but using EditorPath instead of a reference to DOM Node.

**Comment by steida** [comment]
Btw, it's from this project. I am seriously decided to fix contentEditable editors once for all, so I really appreciate any help. Thank you all!

https://github.com/evolu-io/evolu/tree/master/packages/evolu/models

**Comment by steida** [comment]
@grossbart I know source code of almost all contentEditable editors and have experiences with nasty browser issues and everything is tested through Puppeteer etc, so nothing to laugh about 😠😆

As I am thinking about it, it seems all EditorState transformations should return Either or These, so when "it does not work" the developer should be allowed to console.log all intermediate errors.

**Comment by grossbart** [comment]
@steida It's a joyous laugh, I think it's really cool that you're so enthusiastic! 👏 

While I'm at it: I'm in favour of not throwing but returning a value that captures the error, and I support @mlegenhausen's suggestion of using a tagged union for the state, I have found this technique to be very useful.

**Comment by steida** [comment]
Maybe I did not get it. How tagged union can help us? Isn't an optional selection good enough? Imagine a document without any selection, until the user click somewhere. How tagged union can help?

**Comment by giogonzo** [comment]
> This moves the burden of being in the correct state out of the setter

👍 Moving the burden to the caller it's rule #1 of FP (or at least among the top 3 😂)

**Comment by steida** [comment]
@giogonzo But that's what I am doing. It's probably not obvious from the code. 

`state.selection` is `Option<EditorSelection>`
while
`setTextElement` requires `EditorSelection`

Is that what you mean?

```ts
export function setText(text: string): Endomorphism<EditorState> {
  return state => {
    // TODO: Replace toNullable with something.
    const selection = toNullable(state.selection);
    // https://github.com/gcanti/fp-ts/issues/973
    if (selection == null)
      throw new Error('Text can not be set without a selection.');
    return {
      ...state,
      element: setTextElement(text, selection)(state.element),
    };
  };
}
```

**Comment by giogonzo** [comment]
> Isn't an optional selection good enough?

To call that function you need a selection. This is what I mean by moving the burden to the caller, it will be caller's responsibility to come up with a way to obtain such selection, or not call this function otherwise.

If your domain model is modeled in terms of sum types (as opposed to product types - i.e. the one with optional selection) this becomes clear in the intent from the very beginning. Your function is able to operato only on a specific case (the one with the selection) not the other.

I'm not saying this is the only possible legit solution for the problem here (returning `Option`/`Either` encoding the "error condition" could be another valid one, depending on the specific case), but when designing from scratch I tend to prefer it.

I recently saw [this talk](https://www.youtube.com/watch?v=PLFl95c-IiU) which explains the concept at a high level (note: there are a gazillion others, and probably better ones, this is just an example): maybe you'll find it useful

**Comment by steida** [comment]
Scott Wlaschin is legend. Going to watch him now, thank you!

**Comment by steida** [comment]
Great talk. To be sure, is this how it should be written in TypeScript?

type EmailOnly = EmailContactInfo
type AddrOnly = PostalContactInfo
type ContactInfo = EmailOnly | AddrOnly | [EmailContactInfo, PostalContactInfo]

Am I right?

<img width="1148" alt="Screenshot 2019-10-15 at 19 31 07" src="https://user-images.githubusercontent.com/66249/66854911-8c4aa580-ef82-11e9-802d-c0c00a2f160c.png">

**Comment by steida** [comment]
Oh,  I think I got it! The whole setText function needs to have EditorSelectedState, I thought it was a typo 😅So the developer has to select something manually!

**Comment by steida** [comment]
Thank you all, it was very helpful.
