### ISSUE TITLE
How to replace simple spread

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#974]
## 📖 Documentation

That's what I have in pipe:

```ts
state => ({
  ...state,
  element: deleteContentElement(deleteContentSelection)(state.element),
}),
```

I thought I could use insertAt:

```ts
insertAt('element', deleteContentElement(deleteContentSelection)(
```

But it does not work. So I tried monocle:

```ts
Lens.fromProp<EditorState>()('element').modify(
  deleteContentElement(deleteContentSelection),
),
```

It works, but it's super verbose. Does it mean we should use plain spread?

**Comment by giogonzo** [comment]
> That's what I have in pipe:

I think it is completely fine

> I thought I could use insertAt:

`Record` functions work well with homogeneous record types. Not really if you are dealing with an heterogeneous "struct"

> monocle works, but it's super verbose

Typically if you have a structure that you find yourself accessing/modifying often in your app, you'll have the lens for it ready (e.g. as part of a shared file, declared once), and then reuse them wherever you see fit

> Does it mean we should use plain spread?

If the use case is a simple set 1 level deep, I don't see nothing wrong with using spread or `Object.assign`

Hope this helps. May I also suggest the [fp chat slack](https://fpchat-invite.herokuapp.com) for questions like this and #973?  (see the #typescript channel in particular)

**Comment by steida** [comment]
Thank you for the answer. As for Slack, it’s like black hole because answers are not indexed by search engines. Also, docs are very sparce so I believe it’s ok to ask here.

**Comment by steida** [comment]
The reason why I was trying to avoid spread is that it always creates a new object which can lean to unnecessary updates even when prop value has not been changed.

**Comment by steida** [comment]
Or I don't know how to do it. That's code I was trying to improve.

```ts
// Preserve identity, otherwise it would always create new objects.
// I can't believe there is no fp-ts helper for that.
if (!somethingHasBeenNormalized) return element;
return { ...element, children };
```
