### ISSUE TITLE
Record like helpers for Object

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#976]
Related to https://github.com/gcanti/fp-ts/issues/974

I like how Record `insertAt` preserves record identity when the inserted value is already there.
It's useful when we are assigning identical values.

```ts
// Preserve identity, otherwise it would always create new objects.
// I can't believe there is no fp-ts helper for that.
if (!somethingHasBeenNormalized) return element;
// Return new object.
return { ...element, children };
```

I thought Lens could help, but it creates a new object for no change as well. What am I overlooking?

**Comment by pfgray** [comment]
@steida , I'm a little confused, are you looking for a function that deletes values at a given key, but if that key isn't there it just returns the same record, thus preserving the reference? This is the behavior of [`deleteAt`](https://gcanti.github.io/fp-ts/modules/Record.ts.html#deleteat-function).

**Comment by steida** [comment]
Almost, but not deleting, but inserting. I am inserting a `children` value in the example. I just wonder why we have such API for Record and not for Objects. Am I overlooking something?

**Comment by pfgray** [comment]
> API for Record and not for Objects.

I'm still not sure what you're asking here. Records are plain Javascript objects.

**Comment by steida** [comment]
No, they are not. Look:

```ts
import { insertAt } from 'fp-ts/lib/Record';

interface Person {
  name: string;
  age: number;
}

const joe: Person = {
  name: 'Joe',
  age: 42,
};

// @ts-ignore: Argument of type 'Person' is not assignable to parameter of type 'Record<"name" | "age", string>'.
console.log(joe === insertAt('name', 'Joe')(joe));
// It's true, because Joe is already there.
// But we can not use insertAt on Object because it's not Record type.
```

**Comment by pfgray** [comment]
It might be of note that if you adjust the inferred value type, it will compile:
```ts
console.log(joe === insertAt<'name', string | number>('name', 'Joe')(joe));
```
This isn't quite accurate, however since you could pass a number for the `"name"` key.

A version that works for interfaces seems pretty trivial to implement:
```ts
declare function updateAt<A extends object, K extends keyof A>(k: K, v: A[K]): (a: A) => A;
updateAt<Person, 'name'>('name', 'Joe')(joe)
```

**Comment by steida** [comment]
OK, use spread.

**Comment by Almaju** [comment]
I ended up doing that:
```ts
export const upsertAt =
  <K extends string, A, Struct>(k: K, f: (s: Struct) => A) =>
  (s: Struct) =>
    ({
      ...s,
      [k]: typeof f(s),
    } as Omit<Struct, K> & { [k in K]: A })
```
Super annoying not to have a standard way to do it... :(
