### ISSUE TITLE
Dependency on rxjs 

### ISSUE THREAD

**Issue by davetayls** [gcanti/fp-ts#98]
Hey, this looks like a really nice FP library for TypeScript and would love to use it but I'm a bit reluctant to include a dependency on rxjs to my project.

It seems like only a small part of the library and could easily be separated into a separate module, is this something you would consider?

**Comment by gcanti** [comment]
> is this something you would consider?

Definitely. Technically is a breaking change so I'll add this to the 0.3 release (should be out in a few days). 

In the meanwhile you can import only the modules you need

```ts
import * as array from 'fp-ts/lib/Array'
```

**Comment by gcanti** [comment]
> In the meanwhile...

@davetayls even better, if you want to help out testing the 0.3 release, there's a `dev` branch with the `lib` folder committed in so you can install it with

```
npm i gcanti/fp-ts#dev
```

feedback much appreciated

**Comment by davetayls** [comment]
Thanks, really appreciate it. I'll try that work around in the meantime and happy to help test the dev branch. I might as well just use that now as this project won't go out in the wild for a while
