### ISSUE TITLE
Pipe logging

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#984]
## 📖 Documentation

How fp-ts people "debug" pipe? I just created this helper. Is it ok or not? Thank you.

```ts
/**
 * A little helper for pipe logging.
 * `pipe(x, foo, logPipe, bla)`
 */
export const logPipe = <T>(arg: T): T => {
  // eslint-disable-next-line no-console
  console.log(arg);
  return arg;
};
```

**Comment by steida** [comment]
For example, something is failing in sequenceT and I need to know what.

![Screenshot 2019-10-25 at 00 15 16](https://user-images.githubusercontent.com/66249/67529482-94aa8b00-f6bc-11e9-9e1b-25fe94abdae0.png)

**Comment by grossbart** [comment]
In v1 there was a `Trace` module with helpers for this. I'm not sure why it was removed, possibly to reduce the API surface. Anyway, it's simple enough, have a look and copy it to your project, if you need it: https://github.com/gcanti/fp-ts/blob/1.x/src/Trace.ts

It was inspired by https://pursuit.purescript.org/packages/purescript-debug/3.0.0/docs/Debug.Trace

**Comment by steida** [comment]
Thank you. Btw, why Trace is better than logPipe?

**Comment by tonisives** [comment]
After reading https://github.com/gcanti/logging-ts/issues/20, I found a nice logging solution for TaskEither

you can use it in a pipe with just `log(() => "log value")

```
await pipe(
    TE.Do,
    TE.bind("input", () => pipe(validateInput(event), TE.fromEither)),
    log(() => "checking conditions"),
    TE.bind("pre", () => sequenceT(TE.ApplicativePar)(
      verifyAuth(event),
      verifyTokensAvailable(event, 5e9)
    )),
    log(() => "starting job"),
)()
```

this is the log function:

```
import * as C from "fp-ts/lib/Console.js"
import * as L from "logging-ts/lib/IO.js"
import * as TE from "fp-ts/lib/TaskEither.js"

export const withLogger =
  (logger: L.LoggerIO<string>) =>
  <A>(message: (a: A) => string): (<E>(ma: TE.TaskEither<E, A>) => TE.TaskEither<E, A>) =>
    TE.chainFirst((a) => TE.fromIO(logger(message(a))))

export let log = withLogger(C.info)
```
