### ISSUE TITLE
Explain why Readonly array is not good idea

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#987]
## 📖 Documentation

Readonly arrays are great to prevent accidental mutations via sort method, but PITA when used with code requiring normal Array. Long story short, it's: Use it everywhere, nowhere, or cast all the time.

I didn't find any other frictionless solution from the DX perspective than not using readonly arrays at all.

I believe it should be mentioned in the documentation.

**Comment by raveclassic** [comment]
It's ok to accept `ReadonlyArray` or even `ArrayLike` as an argument but things get worse when using them as a return type.

I think the best solution so far is to accept `ArrayLike` and return `Array` if a function constructs a new `Array`. 

Note: we have the same problem in `most` https://github.com/mostjs/core/pull/296#discussion_r326129838

**Comment by steida** [comment]
@gcanti ReadonlyArray really should be banned in fp-ts ecosystem. It's only pain without any measurable benefit. I just spend another hour with `export interface Context extends ReadonlyArray<ContextEntry> {` trying to figure out why I can not use fp-ts Array. Not I have to cast (ugly) or call slice(0) (ugly too).

**Comment by gcanti** [comment]
> ReadonlyArray really should be banned in fp-ts ecosystem


In practice it already is (except for `io-ts`'s `Context`, for legacy reasons)

**Comment by andrei-zhidkov** [comment]
Sorry, but I don't get why the use of `ReadonlyArray` (a built-in type) should be discouraged in the `fp-ts` docs.
Besides, I'm not sure I understand the reason to artificially limit the ReadonlyArray usage, given that the functions in Array.ts are pure.

`ReadonlyArray`s are great, and I'd be glad to submit a PR to support them more (either with overloads to return `ReadonlyArray`s when operating on `ReadonlyArray`s or using ArrayLike as @raveclassic suggested)

**Comment by steida** [comment]
"ReadonlyArrays are great" if everything is read-only array otherwise poor developers have to cast them all the time. If fp-ts people are happy with it casting all the time or not using mutable arrays at all, then ok.

**Comment by SRachamim** [comment]
In our projects we're enforcing using `readonly` and `ReadinlyArray` with functional linting rules[functional linting rules](https://github.com/jonaskello/eslint-plugin-functional/blob/master/docs/rules/prefer-readonly-type.md) .

**Comment by gcanti** [comment]
Actually I'm considering to drop support for mutable modules in v3, https://github.com/gcanti/fp-ts/issues/1226
