### ISSUE TITLE
More examples of using `Task<A>` in documentation (especially in conjunction with other code, such as redux)

### ISSUE THREAD

**Issue by huntwj** [gcanti/fp-ts#989]
## 📖 Documentation

As someone who is fairly invested in the fp-ts and io-ts libraries, I'd love to see more examples of using it to interact with other aspects of my code base.

In this case specifically, I see `Task<A>` as a great candidate for handling async operations in a Redux application. I'm having a little trouble, however, figuring out an elegant way to provide a clean interoperability between the two. I think my holy grail would be some sort of redux-thunk like library that was more TypeScript aware and supported dispatching actions with Tasks attached.

Specifically, how can I provide access to the `dispatch` and `getState` functions provided by the middleware as the tasks are run? Here's some non-working code to help you into the scary place that is my brain:

```ts
const createTaskAction = (task: Task<void>) => ({
  type: "__TASK_ACTION",
  payload: {
    task,
  }
});

// A real task might be far more complicated, but since we're dispatching
// it as an action, it would have to be a Task<void> at the top level. 
// (Or such is my understanding.)
const myTask: Task<void> = () => { 
  const result = doSomethingComplicated();
  dispatch.(updateAction(result));  
  // ^^^ How can I get access to the dispatch here in a composable manner?
}

dispatch(createTaskAction(myTask));
```

Do I need to reroll my own `ReduxTask` that includes the `dispatch` and `getState` parameters?

```ts
export interface ReduxTask<S> {
  (dispatch: Dispatch<AnyAction>, state: S): void;
}
```

Or is there a more elegant way to get there using the existing `Task` type and help prevent re-inventing the wheel?

**Comment by mlegenhausen** [comment]
I would not recommend to dispatch a Task in an `Action` cause they are not serailizable.

Converting from a `Task` to a thunk could look like this

```ts
function toThunk<S, A = never>(f: (s: S) => Task<Option<A>>): (dispatch: (action: A) => void, getState: () => S) => void {
  return (dispatch, getState) => f(getState())().then(a => option.map(a, dispatch))
}
```

Note `Task<Option<A>>` means you can dispatch an action from the task but you don't have to.

**Comment by baetheus** [comment]
I tend to use rxjs instead of fetch and promises in my react apps, so Task doesn't show up very often. However, I did throw together a react hook that utilizes Task that might be helpful: https://gist.github.com/baetheus/a68cef83d01b9827b1e0bc3518e1f1b1
