### ISSUE TITLE
Injecting stateful behavior

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#993]
## 📖 Documentation

One thing is not obvious to me. Is `createFoo` function pure? I suppose it is. But we can not replace readFromDOM with value, so it's not referential transparent I suppose. Should we use IO?

```ts
export const createFoo = (
  value: JSON,
  readFromDOM: (selector: string) => Option<Element>,
): Foo => {
  // We use value for reading from DOM.
};
```

**Comment by vegansk** [comment]
`readFromDOM: (selector: string) => Option<Element>` should be `readFromDOM: (selector: string) => IO<Option<Element>>`, so `createFoo` should return `IO<Foo>`.

**Comment by steida** [comment]
OK, this talk explains it. https://www.youtube.com/watch?v=cxs7oLGrxQ4

A function is not and can not be pure when the injected function is impure.

**Comment by steida** [comment]
@vegansk Thank you a lot. It's so obsious after aha moment.
