### ISSUE TITLE
Promise.allSettled behavior

### ISSUE THREAD

**Issue by amaurymartiny** [gcanti/fp-ts#995]
## 📖 Documentation

`Promise.allSettled` behavior: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

In the docs, there is a `Promise.all()` example, using `array.sequence(TE.taskEither)(myTEs)`:

```
declare const myTEs: TE.TaskEither<E,A>[];

const responses = await array.sequence(TE.taskEither)(myTEs)(); // responses is `Either<E, A[]>`
```

The above behavior is the one from `Promise.all()`. How would I make it like `Promise.allSettled`? Namely, how to write `f` so that:

```
const responses = await f(myTEs); // responses is `Either<E,A>[]`
```

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |    2.1.1        |
| TypeScript |    3.6.4        |

**Comment by gcanti** [comment]
```ts
f = array.sequence(T.task)
```

where `T` comes from

```ts
import * as T from 'fp-ts/lib/Task'
```
