### ISSUE TITLE
Sum type fold boilerplate

### ISSUE THREAD

**Issue by leemhenson** [gcanti/fp-ts#996]
### Current Behavior

Writing a custom fold for every custom sum type is annoying. Is it possible to do better? For example:

```typescript
type Empty = "empty";
type NonEmpty = "non-empty";
type ValueState = Empty | NonEmpty;

const emptyState: ValueState = "empty";
const nonEmptyState: ValueState = "non-empty";

// this bit is essentially dull and mechanical
const foldValueState = <A>(fns: {
  empty: (_: Empty) => A;
  nonEmpty: (_: NonEmpty) => A;
}) => (state: ValueState): A => {
  switch (state) {
    case "empty":
      return fns.empty(state);
    case "non-empty":
      return fns.nonEmpty(state);
    default:
      return unsafeAssertNever(state);
  }
};
```

### Desired Behavior

Better ergonomics for writing the `fold`.

e.g. `foldSumType2`

```typescript
const foldSumType2 = <A, B>(isA: Refinement<A | B, A>, isB: Refinement<A | B, B>) => <C>(fns: {
  onA: (a: A) => C;
  onB: (b: B) => C;
}) => (value: A | B) => {
  if (isA(value)) {
    return fns.onA(value);
  }

  if (isB(value)) {
    return fns.onB(value);
  }

  return unsafeAssertNever(value);
};

// simple contrived example

const fold = foldSumType2(isEmptyState, isNonEmptyState);
const isEmptyValueState = fold({ isA: constTrue, isB: constFalse });
```

This works ok, but it's sad that the record of case functions has keys like `isA`, `isB` etc. Ideally, you would specify meaningful names at the point of invoking `foldSumType2`. E.g.

```typescript
foldSumType2("isEmpty", isEmptyState, "isNonEmpty", isNonEmptyState)({
  isEmpty: constTrue,
  isNonEmpty: constFalse,
})
```

Anyone got any sneaky type-level jiggery-pokery to make something like that work?

**Comment by grossbart** [comment]
I do this in two ways, depending on the underlying data type. What's most important to me is that TypeScript complains if I'm missing a branch when folding or have too many, and these two ways help me achieve that.

With sum types:

```ts
// See https://stackoverflow.com/a/50125960/84816
export type DiscriminateUnion<T, K extends keyof T, V extends T[K]> = T extends Record<K, V>
  ? T
  : never;

export type MkPattern<T extends Record<K, string>, K extends keyof T, A> = {
  [V in T[K]]: (x: DiscriminateUnion<T, K, V>) => A;
};

type A = { type: 'A', message: string } 
type B =  { type: 'B', origin: string }
export type Exception = A | B

export function foldException<A>(e: Exception, pattern: MkPattern<Exception, "type", A>): A {
  return (pattern[e.type] as any)(e);
}
```

I often also have an accompanying function `foldException_` that is curried: `foldException_(exception)(pattern)`.

With plain enum kind of types (that don't have a payload):

```ts
export type Style = "light" | "dark"

export function foldStyle<A>(style: Style, pattern: { [K in Style]: () => A }) {
  return pattern[style]();
}
```

I'm sure this could be simplified further and I would actually greatly appreciate this to be somewhat standardised like you suggest.

**Comment by DenisFrezzato** [comment]
@grossbart's solution looks cool!

I would like to point out [fp-ts-codegen playground](https://gcanti.github.io/fp-ts-codegen) as well, it creates common functions given an ADT.

**Comment by leemhenson** [comment]
One (very slight) annoyance with @grossbart `DiscriminateUnion` is that it requires every inhabitant of the sum type to be a type with a key on it. Imo, it would be better to not have that requirement, but that's subjective. `foldSumTypeN` just works through the `Refinement`s in the order given, so there's no need to have a discriminator key on each case.

**Comment by pfgray** [comment]
@leemhenson  How would you discriminate between values without a discriminant member? 

i.e. if you had a type like:
```ts
type MySum = number | string;
```
how can you write a fold which allows you to supply functions for each type?

A first thought might be to convert the union to a tuple, but there's many issues with this approach outlined here: https://github.com/microsoft/TypeScript/issues/13298 (this whole thread discussion contains a lot of other info).

FWIW, I have a similar technique I've been using, which is slightly more concise, but limits the discrimant name: https://gist.github.com/pfgray/93b2330cf8abde662aa2fe99494bb9b0, which is used like:

```ts
type These<A, B> = ADT<{
  left: {left: A},
  right: {right: B},
  both: {left: A, right: B}
}>
```
and then a `match` function to fold over:
```ts
declare const myThese: These<string, number>;

pipe(
  myThese,
  match({
    left: ({left}) => 'Value is left',
    right: ({right}) => 'Value is right',
    both: ({left, right}) => 'Value is both'
  })
)
```

**Comment by leemhenson** [comment]
> How would you discriminate between values without a discriminant member?

Sequential use of `Refinement` fns, e.g. `foldSumType2` as mentioned above. Unless I'm misunderstanding the question!
